/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  GENE KEYS — EQ  (position-specific readings)
 * ═══════════════════════════════════════════════════════════════════════════
 *  Mars at birth: the feeling one. How you meet emotion, your own and other people's — the reflex at the moment of impact, not the philosophy about it.
 *
 *  Mastery empowers: it names the capacity as an earned strength with the
 *  reader as subject and actor of nearly every sentence, surfaces something
 *  they have underrated in themselves, and ends on a lift rather than a
 *  caveat.
 *
 *  Written from the published Shadow/Gift/Siddhi triads and this sphere's
 *  lens alone — never from the universal reading or a sibling sphere, which
 *  is what stops the readings collapsing into rewordings of one another.
 *  Verified for shape, for distinctness against the universal reading and
 *  every shipped sphere, and for cross-sphere opening clauses.
 * ═══════════════════════════════════════════════════════════════════════════
 */

DGKRoles.register('eq', {
  "1": {
    "gift": "You stay present at the exact moment a feeling turns stale, and something in you quietly refuses to run the old script again. When another person arrives flat or exhausted, your response comes out new and unrehearsed, shaped for them rather than lifted from a comfort you have offered before. Most people reach under pressure for the nearest familiar reassurance, while your attention goes to whatever is genuinely happening in the room at that hour. That freshness is the capacity you underrate most, because it costs you almost nothing and it visibly restarts people who had already given up on being properly met by anyone.",
    "shadow": "Flatness is the tell. When a feeling has run its course the whole emotional system dims, and another person’s distress lands on a dead surface, so you watch them hurting and register nothing back at all. In that trough an old fear surfaces: that the aliveness was only ever borrowed, that it will not return this time, that whoever needed you today happened to catch you empty. So a response gets faked, or you withdraw completely and call it needing space, and the other person walks away unsure whether they had become a burden. The cost compounds quietly, since every unmet moment makes the next honest answer harder to give.",
    "invitation": "Feeling arrives here with nothing stale left inside it, because nothing in this heart is defended anymore. Each response is new, unrehearsed, moving through a life the way spring moves through a field without asking the previous season's permission. Nobody taught this freshness; it simply surfaced once hiding stopped."
  },
  "2": {
    "gift": "You steady while everyone around you scatters, because your body registers which direction a feeling is coming from well before anybody has named it. In a room where grief or anger has no obvious source, you turn toward it without flinching, and the others in the room follow your turning without knowing they did. Most people manage distress by facing away from it, so orientation alone settles a group faster than any advice on offer that day. What you underrate is the rarity of this: you assume anyone can locate the true centre of a difficult moment, and almost nobody can.",
    "shadow": "Dislocation feels like standing in the wrong life during somebody else’s crisis. The moment another person’s emotion fills the space, your sense of where you are drops away, and you either mirror them precisely or freeze at a distance that neither of you can explain afterwards. Beneath it sits an old suspicion that you hold no fixed position of your own, that you are only ever placed by whoever happens to be loudest nearby. So attachment goes hard toward the strongest feeling in the room, followed by resentment at having been occupied by it. Afterwards you cannot say what you felt, only what they felt, and that confusion costs you days.",
    "invitation": "There is no longer a feeling self and a world it is trying to locate itself inside of. Every response continues what is already whole, the way a river continues the rain that fed it. Direction has stopped being a question the heart carries."
  },
  "3": {
    "gift": "You register the mess in a room without needing it to resolve, which is precisely why chaotic people settle down in your company. When somebody’s feeling arrives disordered and contradictory, you leave the raw version intact until its own shape appears, instead of tidying it into a story that can be repeated. Most people need distress to make sense before they can sit near it, and you carry no such requirement, which is a real capacity rather than a mood. It reaches people whose emotions have never once been allowed to be as messy as they actually are.",
    "shadow": "Chaos stops being fertile the moment it becomes your default weather. Small emotional demands start landing as overwhelm, and instead of one clear response you produce five half-responses, all sincere and none finished, leaving the other person more confused than they were before speaking. Somewhere underneath runs a conviction that order is a betrayal, that choosing one feeling kills the rest, so everything keeps churning and gets defended as honesty. In heated moments you escalate rather than land, adding detail and possibility until nobody in the conversation can find the original hurt. What that costs is trust, because people learn that bringing you something simple returns it complicated.",
    "invitation": "Whatever chaos arrives here gets included instantly, with no story built around the mess and no mourning period attached to it. Feeling meets each collapse fresh, the way it met the last one, carrying nothing forward from before. Nothing here needed the world to hold still first."
  },
  "4": {
    "gift": "You soften toward people faster than your own judgement can finish forming, and that half-second lag is where the whole gift lives. When someone lashes out at you, the reason behind their behaviour appears almost immediately, and the finding is genuine rather than a technique you use for staying calm. Most people need several days and an apology before they get there, while you arrive mid-argument, which changes what the argument itself is able to become. That speed of understanding is quietly unusual, and it is why people confess things to you they have never said aloud to anybody.",
    "shadow": "Intolerance shows up as a cold snap. Someone repeats a mistake that has already been explained to them, and warmth vanishes within a second, replaced by a clipped certainty about exactly what is wrong with that person. Underneath runs a fear that an uncategorised human being leaves you permanently at their mercy, so the question gets settled early and the listening quietly stops. That verdict then colours every later exchange between you, and they can sense the file has been closed on them without ever being told. The cost is real relationships pruned for the sake of tidiness, plus a growing private suspicion that people are simply disappointing.",
    "invitation": "This is the atmosphere feeling is held inside of now, not something aimed at anyone. Every hurt, every misread, every wrong turn the heart ever took is simply included rather than resolved. What moves through afterward carries no grudge against its own history."
  },
  "5": {
    "gift": "You linger beside people who are not ready yet, and the lingering is genuinely yours rather than good manners stretched thin over private irritation. When someone is mid-grief and circling the same ground for the fourth time in a month, your attention neither thins out nor starts quietly planning ahead. Most people’s patience is really a countdown, while yours has no clock running inside it, and others can sense that difference within a few minutes. That is why the slow ones eventually open with you: you offered a rhythm nobody else in their life was willing to match.",
    "shadow": "Impatience arrives as a hum under the skin. A conversation that will not get to the point turns you brittle, and you begin finishing sentences, offering fixes, moving somebody along a schedule they were never asked to agree to. Beneath it lies an assumption that feelings are supposed to complete on time, and that a slow one means something has gone wrong with them or with you. So endings get rushed, and the other person learns not to bring you anything that will take a while to say. Later that hum turns inward, your own grief receives the same treatment, and it goes underground instead of through.",
    "invitation": "Every feeling here is allowed exactly the duration it actually needs, because the heart holding it has stopped measuring against a clock. What arrives is neither early nor late; it was always exactly on time. There was never really a hurry."
  },
  "6": {
    "gift": "You handle heat without becoming it, which is the most useful thing a human being can do inside a fight. When two people are escalating in front of you, your voice drops instead of rising, and the exchange loses several degrees within a matter of seconds. Most people either hit back or leave the room, while you stay inside the friction and keep talking, which very few can sustain for any length of time. That steadiness under someone’s anger is a nervous-system skill you never trained for, and it makes you the one others want present when something hard has to be said.",
    "shadow": "Conflict either sticks to you or you stick to it. Some days a raised voice cuts straight through and you are twelve years old again, arguing to win, saying the accurate cruel thing that can never afterwards be unsaid. Other days the exchange gets avoided entirely, agreement is given to keep things pleasant, and the resentment is carried for months under the name of being reasonable. The false belief running both versions is that friction means the relationship is failing, when friction is usually the relationship doing its work. Either way the real disagreement stays unspoken, and closeness thins into a careful arrangement neither of you would choose out loud.",
    "invitation": "Conflict passes through without leaving a mark, because the part of the heart that needed to be right has fully burned off. Two opposing feelings can sit together here, unresolved and unbothered. Nothing left has anything to defend."
  },
  "7": {
    "gift": "You gather frightened people around you without ever announcing that this is what you are doing. When a group’s feeling fractures into panic and blame, you become the one everybody checks for a reaction before deciding how they are going to feel about it. That responsibility does not spike your own alarm, which is unusual, since most people’s fear climbs in step with the volume of the room. What you underrate is how much your steadiness is quietly carrying: one ordinary sentence from you in a bad hour keeps three other people in the room from coming apart.",
    "shadow": "Division starts inside long before it ever shows on the outside. Under pressure the people around you get sorted into those who are with you and those who are not, and your warmth follows that line without any conscious decision being made. The fear beneath it is being left holding the whole group alone, so loyalty gets secured instead of trust, through hinting, allying, and letting a side quietly form. In heated moments you speak for other people’s feelings without asking first, and they feel used by the very person who was protecting them. What it costs is the thing you were building: they follow you, and they stop telling you the truth.",
    "invitation": "Warmth moves through without a personality attached to it anymore. Whoever meets it takes what they came for and continues on, unaware that anything was given. The heart that used to comfort has dissolved into the comforting itself."
  },
  "8": {
    "gift": "You carry your own emotional signature into every room, and people recognise it the way they recognise a voice through a wall. When something moves you, it shows in a form that is unmistakably yours rather than the generic version everybody else in the room performs. Most people flatten their reactions to fit the company they are in, and your refusal to do that gives others permission to be specific about what they are feeling. It is the reason your comfort lands at all, since what people receive sounds like an actual person rather than a printed card.",
    "shadow": "Mediocrity is what happens when the reaction gets edited before it ever leaves you. In a room that seems unimpressed, the real response is swapped for a safe one, and you go home flat and faintly ashamed without being able to say why. Underneath sits a fear that your particular way of feeling things is too much for people, or worse, not enough to be worth the exposure. So somebody else’s register gets borrowed, cooler and funnier and more measured, and the ones who needed the true thing receive a performance instead. The cost is a life surrounded by company that has only ever encountered your imitation of yourself.",
    "invitation": "Every unnecessary gesture has already gone, because there is no longer an audience inside this heart to perform feeling for. What remains is undecorated, exact, complete in its plainness. This is warmth with nobody left inside wanting credit for it."
  },
  "9": {
    "gift": "You persist with a person long after the emotional return on that attention has dropped to nothing at all. When someone is in a long, unglamorous stretch of grief, you keep turning up in small ways that nobody else around them has the stamina to sustain. Most support is a burst that fades inside a fortnight, while yours is a rate, and the rate is what actually carries people through. You underrate this because it feels like doing very little, a message or a chair pulled up, yet repeated across months it becomes the part they remember.",
    "shadow": "Inertia sets in when the small gesture stops feeling worth making. A difficult feeling arrives and gets parked, with a promise to deal with it properly once there is space, and then months pass with the same weight sitting in the same corner. Beneath it sits a suspicion that any small response is pointless against something large, so you wait for a big gesture that never quite gets made. With other people it looks like slow replies to real distress, and by the time you arrive the moment has already closed over. The cost is a quiet backlog of unaddressed feeling that begins to seem permanent rather than merely pending.",
    "invitation": "This heart no longer distinguishes a small feeling from an enormous one; each receives everything, with nothing held in reserve. Nothing can interrupt a heart that isn't waiting for something more important to arrive."
  },
  "10": {
    "gift": "You answer at your own natural size when feeling floods a room, without apologising for it, and that puts other people at ease almost immediately. When somebody nearby is upset, concern is not performed for the room; you meet the actual weight of it, and that proportion is itself the comforting part. Most people amplify or shrink to match the emotional volume around them, while you stay recognisably the same person, which gives everybody else somewhere stable to stand. That ordinariness in emotionally charged moments is far rarer than it has ever looked to you from the inside of your own life.",
    "shadow": "Self-obsession here is not vanity, it is the loop. Another person’s distress arrives and within seconds it has become a question about you: how you handled it, how you appeared, whether you are the sort of person who copes with these things. The fear powering that loop is that being off-centre in a moment means not really existing in it at all. So your own story gets inserted into their crisis, or you fall silent and monitor yourself instead of listening to them. What it costs is presence, because the person in front of you can tell they are being watched from inside somebody else’s self-assessment.",
    "invitation": "This heart requires no further becoming; it simply is, the way a mountain is, with no campaign behind it. Naturalness has stopped being a technique and become the only thing left once technique fully dissolved. Nothing here is auditioning to be lovable."
  },
  "11": {
    "gift": "You brighten a heavy room without pretending that the heaviness is not there, which is a genuinely difficult combination to manage. When someone is despairing in front of you, you keep a clear picture of who they are underneath it and speak to that person rather than to the mood on top. Most encouragement asks people to feel better, while yours reminds them what they are actually like, and that is a different and far more durable intervention. You assume everybody carries such a picture of the people they love, and almost nobody does, which is why they come to you when their own self-image goes dark.",
    "shadow": "Obscurity descends when the picture stops matching the person. What you love is the version held in your head, and the actual human being, irritable and ordinary and disappointing on a Tuesday, starts to feel like a betrayal of it. The fear beneath is that if the ideal was untrue, then none of the warmth you felt was real either. So you drift away, or push them toward the vision with a pressure that reads to them as disappointment, and they end up feeling measured rather than loved. Left alone the same dynamic turns inward, and your own feelings blur into a fog you cannot describe to anybody.",
    "invitation": "This heart has stopped needing a reason to feel warmly toward anyone, because everything that reaches it already carries the warmth inside. Care is no longer a private feeling defended against the world; it is simply how the world looks from inside this heart."
  },
  "12": {
    "gift": "You distinguish a real feeling from a presented one almost on contact, before the sentence in front of you has finished. When somebody offers a rehearsed version of their grief, you notice the seam, and you wait without exposing them until the true thing underneath finally comes up. Most people take emotional statements at face value, while you register the gap and keep the door open, which is why the honest disclosure eventually arrives at all. That combination of accuracy and restraint is unusual, and people trust you with material they have never once rehearsed for anybody.",
    "shadow": "Vanity here is about the sound of your own honesty. Somebody reaches toward you and you become aware of how the response looks, the elegant sentence and the correct measure of emotion, while the actual person slides quietly out of focus. Or the opposite happens: you withhold entirely, deciding their feeling is impure and unworthy of a real answer from someone like you. Beneath both moves is a fear of being contaminated by messy, unbeautiful need that has no shape to admire. The cost falls on people at their least presentable, who reach for you at the exact hour you are hardest to reach, and they never ask twice.",
    "invitation": "Every response here is uncontaminated by the question of how it will be received, not through discipline but because that question genuinely stopped arising. Nothing is performed. What remains is exactly, only, what was actually felt."
  },
  "13": {
    "gift": "You listen at a depth that most people mistake for silence, and it is the reason strangers tell you everything. When someone speaks about a loss, the thing underneath their words reaches you intact, and you do not rush to prove that it did. Most listeners are already waiting to reply, while you are still receiving well past the point where they would have started talking, and people sense that difference in their bodies. That capacity to take in another person’s feeling without immediately converting it into advice quietly repairs things you never find out about.",
    "shadow": "Discord builds wherever everything comes in and nothing goes back out. The room’s grief gets taken on unfiltered, and then you find yourself irritable with the very people who confided in you, unable to explain the irritation to anyone. Running underneath is a belief that your entire value is the listening, so refusing it even once would end the relationship. Secrets accumulate, sides multiply, and you become the hinge between people who are no longer speaking, exhausted by a role that nobody actually assigned. What it costs is your own weather, so crowded with other people’s that you cannot locate a single feeling that began in you.",
    "invitation": "This heart has stopped needing to understand another person from the outside, because the separation that made understanding necessary has already closed. What it receives already includes the one who brought it. There is no longer a comforter and a comforted, only the meeting, happening."
  },
  "14": {
    "gift": "You share warmth without rationing it, and people leave your company carrying noticeably more than they brought in with them. When somebody is depleted, your response is generous in a practical, unfussy way, and the energy behind it is real rather than encouraging noise. Most people give from whatever is left over at the end of the day, while you give from the middle of the supply, and it replenishes you instead of draining you. That renewable quality is the thing you underrate, and it is why tired people gravitate toward you without knowing what they came for.",
    "shadow": "Compromise starts out sounding reasonable and finishes as a slow leak. An arrangement gets accepted that quietly costs you — less honesty, less contact, a thinner version of what you actually wanted — because asking for more felt greedy in the moment. The belief underneath is that appetite for closeness is a character flaw rather than useful information about whether this fits. Months on, the warmth has gone thin and you are performing a generosity you no longer feel, resenting people who never knew a negotiation had happened. The cost is a life of relationships that are almost right, each one settled a little below the level you actually needed.",
    "invitation": "This heart is a source that was never actually short of anything. What it gives costs nothing to give, because the sense of a finite supply \u2014 the thing warmth used to ration so carefully \u2014 has completely dissolved. Generosity here is simply what happens when nothing is being withheld."
  },
  "15": {
    "gift": "You warm to people across an enormous range, from the obviously impressive to the entirely unremarkable, and neither group gets a different reception. When somebody grieves in an inconvenient or unattractive way, your attention does not withdraw the way most attention quietly withdraws in that situation. That tolerance for the whole spectrum of human feeling is a genuine capacity rather than a virtue you decided to adopt at some point. It is why people who have been written off elsewhere bloom in your company, since you were simply the first one who did not flinch at them.",
    "shadow": "Dullness arrives as a grey stretch where nothing at all reaches you. Somebody’s excitement or pain lands on a surface with no give in it, and you go through the motions of caring while privately waiting for the season to change. Beneath that is a fear that the flat version is the real you and the vivid one was a fluke of circumstance. In that state you press people who run to extremes, needing their intensity as proof that you still work properly, then blame them for being too much. The cost is a cycle others come to read as unreliability, and the closest ones start protecting themselves from your winters.",
    "invitation": "Every stage this heart passes through \u2014 the raw, the unfinished, the grieving \u2014 is already flowering on its own terms. Nothing here is behind, and nothing here is early. Feeling blooms in permanent, effortless season."
  },
  "16": {
    "gift": "You shift registers mid-conversation without losing the thread, which is why hard emotional exchanges actually go somewhere with you. When grief turns into anger and then into laughing within ten minutes, all three get followed and not one of them throws you off. Most people meet a single emotional key well and go stiff in every other one, while your range is wide enough that nobody has to choose which feeling to bring you. That flexibility looks like natural ease from the outside, and it is really a skill you have been quietly building since early childhood.",
    "shadow": "Indifference is the switch that flips whenever enthusiasm goes unreturned. Real feeling gets offered, it lands wrong, and something closes so completely that a week later you can look at the same person with nothing whatsoever in you. The belief underneath is that caring is only safe when it is matched, so the withdrawal is made instant and total rather than risking a second disappointment. Other people experience it as a light going out with no explanation offered to them at any point. What it costs is repair, because a relationship that could have survived one clumsy moment does not survive your absolute departure from it.",
    "invitation": "The distance between someone learning to feel and someone who has mastered feeling was always the illusion doing the work, and here it has closed. Whatever moves through this heart simply moves correctly, the way water moves downhill. This is warmth with the performer fully absent from it."
  },
  "17": {
    "gift": "You read the turn in somebody’s mood before their own face has caught up with it. When somebody is agitated, you notice which way it will break, toward tears or blame or a long silence, and adjust yourself without ever announcing the forecast. Most people respond to the emotion directly in front of them, while you respond to the one arriving in ten minutes, which is why situations de-escalate around you so reliably. That anticipation is not a party trick at all, and you underrate it because it happens far too quickly in you to feel like thinking.",
    "shadow": "Opinion is what the sight becomes when it stops being willing to wait. Somebody begins describing a hurt and the diagnosis is already delivered before they have finished, accurate and unwanted and received as being overruled in their own story. The fear underneath is that not knowing leaves you at a disadvantage in your own life, so certainty arrives early and then gets defended hard. In heated moments you correct people about their own feelings, which is the fastest known way to lose them entirely. The cost is that your genuine foresight stops being believed, because for years it has been indistinguishable from your reflexive verdicts.",
    "invitation": "This heart senses from a vantage with no blind spot left in it, not because more was learned but because opinion \u2014 the thing that used to require a verdict \u2014 has stopped existing at all. What it feels already accounts for everyone in the room."
  },
  "18": {
    "gift": "You notice exactly what is off in an emotional situation, and the noticing works as service rather than as fault-finding. When someone says they are fine and plainly are not, you name it with enough care that they can admit it instead of defending themselves. Most people either miss the discrepancy entirely or point at it clumsily, while you manage both parts at once, the accuracy and the timing. That is a rare pairing indeed, and it is why the people around you get to fix things early rather than long after the damage has been done.",
    "shadow": "Judgement turns on the closest people, because they are the ones you look at for longest. A small emotional failing in someone you love catches your eye, and returning to it becomes compulsive, correcting and mentioning and filing it away as evidence for later. The fear underneath is that anything imperfect left unnamed will grow until it eventually hurts you. So affection gets audited, and the people being audited become careful with you rather than close to you. Turned inward, the same eye goes over your own reactions until nothing you feel seems acceptable enough to show, and you go quiet in the moments you most want contact.",
    "invitation": "Nothing here needs correcting anymore, because the part of the heart that used to judge has gone quiet. Every so-called flaw in another person was already exactly what the encounter required. What remains cannot be improved, only witnessed."
  },
  "19": {
    "gift": "You sense need before it is spoken, and before the person carrying it has admitted to themselves that they have it. When somebody walks in holding something heavy, your whole system registers it and you adjust the room without ever making a show of the adjustment. Most people wait to be told, while your reading of unspoken need is fast enough that people feel cared for without being able to point at what you did. That sensitivity is information rather than anxiety, and the people nearest to you rely on it far more than they ever say aloud.",
    "shadow": "Co-dependence begins as excellent attunement and ends with no boundary anywhere. Another person’s mood becomes your weather, and rest is impossible while they remain unsettled, so managing them gets carried out under the honourable name of loving them. The belief driving all of it is that being needed is the only reliable way to be kept by anyone. So you make yourself indispensable, then resent the dependency you built, then feel guilty about the resentment itself. The cost lands on both sides, because they never learn to carry their own state, and you never discover whether somebody who did not require you would still want you.",
    "invitation": "This heart has stopped protecting its own needs, not from depletion but because there is no longer a separate self whose needs require protecting. What it gives costs nothing, because the giver and the given were never actually two things. This is generosity with no ledger left to balance."
  },
  "20": {
    "gift": "You land in a difficult moment whole, with nothing of you left behind in the room you just walked out of. When somebody is falling apart, your attention is undivided, and they can feel that fact before you have said a single word to them. Most comfort is delivered by people who are half elsewhere, while yours is not, and the difference registers in the other person’s body within seconds. You assume this is perfectly ordinary attention, and it simply is not; it remains the single most valuable thing you bring to anybody’s worst hour of the year.",
    "shadow": "Superficiality is the reflex whenever a moment asks for more than you want to give it. The right words come out at the right volume, none of it costs anything, and the other person leaves technically comforted and privately alone with the whole thing. Underneath sits a fear that full contact with somebody’s pain would take something from you that does not come back afterwards. So exchanges get skimmed and kept moving, and the frequency of contact gets mistaken for the depth of it. The cost accumulates quietly: a wide circle of people who like you, and not one who would call at three in the morning.",
    "invitation": "Every response here is made entirely in the current instant, with no history dragging behind it and no plan running ahead. It arrives complete, the way a note arrives complete the moment it is struck. Nothing in this heart is preparing for anything else."
  },
  "21": {
    "gift": "You stand in front of other people’s fear rather than behind it, and you do it without any dramatics attached. When a situation turns frightening, you take the weight and make the decision, and everybody present breathes out at roughly the same moment. Most people’s courage arrives once the danger has passed, while yours arrives during it, which is a nervous-system difference rather than a moral achievement. That is why people who never ask anyone for anything end up asking you anyway: responsibility gets taken without anybody being made to feel small for having needed it.",
    "shadow": "Control tightens precisely when feeling threatens to take over the room. Somebody’s grief becomes a thing to be handled, with timelines set and decisions made on their behalf, and your care arrives sounding much like instruction. The fear behind that grip is that letting go of the reins invites something you would not recover from. So you take charge of moments that only ever wanted your company, and the people involved end up feeling commanded rather than accompanied. The deeper cost is that nobody ever gets to look after you, because you have never once been in the room without a job to do.",
    "invitation": "Nothing here needs defending anymore, because there is nothing left that could threaten it. Every feeling is simply met, cleanly, with the full weight of an open heart and no residue of needing anyone's approval. Courage has dissolved into something closer to gravity."
  },
  "22": {
    "gift": "You keep your manners when the emotional temperature spikes, and it changes what the other person is able to say next. When somebody is furious at you, courtesy holds without turning cold, which very few people manage while under direct attack. Most people match whatever register they are handed, while you offer something better, and the exchange gets a chance to become an actual conversation. That composure under real pressure is not politeness at all; it is the specific thing that lets another person climb down from their anger without being humiliated in front of anyone.",
    "shadow": "Dishonour is what shame does when a feeling grows too big to carry gracefully. A moment overwhelms you and the behaviour that follows does not match who you are, cutting or seductive or wildly disproportionate, and then months go into managing the memory of it. The belief underneath is that your emotional intensity is fundamentally disgraceful and has to be kept permanently out of sight. So you either over-control until you are charming and unreachable, or spill everywhere at once and withdraw in embarrassment afterwards. What it costs is the middle range, where feeling can be strong and still dignified, and where most real intimacy actually happens.",
    "invitation": "Every last trace of self-consciousness has gone from how this heart moves through a room. Feeling arrives the way weather arrives \u2014 without asking whether it is welcome, and welcomed anyway. Nothing here was ever trying to be graceful; it simply no longer knows another way to move."
  },
  "23": {
    "gift": "You simplify a badly tangled emotional situation down to the single short sentence that actually matters inside it. When someone has been circling the same hurt for an hour, you say the one true thing and the circling stops almost at once. Most people add more context and comparison and reassurance, while you subtract instead, and subtraction is exactly what an overwhelmed person genuinely needs in that moment. That instinct for the essential is never bluntness in disguise, and the people who receive it from you consistently describe the experience afterwards as relief rather than as correction.",
    "shadow": "Complexity is where the simple thing hides whenever saying it feels dangerous. You know the one sentence and offer six instead, cushioned and qualified, and the other person leaves the conversation with nothing usable in their hands. Or the reverse happens, and the essential truth gets delivered at the wrong hour with no warmth around it, landing as an assault rather than a gift. Underneath both is real uncertainty about whether your directness is welcome anywhere, so the timing goes wrong in both directions. The cost is identical either way, since you carry accurate perceptions about people you love and never get them across.",
    "invitation": "Feeling here has been reduced to the one true thing that was always underneath all the rest. Everything unnecessary has already fallen away, not through editing but through a clarity so total that complexity never had anywhere left to hide. What remains is the whole of it, in almost nothing."
  },
  "24": {
    "gift": "You return to the same feeling until it finally yields something new, and that returning takes a kind of courage. Where others distract themselves out of a difficult emotion, you go back in, not compulsively, but because the fourth pass says something the first three did not. Most people treat a recurring feeling as a malfunction to be silenced, while you treat it as unfinished, and that produces genuinely original understanding of your own life. It is also why you sit easily with somebody stuck on a loop without any urge at all to hurry them off it.",
    "shadow": "Addiction is the same returning with the exit quietly removed. A feeling arrives and, rather than passing through, it gets rerun: the argument replayed, the message reread, the ache pressed once more to check that it is still there. Beneath it is a fear that stopping the loop would mean whatever hurt you has finished mattering to anyone. With other people the pattern shows as one story told for years at the same emotional pitch, until the ones who love you begin bracing for it. The cost is the quiet on the far side of the feeling, never reached because you restart just before it arrives.",
    "invitation": "This is a heart with nothing left circling inside it. What moves through arrives whole, the way an answer arrives before the question finishes forming, with no inner static left to filter it through. This is feeling with the one who used to manage it fully out of the way."
  },
  "25": {
    "gift": "You hold somebody’s pain steadily without shrinking away from any part of it, which is rarer than any comforting sentence. When somebody brings you something genuinely unbearable, your heart does not close over; it stays open at exactly the size the situation happens to require. Most people manage their own discomfort first and attend to the other person second, and you reverse that order without any visible effort at all. It is why the badly hurt keep finding you, since you were the one person who never needed their suffering to be tidied or made smaller.",
    "shadow": "Constriction is the reflex to seal shut after a hard hit. Something wounds you and the aperture narrows: same face, same words, but the openness has quietly gone, and the narrowing gets defended afterwards as being sensible now. The conviction underneath is that a heart left open will be injured again in precisely the same place. So you turn selectively cold, generous with strangers and quietly armoured toward the few remaining people who could actually reach you. What it costs is the specific closeness you keep saying you want, kept just out of range by a decision that was made in an old moment.",
    "invitation": "This heart no longer distinguishes what it is willing to hold. Every boundary that used to define where care stopped has quietly stopped mattering. What remains simply holds everything, the way sky holds every kind of weather without preference."
  },
  "26": {
    "gift": "You play difficult emotional moments with a light touch that keeps everybody’s dignity intact on the way through them. When tension builds inside a group, you find the angle, a joke or a redirection or a well-placed question, that lets people out again without anyone losing face. Most people either confront or avoid entirely, and your third option is a real skill that you use far more instinctively than you realise. It is why hard conversations that would have detonated in almost any other company manage to land quietly whenever you happen to be in the room.",
    "shadow": "Pride shows up as the sentence you will not say. Something hurt, and admitting it feels like handing over an advantage, so a version of yourself that was never affected gets presented and the whole exchange gets run from behind it. The fear underneath is that visible need would make you controllable by anybody who noticed. So the same lightness that spares other people becomes a way of never being caught out, and the ones closest to you sense they are being handled rather than known. The cost is that your real state stays private so long that it eventually stops being available to you either.",
    "invitation": "Nothing here carries a signature anymore, not from humility but because there is no longer anyone left who needs credit for having felt it. What moves through this heart simply moves through the world unclaimed, more powerful for having no name attached to defend it."
  },
  "27": {
    "gift": "You reach toward whoever is struggling before any calculation about what it costs or whether they have earned it has even begun. When somebody is depleted, your first movement is straight toward them, and the impulse is genuine rather than dutiful, which people can tell almost immediately. Most people run a quick internal check about cost and reciprocity, and that check does not fire in you, which is why your care arrives faster and lands cleaner. You underrate it because the whole movement feels automatic from the inside, and the people receiving it have rarely encountered anything like it before.",
    "shadow": "Nourishment handed out without limit turns into a ledger nobody ever agreed to keep. Everyone gets fed, and then a quiet score starts running, and you find yourself hurt by people who never knew a debt existed in the first place. The fear beneath it is that stopping would reveal you were only ever wanted for what you provide. The other side is equally costly: in depleted stretches you hoard, refusing small acts that would take nothing, justified by everything you have already given. What it costs is faith in your own generosity, which begins to feel transactional even at the moments when it is entirely real.",
    "invitation": "The separation between the one who gives comfort and the one who receives it has fully collapsed here. Nourishment simply moves through, the way breath moves through a body, needing no accounting on either side. What is felt was never actually anyone's to keep."
  },
  "28": {
    "gift": "You face the darkest feelings without needing a lesson to be attached to them afterwards. When somebody is in real despair, you go all the way in with them rather than throwing a rope from the safety of the edge. Most people accompany distress up to a point and then start reaching for meaning, while you carry no such limit, and they can sense there is no floor below which you leave. That willingness to go the whole way into a feeling is why you get trusted with the things nobody else in their life is ever told.",
    "shadow": "Purposelessness hits as a sudden conviction that none of this matters, usually just after a period of intensity has passed. In that state other people’s feelings look small and theatrical, and either you say so out loud or you go missing and return with no explanation. The fear driving the pattern is that a life without high stakes is not worth being present for, so risk gets chased inside relationships through provoking, gambling, and testing whether anything is real. The cost lands on people who wanted steadiness and received an intensity cycle instead, and on you, because each flat stretch grows darker than the last one.",
    "invitation": "This heart has stopped needing its feelings to outlast anything, because the fear that time was running out \u2014 the thing that once gave every feeling its whole urgency \u2014 has genuinely gone quiet. What arrives is complete in every moment it exists, with nothing riding on how long it lasts."
  },
  "29": {
    "gift": "You commit fully once you are actually in, and the people around you feel the whole of you arrive at once. When somebody needs you through something long and unpleasant, your yes has no reservation inside it and nothing has been kept back for later use. Most support gets offered with a private exit built in, and yours does not, which changes what another person is willing to risk in your company. That total presence in a chosen moment is exactly what you underrate, since you assume everybody else means their yes as completely as you do.",
    "shadow": "Half-heartedness is the yes given to avoid a difficult conversation. Agreement gets made to be there emotionally, and then you arrive at forty percent, resentful and unreachable, and the other person cannot name what is wrong because you technically showed up. The fear underneath is that a genuine no would end the relationship outright, so you spend yourself on things you never actually wanted. The exhaustion that follows gets blamed on whoever you said yes to in the first place. What it costs is the depth you are capable of, spread so thin across obligations that nothing receives the version of you that would have mattered.",
    "invitation": "Whatever this heart gives, it gives without measuring the return, not as a discipline but because the question of return has stopped arising at all. Feeling is offered completely, the way a candle gives its light without keeping any of it back for later."
  },
  "30": {
    "gift": "You burn hot without setting fire to the people standing around you, and that heat is the entire point of you. When something moves you, longing or delight or grief, it comes through at full strength and gives everybody nearby quiet permission to want things again. Most people cool a feeling down before ever letting it out, while yours arrives entirely intact, which is precisely why rooms come alive around you. That intensity is not a problem to be managed down, and the people who love you would not trade it for anything calmer or more convenient.",
    "shadow": "Desire turns from fuel into fire the moment it becomes about the having. A longing catches and the entire emotional system organises around it, the person or the reconciliation or the moment that will finally settle you, and everything else goes thin. The fear underneath is that if the wanting ever stopped there would be nothing left inside you at all. So the heat gets kept going through drama or pursuit or grievance, burning through people who came for warmth and found a furnace. The cost is rapture itself, which requires lightness in order to survive and cannot last when it is demanded on schedule.",
    "invitation": "Every want this heart ever carried has resolved into a single undivided longing that already has what it was reaching for. Feeling here is no longer trying to satisfy anything, because desire itself has burned down to its own source. This is fulfilment with nothing further left to want."
  },
  "31": {
    "gift": "You put words to the thing a room has silently agreed never to mention, and you do it out loud. When a group is politely pretending, your voice names the tension aloud and the whole atmosphere reorganises itself around the truth within moments. Most people wait for a permission that never arrives at all, while you simply go first, and going first costs you something real every single time it happens. That is why people follow your emotional lead in a crisis, not because you sound certain about anything, but because you said the exposed thing while it still mattered.",
    "shadow": "Arrogance is the same voice with the listening taken out. Under pressure you speak with a certainty that has not been earned yet, over people still forming their own feelings, and the whole thing gets called leadership. The fear underneath is that hesitating would reveal you have no better idea than anyone else in the room. So the position gets committed to hard, and whoever disagrees goes quiet rather than argue, which then reads back to you as agreement. The cost is a room that stops telling you anything true, and a widening gap between the confidence in your voice and what you actually know.",
    "invitation": "The one who used to speak has fully dissolved back into what is being said. Warmth still moves through this heart, but with no one standing at the centre of it collecting the credit. What remains is care with nobody left inside wanting to be recognised as its source."
  },
  "32": {
    "gift": "You trace what somebody felt years ago and still treat it as entirely real, which makes people feel held across long stretches of time. When somebody returns years later to an old grief, you have kept it accurately rather than expecting them to be finished with it by now. Most sympathy has a shelf life of a few weeks, and yours does not, which is enormous to anyone carrying something long. That fidelity to what once mattered is quietly one of the most loyal things a person can do for another human being over a lifetime.",
    "shadow": "Failure is the fear that governs how much of yourself ever gets committed. A relationship starts to matter and something in you calculates the odds, withholds the final twenty percent, and then calls that caution wisdom. Sitting underneath all of it is a conviction that being emotionally wrong about somebody again would simply be unsurvivable. So old hurts get preserved as evidence, past wreckage gets replayed in detail, and a defunct disappointment sets the terms of a new person’s welcome. The cost is time, years of relationships conducted at a safe distance, guarded against a failure that already happened and cannot repeat itself in the same form.",
    "invitation": "What this heart holds is held sacred without effort, because reverence has stopped requiring an object separate from the one holding it. Feeling simply preserves itself, the way roots hold soil without being asked. Failure has nowhere left to land, because nothing here is measured against succeeding."
  },
  "33": {
    "gift": "You withdraw after a charged exchange and return with the whole thing sorted, which strikes people who have never needed that gap as coldness. You recall the exact sentence that turned an argument days later, when everyone else has blurred the night into one general bad mood. Most people rerun a conflict on a loop and get nowhere; you set it down, go quiet, and come back with the single line worth saying. That habit of stepping out of the heat gives the people around you room to stop performing a reaction they do not actually feel.",
    "shadow": "Under real pressure the gap gets longer, and the retreat that once digested feeling starts swallowing it instead. Someone raises their voice and you go absent behind your own eyes, present in the room and gone from the exchange, so they end up arguing with a wall. Whole conversations vanish afterwards, so the same hurt arrives again next month with nothing learned and the other person doing the remembering for both of you. Underneath sits an old conviction that feeling something fully will take you under and you will not surface, so you leave early every time. The bill comes due when people stop bringing you anything real, having learned you will not be there when it lands.",
    "invitation": "This heart has stopped needing to remember its own history, because everything that mattered from it is already, continuously, present. What moves through it arrives as disclosure rather than reaction \u2014 not produced, only finally seen. Nothing here was ever actually hidden."
  },
  "34": {
    "gift": "You surge when the temperature in a room rises, and what arrives in you is enormous, steady and strangely calm rather than frantic or scattered. You stand in front of somebody's rage without flinching, which lets them finish saying the thing they have been swallowing for months. Where most people halve themselves in a confrontation and speak from somewhere small, your size stays exactly the same, and that alone settles the room. It has never struck you as unusual to be unfrightened by another person at their worst, and to still be standing there when they finish.",
    "shadow": "Force that meets no resistance keeps going, and yours arrives faster than any judgement about whether it belongs in this particular room. A small slight lands and the response comes out three sizes too big, so the other person goes silent and their silence gets read as agreement. Weeks later they are still handling you carefully, and the conversation that cost them something registered with you as nothing at all. Somewhere underneath is a belief that softening even slightly means losing, that any yielding gets marked down as weakness by whoever happens to be watching. The people who love you learn to time their honesty around your weather, which is a lonelier arrangement than it sounds.",
    "invitation": "Feeling here has nothing left to prove through it. What this heart carries holds its full weight without display, the way a mountain doesn't announce its own size. This is strength that has stopped needing an audience to confirm it."
  },
  "35": {
    "gift": "You venture toward feeling that other people organise their whole lives to avoid, and risk in a room draws you in rather than warning you off. You go first into the awkward conversation, the grief, the unfinished thing, and your appetite for it makes whoever is with you braver simply by contact. Almost everyone waits until they feel safe before opening a difficult subject; you open it hungry, genuinely curious about what is actually in there. That appetite is the reason people tell you things inside twenty minutes that they have not told anyone else in years.",
    "shadow": "Appetite for emotional weather turns into a requirement for it, and a settled relationship starts registering as a room with the air removed. Nothing dramatic has happened for a month, so a fight gets started, a message gets sent, an exit gets rehearsed, all in the name of feeling something again. Whoever loves you experiences that as a verdict on them, and they are never told it was really about the flatness rather than about their failings. Beneath it is a fear that a life without intensity is a life not lived, and that ordinary contentment is a slow form of dying. The cost is a run of endings with nothing actually wrong in them.",
    "invitation": "This heart's hunger has finally consumed its own edges. Nothing further is being chased, because the sense of a next thing worth wanting has quietly dissolved. What remains simply continues, complete in every direction at once."
  },
  "36": {
    "gift": "You wade into other people's crises without needing the water to settle first, and the worse things get the steadier you become. You sit with someone in the middle of the night without trying to fix them, which is a different skill from giving advice and far rarer. Plenty of people offer help that quietly asks the other person to calm down; you ask for nothing back and stay until the storm has moved through. Being near raw human distress without flinching is uncommon, and the people you have done it for never forget who was in the room.",
    "shadow": "Trouble is where you feel most useful, so a settled life starts to feel like something important has gone missing. Calm weeks make you restless, and a small tension gets pressed on until it becomes an event of the kind you know how to handle. Other people's storms are absorbed as your own weather, and by Thursday you are carrying four crises with no idea which of the feelings started out yours. Beneath it runs a quiet belief that you are only wanted in an emergency, that nobody would choose your company on an ordinary Tuesday afternoon. What it costs is exhaustion nobody can account for, and friendships that only ever meet at the worst moment.",
    "invitation": "This heart is built entirely from what turbulence once taught, with none of the original wound left in it to manage. It already knows what crisis feels like from the inside, and holds it without flinching. This is feeling with nothing left needing to be defended."
  },
  "37": {
    "gift": "You thaw people quickly, and those who arrived braced for something formal end up telling you about their family and their divorce. You notice when somebody is being left slightly outside the circle, and you move toward them before anybody else in the room has registered the gap. Nearly everybody waits to be introduced to a feeling; you offer yours first, which is exactly what makes the exchange safe enough for the other person to enter. Your instinct to feed, cover and include is not softness, but the specific competence that keeps groups of humans in one piece.",
    "shadow": "Belonging starts to feel conditional, and the price paid for it is your own preference, handed over quietly, again and again. Someone raises their voice at the table and you agree with them before you have checked whether you actually do. Months of that build a resentment you would never say out loud, and it leaks sideways as sulks, small withdrawals and a martyred kind of helpfulness. Underneath is the old fear that the warmth is the reason you are kept, and that a version of you with needs would be shown the door. The cost is that nobody in your family knows what you want, and by now that includes you.",
    "invitation": "There is no more distance left between this heart and whoever it reaches. What it offers arrives already warm, needing no translation, the way a hand finds another hand in the dark without having to look. Equality has stopped being a principle and become the simple shape of contact."
  },
  "38": {
    "gift": "You outlast the difficult feeling in a room, and the argument nobody else had stamina for is the one you are still inside an hour later. You fight for people who are not present to defend themselves, and you do it without needing them to find out it happened. Others give up on a strained relationship at the second hard conversation; you go back for the fourth, which is why things get repaired around you. Your stamina for conflict is the thing you discount most, and the willingness to stay in it until something true emerges is genuinely rare.",
    "shadow": "Without an opponent the energy has nowhere to go, so a fight gets manufactured out of whatever is nearest and smallest. A partner says something mildly careless and it becomes a two-hour position war neither of you wanted, defended long after you stopped believing in it. Loyalty turns into taking up battles nobody asked you to take, and then feeling wronged when the person defended looks embarrassed rather than grateful. The belief running underneath is that ease has to be earned, and that a life without struggle in it would not count as a life. What it costs is rest, and people who flinch very slightly when you walk in warm.",
    "invitation": "This heart no longer needs an opponent to prove its endurance against. What moves through it simply continues, complete in its own right, with the entire notion of struggle quietly retired. This is strength with nothing left it needs to overcome."
  },
  "39": {
    "gift": "You provoke honest feeling out of people who have been polite for years, and something in your presence makes pretending unusually hard work. You say the sentence everyone was avoiding, and the whole room breathes out, because the tension got named instead of sat inside for another hour. Where others manage an atmosphere by keeping it flat, you push until it moves, and situations that had been stuck for months come unstuck around you. Being the one who breaks the surface is rarer than you think, and people are secretly relieved every time you do it.",
    "shadow": "Reaction becomes the proof of contact, so somebody gets needled until they finally show you something, and the outburst gets counted as intimacy. A quiet evening starts feeling like distance, and within twenty minutes the sore subject has been found and pressed without any decision to press it. People then begin guarding themselves in your company and offering the smooth version, which produces exactly the flatness you were trying to break. Underneath is a fear that a calm room means nobody is really there, and that being loved quietly is the same as being ignored. The cost is that the reactions you provoke become the only closeness on offer.",
    "invitation": "This heart has stopped provoking anyone, because the charge that used to require a reaction from other people has fully discharged. What moves through the room does so cleanly, the way a held breath finally releases. Nothing here needs anyone to notice it happened."
  },
  "40": {
    "gift": "You decline what other people find impossible to decline, and the word no leaves you cleanly, with no paragraph of justification attached to it. You give enormously once you have chosen to, and the giving is wholehearted precisely because it was never extracted from you in the first place. Almost everybody says yes and then resents it for a fortnight; you decline in the moment and keep the relationship intact, which is a much shorter road. Protecting your own reserves without apology is unusual, and the people around you have learned that your yes means something.",
    "shadow": "The refusing arrives too late, after weeks of giving past the line, when there is nothing left to be gracious with. Someone asks for one more small thing and the answer detonates, wildly out of proportion to the request and aimed at entirely the wrong person. Then comes the retreat, days of unreachable silence, while the other side tries to work out what they did and gets it wrong. Running under all of it is the conviction that the only alternative to total generosity is total withdrawal, with nothing available in between. What it costs is the closeness you actually wanted, spent in advance on people who never asked for that much.",
    "invitation": "The exhaustion of carrying feeling alone has completely resolved here. Warmth continues, but without the sense of a separate self doing the lifting. What arrives now comes with the same ease water finds its own level, asking nothing, resisting nothing."
  },
  "41": {
    "gift": "You kindle feeling before there is anything to feel it about, and the anticipation you carry is catching for whoever happens to stand near you. You start emotional weather in a room out of nothing, which is why gatherings tilt toward warmth about ten minutes after you arrive. Almost nobody originates a mood; most people simply react to whichever one is already present, and others find themselves inside yours before noticing where it began. Beginning something real in another person from a standing start, with no cue at all to work from, is far less common than you assume.",
    "shadow": "The imagined version arrives first and it is always richer, so the actual evening turns up looking thin beside it. A conversation gets rehearsed a dozen times before it happens, and when it finally happens you are answering the rehearsal rather than the person in front of you. Disappointment then lands on them as coolness, and they have no idea which script they just failed. Beneath it sits the belief that the feeling you want does not exist out here, so it is safer to manufacture it privately in advance. The cost is a long-running loneliness inside relationships that are, from the outside, entirely available to you.",
    "invitation": "This heart radiates outward before there was ever a reason to. What it offers no longer waits for the right conditions, because it has become the condition itself. This is feeling with the anticipation fully spent \u2014 only the warmth, endlessly renewing."
  },
  "42": {
    "gift": "You accompany people all the way to the end of a thing, including the endings everyone else finds a reason to miss. You sit with grief without hurrying it toward a lesson, which is why the bereaved and the newly abandoned come to you before anyone else. Most people get uncomfortable at the exact point where nothing helps; you stay past that point, doing very little and saying less, and it steadies the whole room enormously. Being present at a finish without trying to make it mean something is a capacity you have never counted as one.",
    "shadow": "Endings are fine in principle and unbearable in practice, so the hand stays closed long after the thing itself has finished. A relationship dies quietly and gets kept on life support, with the expected version replayed nightly instead of the one that actually happened. Grief gets rushed in other people too, so a friend cries and the silver lining is produced before the crying has properly started. Underneath is a fear that letting go completely would leave nothing behind to prove any of it ever happened. The cost is a life crowded with unfinished feeling, and a present moment that never gets your full attention.",
    "invitation": "Every feeling here is released the moment it has run its course, with no attachment left to how it was received. It is let go completely, the way a held note is finally allowed to end. What remains is simply the next feeling, arriving already welcome."
  },
  "43": {
    "gift": "You quieten when other people escalate, and the stillness you drop into is where the real message finally becomes audible to you. You hear what somebody means underneath what they are shouting, and hours later you return with a sentence that reframes the entire thing. Nearly everyone answers at the speed of the provocation; you wait for as long as it takes, and the answer that eventually arrives is worth more than five fast ones. That delay of yours is not slowness but a rare tolerance for not knowing yet, held in the middle of somebody else's urgency.",
    "shadow": "Going inward looks identical to shutting down, and from the outside the silence reads as contempt for whatever was just said. Someone brings their distress and appears to be received by nothing, so they say it again louder, at which point you become even less reachable. Advice offered before you are ready gets dismissed outright, including the accurate kind, which costs you years of shortcuts people handed over freely. Beneath it runs a private certainty that nobody else's understanding is worth as much as your own eventual one. The result is that people stop repeating themselves, and you lose the very input your insight was built to work on.",
    "invitation": "This heart has stopped needing the slow route to understanding, because knowing now arrives whole, ahead of the feeling that would have asked for it. What moves through it carries no residue of the deafness it once had to work around. This is feeling with nothing left in the way of it."
  },
  "44": {
    "gift": "You size somebody up on contact, and within a minute of meeting them you know whether you are safe in their company or not. You read a group's real allegiances long before anyone announces them, which makes you almost impossible to place in a room dishonestly. Plenty of people need two years and a betrayal to learn what your first handshake told you, and your accuracy on this runs unusually high. That instinct is a form of loyalty, because you are sorting early for the handful of people you intend to go the whole distance with.",
    "shadow": "The verdict arrives in seconds and there is no appeal, so a person gets written off over a tone of voice that had nothing to do with you. Someone resembles an old betrayal and they inherit the whole sentence, unaware that they are serving time for another person's crime. Suspicion runs quietly in the background of good relationships, scanning for the moment of proof, and the scanning itself makes a distance the other one can feel. What sits underneath is a belief that everybody turns eventually, so the only safety available is knowing first. The cost is a smaller circle every year, perfectly defended and increasingly empty.",
    "invitation": "This heart is fully woven into everyone else's, with the old suspicion of other people's motives completely resolved. What moves through it no longer needs to manage the room around it, because the separation that made managing necessary has dissolved. This is warmth that governs itself."
  },
  "45": {
    "gift": "You assume responsibility for how a room feels once people are inside it, which is a weight most hosts never notice themselves avoiding. You register who is uncomfortable and adjust the whole evening around them, without announcing it and without expecting anybody in the room to say thank you. Where others attend a gathering, you hold one, and the difference shows up in whether the quietest person there ends up speaking by the end of the night. Being answerable for a group's emotional temperature is rarer than charisma and worth considerably more than it, though nobody hands out credit for it.",
    "shadow": "Responsibility for the room slides into ownership of it, and the group's feelings start needing your approval before they are allowed to exist. Somebody is unhappy at your table and it registers as insubordination rather than information, so their mood gets managed instead of heard. Dissent is absorbed smoothly and generously, and the person still leaves knowing they lost something they cannot quite name. Underneath is the fear that a group you do not steer will drift away from you entirely, and that belonging has to be administered to survive. The cost is a circle of people who are loyal and slightly careful, which is not the same thing as close.",
    "invitation": "Whatever passes through this heart is shared before it was ever finished being felt. Every feeling moves freely between the one holding it and everyone it touches, with no ownership left to negotiate. What remains is simply the feeling, held in common."
  },
  "46": {
    "gift": "You lighten heavy rooms without making anybody's pain smaller, and the timing of it is a genuine skill rather than a personality trait. You find the moment when a family in crisis is able to laugh again, and that laugh does more repair than the previous three hours managed. Most people treat delight as what happens once the serious business is finished; you carry it in with you, and difficult things become survivable. Your knack for pleasure in the middle of hard weather is uncommon, and people leave your company noticeably steadier than they arrived, without quite knowing why.",
    "shadow": "Heaviness gets deflected on arrival, so a friend starts describing something genuinely bad and a joke is out of your mouth before they finish. It works, which is the problem, since the room lifts, the subject moves on, and nobody ever gets to put the hard thing down properly. Your own grief goes the same way, postponed with plans and pleasure until it turns up months later wearing a completely unrelated face. Beneath the lightness is a suspicion that dropping fully into sadness would end with you not coming back up. What it costs is depth, and friends who adore your company without ever once having been comforted by you.",
    "invitation": "This is delight with nothing left holding it back \u2014 a heart that has stopped needing permission to feel good about existing. What moves through it carries the same unguarded joy the body feels for no reason at all. This is aliveness with the entire question of deserving it dropped."
  },
  "47": {
    "gift": "You inhabit low moods without needing them fixed, and you stay down there long enough for something to actually change shape. You are unfrightened by other people's darkness, so the ones who are ashamed of their worst weeks bring them to you unedited, in language they have never used with anybody else. Almost everyone tries to talk somebody out of despair within about four minutes; you sit inside it alongside them, and that by itself is medicine. Keeping company with a bad feeling until it turns is genuinely rare, and you have always assumed everybody could do it.",
    "shadow": "The descent stops being temporary and becomes an identity, and the low place gets defended as though it were the only truth about you. Comfort arrives and is refused, since accepting it would mean the suffering was optional, so the people who came closest get turned away at the door. Old material is rehearsed rather than processed, the same wound in the same words in the same year, with none of it moving anywhere at all. Underneath is a belief that depth requires damage, and that a happier version of you would necessarily be a shallower one. The cost is time, whole seasons spent in a room you were holding the key to.",
    "invitation": "Every old wound in this heart has been fully metabolised into its opposite. What moves through it no longer carries the shape of what it survived \u2014 it has become something the original weight could never have predicted. This is transmutation completed, with nothing left needing to transform."
  },
  "48": {
    "gift": "You improvise comfort with nothing prepared, and whatever you find to say in the moment lands better than any rehearsed condolence would. You stay useful in situations that have no correct response available, which is the exact place where most competent people freeze entirely. Where others need a script before entering somebody's worst news, you go in empty-handed, trusting whatever turns up, and something adequate arrives every single time you do it. That resourcefulness under emotional pressure is the thing you dismiss as making it up, and hardly anybody else in your life does it half as well.",
    "shadow": "The doubt turns up at the worst moment, when somebody needs you and a voice says you are not enough for this, so you hesitate a beat too long. That hesitation gets read as indifference, the person turns to someone less careful and more available, and the whole story confirms itself neatly. Referral becomes the habit, so people are sent to professionals, books and other friends, anyone whose adequacy you trust further than your own. Underneath sits a belief that comfort has a correct form, and that yours would be found wanting if it were ever examined closely. The cost is a lifetime of being the person who could have helped, standing slightly back.",
    "invitation": "This heart has stopped needing to solve for adequacy, because the sense of falling short \u2014 the engine behind so much comforting \u2014 has genuinely gone quiet. What it offers simply already has what it needs, every time, without scrambling for it first."
  },
  "49": {
    "gift": "You sever what has gone bad, and the cut comes out clean rather than cruel, a distinction most people never manage to make. You know months ahead of everyone else that a relationship has finished, and you stop pretending long before the pretending turns expensive. Plenty of people stay inside dead arrangements for years out of politeness; you end them, and everybody involved gets their life back sooner. Your instinct for when something is genuinely over runs unusually true, and it has saved you more years of your life than you have ever sat down and added up.",
    "shadow": "The ending arrives at the speed of the feeling, before the feeling has been checked against anything, and a decade goes over the side in an afternoon. One remark crosses a line and the door shuts permanently, with no route back offered and no explanation given to the person left outside it. Afterwards comes the cold calm of certainty, which is the most convincing sensation in the world and is wrong roughly half the time. Beneath the speed is a fear of being trapped somewhere with no exit, which makes leaving first feel like the only safety on offer. The cost is a history of people who never found out what they did.",
    "invitation": "This heart starts over completely, as many times as required, without carrying forward any residue of what came before. What moves through it now is never a reaction to the last hurt \u2014 it arrives new, entire, unrelated to its own history. This is renewal with nothing left it is reacting against."
  },
  "50": {
    "gift": "You uphold a standard of care in every group you belong to, and people behave better around you without ever being asked to. You feel it immediately when something has gone wrong in a family or a team, long before there is evidence anybody could point at. Nearly everybody notices a broken atmosphere once it has already become a crisis; you catch it at the first wrong note and move early. Carrying responsibility for the emotional health of a group is a form of love, and it almost never gets named as one by the people it protects.",
    "shadow": "The standard hardens into policing, and values that once protected people start being enforced upon them, beginning with the ones who love you most. A relative behaves badly at a wedding and it costs them your warmth for a year, which is a far heavier sentence than the crime deserved. Meanwhile the responsibility never lifts, since every group you enter becomes yours to hold, and nobody offers to take a turn because nobody was ever asked. Underneath is a fear that without you maintaining it, everything decent would quietly rot in place. The cost is a permanent low-grade resentment and a reputation for being slightly hard to be human around.",
    "invitation": "This heart governs itself the way a healthy body governs its own temperature, without any conscious oversight at all. What moves through it simply stays in balance, correcting itself before an imbalance could ever be named. Nothing here has anywhere left to take hold."
  },
  "51": {
    "gift": "You rouse people who have gone numb, and something in your directness snaps a room out of its comfortable half-sleep. You act first in an emergency, before fear has finished arriving, which is why people look toward you when the news is bad. Most people freeze for the crucial thirty seconds; you move, and that gap is the whole difference between a story people tell afterwards and a disaster nobody recovers from. The courage you are running on an ordinary day is invisible to you, and being first without being asked is much rarer than you think.",
    "shadow": "The jolt becomes the method, so people are woken up whether or not they asked for it, and the shock is delivered as though it were a favour. A conversation grows too settled and something disruptive gets dropped into it, followed by an odd satisfaction at the scramble that comes next. Your own agitation is treated as a signal about the world rather than weather in you, so everyone nearby ends up living inside your alarms. Underneath is the belief that stillness is death, and that a life without shocks in it stops being real. What it costs is people who never quite unclench, and friends who brace slightly when your name appears.",
    "invitation": "What moves through this heart arrives the way lightning arrives \u2014 sudden, total, over before it can be resisted \u2014 and yet it has stopped requiring anyone's fear to work. This is aliveness with nothing left of the original agitation."
  },
  "52": {
    "gift": "You absorb heat without passing it on, and pressure that would ricochet through anybody else simply stops when it reaches you and goes no further. You hold your reaction in the second it arrives, which gives everyone else in the room time to find their footing again. Almost everyone discharges tension immediately onto whoever is nearest; you keep it, and that restraint has prevented more damage than you have ever counted. Your presence lowers the temperature of a hard conversation before you have said a word, and people move toward you in a crisis for exactly that reason.",
    "shadow": "Restraint slides into storage, and feeling that never got expressed does not vanish but sits there, quietly hardening into something much less workable. Someone hurts you and nothing shows on the surface, so they carry on doing it, sincerely unaware that anything landed at all. Then a small thing goes wrong on a Tuesday and four months of held material arrives at once, at the wrong person, in entirely the wrong volume. Underneath is a conviction that expressed feeling is dangerous and unattractive, and that holding it is simply what adults are supposed to do. The cost is a backlog of unfinished conversations and people who describe you as calm when you are nothing of the kind.",
    "invitation": "This heart is built from a centre that never actually moves, no matter how much feeling surrounds it. What it holds carries the same unbroken quiet a mountain keeps through every storm that passes over it. Restraint has stopped being effort and simply become what is true."
  },
  "53": {
    "gift": "You meet the start of anything with an openness most adults mislaid somewhere around thirty, and it reads as appetite rather than naivety. You begin things at full emotional volume, and the beginning you generate carries a whole group through its awkward first weeks. Most people hold something back at the start in case it disappoints; you arrive completely, with nothing kept in reserve, and the people you arrive at feel chosen rather than merely met. Your enthusiasm is a resource others borrow from constantly, without ever once noticing where the extra energy in the room came from.",
    "shadow": "Beginnings are easy and the middle is where you go missing, so the person who felt chosen last month is now working out what changed. Enthusiasm makes promises your attention has no intention of keeping, and the drop from that height is the part that actually hurts them. Feedback arrives and lands as an attack rather than information, since the excitement it interrupts feels like the truest thing about you. Beneath it is a fear that slowing down means the aliveness stops, and that maturity is only a longer word for dullness. What it costs is a trail of people who loved the first three weeks and never got the fourth.",
    "invitation": "This heart has run out of ways to stay small, because its own growth has stopped requiring anything to grow toward. What it offers simply keeps expanding on its own accord, the way a seed doesn't decide to become a tree. Nothing here is rushing, and nothing here is finished."
  },
  "54": {
    "gift": "You yearn openly, and the wanting in you works as an engine rather than something embarrassing to be hidden under modesty. You feel the pull toward more life, more depth and more contact, and that pull drags whoever happens to be standing beside you upward as well, whether or not they asked for it. Where most people learn to want quietly and settle early, your appetite stays intact, and your life keeps enlarging while others plateau. That refusal to be satisfied is not greed but the exact fuel that gets people out of situations they were told to accept.",
    "shadow": "The wanting turns into scorekeeping, and whatever somebody gives you gets measured against what was expected rather than received as it is. A friend does well and something sour arrives ahead of the congratulations, uninvited and quickly hidden, leaving a small permanent distance between you. Every arrival feels thin, so the climbing resumes before you have felt anything at all about the place you just reached. Underneath is the belief that you are worth what you have accumulated, and that pausing to enjoy it is the moment it gets taken away. The cost is a life full of arrivals that you were not present for.",
    "invitation": "This heart offers what it holds with no personal gain left attached to it. Warmth rises the way heat rises, without effort, without a destination it is trying to reach. Wanting has fully converted into something that no longer needs a name."
  },
  "55": {
    "gift": "You ride out the enormous emotional systems that move through you, and they pass over without flattening you underneath them. You know a low will pass without anybody having to talk you out of it, which makes you unusually undemanding in a storm. Nearly everyone hands their feelings to whoever is nearest; you keep yours and work them through on your own, so your relationships stay clean of debts nobody agreed to. Owning your own weather is the most freeing thing about you, and it is far less common in the people around you than you have ever assumed.",
    "shadow": "The mood lands and immediately looks for a culprit, usually whoever happened to be standing in the kitchen at the time. Someone answers a message slowly and the whole afternoon goes into building a case against them, complete with evidence and back catalogue. Feelings get treated as verdicts about other people rather than weather passing through, so relationships take damage that had nothing to do with them. Beneath it runs the belief that your emotional state is being done to you, which conveniently means somebody else has to change first. The cost is a life spent waiting for other people to make you feel better, which they have no power to do.",
    "invitation": "The entire question of being owed anything has been permanently resolved here. What this heart feels simply exists, complete in itself, needing no explanation and no permission. This is the one siddhi that is also its own gift \u2014 freedom was never actually elsewhere, only unrecognised."
  },
  "56": {
    "gift": "You taste a feeling the way other people taste food, and pleasure in your company becomes a shared event rather than a private one. You turn an ordinary evening into something people still describe a decade later, mostly through the sheer quality of the attention you pay to whoever is in front of you. Most people are half elsewhere while something good is happening; you are entirely inside it, and everyone at the table registers the difference. Your capacity for full-blooded enjoyment is handed out constantly and almost never counted by you as one of your abilities.",
    "shadow": "Flatness is intolerable, so the moment a feeling levels off, something brighter gets located and the current room quietly loses you. A conversation goes deep and slow and your hand reaches for a phone, a story, a drink, anything with more colour in it than this. People notice being left mid-sentence, and after a while they stop offering the slow material, which is where all the real closeness actually lives. Underneath is a fear of what stillness would let in, and a suspicion that ordinary life without stimulation would be unbearable. The cost is a wide, glittering and curiously lonely life, full of company and short on being known.",
    "invitation": "This heart is so fully alive that no further stimulation is required to feel it. What moves through it carries its own charge, self-generating, the way certain nights don't need an occasion to feel significant. Distraction has nowhere left to pull attention away to."
  },
  "57": {
    "gift": "You detect a change in a room before anything visible has happened, and the shift you pick up gets confirmed almost every time. You know when somebody is not alright while they are still saying they are fine, and you adjust toward them without making a scene. Where others need words before responding to distress, you answer the atmosphere itself, which is why children and animals settle around you long before the adults do. That early warning of yours is not anxiety but fine-grained perception, and you have discounted it as nerves for most of your adult life.",
    "shadow": "The signal never stops arriving, so ordinary rooms fill with warnings and dread becomes impossible to tell apart from information. A partner comes home quiet and within a minute a catastrophe has been constructed and acted upon, which manufactures the very tension you were sensing the absence of. Certainty about what somebody feels gets ahead of asking, and people find themselves accused of moods they were never in. Beneath it sits a belief that being ready for the worst is what prevents it, and that your vigilance keeps everyone safe. The cost is exhaustion, and a habit of trusting the alarm further than the person standing in front of you.",
    "invitation": "Feeling here arrives with nothing left to verify it against. What this heart knows is simply known, immediately, the way a struck bell simply rings. This is unease fully resolved into the very thing it was always trying to become."
  },
  "58": {
    "gift": "You buoy the people around you, and your aliveness raises the level of a room in a way that outlasts your actual presence in it by several hours. You feel exactly where a situation is dragging and put energy at that point, which is why stuck moods lift once you arrive. Most people wait for their mood to improve before generating any; you make yours and hand it out, which is a completely different economy. Much of somebody else's good week came from twenty minutes with you and no advice whatsoever, and you have never counted that as anything.",
    "shadow": "The same sensitivity that finds joy finds fault, and whatever is wrong with a room announces itself well before anything good gets noticed. A partner's small habit becomes unbearable on a Wednesday, and the improvement you suggest lands on them as a verdict rather than an idea. Restlessness dressed as helpfulness turns into a long project of correcting the people nearest you, none of whom applied for the work. Underneath is a belief that satisfaction is dangerous, and that if you stopped adjusting things everything would slide. The cost is that the people you love feel like a job in progress instead of good company.",
    "invitation": "This heart has stopped needing anything to be different in order to feel complete. What moves through it carries the same uncaused wellbeing a body feels in deep rest, whether or not anything outside it changes at all. Dissatisfaction has quietly run out of ground to stand on."
  },
  "59": {
    "gift": "You confide first, and the directness of it gives other people permission to stop performing a version of themselves for you. You go straight at the real subject, so a friendship with you reaches in eighteen months the depth most friendships take a decade to come anywhere near. Almost everybody manages closeness by keeping a few small untruths in circulation; you clear them out, and what remains is unusually solid. Your appetite for being genuinely known, including the parts of you that are not remotely flattering, is far braver than you have ever given yourself credit for.",
    "shadow": "The almost-true sentence gets used to keep things smooth, and each small edit puts another millimetre between you and the person you love. Someone asks how you are and a defensible half-answer comes out automatically, before any decision was made about what to say. Closeness then gets performed with the full technique of the real thing, which fools everybody including you, and leaves you privately unmet. Underneath is the belief that the unedited version would not survive contact, and that being fully seen ends with being left. What it costs is precisely the thing you wanted, which was somebody knowing you and staying anyway.",
    "invitation": "There is no barrier left between what this heart holds and what it shows. What moves through it holds nothing back, not out of confession but because there is genuinely nothing left to conceal. Intimacy has stopped being an act performed for someone and become the plain condition of feeling itself."
  },
  "60": {
    "gift": "You level with people when the news is bad, and the plain sentence you offer is kinder than the reassurance everybody else is producing. You stay steady inside a limit that others are still arguing with, which makes you the one to have nearby in a genuine crisis. Most people meet hard facts with a burst of optimism that helps nobody; you name the constraint, and the room gets its feet back. Refusing to inflate a situation is a form of respect, and people trust you in a crisis because you have never once sold them comfort they could not use.",
    "shadow": "Realism turns into a weapon aimed at hope, and somebody's fragile new plan is met with every reason it will not work. The accuracy is not the problem, the timing is, arriving while they were still gathering the courage to try, which is when it does maximum damage. Your own feeling gets rationed on the same principle, so joy is inspected for exaggeration before it is allowed anywhere near the surface. Underneath is a fear that hoping for more than is reasonable is how people get humiliated, and being right beats being disappointed. The cost is a life that is accurate, contained and quietly smaller than it needed to be.",
    "invitation": "This heart no longer needs a rule imposed on it from outside, because it has become, entirely, its own correct limit. What it offers fits exactly what was required, with nothing wasted and nothing missing. This is feeling with the last trace of restriction gone."
  },
  "61": {
    "gift": "You bear feeling at a size other people ration carefully, and awe, dread and love arrive in you at full volume without breaking anything. You go quiet in the presence of something enormous, and that stillness of yours changes the register for everyone standing nearby. Nearly everybody flinches away from the overwhelming and reaches for a joke; you stay exactly where you are, and what comes through you afterwards is worth every minute of the wait. Your tolerance for feeling far too much is not instability but capacity, and hardly anybody in your life actually has it.",
    "shadow": "The pressure builds with nowhere to put it, and certainty arrives dressed as revelation, which is the most dangerous feeling you own. Something enormous lands and gets taken as a message meant specifically for you, then acted upon in a way that costs a relationship. Ordinary reassurance becomes impossible to accept, since whoever offers it clearly has no idea what you are carrying inside. Beneath the intensity sits a terror of being merely normal, so the flooding is preferred to a settled life that would feel like nothing much. The cost is isolation at precisely the moment you are least able to assess your own state.",
    "invitation": "This heart is touched by something that was never actually separate from it, only unrecognised until now. What moves through it carries an awe that answers questions before the heart finishes asking them. This is longing completed, resting in what it was always reaching for."
  },
  "62": {
    "gift": "You find the exact word for what somebody is going through, and the accuracy of it visibly relieves them on the spot. You separate three tangled emotions inside one conversation and hand them back in order and named, which is why people bring you their confusion before anybody else hears it. Where others offer sympathy in general terms, you get the detail right, and being understood precisely comforts far more than being understood broadly. Your accuracy about inner states is a real skill, and you spend it on other people far more generously than you have ever spent it on yourself.",
    "shadow": "Precision becomes a place to stand outside the feeling, so a description of the emotion gets offered where the emotion itself was wanted. Someone is crying and receives a clarification about what they are actually experiencing, technically correct and completely beside the point. Small inaccuracies in how others describe their own lives get corrected by reflex, and each correction spends a little of the trust that made them speak. Beneath it is the belief that a feeling named exactly enough cannot ambush you, and that language works as a form of protection. What it costs is being met, since nobody feels held by an accurate summary of themselves.",
    "invitation": "Every feeling this heart arrives at has become exactly sufficient \u2014 nothing more, nothing less. What moves through it requires no further precision because precision has stopped being effortful and simply become the shape feeling takes. This is warmth with nothing left to correct."
  },
  "63": {
    "gift": "You question comfort that arrives too easily, and the reassurance everybody else swallows gets held up to the light by you first. You ask the thing in the room that nobody wanted asked, and the honesty that follows is worth ten seconds of general discomfort. Almost everyone accepts an explanation because it settles the atmosphere; you keep going until the answer is actually true, which protects the whole group from a comfort that would have cost them later. Refusing to be soothed by something false is a rare form of loyalty, and the people who understand that trust you completely.",
    "shadow": "The questioning turns inward on affection, so love arriving gets examined for motive rather than received, and the examination is felt by whoever offered it. Somebody says something kind and a fast internal audit begins, asking what they want, what they have missed and how long before they revise it. Tests get set that nobody is ever told about, and when the person fails one, the doubt reports back that it was right all along. Underneath is a belief that being taken in is worse than being alone, so certainty gets chosen over closeness every time. The cost is that good things are disqualified early and you never find out what they were.",
    "invitation": "This heart is built entirely without doubt, not because doubt was defeated but because it completed itself into certainty. What it feels no longer needs proving; it simply stands, the way daylight doesn't need to argue that it has arrived. Longing ends here, not in an answer but in the wanting dissolving."
  },
  "64": {
    "gift": "You tolerate emotional confusion better than almost anyone, holding six unsorted feelings at once without forcing them into a tidy story before their time. You let a mess stay a mess until the picture assembles itself, and what surfaces beats every quick conclusion that was available to you at the start. Most people grab the first available explanation to end the discomfort; you wait it out for days if necessary, and the understanding you eventually reach is worth every hour of the delay. Your patience with your own unresolved state is a strength you have mistaken for slowness your entire life.",
    "shadow": "The swirl arrives all at once and something has to be done about it immediately, so a decision gets made purely to stop the noise. A relationship ends, a message is sent, an apology is offered for a mood you have not understood yet, and none of it fits what was happening. Other people's confusion is intolerable too, so they are handed a neat explanation of themselves which they then go away and believe. Beneath it runs a fear that the not-knowing will never resolve, and that this is simply what your inner life is now. The cost is a run of decisions made under pressure that hindsight cannot make any sense of.",
    "invitation": "This heart is made from a confusion so completely passed through that it turned, on its own, into light. What moves through it no longer needs the picture to make sense first \u2014 feeling arrives already whole, already clear. This is the last key, completing a circle back to the very first freshness it began with."
  }
});
