'use strict';

/**
 * Destiny Matrix — Micro-Content Engine
 * ─────────────────────────────────────
 * Two content layers:
 *
 *  1. nodes["NUM_KEY"]  — position-specific deep reading.
 *     KEY is the NODES[i].key value: A, B, C, D, or E.
 *     Written for the exact psychological lens of each host star.
 *
 *  2. general[NUM]  — universal archetype fallback used when a
 *     position-specific entry doesn't yet exist.
 *
 * API:
 *   DMicroContent.get(arcanaNum, nodeKey)
 *     → { heading, why, shadow, path } or null
 */

window.DMicroContent = (function () {

  // ── POSITION-SPECIFIC DEEP READINGS ──────────────────────────────────────
  // Keys: arcana number + "_" + node key  (e.g. "8_A", "5_B")

  const nodes = {

    // ── 8 in CORE CHARACTER (A · Left / Day of Birth) ──────────────────────
    '8_A': {
      heading: 'The Character Calibrated by Cause and Effect',
      why: `The number 8 sitting in your Core Character position — the Day of Birth, the persona you project before you say a word — means you arrived already wired for Justice. Not justice as courtroom or punishment, but as the deep, cellular reading of cause and effect: an instinct for what is fair, what is owed, what is out of balance in a room. People feel it in you before they can name it — a certain moral gravity, a sense that you are quietly keeping an internal ledger of what is true. This is the psychological portrait you were born wearing: measured, observant, reluctant to be swept along by what everyone else has simply agreed to believe. As a child you were likely the one who noticed the inconsistency, who felt the injustice of a situation in your body, who could not let a broken promise pass without something in you registering it. The gift is real — emotional steadiness, an honesty others come to rely on, and an intuitive grasp that every action sets something in motion that eventually returns.`,
      shadow: `The shadow of Justice in the Character position is the tilt from discernment into judgment. The same faculty that reads imbalance so accurately can curdle into a permanent verdict-making machine — measuring everyone, including yourself, against a standard no living person consistently meets. You can find yourself complaining, quietly or aloud, that the world is unfair, that people do not play by the rules you hold sacred — and the complaint becomes its own cage, keeping you at war with a reality that does not bend to your ledger. But it is worth asking a harder question than "why does this keep happening to me": what internal vibration is this pattern actually mirroring back? A life that repeatedly presents you with broken promises and unpunished unfairness is not simply bad luck arriving from outside — it is, more often, the external echo of an internal state still organized around lack, distrust, or an old unhealed account that has not yet been closed. This can initially feel like an uncomfortable thing to accept, because it removes the comfort of the external scapegoat. There is also the subtler trap of *repeating the very patterns you condemn:* the person so afraid of being treated unjustly that they preemptively withhold, control, or keep score, and so magnetize the exact imbalance they were most trying to avoid. Held in the body, this becomes rigidity — the braced jaw and shoulders of someone perpetually holding the scales level against a world their own frequency keeps recreating.`,
      path: `The evolution of the 8 in Character is to turn the scales inward before you turn them on the world — not to condemn yourself, but to calibrate. This is, admittedly, the harder and less comfortable path: it places the entirety of responsibility for what you keep attracting squarely on your own internal state, eliminating the external factors and individuals your ego would prefer to blame. But that same shift is profoundly empowering, because it means the fairness you are seeking is not something you have to wait on the world to supply. Begin by reviewing where imbalance keeps showing up across your life — money, relationships, work — and treat each recurrence not as evidence against the world but as information about the vibration you are still emitting beneath the surface. True Justice is not the accumulation of verdicts against people who have wronged you; it is the restoration of balance within, and that restoration is what finally changes what you draw toward you. Your character was built to hold truth. The mastery is learning to hold it *warmly* enough that your own frequency stops calling in what it once needed to prove.`,
      positive: `Your external world genuinely reflects your internal ledger: fairness comes easily to you because your own frequency is calibrated in integrity, and people, deals, and circumstances that honor that integrity are what you consistently draw toward yourself.`,
      negative: `Repeated encounters with unfair people and broken agreements are not simply bad luck — they are being drawn toward you by an unresolved internal account, a vibration still braced for injustice that keeps recreating the very imbalance it is trying to avoid.`,
    },

    // ── 5 in SKY LINE (B · Top / Spiritual Potential / Divine Talents) ─────
    '5_B': {
      heading: 'The Channel to Higher Order',
      why: `The 5th Arcana at the top of your matrix — the Sky Line, the seat of spiritual potential and divine talent — carries the frequency of the Hierophant: keeper of sacred law and bridge between higher order and lived life. This is the highest, most vertical point of your chart, the place where you reach *upward* — and it means your spiritual gift is one of transmission. You were born with an instinct for the codes beneath things: the sense that beyond the visible rules of the world there is a deeper order, a lineage of meaning, a structure to existence that can be learned, honored, and passed on. Many people search their whole lives for a framework that makes the cosmos legible; you arrived already suspecting one exists. That is what "divine talent" means here — not that you were handed easy faith, but that you carry an aptitude for wisdom itself: for study that becomes devotion, for turning hard-won understanding into something you can hand to another person intact.`,
      shadow: `The shadow of the Hierophant on the Sky Line is the moment living spirit hardens into rigid doctrine. The same reverence that lets you honor sacred structure can collapse into dogma — the conviction that there is one right way to reach the heights, and that deviation is not merely different but *wrong.* But it is worth noticing what this rigidity is actually doing at the level of vibration: a closed channel does not just fail to teach well, it fails to receive well, and a life that keeps delivering rooms full of people who resist your wisdom rather than absorb it is often a mirror of a frequency that has already decided it knows, and is no longer genuinely open to being met. You may find yourself lecturing where you meant to teach, defending a tradition rather than transmitting its living core, or seeking spiritual authority as a *position* to occupy rather than a service to perform. When the Sky Line closes this way, the channel narrows — spiritual potential becomes spiritual performance, and the world you attract narrows along with it.`,
      path: `The integrated 5 on the Sky Line becomes the rarest kind of teacher: the one who holds the codes lightly enough to let them evolve, and who celebrates the moment a student sees further than they did. Your spiritual work is to keep the channel *open* — to treat every framework, however sacred, as a living transmission rather than a finished monument. This is uncomfortable precisely because it removes the safety of certainty: it is far easier to defend a fixed doctrine than to keep asking what wants to be revised. But an open channel is also what determines what flows back to you — the teachers, students, and opportunities that arrive in your life are responding to the frequency of your own openness, not to the size of what you already know. The divine talent of this position reaches full voltage not when you have mastered the law, but when you become a clear conduit for it — turning higher order into something others can actually climb, and something that keeps climbing back toward you.`,
      positive: `Your channel stays genuinely open, and the wisdom, teachers, and students who reach you reflect that openness back — real transmission arriving in both directions rather than a monologue performed at a closed room.`,
      negative: `A frequency that has already decided it knows keeps attracting rooms that resist rather than receive — the same defensiveness that hardens your teaching into dogma is what narrows the doors that open to you.`,
    },

    // ── 4 in EARTH LINE (C · Right / Material & Money / Year of Birth) ─────
    '4_C': {
      heading: 'The Architecture of Your Material World',
      why: `The 4th Arcana on your Earth Line — the right axis of the matrix, the seat of material and financial potential, encoded from your year of birth — is one of the most grounding energies in the entire system. The Emperor here speaks of a capacity to *build:* to bring order to the physical world, to raise structures that hold weight, to convert vision into something durable that generates real security. This is the frequency of the sovereign and the architect. Wherever the Emperor governs your material line, you carry an inbuilt understanding that wealth and stability are not luck — they are constructed, through discipline and the willingness to take responsibility for an outcome. You can hold a plan across time. You can stay with the unglamorous, foundational work that most people abandon. And there is a quiet authority in you around money and resources — a sense that you are meant to be the one who builds the container, not the one who waits inside someone else's.`,
      shadow: `The shadow of the Emperor on the Earth Line is structure that has forgotten what it was built to serve. It can appear as financial stagnation dressed up as caution — an unwillingness to risk, expand, or dismantle a system that technically works but no longer grows. It can appear as rigidity: gripping resources so tightly that nothing new can flow in, mistaking the accumulation of order for genuine prosperity. Money that will not move is not being protected — it is being told, at the level of vibration, that there is not enough of it to risk, and that exact frequency of scarcity is what a gripping hand keeps drawing back toward itself. And it can appear as its inverse — a resistance to authority itself, a reluctance to be the one in charge that leaves your material potential unbuilt, waiting on someone else's structure to arrive and rescue it. The Emperor in shadow confuses the walls with the kingdom, defending a fortress when what is needed is a renovation.`,
      path: `Your material liberation is not to tear the structure down but to become its conscious architect — to build with sovereignty rather than fear. This requires accepting the less comfortable half of the equation first: your current financial reality is not an accident happening to you, it is the structure your own beliefs about money have been quietly building all along. Begin with an honest audit of your foundations: which financial and practical structures genuinely protect what matters, and which have quietly become prison walls maintained out of habit? Real authority over your material world does not need to grip; it can afford to be generous, flexible, expansive, because it trusts its own capacity to rebuild — and that trust, more than any single strategy, is what a healthy relationship to wealth is actually built from. You were born able to construct security from the ground up. The mastery is building something strong enough to stay open, because an open structure is what abundance can actually move through.`,
      positive: `You build real, durable security from a genuine trust in your own capacity — money and resources move toward you because your relationship to them is generous and open rather than gripped, so the flow keeps replenishing itself.`,
      negative: `Resources get held so tightly nothing new can enter, and that scarcity-braced grip is exactly the frequency that keeps material stagnation in place — the fortress you're defending is the same structure keeping real abundance out.`,
    },

    // ── 17 in KARMIC TAIL (D · Bottom / Past-Life Lessons / Core Karma) ───
    '17_D': {
      heading: 'The Light You Learned to Hide',
      why: `The 17th Arcana at the base of your matrix — the Karmic Tail, the seat of past-life lessons and the deepest inherited work of the soul — is a profound and delicate placement. The Star here means the lesson you carried into this life circles around *visibility and light:* the capacity to shine, to be seen, to offer hope and creative brilliance to the world. The Karmic Tail is the one position in the matrix that arrives locked in its shadow — it marks not a gift you were handed, but a debt the soul came to repay. And the debt of the Star is the debt of dimmed light: a past pattern of talent hidden, brilliance traded away for safety, a radiance possessed but never fully offered. You may feel this as a strange, wordless conviction that you are meant for something luminous, running alongside an equally strong instinct to shrink from exactly that exposure. Both are true. Both come from the same place.`,
      shadow: `The shadow of the Star in the Karmic Tail is the quiet, structural belief that your light is dangerous — to you or to others — and is safer kept low. It surfaces as impostor feeling that arrives precisely when recognition is near; as a talent left deliberately underdeveloped so it can never be judged; as the tendency to pour your vision into everyone else's potential while withholding it from your own. This is worth naming plainly: a life that keeps offering visibility and then watches you decline it is not choosing that pattern for you — you are the one broadcasting, beneath conscious awareness, that being seen is unsafe, and the world is simply responding to the frequency you are actually emitting rather than the one you say you want. Because this is karmic rather than merely personal, it can feel less like a choice and more like gravity — a repeating pull back toward obscurity every time you approach the edge of being truly seen. Left unexamined, the Star's tail becomes a life spent orbiting a stage you never step onto, mistaking the fear of your own brightness for humility.`,
      path: `The work of this position is redemptive by design — the Karmic Tail is the one place the matrix explicitly asks you to move an energy *out* of its shadow and into its light, and in doing so, to complete something older than this lifetime. For the Star, that means the deliberate, uncomfortable practice of letting yourself be seen *before* you feel ready: sharing the work, occupying the visibility, allowing your light to land on other people even though every karmic instinct says to dim it. This is not a matter of waiting for the world to finally offer you a stage — the world will keep matching whatever frequency you are actually emitting, which means the visibility you want has to be broadcast internally before it can arrive externally. You do not have to manufacture brilliance — it is already yours, and always was. You only have to stop hiding it. Each time you choose to be visible where you would once have vanished, you pay down the debt, change the frequency, and reclaim the exact gift you came here to finally give.`,
      positive: `You broadcast a genuine willingness to be seen, and the world responds in kind — recognition, opportunity, and audience arrive because your own frequency has stopped signaling that your light is unsafe.`,
      negative: `A frequency still broadcasting that visibility is dangerous keeps drawing situations that let you stay hidden — opportunities to be seen arrive and then get quietly declined, matching the very signal you're actually emitting.`,
    },

    // ── 7 in SOUL CENTER (E · Center / Comfort Zone / Foundation of Purpose) ──
    '7_E': {
      heading: 'Born to Navigate, Learning to Trust the Current',
      why: `The 7th Arcana at the absolute centre of your matrix — in the Soul Purpose position — is one of the most demanding and most liberating placements available in this system. The Chariot at the centre does not mean you are here to arrive at a fixed destination. It means your fundamental life current *is navigation itself.* You are here to master the art of movement: not speed necessarily, not achievement in the conventional sense, but the sustained, disciplined, internally generated capacity to keep going in a chosen direction regardless of the conditions that arise. This is both an enormous gift and an enormous pressure, because a 7 at centre often experiences stillness as failure before they learn to recognise it as preparation. Your soul carries what might be described as a built-in compass — an internal sense of where true north is that operates even when the maps you have been given by other people point elsewhere. The lifelong work is learning to trust that compass over the noise of external instruction.`,
      shadow: `The deepest shadow of the 7 in the Soul Purpose position is the belief — rarely examined and therefore rarely challenged — that you must figure everything out alone. The Chariot is a solitary image: powerful, contained, masterful. And this image can become, over time, a very elegant prison. You have likely developed an extraordinary capacity for self-sufficiency that, looked at with genuine honesty, is also an extraordinary capacity for a particular kind of loneliness — the loneliness of the person who has learned that asking for help creates more complexity than it resolves. It is worth noticing that a life which keeps delivering unreliable help, or help that arrives too late to matter, is not simply proof that people cannot be trusted — it is frequently the world matching a frequency that has already decided, long before anyone actually failed you, that receiving is not safe. The result, in adult life, is a controlled and mostly invisible isolation. You may not experience yourself as lonely. You may experience yourself as simply *efficient.* But efficiency in the domain of the soul is not a virtue — it is a coping mechanism that has outlasted its usefulness, and it is quietly emitting the very signal that keeps genuine support at arm's length.`,
      path: `The liberated 7 in the Soul Purpose discovers, usually through a moment of crisis that temporarily overrides the self-sufficiency strategy, that the Chariot was never designed to be driven by one person. By its ancient nature, a chariot requires a driver, horses, and terrain — a collaboration between directed will, vital energy, and the actual world as it is. Your path forward is the active, uncomfortable, deeply counter-instinctive practice of receiving: receiving help without immediately improving upon it, receiving love without cataloguing its imprecision, receiving the intelligence of people who see you differently than you see yourself. This is the harder truth to accept, because it removes the comfort of "people just aren't reliable" and places the responsibility on the frequency you are emitting — but it is also the empowering half of the same fact: change what you are willing to receive, and what shows up to meet you changes with it. The soul purpose of the 7 is movement, and the movement with the most genuine consequence right now is the inward one, toward trust, toward the recognition that your compass is reliable enough that you can occasionally let someone else read it alongside you.`,
      positive: `You move with a steady, self-generated sense of direction and a genuine openness to receiving support along the way — and because that openness is real, capable people and real help consistently show up to meet it.`,
      negative: `A frequency that has already decided receiving isn't safe keeps attracting help that is unreliable, late, or absent — confirming the very belief that self-sufficiency is the only option, and deepening the isolation it was meant to protect against.`,
    },

    // ── 5 in RELATIONSHIP (Love channel — Ideal Partner / Relationship Harmony) ──
    '5_LOVE': {
      heading: 'The Partner You Are Still Waiting to Be Taught By',
      why: `The 5th Arcana sitting in your Relationship channel means the frequency governing your intimate life is the Hierophant: the seeker and keeper of codes, of earned structure, of the difference between a connection that has been tested against real standards and one that simply feels good in the moment. This is not a cold or transactional placement — it means you fall in love with substance. You are drawn to partners who carry some kind of depth, tradition, or hard-won knowledge, and you offer, in return, a rare and genuine reverence: the capacity to actually study another person, to learn the specific architecture of how they work, and to honor what it took them to become who they are. Relationship, for you, is one of the primary places you expect to be taught something true about how life actually operates.`,
      shadow: `The shadow of the 5 in Relationship is love organized around an unspoken exam. You can find yourself measuring a partner against a standard of what a relationship is "supposed" to look like — inherited from family, from culture, from an idealized version of commitment — and quietly withholding full arrival into the relationship until it passes. The subtler trap is treating the partner as a student rather than an equal: correcting, instructing, holding the position of the one who knows how this is done. And because the 5 respects earned authority, you can also find yourself deferring to a partner's confidence or credentials over your own instincts about what is actually happening between you, mistaking their certainty for correctness. A relationship that keeps handing you partners who feel like they're auditioning, or who audition you, is mirroring a frequency that has not yet let intimacy be safe without a passing grade.`,
      path: `The integration of the 5 in Relationship is letting the partnership itself become the sacred text, rather than measuring it against one you inherited elsewhere. This is the harder, more exposing shift: it means releasing the comfort of an external rulebook and trusting what is actually true between the two of you, even when it doesn't match the tradition you were handed. Practice offering your reverence and attention without requiring the relationship to first prove its worthiness — the standard that matters is the one built together, not the one applied in advance. Once love stops being graded, it becomes available to actually teach you something no book ever could.`,
      positive: `You bring real depth, respect, and earned trust into partnership — a relationship that functions like living wisdom, each of you genuinely teaching the other rather than performing for a standard.`,
      negative: `Love stays organized around an unspoken exam — partners keep arriving who feel like they're auditioning, or who put you through one, because intimacy hasn't yet been permitted to exist without first passing.`,
    },

    // ── 17 in MONEY (Wealth Potential / Ideal Profession channel) ──────────
    '17_MON': {
      heading: 'The Wealth That Waits on Permission to Shine',
      why: `The 17th Arcana in your Money channel ties your financial flow directly to the frequency of hope and authentic radiance rather than to grinding, joyless effort. The Star governing this position means your most abundant income is available precisely when you are operating from genuine visibility — sharing your real gift, letting your actual light be seen in your work — rather than from a strategy borrowed from someone else's idea of what a stable career looks like. This is one of the more luminous financial placements in the matrix: money that arrives almost as a byproduct of authenticity, once the authenticity is actually offered rather than rehearsed in private.`,
      shadow: `The shadow of the 17 in Money is income that stays conditional on external validation before it's allowed to flow — a launch delayed until every condition feels perfect, a rate quietly undercut because charging full price for something so personal feels like an imposition, a body of work kept private until it's "ready" in a way that never quite arrives. Because the Star's gift is genuine, its withholding is expensive: the financial cost of the 5-17-12-style pattern is not laziness, it's brilliance still waiting for permission. A bank account that keeps running sporadic and thin is often mirroring a light that is still being kept low rather than freely offered to the market that would gladly pay for it.`,
      path: `The integration of the 17 in Money is treating visibility itself as the transaction — letting the work be seen at the stage it's actually in, rather than the stage you wish it had reached. This is uncomfortable because it removes the comfort of the private, perfecting phase and places the responsibility on the frequency of what you're willing to show right now. Begin with the smallest real offer: a rate that reflects the work's actual value, a piece of work released before it feels fully polished. The financial flow you're waiting to feel ready for is, in this position, directly downstream of the visibility you're willing to permit today.`,
      positive: `Money arrives in rhythm with genuine visibility — the more authentically you let your work be seen at the stage it's actually in, the more consistently and generously it gets paid for.`,
      negative: `Income stays sporadic and undervalued, mirroring a light that's still being kept low — a launch delayed, a rate undercut, a body of work withheld until conditions that never quite arrive.`,
    },

    // ── 13 in PATERNAL SPIRITUAL (Ancestral Square, Age-10 anchor) ──────────
    '13_F': {
      heading: 'The Inheritance That Had to End Before It Could Be Yours',
      why: `The 13th Arcana in your Paternal Spiritual corner means the belief system, worldview, or spiritual inheritance passed down through your father's line was never meant to be received intact — it was meant to be transformed. Transformation here, on the ancestral diagonal, is a generational instruction: something in the paternal spiritual lineage — a rigid faith, an unspoken code about how a man is supposed to relate to meaning, a belief about what is and isn't permitted to be questioned — reached the end of its natural life inside you specifically so it could be rebuilt into something that actually fits the person you became. You did not inherit a finished structure. You inherited raw material and a mandate to remake it.`,
      shadow: `The shadow of the 13 in this corner is treating the paternal inheritance as something to either swallow whole or reject entirely, rather than metabolize. Swallowed whole, it becomes belief you never actually examined, quietly running your life from behind the curtain. Rejected entirely, it becomes an equally unexamined reaction — defining yourself by opposition to your father's worldview rather than by an actual position of your own. Both are forms of the same avoidance: refusing the harder work of transformation, which requires taking what was given, letting the parts that no longer serve genuinely die, and consciously choosing what to keep. A life that keeps circling the same unresolved question about faith, authority, or meaning — arriving in new disguises but never actually settling — is the paternal line's spiritual inheritance still waiting for its necessary ending.`,
      path: `The integration of the 13 in the Paternal Spiritual corner is a conscious inheritance audit: naming, specifically, what belief or worldview arrived through your father's line, and asking honestly what part of it is genuinely yours and what part you have simply never gotten around to examining. This isn't a betrayal of your father — the 13 is not asking you to reject him, it's asking you to complete a transformation that was likely his to do as well and may not have finished. What survives the audit becomes real conviction rather than inherited furniture. What doesn't survive gets to be released with respect rather than resentment — and the spiritual restlessness that has followed you finally has somewhere to land.`,
      positive: `You've done the work of separating your father's inherited worldview from your own genuine conviction — what you carry spiritually from that line is now consciously chosen, not simply installed.`,
      negative: `An unexamined paternal belief still runs quietly in the background — either swallowed whole as unquestioned truth or rejected wholesale as pure reaction, with the same restless spiritual question resurfacing in new disguises.`,
    },

    // ── 9 in MATERNAL SPIRITUAL (Ancestral Square, Age-30 anchor) ───────────
    '9_G': {
      heading: 'The Silence You Learned Before You Learned Words',
      why: `The 9th Arcana in your Maternal Spiritual corner means the spiritual inheritance passed down through your mother's line arrived primarily through silence rather than instruction — an inward, private relationship to meaning, faith, or inner knowing that was modeled more than taught. The Hermit's gift here is real: you likely carry an inherited capacity for genuine solitary depth, an ability to sit with the unanswerable that many people never develop. But because it arrived wordlessly, you may also have inherited the assumption that the deepest spiritual matters are not things you discuss — that the correct response to the sacred is to go quiet and go inward, the way the maternal line did before you.`,
      shadow: `The shadow of the 9 in this corner is a spiritual life that stays entirely private by default, not because privacy was chosen but because the maternal lineage never modeled another option. This can show up as genuine wisdom that never gets offered to the people who could use it, or as a quiet, generational loneliness — women in your line who each carried real inner depth alone, never quite realizing others around them were carrying something similar in the same silence. A pattern of feeling spiritually or emotionally unseen by the people closest to you, generation after generation, is less a personal failing than an inherited transmission that was never given the chance to become spoken.`,
      path: `The integration of the 9 in the Maternal Spiritual corner is honoring the depth of what was passed down while consciously choosing to give it a voice the previous generations may not have had access to. This doesn't mean abandoning the inward orientation — the solitary depth is a genuine gift — it means occasionally bringing what you find there back out into relationship, breaking a silence that was inherited rather than chosen. Each time you speak the maternal line's quiet wisdom aloud, you complete a transmission that was waiting, for at least one generation, to finally be received.`,
      positive: `You carry the maternal line's genuine capacity for depth and inner knowing, and you've learned to voice it — sharing what was historically kept silent, so the wisdom actually reaches people instead of staying inherited-but-unspoken.`,
      negative: `A default, inherited silence keeps real depth from ever being offered — the same quiet, generational loneliness repeating itself because going inward was modeled, and speaking outward never was.`,
    },

    // ── 21 in PATERNAL MATERIAL (Ancestral Square, Age-50 anchor) ───────────
    '21_H': {
      heading: "The Completion Your Father's Line Was Still Building Toward",
      why: `The 21st Arcana in your Paternal Material corner means the material legacy from your father's line — how to build, provide, and arrive at a durable, complete result in the physical world — was oriented toward genuine mastery, not just survival. The World in this corner suggests a paternal lineage that was, at some level, working toward full arrival: a finished house, a business brought to maturity, a life's work rounded into something whole. Whether or not any individual in that line actually reached full completion, the orientation itself — build toward whole, not partial — is what arrived in you materially through your father's side.`,
      shadow: `The shadow of the 21 in this corner is an inherited material perfectionism: the sense that nothing counts as truly built until it is completely, unquestionably finished, which can make you reluctant to claim material progress that is real but not yet total. This can also surface as a generational pattern of almost-arrivals — a father's line where the business nearly succeeded, the property was nearly paid off, the plan nearly reached its full form, again and again, one generation handing the nearly-there quality to the next along with the unfinished project itself. Financial life that keeps feeling permanently one stage short of secure is often this inherited orientation toward totality, still waiting for someone in the line to actually let a cycle complete.`,
      path: `The integration of the 21 in the Paternal Material corner is being the one who actually closes a cycle the paternal line kept almost-closing. This means letting material progress count as real before it is total — recognizing a milestone as an actual arrival rather than a waypoint to some further, always-receding finish line. You inherited the orientation toward mastery; the specific gift you can offer the line is completion itself, permission to say a given stage of building is genuinely, currently done.`,
      positive: `You bring real material projects to genuine completion rather than permanent near-arrival — closing cycles your father's line kept almost-closing, and letting milestones count as real before they're total.`,
      negative: `An inherited material perfectionism keeps everything one stage short of finished — the family pattern of the nearly-there business, the nearly-paid-off property, repeating because completion itself was never modeled as achievable.`,
    },

    // ── 7 in MATERNAL MATERIAL (Ancestral Square, Age-70 anchor) ────────────
    '7_I': {
      heading: "The Steering Your Mother's Line Handed You Unfinished",
      why: `The 7th Arcana in your Maternal Material corner means the practical, material navigation skill passed down through your mother's line was one of directed forward motion under difficult conditions — women who kept moving, kept the household or the finances or the family's practical survival on a chosen course, often without the luxury of stopping to ask whether the direction was actually sustainable. The Chariot here is a real inheritance of resourcefulness and material determination. What often comes bundled with it is an equally inherited belief that the only way to keep the material vehicle moving is to drive it entirely alone.`,
      shadow: `The shadow of the 7 in this corner is a material life organized around solo endurance, inherited specifically from the maternal line's practical survival strategy — the assumption that asking for material help, sharing the load of provision, or admitting the current direction isn't working would be a kind of failure the women before you didn't allow themselves either. This can show up as chronic overextension around money and logistics, a reflexive refusal of support even when it's genuinely offered, and a materially exhausting sense that everything practical depends on you alone continuing to steer. A financial or logistical life that feels perpetually solo, even when people are actually available to help, is this maternal navigation pattern still running on the old terrain.`,
      path: `The integration of the 7 in the Maternal Material corner is steering the vehicle your mother's line handed you while actually letting other hands touch the reins. This is a genuine departure from the inherited pattern, not a rejection of it — you keep the real skill of directed, resourceful material movement, but you update the belief that skill requires total solitude. Practically: let one material task — a bill, a decision, a piece of the load — be shared rather than solely carried, and notice that the vehicle keeps moving. The maternal line's resourcefulness was real. The solo-driving belief was circumstance, not law, and you're free to update it.`,
      positive: `You carry your mother's line's real material resourcefulness and directed determination, while letting genuine help actually reach you — the vehicle keeps moving because more than one set of hands is finally on the reins.`,
      negative: `An inherited belief that material survival must be steered entirely alone keeps you chronically overextended — support goes reflexively refused even when it's genuinely available, echoing a pattern that was once circumstance, not law.`,
    },

  }; // end nodes


  // ── GENERAL FALLBACK — ALL 22 ARCANA ─────────────────────────────────────

  const general = {

    1: {
      heading: 'The Magician — Where Intention Meets Reality',
      why: `The 1st Arcana carries the frequency of pure origination: the moment before the moment, where something that did not exist becomes possible. In any position in your matrix, this energy marks a place where you were given — or are still discovering — the capacity to generate reality from attention and intention. The Magician does not wait for conditions to be perfect. The Magician understands, on a level that transcends rational explanation, that the conditions become available in response to the act of beginning.`,
      shadow: `When disconnected from its source, the 1 becomes manipulation: the misuse of the very real power to shape perception and direct attention toward outcomes that serve the ego rather than the genuine unfolding. There is also a pattern of scattered initiation — the Magician who starts brilliantly and then dissipates, moving to the next beginning before the first has taken root, because completion requires a different energy than creation and the 1 has not yet learned to provide it. A life full of starts that never land is not bad timing repeating itself; it is the vibration of "beginning" being emitted over and over without the matching frequency of "sustaining" ever being offered for the world to respond to.`,
      path: `Your work with this energy is to ground the gift. To ask, not just "what can I bring into being?" but "what am I willing to sustain?" The tools on the Magician's table are not decorative — they represent all four elements, all four domains of human life. Mastery comes from integrating them, not from wielding only the ones that feel natural. Once you emit the frequency of genuine follow-through, the collaborators and conditions capable of matching that frequency finally have something to respond to.`,
      positive: `You generate momentum from nothing more than clear intention, and the conditions for success assemble themselves in response to a frequency of genuine follow-through, not just enthusiasm for the start.`,
      negative: `A pattern of brilliant starts that never take root is the world matching the actual frequency being emitted — the energy of beginning, offered again and again, with no matching signal of sustained commitment for reality to respond to.`,
    },

    2: {
      heading: 'The High Priestess — The Wisdom That Does Not Speak First',
      why: `The 2nd Arcana in your matrix marks a position governed by depth, by the intelligence of the interior, and by the cyclical rhythms that cannot be forced into linear logic. The High Priestess knows. The challenge is that she knows in a way that is difficult to translate into the language that the external world rewards — the language of proof, of certainty, of explicit justification. Wherever this energy lives in your matrix, it marks a place where your most reliable guidance is the kind that arrives in stillness.`,
      shadow: `The shadow of the 2 is passivity that wears the costume of wisdom. There is a difference between the genuine receptivity of the High Priestess — which is an active, disciplined orientation — and the passive withdrawal that avoids the discomfort of action by framing it as waiting for clarity. There is also a pattern of using psychic or emotional sensitivity as a kind of privacy screen: perceiving others so clearly that they cannot perceive you in return, which maintains a sense of safety at the cost of genuine connection — and a life that keeps delivering relationships which never quite reach real intimacy is often just matching the actual signal being sent: come close enough to be understood, not close enough to be known.`,
      path: `The integration of the High Priestess is learning to act *from* your knowing, not despite the uncertainty that always accompanies it. She does not wait until the mystery is resolved. She steps forward in the mystery, with the mystery. That is the teaching: that the interior intelligence you carry is not a substitute for engagement with the world but a way of engaging with it that the world genuinely needs — and the more fully you let that knowing be visible rather than private, the more the world begins offering back the depth of connection it was quietly withholding to match your own reserve.`,
      positive: `Your most reliable guidance arrives in stillness, and you act on it visibly enough that the world responds in kind — real depth and understanding meeting you back at the level you were willing to first extend it.`,
      negative: `Perceiving others clearly while staying unreadable yourself keeps genuine intimacy at a careful distance — the relationships that arrive stay shallow because that is precisely the depth your own guardedness has been signaling is safe.`,
    },

    3: {
      heading: 'The Empress — The Creative That Gives From Overflow',
      why: `The 3rd Arcana marks a position in your matrix infused with the frequency of creative abundance — not just artistic creativity, but the generative principle itself: the capacity to bring things into being, to nurture them through stages of development, and to sustain the conditions in which other living things can flourish. The Empress does not create from scarcity. She creates from overflow. And wherever this energy lives in your chart, it marks a place where you are capable of extraordinary generosity — and where you are also learning the difference between giving from genuine abundance and giving to manage the anxiety of needing to be needed.`,
      shadow: `The shadow of the 3 is the codependency of the nurturer: the person whose sense of self is so thoroughly organized around care, around creativity-in-service-of-others, that they lose contact with what they actually want to generate for themselves. There is also a pattern of indulgence — using sensory pleasure or creative output as a buffer against the discomfort of sitting with unprocessed emotion. A life that keeps handing you people and situations that need endless tending is not simply unlucky — it is responding to a frequency that has quietly equated being needed with being loved, and will keep manifesting exactly the dependents required to confirm it.`,
      path: `Your work is to discover what you want to create when the creation is entirely, unapologetically for you. Not for approval. Not for someone's growth. Not to demonstrate your value. Just because it calls to you. That act — creating from pure desire rather than from relational function — is where the Empress energy reaches its full voltage, and it is also what finally changes what you draw toward you: relationships built on genuine mutual generosity rather than one-sided need.`,
      positive: `You create and nurture from genuine overflow, and the relationships that reach you mirror that abundance back — connection built on mutual generosity rather than on one person's need to be needed.`,
      negative: `A frequency organized around being needed keeps attracting people and situations that require endless tending — the world obligingly supplies the dependents required to keep confirming that your worth is conditional on caretaking.`,
    },

    4: {
      heading: 'The Emperor — Structure as Foundation, Not as Cage',
      why: `The 4th Arcana marks a position in your matrix where the frequency of order, authority, and structural intelligence is asking to be integrated. The Emperor is not a character who imposes structure for its own sake — the deepest expression of this energy is someone who has genuinely understood why structure exists: because without it, what we are building cannot hold its own weight. In whatever context this energy appears in your chart, it marks a place where you have either inherited a very specific set of rules about how things should operate, or a place where you are being asked to build the foundational container that will allow something important to grow.`,
      shadow: `When operating from fear, the Emperor energy becomes rigidity: the maintenance of structure as an end in itself, even when the structure is no longer serving life but containing it. The shadow here is the person who cannot tolerate uncertainty, who enforces rules primarily because their own sense of stability depends on those rules being followed, and who experiences genuine creativity or spontaneity as a threat rather than a resource. It is worth noticing that a life full of people who resist your authority rather than recognize it is rarely a coincidence of difficult personalities — it is the world matching a frequency of control that is emitted from fear, not from genuine strength.`,
      path: `The integration of the 4 is learning to distinguish between structures that protect and structures that imprison — and having the courage to renovate the latter without dismantling the former. True authority does not need to be enforced. It is recognized. Your path is to build things that are strong enough to be genuinely flexible — and the more your own relationship to authority relaxes out of fear, the less resistance you find yourself needing to manage in the people and structures around you.`,
      positive: `You build containers strong enough to let something important grow, and because your authority comes from genuine stability rather than fear, the people around you recognize and cooperate with it rather than resisting it.`,
      negative: `Rigid rules enforced from fear keep drawing resistance rather than recognition — the more the grip tightens to manage an internal sense of instability, the more the external world seems to rebel against it.`,
    },

    5: {
      heading: 'The Hierophant — The Bridge Between Wisdom and Living',
      why: `The 5th Arcana carries the frequency of transmission: knowledge that moves through relationship, through teaching, through the passing of something carefully cultivated from one generation or context to the next. Wherever this energy lives in your matrix, it marks a place shaped by an awareness of social and spiritual codes — not as arbitrary rules but as the accumulated crystallisation of what previous generations learned through experience. The gift of the 5 is that it carries genuine respect for what took time and difficulty to earn.`,
      shadow: `The shadow is the conversion of living transmission into static doctrine: knowledge that is defended rather than offered, tradition that is enforced rather than invited, spiritual authority that becomes a position rather than a service. The specific trap for the 5 is the need for the student to remain a student — because the teacher's identity depends on there being someone who knows less. Students who quietly drift away, or who never quite surpass you, are not simply an unlucky run of unmotivated people; they are meeting the actual frequency being offered, which is transmission conditioned on staying beneath rather than genuinely rising.`,
      path: `The integration of the Hierophant is the teacher who genuinely celebrates when the student surpasses them. Who understands that the real goal of transmission is to make themselves unnecessary. This is the most advanced expression of the 5 — and it requires a profound freedom from the ego that has organized itself around being the one who knows. Once that freedom is real, the caliber of student and the depth of relationship that reach you rises to match it.`,
      positive: `You offer what you know freely enough that students genuinely rise past you, and that same generosity is what draws deeper knowledge and better collaborators back toward you in turn.`,
      negative: `A need to keep the student dependent quietly caps the relationship's growth — the frequency of "stay beneath me" is what students eventually sense and drift away from, or simply never outgrow.`,
    },

    6: {
      heading: 'The Lovers — The Courage of the Aligned Choice',
      why: `The 6th Arcana in your matrix marks a position governed by the fundamental human experience of choice — and specifically, by what happens internally in the moment of genuine choosing. The Lovers is not primarily about romantic partnership; it is about the crossroads. About the moment where two genuinely different paths diverge, where the decision cannot be made by logic alone, and where the act of choosing one thing necessarily means leaving another behind. Wherever this energy lives in your chart, it marks a place where you are being asked, repeatedly, to make choices that reflect your actual values rather than your desire to avoid conflict.`,
      shadow: `The shadow of the 6 is indecision that presents as openness: the person who maintains optionality as a way of avoiding the grief of the roads not taken. There is also a very specific pattern here of external dependency — looking to other people, to circumstances, to systems of belief, to tell you what the right choice is, because the responsibility of genuine self-determination feels too exposing. This can manifest as chronic people-pleasing: the systematic subordination of your own preferences to maintain relational harmony, until you have lost contact with what you actually prefer — and a life that keeps handing you decisions made for you rather than with you is often just the world honoring the vacancy you left where your own choice was supposed to be.`,
      path: `The integration of the Lovers is learning to grieve the unchosen path as an act of respect for the chosen one. Every genuine decision is also a genuine loss. The person who can make a choice and fully commit to it — while acknowledging what was released in that commitment — is the person the 6th Arcana is asking you to become. The more clearly you occupy your own preference, the less the world seems to need to choose for you.`,
      positive: `You make choices that genuinely reflect your values and commit to them fully, and because that decisiveness is real, the people and circumstances around you stop trying to fill a vacancy you no longer leave open.`,
      negative: `A pattern of others deciding for you is not simply pushy people — it is the world filling the exact space left by an unoccupied preference, matching the vacancy with decisions made on your behalf.`,
    },

    7: {
      heading: 'The Chariot — The Art of Directed Will',
      why: `The 7th Arcana in your matrix marks a position infused with the frequency of navigation, direction, and the disciplined application of will toward a chosen course. The Chariot is one of the most internally demanding energies in the system — not because it requires force, but because it requires a sustained quality of self-authorship that most people only access in brief moments. Wherever the 7 appears in your chart, it marks a place where you are being asked to *steer* — to maintain a direction that comes from genuine inner knowing rather than from the gravitational pull of your environment.`,
      shadow: `The shadow of the 7 is control that has lost its relationship with trust. The Charioteer who grips the reins so tightly that the horses cannot move with their own intelligence, who mistakes iron self-discipline for genuine mastery, and who experiences any deviation from the planned course as a personal failure. There is also the shadow of the solitary driver: the inability to let others contribute to the journey, the conviction that any collaboration will compromise the direction — and a life that keeps delivering unreliable collaborators is frequently just meeting a frequency that never actually left room for anyone else to drive.`,
      path: `Mastery of the Chariot does not mean you never veer. It means you know how to return to your true north after you have. The integration is the flexibility within the direction — the rider who trusts the horses enough to loosen the reins when the terrain calls for it, knowing that the destination remains. That same trust is what finally allows genuinely capable collaborators to show up, because you are no longer emitting a signal that leaves no room for them.`,
      positive: `You steer with genuine self-authorship while trusting others enough to let them actually contribute — and because that trust is real, capable collaborators keep showing up to help carry the direction.`,
      negative: `A grip too tight for anyone else to help drive keeps attracting collaborators who never quite measure up — not because good help is scarce, but because the frequency never left room for it to arrive.`,
    },

    8: {
      heading: 'Justice — The Calibration That Begins Within',
      why: `The 8th Arcana in your matrix marks a position governed by the frequency of balance, accountability, and the precision of genuine truth. Not the truth that wins arguments, but the truth that remains standing after the argument is over — the objective, structural kind that does not shift based on who is in the room or what outcome is desired. Wherever Justice appears in your chart, it marks a place where you have both the capacity and the responsibility to see clearly, to call things by their accurate names, and to hold yourself and others to a standard that is grounded in actual fairness rather than in preference.`,
      shadow: `The shadow of the 8 is the judge who has never turned the scales upon themselves. The person who maintains an extraordinarily high standard for others' behaviour while operating with an unconscious set of exemptions for their own. There is also a pattern of black-and-white thinking — the compression of genuinely complex situations into simple verdicts — that can cause real harm to relationships and to the person themselves, who feels perpetually caught between the impossible standard and the inevitable shortfall. A life that keeps supplying people to judge is rarely bad luck; it is a frequency of unresolved self-judgment finding external targets to land on.`,
      path: `The integration of Justice begins with the compassionate application of its own medicine: turning the honest, precise gaze inward first. Not to condemn yourself — the 8 is not about punishment — but to calibrate. To ensure that what you are asking of the world, you are genuinely offering yourself. Once the scales settle within, the external verdicts you used to attract have far less raw material to work with.`,
      positive: `You see clearly and call things by their accurate names, holding yourself to the same honest standard you hold others to — and because the scales are settled internally, the world stops handing you so much to judge.`,
      negative: `An unconscious exemption for yourself keeps drawing people and situations that mirror exactly the imbalance you refuse to see in your own conduct — the world supplying fresh material for a verdict that was never really about them.`,
    },

    9: {
      heading: 'The Hermit — The Light That Must Eventually Be Shared',
      why: `The 9th Arcana in your matrix marks a position governed by deep internal wisdom — the kind that comes not from study alone but from genuine solitary integration of experience. The Hermit has walked a road that required going inward. Wherever this energy appears in your chart, it marks a place where some of your most important knowing was gathered in periods of withdrawal, of quiet, of choosing depth over surface. The 9 carries a lantern not for its own navigation — the Hermit already knows the path — but to illuminate the way for others who are still finding their footing in the dark.`,
      shadow: `The shadow of the Hermit is the withholding that masquerades as wisdom. The belief that what you have gathered in solitude is too refined, too hard-won, or simply too difficult to translate for people who have not done the same work. This can shade into isolation not as a chosen practice of renewal but as a permanent state — a life organized around maintaining the conditions of contemplation at the expense of genuine engagement. A world that keeps feeling distant and unreachable is often responding to a lantern that was quietly turned inward rather than out.`,
      path: `You have gathered something real in your solitude. The question the 9 is asking is: what will you do with it? Not in a utilitarian sense. But in the deeper sense of recognizing that the light was never just for you. The integration is the practice of translation — of finding the language that makes what you know available to the people around you, without diminishing it. As the lantern turns outward, connection stops feeling scarce, because you have finally offered something for it to gather around.`,
      positive: `Deep, hard-won inner knowing becomes a lantern for others, and because you're genuinely willing to translate and share it, connection and recognition gather around you rather than staying just out of reach.`,
      negative: `A lantern kept turned inward is what keeps the world feeling distant — withholding what you've gathered in the name of humility only confirms the isolation it was meant to protect against.`,
    },

    10: {
      heading: 'The Wheel of Fortune — Learning to Work With the Current',
      why: `The 10th Arcana in your matrix marks a position infused with the frequency of cycles, timing, and the intelligence of turning. Everything in material reality moves in cycles: seasons, economies, relationships, creative processes, internal states. Wherever the 10 appears in your chart, it marks a place where you are being asked to develop a relationship with the turning of things — to recognise that what goes down will eventually come up, and that what is up is not permanent either, and to locate your stability not in the position of the wheel but in your relationship to the wheel's centre.`,
      shadow: `The shadow of the 10 is victim consciousness in the face of cyclical change: the experience of the wheel's turning as something happening *to* you rather than *through* you. When the 10 operates from fear, it can generate either a desperate grasping for control — trying to stop the wheel at the high point — or a passive resignation that uses "what goes up must come down" as a reason not to fully invest in the upswing. A life that keeps confirming "things always fall apart for me" is often just the belief being handed back exactly as it was broadcast — expectation operating as a self-fulfilling frequency.`,
      path: `The Wheel teaches its deepest lesson through surrender that is *active* rather than passive. You do not resist the current; you learn to read it well enough to navigate within it. Begin by mapping your own cycles: your creative rhythms, your social energy, your motivation. Over time, you will see the pattern. And in seeing the pattern, you will find the stability that the Wheel is actually offering — a stability that stops broadcasting "collapse is coming" and so stops calling it in.`,
      positive: `You locate your stability in your relationship to the cycle itself, and because you're not broadcasting a fear of the downswing, the upswings you invest in get to run their full, uninterrupted course.`,
      negative: `A belief that things always eventually fall apart becomes a self-fulfilling frequency — the anxious grip on the high point, or the passive resignation before the low, calls in the exact collapse it was bracing for.`,
    },

    11: {
      heading: 'Strength — Power That Does Not Need to Prove Itself',
      why: `The 11th Arcana marks a position in your matrix where the frequency of genuine power — not dominance, not force, but the quiet, sustained, deeply embodied form of strength that tames rather than breaks — is asking to be expressed. The image is always of the gentle hand at the jaw of the lion: not overpowering the animal but working *with* its nature. Wherever the 11 appears in your chart, it marks a place where you have real capacity, real endurance, real ability to hold what others cannot. And it marks a place where the distinction between strength-as-service and strength-as-armor is the central evolutionary question.`,
      shadow: `The shadow of the 11 is the identity organized entirely around capability. The person who cannot rest because resting feels like weakness; who cannot receive help because receiving feels like incompetence; who cannot show vulnerability because somewhere in the early architecture of their life, vulnerability had consequences. The physical cost of chronic 11-in-shadow is significant: the jaw, the lower back, the heart working overtime against a baseline of suppressed effort — and a life that keeps handing you people who lean but never lift is matching a frequency that never actually signaled it wanted to be helped.`,
      path: `Strength at the level the 11 is calling for is not the absence of vulnerability. It is the capacity to remain present *with* vulnerability — your own and others' — without needing to immediately resolve it. That is the lion tamed: not broken, not suppressed, but trusted. Once vulnerability is genuinely welcomed rather than defended against, the people who show up start offering real reciprocity instead of simply more weight to carry.`,
      positive: `You hold real weight for others with a quiet, embodied endurance, and because you're genuinely open to receiving in return, the people around you offer real reciprocity rather than simply more to carry.`,
      negative: `A capability that never signals it wants help keeps attracting people who lean without lifting — the world matching the exact frequency of a strength that has never once asked to be met halfway.`,
    },

    12: {
      heading: 'The Hanged Man — The Wisdom Available in Suspension',
      why: `The 12th Arcana in your matrix marks a position infused with the frequency of voluntary suspension — the willingness to surrender a position, a certainty, or a direction of movement in order to receive a perspective that was simply not available from the previous orientation. The Hanged Man is not a victim. He has chosen his position on the tree. And in that choice — in the act of releasing the ground beneath his feet — he discovers that the world looks entirely different from upside down. Wherever this energy appears in your chart, it marks a place where your most significant growth has come, or will come, through the willingness to stop pushing and allow something to be revealed.`,
      shadow: `The shadow of the 12 is the martyrdom that refuses to acknowledge itself as chosen. The pattern of voluntary suffering that is framed as circumstance, of sacrifice that is offered publicly and tracked carefully, of suspension that has gone on long past its teaching moment because the identity of "the one who waits, who endures, who is misunderstood" has become more comfortable than the return to active life. A world that keeps failing to notice the sacrifice is not being cruel — it is responding to a frequency that has quietly stopped expecting the return to ever actually happen.`,
      path: `Your integration is recognising that the suspension has a purpose *and* an endpoint. You do not hang forever. The Hanged Man eventually descends — changed, expanded, carrying knowledge that only this particular orientation could have provided. Begin asking: what am I seeing differently from this angle that I could not see before? And then: what do I do with this new sight when I return to the ground? The moment you genuinely expect the descent, the ground has a way of appearing to meet you.`,
      positive: `You can voluntarily release a certainty in order to see from a new angle, and because you genuinely expect the return to active life, the ground reliably reappears when it's time to come down.`,
      negative: `A suspension that has quietly stopped expecting its own end keeps the ground from reappearing — the world matches an identity that has stopped believing the waiting was ever going to conclude.`,
    },

    13: {
      heading: 'Transformation — The Gift Inside the Necessary Ending',
      why: `The 13th Arcana in your matrix marks a position governed by the frequency of metamorphosis — specifically, the kind that cannot happen without genuine release. Not the controlled, scheduled kind of change, but the deep cellular kind: the dissolution of a form that has completed its function so that something more aligned can take its place. Wherever the 13 appears in your chart, it marks a place where clinging to what has already ended is the specific obstacle, and where the willingness to let something fully die — a belief, a relationship, a version of yourself, a strategy that once worked — is the exact doorway to what comes next.`,
      shadow: `The shadow of the 13 is the person who has survived so many genuine endings that they have developed a kind of unconscious addiction to crisis — recreating the intensity of transformation at the level of drama because the stillness of consolidation feels dangerously close to the stillness before the collapse. There is also the opposite pattern: the person who refuses any genuine ending, who keeps things alive through sheer will past the point of natural completion, accumulating the weight of what should have been released — and a life that keeps delivering abrupt collapses is often just matching a frequency still bracing for one, refusing the quieter release that was actually available.`,
      path: `The 13 in integration is the master of beginnings *because* they have stopped being afraid of endings. Your work is to develop a discernment practice: to be able to sit with something and honestly ask whether it is in a difficult phase that wants to be worked through, or whether it has genuinely completed and wants to be honoured and released. These require very different responses, and the 13 must learn to tell them apart — and once genuine endings are allowed to complete quietly, reality stops needing to manufacture dramatic ones to get your attention.`,
      positive: `You let things end cleanly when they've actually completed, and because your relationship to endings is calm rather than crisis-driven, transitions arrive gently instead of as sudden collapse.`,
      negative: `A refusal to let anything genuinely end keeps accumulating weight until reality manufactures a dramatic collapse to force the release that a quiet letting-go could have handled all along.`,
    },

    14: {
      heading: 'Temperance — The Alchemy of Integration',
      why: `The 14th Arcana in your matrix marks a position infused with the frequency of integration — specifically, the alchemical kind that combines apparently incompatible elements into something genuinely new. The Temperance figure pours liquid between two cups, perpetually, with absolute patience. Not because she doesn't know what she's doing — but because the process of combining requires exactly as long as it requires, and rushing it produces something other than the intended compound. Wherever this energy appears in your chart, it marks a place where your particular form of genius involves the patient synthesis of opposites: ideas, people, timelines, strategies that others cannot imagine coexisting.`,
      shadow: `The shadow of the 14 is the false middle ground — the person who avoids the discomfort of genuine polarity by papering it over with a premature harmony that satisfies no one. There is also the pattern of avoidance through perpetual balancing: staying so focused on managing the equilibrium that genuine depth — the kind that requires tipping fully into one direction before you can know the other — never becomes available. Relationships and situations that keep feeling watered-down rather than resolved are matching a frequency that has been avoiding real contact rather than genuinely blending anything.`,
      path: `The integration of Temperance is the willingness to fully inhabit the extremes long enough to understand them from the inside before attempting to synthesize them. You cannot blend what you have not genuinely encountered. Your path is to stop moderating your experience prematurely and to trust that the alchemy will happen — it simply requires the full intensity of each ingredient. Once you allow the full intensity, life stops handing you diluted, unresolved versions of what you actually want.`,
      positive: `You patiently synthesize things that seem incompatible into something genuinely new, and because you let each ingredient reach full intensity first, what you draw together actually holds.`,
      negative: `A premature, papered-over harmony keeps drawing situations that feel watered-down rather than resolved — the avoidance of real polarity showing up as relationships and outcomes that never quite land.`,
    },

    15: {
      heading: 'The Devil — Reclaiming What Binds You',
      why: `The 15th Arcana in your matrix marks a position where the frequency of material power, primal attachment, and the shadow of the ego's relationship to security is asking to be honestly confronted. The Devil is not evil in the cartoonish sense. He represents the specific and very human experience of being bound to something — a substance, a relationship dynamic, a financial pattern, a belief system — that you know is not serving your highest expression but which provides a form of comfort, familiarity, or stimulation that you have not yet found an adequate substitute for. The figures in the classic image are not locked in chains. They are loosely bound, and the chains could slip off at any moment. The question is what it would mean to let them.`,
      shadow: `The shadow of the 15 is the use of material power — money, status, physical dominance, sexual energy — as a substitution for genuine intimacy or self-worth. The person in the grip of the 15's shadow mistakes accumulation for security, and control for love. There is also the pattern of projection: attributing to others the shadow qualities that belong to yourself, which keeps you trapped in repetitive cycles of resentment and perceived victimisation — a cycle of people who seem to consistently take advantage is often the frequency of an unexamined attachment recreating the exact dynamic it resents.`,
      path: `The liberation the 15 is offering is not the elimination of pleasure or material engagement — it is the *unchaining* of pleasure from compulsion. The ability to fully enjoy without needing. To engage with the material world as a genuine participant rather than as someone in its service. Your work begins with naming what you are actually attached to and asking, with honest curiosity rather than self-judgment, what that attachment is providing. As the compulsion loosens, the relationships and resources that arrive stop mirroring the old bind back to you.`,
      positive: `You engage fully with pleasure, money, and the material world as a genuine participant, and because the chains are genuinely loose, the relationships and resources that arrive feel like abundance rather than compulsion.`,
      negative: `An unexamined attachment to control or security keeps recreating the exact dynamic it resents — the same bind, mistaken for love or safety, showing up again in a different disguise.`,
    },

    16: {
      heading: 'The Tower — The Gift Hidden in the Collapse',
      why: `The 16th Arcana in your matrix marks a position governed by the frequency of sudden, lightning-strike revelation — the kind that restructures reality faster than the mind can process it. The Tower is not the collapse itself; it is the *clarity* that the collapse makes available. Whatever was built on a false foundation must eventually reveal itself, not as punishment but as a structural inevitability. Wherever this energy appears in your chart, it marks a place that has experienced — or will experience — a moment of radical reorganisation that felt like destruction from the inside but proved, in retrospect, to be the most important reorientation of your trajectory.`,
      shadow: `The shadow of the Tower is the person who has identified so deeply with the drama of collapse that they recreate it continuously — burning down functional structures out of a compulsive need for the intensity of the Tower moment, or the freedom from responsibility that a genuine crisis temporarily provides. There is also the opposite: the person who is so afraid of the Tower that they maintain increasingly fragile structures through sheer will, refusing to let anything naturally complete, which means the eventual collapse carries far more weight than it needed to — a life of repeated dramatic upheaval is rarely bad fortune; it is a frequency still identified with crisis as the only believable form of change.`,
      path: `The integration of the 16 is the capacity to initiate necessary endings before they initiate themselves — to survey your life with genuine honesty and ask which structures are built on true foundations and which are maintained by the energy of avoidance. This is not nihilism. It is architectural intelligence applied to the construction of your life. Once change no longer has to arrive as crisis to be believed, reality stops needing to deliver it that way.`,
      positive: `Sudden clarity becomes a tool you can use deliberately, and because change no longer needs to arrive as crisis to feel real, transitions in your life get to unfold gradually instead of catastrophically.`,
      negative: `An identity still organized around crisis as the only believable form of change keeps summoning collapse to prove that change is actually happening — the drama becoming necessary rather than incidental.`,
    },

    17: {
      heading: 'The Star — Luminosity as a Lived Practice',
      why: `The 17th Arcana in your matrix marks a position infused with the frequency of cosmic hope — not the brittle, conditional hope that depends on outcomes, but the structural kind: the capacity to continue generating light even in conditions that offer no external confirmation that the light is warranted. The Star appears in the Tarot following the Tower — she rises after the collapse, pouring water from two vessels onto the earth and the stream simultaneously, healing what was broken, replenishing what was depleted. Wherever this energy lives in your chart, it marks a place where your capacity for renewal is one of your most genuine gifts to the people around you.`,
      shadow: `The shadow of the 17 is the idealism that has not yet learned to land: the person whose vision of what is possible is so luminous that it perpetually transcends the actual, the present, the imperfect. This creates a quiet but persistent grief — the gap between the world as it is and the world as you see it could be — that can make intimate relationship very difficult, because no actual human being can sustain the frequency of their own highest potential without interruption. A life that keeps disappointing against your vision of it is not the world failing you — it is a frequency permanently pitched toward potential rather than toward what is actually, presently here to be met.`,
      path: `The Star's full expression is bringing her light *into* the wound rather than above it. Not pretending the wound is not there, not transcending it, but literally pouring light into the place that is broken and trusting the regenerative intelligence of that process. This requires being willing to get close to what is damaged — including within yourself — rather than holding the vision of wholeness at a safe distance. Once your light is offered to what is actually present, the world stops arriving as a disappointment and starts arriving as material to work with.`,
      positive: `You generate genuine hope and renewal by meeting what is actually present rather than only its potential, so relationships and circumstances feel met and nourished instead of quietly judged against a vision.`,
      negative: `A frequency permanently pitched toward potential rather than the present keeps the actual world arriving as a disappointment — no person or moment can ever quite satisfy a light that's aimed somewhere else.`,
    },

    18: {
      heading: 'The Moon — Navigating the Depths Without Being Consumed',
      why: `The 18th Arcana in your matrix marks a position governed by the deep unconscious, by the psychic and emotional currents that move beneath the surface of daily awareness, and by the cyclical, non-linear intelligence of the interior life. The Moon does not illuminate the way the Sun does. It offers a softer, more ambiguous light that reveals the outlines of things without fully explaining them — and this is not a failure of the Moon but its specific contribution. Wherever this energy appears in your chart, it marks a place where your most reliable guidance arrives through dreams, through somatic knowing, through the felt sense that something is true before you can explain why.`,
      shadow: `The shadow of the Moon is the confusion that comes when the interior and exterior worlds are no longer clearly distinguishable — when the emotional atmosphere of the subconscious is projected onto circumstances without being recognised as projection. This can manifest as paranoia, as the experience of reality as fundamentally threatening or deceptive, as a chronic inability to trust appearances because you are always sensing what might lie beneath them. There is also the shadow of escapism: using the Moon's gifts of fantasy and interior richness as a substitute for engaged, embodied participation in actual life — and a world that keeps confirming your suspicion is often just an unexamined subconscious atmosphere finding matching evidence in whatever ambiguous thing it looks at.`,
      path: `The integration of the Moon is learning to move through the deep waters without being swept away by the current — to maintain a thread back to the surface even when you are diving. This requires developing practices that ground your interior world in the physical: movement, breath, the specific materiality of the body as an anchor point for the psychic sensitivity that this Arcana carries. The clearer that anchor becomes, the less external circumstance is available to be misread as confirmation of an old fear.`,
      positive: `You sense what's true before you can explain it, and because your interior world is genuinely anchored, that intuition reads real undercurrents rather than projecting old fears onto ambiguous circumstances.`,
      negative: `An unexamined subconscious atmosphere gets projected outward and then finds matching "evidence" everywhere it looks — deepening a suspicion of reality that was never actually about the present moment.`,
    },

    19: {
      heading: 'The Sun — The Radiance That Serves Rather Than Performs',
      why: `The 19th Arcana in your matrix marks a position infused with the frequency of genuine vitality — the kind that radiates outward not as performance but as the natural consequence of being genuinely, authentically alive in the direction of your actual nature. The Sun does not try to shine. The Sun shines because that is what the Sun does. Wherever this energy appears in your chart, it marks a place where your most natural state — when you are not managing other people's perceptions of you, when you are not dimming yourself to avoid the discomfort of your own brightness — is one of genuine warmth, clarity, and the kind of joyful engagement with life that other people find both inspiring and, occasionally, confronting.`,
      shadow: `The shadow of the Sun is the narcissism of the person who has confused their radiance with their worth — who needs to be the brightest source of light in every room and becomes genuinely destabilised when someone else brings a comparably vivid energy. There is also the pattern of burning people: of projecting so much solar intensity onto the people closest to you that they cannot grow in your light because there is simply too much of it. The Sun in shadow scorches what it intends to nourish, and the wilted relationships that keep resulting are the world honestly reporting back the actual temperature being emitted.`,
      path: `The integration of the 19 is the capacity to be genuinely delighted by other people's light — to expand in the presence of another's brightness rather than competing with it. This is the solar consciousness at its most evolved: not a single sun, but part of a galaxy. Your vitality, when it is genuinely integrated, becomes a climate in which other things grow — and a climate that lets other things grow is what finally draws people who want to stay in it.`,
      positive: `Your natural warmth and vitality become a climate other people genuinely grow in, and because your light doesn't need to compete, the people closest to you flourish rather than shrink or scorch.`,
      negative: `A need to be the brightest source of light in every room scorches what it touches, and the wilted or distant relationships that result are the world accurately reflecting the actual heat being given off.`,
    },

    20: {
      heading: 'Judgement — The Call That Cannot Be Unfired',
      why: `The 20th Arcana in your matrix marks a position governed by the frequency of awakening — the moment when the old version of yourself becomes genuinely untenable, when the life you have been living no longer fits the person you have become, and when the inner summons to a fuller expression cannot be postponed without a very significant cost. Judgement is not punishment. It is revelation. The figures rising from their coffins in the classic image are not being called to account for their failures; they are being called *home* to what they actually are. Wherever this energy lives in your chart, it marks a place where you have heard, or are about to hear, exactly this kind of summons.`,
      shadow: `The shadow of the 20 is the person who hears the call and then spends the rest of their life preparing to answer it — reading more, learning more, clearing more, refining more — because the act of genuinely answering requires being seen in full, and being seen in full requires a vulnerability that feels, from the inside, like the risk of everything. There is also the pattern of perpetual reckoning without resolution: using the self-awareness of the 20 to maintain a state of constant self-examination that substitutes for actual movement — a life that keeps signaling "not yet ready" is emitting exactly that frequency, and the world simply keeps agreeing.`,
      path: `Answering the call of the 20 does not require perfection. It does not require the full clearing of everything that has come before. It requires the single, courageous act of rising from the place where you have been lying down and beginning to move in the direction the trumpet is pointing. The rest reveals itself in the movement — and the moment you actually move, the opportunities that once seemed to be waiting on your readiness start meeting you partway.`,
      positive: `You answer the summons when it arrives rather than endlessly preparing for it, and because you're actually moving, the opportunities and recognition you were waiting to feel ready for start meeting you partway.`,
      negative: `Endless preparation broadcasts "not yet ready" more clearly than any spoken doubt could — and the world, quietly matching that frequency, keeps agreeing and withholding the very opening you're waiting for.`,
    },

    21: {
      heading: 'The World — The Permission to Be Complete',
      why: `The 21st Arcana in your matrix marks a position infused with the frequency of genuine completion — not the artificial kind that is declared before the work is done, but the real kind that arrives when a full cycle has been genuinely lived through, integrated, and allowed to come to its natural conclusion. The World is the last card of the Major Arcana before the cycle begins again with the Fool. The figure at its centre dances within the wreath, held by the four elemental beings, fully contained and fully free simultaneously. Wherever this energy appears in your chart, it marks a place where mastery — genuine, hard-won, quietly radiant mastery — is either already present or is the specific destination toward which this area of your life is moving.`,
      shadow: `The shadow of the 21 is the fear of completion — specifically, the fear that completing something means facing the next beginning, and the next beginning carries with it all the uncertainty that the current cycle has already absorbed. This can manifest as perfectionism that prevents completion: always finding one more thing to refine, one more element to add, one more preparation to make before the work is considered done. It can also manifest as the compulsive restarter: the person who dismantles the near-complete to rebuild from scratch, not because the work is wrong but because completion itself feels too exposing — a life full of unfinished projects is broadcasting "almost" as its steady frequency, and the world keeps handing back exactly that: near-misses, not arrivals.`,
      path: `The integration of the World is learning to stand, fully, in what has already been accomplished — before the next cycle has been initiated. To actually let something be finished. To receive the completion before moving. This is the most underrated act of courage in a culture that rewards perpetual motion: the willingness to stop, to acknowledge that something real was built here, and to allow that acknowledgement to land. The moment completion is genuinely permitted, the frequency of "almost" stops being what the world keeps reflecting back.`,
      positive: `You can stand fully in genuine completion, and because "finished" is a frequency you actually permit, recognition and reward arrive as real arrivals rather than as another near-miss.`,
      negative: `A frequency stuck on "almost" — never letting anything be genuinely done — keeps drawing near-misses rather than arrivals, the world simply matching the incompletion being broadcast.`,
    },

    22: {
      heading: 'The Fool — The Courage That Has Forgotten to Be Afraid',
      why: `The 22nd Arcana in your matrix marks a position infused with the frequency of pure potential — the energy of the beginning that has not yet been shaped by outcome, of the step taken before the foot knows where it will land. The Fool is not naive in the pejorative sense. The Fool carries a very specific kind of intelligence: the intelligence of the present moment unconstrained by the accumulated weight of past experience. Wherever this energy appears in your chart, it marks a place where your most generative quality is the willingness to begin — again, and again, and again — without needing the safety of a guaranteed outcome.`,
      shadow: `The shadow of the 22 is the recklessness that refuses to absorb the lessons the previous cycles have offered — the person who leaps perpetually not from genuine freedom but from an unexamined avoidance of the responsibility that maturation requires. The Fool in shadow is the eternal beginner who uses freshness as an exemption from depth, and who mistakes the excitement of initiation for the richness that only sustained engagement can provide — a life that keeps repeating the same lesson in a new costume is not bad luck; it is a frequency still refusing to actually absorb what it already encountered.`,
      path: `The integration of the Fool is the most paradoxical achievement in the system: to bring the freshness, the fearlessness, and the genuine openness of the beginning *through* the full weight of experience rather than despite it. To know everything that the previous 21 Arcana have taught and to begin again anyway, with your eyes open. This is the Fool at full power — not innocent of difficulty, but genuinely undeterred by it. Once a lesson is genuinely absorbed rather than skipped past, life stops needing to hand it back in a new disguise.`,
      positive: `You begin again and again with real lessons genuinely absorbed rather than skipped past, so each new beginning meets fresh terrain instead of the same lesson wearing a different costume.`,
      negative: `Skipping past a lesson instead of absorbing it keeps that same lesson returning in a new disguise — the thrill of another fresh start standing in for the depth that was actually being asked for.`,
    },

  }; // end general


  // ── Public API ─────────────────────────────────────────────────────────────

  /**
   * get(arcanaNum, nodeKey)
   * Returns the richest content available for this arcana in this position.
   * Falls back to general[arcanaNum] if no position-specific entry exists.
   */
  function get(arcanaNum, nodeKey) {
    return nodes[arcanaNum + '_' + nodeKey] || general[arcanaNum] || null;
  }

  return { get };

})();
