'use strict';

/**
 * Destiny Matrix — Micro-Content Engine
 * ─────────────────────────────────────
 * Two content layers:
 *
 *  1. nodes["NUM_KEY"]  — position-specific deep reading.
 *     KEY is the NODES[i].key value: A, B, C, D, or E.
 *     Written for the exact psychological lens of each host star.
 *
 *  2. general[NUM]  — universal archetype fallback used when a
 *     position-specific entry doesn't yet exist.
 *
 * API:
 *   DMicroContent.get(arcanaNum, nodeKey)
 *     → { heading, why, shadow, path } or null
 */

window.DMicroContent = (function () {

  // ── POSITION-SPECIFIC DEEP READINGS ──────────────────────────────────────
  // Keys: arcana number + "_" + node key  (e.g. "8_A", "5_B")

  const nodes = {

    // ── 8 in CORE CHARACTER (A · Left / Day of Birth) ──────────────────────
    '8_A': {
      heading: `You Arrived Already Keeping the Score`,
      why: `You were born with an instinct for fairness that most people spend a lifetime developing. Before you say a word, people sense a kind of moral gravity in you — the sense that you're quietly reading a room for what's true, what's owed, what's out of balance. As a child, you were probably the one who noticed the inconsistency, who felt an injustice land in your body before you could explain why, who couldn't let a broken promise pass without something in you registering it. That's not you being difficult. That's Justice — the 8th Arcana — sitting in your Core Character, the persona you project before you even say a word. It gives you real steadiness, an honesty people learn to rely on, and a gut sense that every action eventually comes back around.`,
      shadow: `The same instinct that reads a room so accurately can slide into something harder: a habit of quietly judging everyone, including yourself, against a standard no one actually meets. You might catch yourself complaining, out loud or just internally, that people don't play fair, that the world keeps breaking its own rules — and the complaint becomes its own trap, keeping you locked in a fight with a reality that won't bend to your ledger. Here's the harder question worth asking: what does it say about you that this keeps happening? A life that keeps handing you broken promises and unpunished unfairness usually isn't bad luck — it's often an echo of something in you that's still bracing for injustice, or still keeping score in ways that make people want to hide their own. You might even notice yourself doing, in small ways, the very thing you can't stand in others — withholding, controlling, keeping tabs — which only invites more of the same back.`,
      path: `Try turning the scales inward before you turn them on the world. Not to punish yourself — that's not the point — but to actually check your own calibration. This is the less comfortable path, because it puts the responsibility for what you keep running into on you instead of on everyone else. But it's also the more empowering one, because it means the fairness you're looking for doesn't have to wait on the world to hand it to you. Start by noticing where imbalance keeps showing up — money, relationships, work — and instead of treating each one as more proof the world is unfair, ask what it's telling you about what you're still carrying. Real justice isn't a pile of verdicts against people who've wronged you. It's restoring your own internal balance — and that's the part that actually changes what starts showing up for you.`,
      positive: `Fairness comes easily to you, because your own sense of integrity is settled — the people, deals, and situations that honor that integrity are what you consistently draw toward yourself.`,
      negative: `Repeated run-ins with unfair people and broken promises aren't just bad luck — they're often being pulled toward you by something unresolved inside, a part of you still braced for injustice that keeps recreating exactly what it's trying to avoid.`,
    },

    // ── 5 in SKY LINE (B · Top / Spiritual Potential / Divine Talents) ─────
    '5_B': {
      heading: `You Were Born Suspecting There's a Deeper Order`,
      why: `Most people spend their whole lives looking for a framework that makes the world make sense. You arrived already suspecting one exists. The Hierophant sits at the top of your matrix, in your Sky Line — your spiritual potential — and it means your gift is one of transmission: an instinct for the codes underneath things, a sense that beyond the visible rules there's a deeper structure you can learn, hold, and eventually hand to someone else intact. That's what "divine talent" means in this position. Not that faith came easy to you, but that you have a real aptitude for wisdom itself — for study that turns into devotion, and hard-won understanding you can actually pass on.`,
      shadow: `The risk is that living spirit hardens into rigid doctrine. The same reverence that lets you honor structure can curdle into the conviction that there's exactly one right way up, and anyone doing it differently isn't just different — they're wrong. Notice what that actually does: a closed channel doesn't just teach badly, it stops receiving too. If you keep finding rooms full of people who resist your wisdom instead of taking it in, that's often a sign the channel has already narrowed, that some part of you has already decided it knows and stopped being genuinely open. You might catch yourself lecturing when you meant to teach, or defending a tradition instead of actually passing on its living core, treating spiritual authority as a position to hold instead of something you offer in service.`,
      path: `The best version of you becomes a rare kind of teacher — one who holds the codes lightly enough to let them keep evolving, who's genuinely glad when a student sees further than you do. Your work is keeping the channel open: treating every framework, even the sacred ones, as something alive rather than a finished monument. That's uncomfortable, because it means giving up the safety of certainty — it's much easier to defend a fixed answer than to keep asking what needs revising. But an open channel is also what determines what comes back to you. The teachers, students, and opportunities that reach you are responding to how open you actually are, not to how much you already know. Your gift reaches full strength not when you've mastered the law, but when you become someone others can genuinely climb through — and who keeps climbing back toward you in return.`,
      positive: `Your channel stays genuinely open, and the wisdom, teachers, and students who reach you reflect that back — real exchange in both directions, not a monologue delivered to a closed room.`,
      negative: `Once you've quietly decided you already know, the rooms you reach tend to resist rather than receive — the same defensiveness that hardens your teaching into dogma is what narrows the doors that open to you.`,
    },

    // ── 4 in EARTH LINE (C · Right / Material & Money / Year of Birth) ─────
    '4_C': {
      heading: `You Were Built to Construct Security, Not Wait for It`,
      why: `You carry one of the most grounding energies in the whole system on your Earth Line — your material and financial potential, encoded from your year of birth. The Emperor speaks of a real capacity to build: to bring order to the physical world, raise structures that can actually hold weight, and turn a vision into something durable enough to generate real security. You understand, in your bones, that wealth and stability aren't luck — they're constructed, through discipline and a willingness to take responsibility for the outcome. You can hold a plan across time. You can stay with the unglamorous, foundational work most people abandon halfway through. And there's a quiet authority in you around money — a sense that you're meant to build the container, not wait around inside someone else's.`,
      shadow: `The shadow shows up as structure that's forgotten what it was built to serve. Sometimes that looks like financial stagnation dressed up as caution — an unwillingness to risk or expand or dismantle a system that technically still works but has stopped growing. Sometimes it looks like rigidity: gripping resources so tightly that nothing new can get in, mistaking a pile of order for actual prosperity. Money that won't move isn't being protected — it's being told, at a deep level, that there isn't enough of it to risk, and that exact scarcity is what a tight grip tends to keep pulling back toward itself. It can also show up as the opposite — a resistance to being the one in charge, leaving your material potential unbuilt while you wait for someone else's structure to come rescue you.`,
      path: `Your work isn't to tear the structure down — it's to become its conscious architect, building with confidence instead of fear. That means accepting the less comfortable half of this first: your current financial reality isn't something happening to you, it's the structure your own beliefs about money have quietly been building all along. Start with an honest audit: which structures genuinely protect what matters, and which have quietly turned into prison walls you're maintaining out of habit? Real authority over your material world doesn't need to grip. It can afford to be generous and flexible because it trusts its own ability to rebuild — and that trust, more than any single strategy, is what a healthy relationship to money is actually made of. You were built to construct security from the ground up. The mastery is building something strong enough to stay open, because an open structure is what abundance can actually move through.`,
      positive: `You build real, durable security from genuine trust in your own capacity — money and resources move toward you because your relationship to them is generous and open rather than gripped, so the flow keeps replenishing itself.`,
      negative: `Resources held too tightly leave no room for anything new to enter, and that scarcity-driven grip is exactly the frequency that keeps material stagnation in place — the fortress you're defending is the same structure keeping real abundance out.`,
    },

    // ── 17 in KARMIC TAIL (D · Bottom / Past-Life Lessons / Core Karma) ───
    '17_D': {
      heading: `The Light You Learned to Turn Down`,
      why: `Something in you carries a deep, wordless conviction that you're meant for something luminous — and, right alongside it, an equally strong instinct to shrink from exactly that exposure. Both of those are real, and they come from the same place. The Star sits at the base of your matrix, in your Karmic Tail — the deepest inherited work of the soul — and the lesson you carried into this life circles around visibility and light: the capacity to shine, to be seen, to offer hope and brilliance to the people around you. This is the one position in the matrix that arrives already in shadow. It's not a gift you were simply handed. It's a debt the soul came here to repay — the debt of dimmed light, a past pattern of brilliance traded away for safety, talent kept but never fully offered.`,
      shadow: `You might notice a quiet, structural belief that your light is dangerous — to you or to someone else — and safer kept low. It can show up as impostor feelings that arrive right when recognition is finally within reach, as a talent you've deliberately left half-developed so it can never really be judged, as a habit of pouring your belief into everyone else's potential while withholding it from your own. It's worth naming plainly: if life keeps handing you visibility and you keep quietly turning it down, that's not something happening to you — it's a signal you're broadcasting that being seen isn't safe, and the world is simply responding to that. Because this runs deeper than a personal habit, it can feel less like a choice and more like gravity — a pull back toward staying unseen every time you get close to the edge of being truly known.`,
      path: `This position is built for redemption — it's the one place in the matrix that explicitly asks you to move something out of shadow and into light, and finish something older than this lifetime. For you, that means practicing the uncomfortable thing: letting yourself be seen before you feel ready. Share the work. Take up the visibility. Let your light land on other people even when every old instinct says to dim it. You don't have to wait for the world to hand you a stage — the world tends to match whatever you're actually broadcasting, which means the visibility you want has to start with you before it can arrive from outside. You don't have to manufacture the brilliance. It's already yours, and it always was. You just have to stop hiding it. Every time you choose visible over vanished, you pay the debt down a little and reclaim the exact gift you came here to give.`,
      positive: `You're genuinely willing to be seen, and the world responds in kind — recognition, opportunity, and audience arrive because you've stopped signaling that your light needs to stay hidden.`,
      negative: `When some part of you is still broadcasting that visibility isn't safe, you keep meeting chances to be seen and then quietly declining them — matching the very signal you're actually sending.`,
    },

    // ── 7 in SOUL CENTER (E · Center / Comfort Zone / Foundation of Purpose) ──
    '7_E': {
      heading: `You're Here to Navigate, Not to Arrive`,
      why: `You might experience stillness as failure long before you learn to recognize it as preparation — and that's one of the clearest signs of where you are. The Chariot sits at the absolute center of your matrix, in your Soul Purpose, and it doesn't mean you're here to reach some fixed destination. It means your fundamental life current is navigation itself. You're here to master movement — not necessarily speed, not conventional achievement, but the sustained, disciplined, internally generated ability to keep going in a chosen direction no matter what conditions show up. That's both a real gift and real pressure. Your soul carries something like a built-in compass, an internal sense of true north that keeps working even when everyone else's map points somewhere different. The lifelong work is trusting that compass over the noise of everyone telling you what to do instead.`,
      shadow: `The deepest trap here is a belief you've probably never fully examined: that you have to figure everything out alone. The Chariot is a solitary image — powerful, contained, masterful — and over time, that image can quietly become an elegant prison. You've likely built an extraordinary capacity for self-sufficiency that, looked at honestly, is also an extraordinary capacity for a very particular kind of loneliness — the loneliness of someone who's learned that asking for help usually creates more complication than it solves. It's worth noticing: if help keeps arriving unreliable or too late to matter, that's rarely just proof that people can't be trusted. More often, the world is matching something you decided long before anyone actually let you down — that receiving isn't safe. You might not experience yourself as lonely. You might just experience yourself as efficient. But efficiency, in the domain of the soul, isn't a virtue — it's a coping strategy that's outlived its usefulness, and it quietly keeps real support at arm's length.`,
      path: `You'll likely discover, often through a moment that overrides your usual self-sufficiency, that the Chariot was never meant to be driven by one person alone. A chariot needs a driver, horses, and terrain — a collaboration between will, energy, and the actual world as it is. Your path forward is the uncomfortable, counter-instinctive practice of receiving: taking help without immediately fixing it, taking love without cataloguing its flaws, taking in the perspective of people who see you differently than you see yourself. This is the harder truth to sit with, because it removes the comfort of "people just aren't reliable" and puts the responsibility on what you're actually willing to receive — but change what you're open to, and what shows up to meet you changes right along with it. Your soul's purpose is movement, and the most meaningful movement right now might be the inward one — toward trust, toward letting your reliable compass be read by someone else alongside you.`,
      positive: `You move with a steady, self-generated sense of direction and a genuine openness to receiving support along the way — and because that openness is real, capable people and real help consistently show up to meet it.`,
      negative: `When some part of you has already decided receiving isn't safe, help tends to arrive unreliable, late, or absent — quietly confirming the belief that self-sufficiency is the only option, and deepening the isolation it was meant to protect you from.`,
    },

    // ── 5 in RELATIONSHIP (Love channel — Ideal Partner / Relationship Harmony) ──
    '5_LOVE': {
      heading: `You Fall for Substance, Not Just Chemistry`,
      why: `You're not drawn to a connection just because it feels good in the moment — you fall in love with substance. The Hierophant governs your relationship channel, which means intimacy runs on the frequency of the seeker and keeper of codes: earned structure, depth, the difference between a connection that's been tested against real standards and one that's just easy. You're drawn to partners who carry some kind of depth, tradition, or hard-won knowledge, and in return you offer something rare — genuine reverence, the willingness to actually study another person, to learn the specific architecture of how they work, and to honor what it took them to become who they are. For you, relationship is one of the primary places you expect to be taught something true about how life actually works.`,
      shadow: `The risk is love organized around an unspoken exam. You might find yourself measuring a partner against a standard of what a relationship is "supposed" to look like — inherited from family, culture, or an idealized version of commitment — while quietly holding back your full arrival until they pass. A subtler trap is treating a partner like a student rather than an equal: correcting, instructing, holding the position of the one who knows how this is done. And because you respect earned authority, you might also defer to a partner's confidence over your own read of what's actually happening between you, mistaking their certainty for correctness. If your relationships keep handing you partners who feel like they're auditioning for you, or who audition you right back, that's often a sign intimacy hasn't yet been allowed to exist without a passing grade.`,
      path: `Try letting the relationship itself become the sacred text, instead of measuring it against one you inherited somewhere else. That's the harder, more exposing shift — it means letting go of an external rulebook and trusting what's actually true between the two of you, even when it doesn't match the tradition you were handed. Practice offering your attention and reverence without requiring the relationship to earn it first. The standard that actually matters is the one you build together, not the one you bring in ahead of time. Once love stops being graded, it finally has room to teach you something no book ever could.`,
      positive: `You bring real depth, respect, and earned trust into partnership — a relationship that functions like living wisdom, each of you genuinely teaching the other rather than performing for a standard.`,
      negative: `When intimacy hasn't been allowed to exist without first passing a test, love tends to stay organized around an unspoken exam — partners keep arriving who feel like they're auditioning, or who put you through one.`,
    },

    // ── 17 in MONEY (Wealth Potential / Ideal Profession channel) ──────────
    '17_MON': {
      heading: `Your Money Follows Your Willingness to Be Seen`,
      why: `Your most abundant income tends to show up exactly when you're operating from genuine visibility — sharing your real gift, letting your actual light be seen in your work — rather than following a strategy borrowed from someone else's idea of a stable career. The Star governs your money channel, tying your financial flow directly to hope and authentic radiance rather than to grinding, joyless effort. This is one of the more luminous financial placements in the matrix: money that arrives almost as a byproduct of authenticity, once you actually offer the authenticity instead of rehearsing it in private.`,
      shadow: `The risk is income that stays conditional on approval before it's allowed to flow — a launch you keep delaying until every condition feels perfect, a rate you quietly undercut because charging full price for something so personal feels like too much, a body of work you keep private until it's "ready" in a way that never quite arrives. Because your gift is genuine, withholding it is expensive: a thin, sporadic bank account is often a light that's still being kept low rather than freely offered to a market that would gladly pay for it.`,
      path: `Try treating visibility itself as the transaction — letting your work be seen at the stage it's actually in, rather than the stage you wish it had reached. That's uncomfortable, because it removes the comfort of staying private while you perfect things, and it puts the responsibility on what you're willing to show right now. Start with the smallest real offer: a rate that reflects the actual value of your work, a piece released before it feels fully polished. The financial flow you're waiting to feel ready for is, for you, directly downstream of the visibility you're willing to allow today.`,
      positive: `Money arrives in rhythm with genuine visibility — the more authentically you let your work be seen at the stage it's actually in, the more consistently and generously it gets paid for.`,
      negative: `Income stays sporadic and undervalued when your light is still being kept low — a launch delayed, a rate undercut, a body of work withheld until conditions that never quite arrive.`,
    },

    // ── 13 in PATERNAL SPIRITUAL (Ancestral Square, Age-10 anchor) ──────────
    '13_F': {
      heading: `You Inherited Raw Material, Not a Finished Belief`,
      why: `The belief system, worldview, or spiritual inheritance passed down through your father's line was never meant to be received intact — it was meant to be transformed. Transformation, the 13th Arcana, sits in your Paternal Spiritual corner as a generational instruction: something in that lineage — a rigid faith, an unspoken code about how a man is supposed to relate to meaning, a belief about what's allowed to be questioned — reached the end of its natural life inside you specifically so it could be rebuilt into something that actually fits who you became. You didn't inherit a finished structure. You inherited raw material, and a mandate to remake it.`,
      shadow: `The trap is treating that inheritance as something to either swallow whole or reject entirely, rather than actually work through. Swallowed whole, it becomes belief you never examined, quietly running your life from behind the curtain. Rejected outright, it becomes an equally unexamined reaction — defining yourself by opposition to your father's worldview instead of by any actual position of your own. Both are ways of avoiding the harder work: taking what was given, letting the parts that no longer serve you actually die, and consciously choosing what's worth keeping. If you keep circling the same unresolved question about faith, authority, or meaning — showing up in new disguises but never quite settling — that's often the paternal line's spiritual inheritance still waiting for its ending.`,
      path: `Try a conscious inheritance audit: name, specifically, what belief or worldview arrived through your father's line, and ask honestly what part of it is genuinely yours versus what you've simply never gotten around to examining. This isn't a betrayal of your father — this isn't asking you to reject him, it's asking you to complete a transformation that was likely his to do as well, and may not have finished. What survives the audit becomes real conviction instead of inherited furniture. What doesn't survive gets released with respect instead of resentment — and the spiritual restlessness that's been following you finally has somewhere to land.`,
      positive: `You've separated your father's inherited worldview from your own genuine conviction — what you carry spiritually from that line is now consciously chosen, not simply installed.`,
      negative: `An unexamined paternal belief keeps running quietly in the background — either swallowed whole as unquestioned truth or rejected wholesale as pure reaction, with the same restless spiritual question resurfacing in new disguises.`,
    },

    // ── 9 in MATERNAL SPIRITUAL (Ancestral Square, Age-30 anchor) ───────────
    '9_G': {
      heading: `You Learned Depth Before You Learned to Speak It`,
      why: `The spiritual inheritance passed down through your mother's line arrived mostly through silence rather than instruction — an inward, private relationship to meaning, faith, or inner knowing that was modeled more than it was taught. The Hermit sits in your Maternal Spiritual corner, and the gift here is real: you likely carry an inherited capacity for genuine solitary depth, an ability to sit with the unanswerable that most people never develop. But because it arrived wordlessly, you may have also inherited the assumption that the deepest spiritual matters aren't things you talk about — that the correct response to the sacred is to go quiet and go inward, the way the maternal line did before you.`,
      shadow: `This can show up as a spiritual life that stays entirely private by default — not because you chose that, but because the maternal lineage never modeled another option. You might have genuine wisdom that never gets offered to the people who could actually use it, or a quiet, generational loneliness — women in your line who each carried real inner depth alone, never quite realizing the people around them were carrying something similar in the same silence. If you keep feeling spiritually or emotionally unseen by the people closest to you, generation after generation, that's less a personal failing than an inherited pattern that was never given the chance to become spoken.`,
      path: `Try honoring the depth of what was passed down while consciously giving it a voice the generations before you may not have had access to. That doesn't mean abandoning your inward orientation — the solitary depth is a genuine gift — it means occasionally bringing what you find there back out into relationship, breaking a silence that was inherited rather than chosen. Every time you speak the maternal line's quiet wisdom out loud, you complete something that was waiting, for at least one generation, to finally be received.`,
      positive: `You carry the maternal line's genuine capacity for depth and inner knowing, and you've learned to voice it — sharing what was historically kept silent, so the wisdom actually reaches people instead of staying inherited-but-unspoken.`,
      negative: `A default, inherited silence keeps real depth from ever being offered — the same quiet, generational loneliness repeats itself because going inward was modeled, and speaking outward never was.`,
    },

    // ── 21 in PATERNAL MATERIAL (Ancestral Square, Age-50 anchor) ───────────
    '21_H': {
      heading: `You Come From a Line That Kept Almost Finishing`,
      why: `The material legacy from your father's line — how to build, provide, and arrive at a durable, complete result — was oriented toward genuine mastery, not just survival. The World sits in your Paternal Material corner, and it points to a paternal lineage working, at some level, toward full arrival: a finished house, a business brought to maturity, a life's work rounded into something whole. Whether or not anyone in that line actually reached full completion, the orientation itself — build toward whole, not partial — is what arrived in you materially through your father's side.`,
      shadow: `The risk is an inherited material perfectionism: the sense that nothing truly counts as built until it's completely, unquestionably finished, which can make you reluctant to claim real progress that just isn't total yet. This can also show up as a generational pattern of almost-arrivals — a father's line where the business nearly succeeded, the property was nearly paid off, the plan nearly reached its full form, again and again, one generation handing the nearly-there quality to the next along with the unfinished project itself. A financial life that keeps feeling permanently one stage short of secure is often this inherited orientation toward totality, still waiting for someone in the line to actually let a cycle complete.`,
      path: `Try being the one who actually closes a cycle your paternal line kept almost-closing. Let material progress count as real before it's total — recognize a milestone as an actual arrival rather than a waypoint to some further, always-receding finish line. You inherited the orientation toward mastery. The specific gift you can offer your line now is completion itself — permission to say a stage of building is genuinely, currently done.`,
      positive: `You bring real material projects to genuine completion rather than permanent near-arrival — closing cycles your father's line kept almost-closing, and letting milestones count as real before they're total.`,
      negative: `An inherited material perfectionism keeps everything one stage short of finished — the family pattern of the nearly-there business, the nearly-paid-off property, repeating because completion itself was never modeled as achievable.`,
    },

    // ── 7 in MATERNAL MATERIAL (Ancestral Square, Age-70 anchor) ────────────
    '7_I': {
      heading: `You Learned to Steer, Never to Ask for a Hand`,
      why: `The practical, material navigation skill passed down through your mother's line was one of directed forward motion under difficult conditions — women who kept moving, kept the household or the finances or the family's practical survival on a chosen course, often without the luxury of stopping to ask whether the direction was actually sustainable. The Chariot sits in your Maternal Material corner, a real inheritance of resourcefulness and determination. What often comes bundled with it is an equally inherited belief that the only way to keep the material vehicle moving is to drive it entirely alone.`,
      shadow: `This can show up as a material life organized around solo endurance — inherited specifically from the maternal line's survival strategy, the assumption that asking for help, sharing the load, or admitting the current direction isn't working would be a kind of failure the women before you didn't allow themselves either. You might notice chronic overextension around money and logistics, a reflexive refusal of support even when it's genuinely offered, an exhausting sense that everything practical depends on you continuing to steer alone. A financial or logistical life that feels perpetually solo, even when people are actually available to help, is often this maternal navigation pattern still running on old terrain.`,
      path: `Try steering the vehicle your mother's line handed you while actually letting other hands touch the reins. This isn't a rejection of the pattern — you keep the real skill of directed, resourceful movement, but you update the belief that it requires total solitude. Practically: let one material task — a bill, a decision, a piece of the load — be shared instead of solely carried, and notice that the vehicle keeps moving anyway. The maternal line's resourcefulness was real. The solo-driving belief was circumstance, not law, and you're free to update it.`,
      positive: `You carry your mother's line's real material resourcefulness and directed determination, while letting genuine help actually reach you — the vehicle keeps moving because more than one set of hands is finally on the reins.`,
      negative: `An inherited belief that material survival must be steered entirely alone keeps you chronically overextended — support goes reflexively refused even when it's genuinely available, echoing a pattern that was once circumstance, not law.`,
    },

  }; // end nodes


  // ── GENERAL FALLBACK — ALL 22 ARCANA ─────────────────────────────────────

  const general = {

    1: {
      heading: `You Bring Things Into Being Just by Beginning`,
      why: `You don't wait for conditions to be perfect. Some part of you understands, on a level that doesn't need rational explanation, that the right conditions tend to show up in response to the act of starting — not before it. Wherever the Magician lives in your matrix, it marks a place where you carry, or are still discovering, a real capacity to generate reality from attention and intention. This is the frequency of pure origination — the moment before the moment, where something that didn't exist becomes possible because you moved first.`,
      shadow: `Disconnected from its source, this energy can turn into manipulation — using a very real power to shape perception and direct attention toward outcomes that serve your ego rather than what's genuinely unfolding. You might also notice a pattern of scattered starts: beginning brilliantly and then dissipating, moving to the next idea before the first has taken root, because finishing takes a different kind of energy than starting, and you haven't quite learned to supply it yet. A life full of starts that never land isn't bad timing repeating itself — it's the frequency of "beginning" being sent out again and again, with no matching signal of "sustaining" for the world to actually respond to.`,
      path: `Try grounding the gift. Ask not just "what can I bring into being," but "what am I actually willing to sustain." The tools on the Magician's table aren't decorative — they represent all four elements, all four domains of a life. Mastery comes from working with all of them, not just the ones that come naturally. Once you're genuinely broadcasting follow-through, the collaborators and conditions that can match that frequency finally have something to respond to.`,
      positive: `You generate momentum from nothing more than clear intention, and the conditions for success assemble themselves in response to a frequency of genuine follow-through, not just enthusiasm for the start.`,
      negative: `A pattern of brilliant starts that never take root is the world matching the actual frequency being sent out — the energy of beginning, offered again and again, with no matching signal of sustained commitment for reality to respond to.`,
    },

    2: {
      heading: `Your Best Guidance Arrives in Stillness`,
      why: `You know things in a way that's hard to translate into the language the outside world tends to reward — the language of proof, certainty, explicit justification. Wherever the High Priestess lives in your matrix, it marks a place governed by depth, the intelligence of your interior, and cyclical rhythms that resist being forced into straight lines of logic. Your most reliable guidance is the kind that shows up in stillness — not the kind you can argue your way to.`,
      shadow: `The shadow here is passivity wearing the costume of wisdom. There's a real difference between genuine receptivity — which is actually an active, disciplined stance — and passive withdrawal that avoids the discomfort of acting by dressing itself up as "waiting for clarity." You might also use your sensitivity as a kind of privacy screen — perceiving other people so clearly that they can't perceive you back, which feels safe but costs you real connection. If your relationships keep stopping short of real intimacy, that's often just matching the actual signal you're sending: come close enough to be understood, not close enough to be truly known.`,
      path: `Try acting from your knowing, not despite the uncertainty that always comes with it. The High Priestess doesn't wait until the mystery resolves — she steps forward inside the mystery, with it. That's the lesson: your interior intelligence isn't a substitute for engaging with the world, it's a way of engaging with it that the world genuinely needs. The more visible you let that knowing be, instead of keeping it private, the more the world starts offering back the depth of connection it's been quietly withholding to match your own reserve.`,
      positive: `Your most reliable guidance arrives in stillness, and you act on it visibly enough that the world responds in kind — real depth and understanding meeting you back at the level you were willing to first extend it.`,
      negative: `Perceiving others clearly while staying unreadable yourself keeps genuine intimacy at a careful distance — the relationships that arrive stay shallow because that's precisely the depth your own guardedness has been signaling is safe.`,
    },

    3: {
      heading: `You Give Best When You're Giving From Overflow`,
      why: `You're capable of extraordinary generosity — and you're also, quietly, still learning the difference between giving from genuine abundance and giving to manage the anxiety of needing to be needed. Wherever the Empress lives in your matrix, it marks a position infused with creative abundance: not just artistic creativity, but the generative principle itself — the capacity to bring things into being, nurture them through their stages, and hold the conditions that let other living things flourish. The Empress doesn't create from scarcity. She creates from overflow.`,
      shadow: `The trap here is the codependency of the natural nurturer — your sense of self getting so wrapped up in caretaking, in creativity-in-service-of-others, that you lose touch with what you actually want to make for yourself. You might also notice a pull toward indulgence — using sensory pleasure or creative output as a buffer against sitting with an unprocessed feeling. If your life keeps handing you people and situations that need endless tending, that's not simply bad luck — it's often responding to a quiet equation you've made between being needed and being loved, and it will keep manifesting exactly the dependents required to confirm it.`,
      path: `Try figuring out what you want to create when the creation is entirely, unapologetically for you. Not for approval. Not for someone's growth. Not to prove your value. Just because it calls to you. That's where this energy reaches its full strength — and it's also what finally changes what you draw toward you: relationships built on genuine mutual generosity instead of one person's need to be needed.`,
      positive: `You create and nurture from genuine overflow, and the relationships that reach you mirror that abundance back — connection built on mutual generosity rather than on one person's need to be needed.`,
      negative: `When your worth quietly gets tied to being needed, life tends to keep sending you people and situations that require endless tending — obligingly supplying the dependents required to keep confirming that caretaking is the price of being loved.`,
    },

    4: {
      heading: `You Build the Container Others Grow Inside`,
      why: `Wherever the Emperor lives in your matrix, it marks a place where order, authority, and structural intelligence are asking to be integrated. This isn't about imposing structure for its own sake — the deepest version of this energy comes from someone who genuinely understands why structure exists: without it, what you're building can't hold its own weight. In this part of your life, you've either inherited a very specific set of rules about how things should work, or you're being asked to build the foundational container that lets something important actually grow.`,
      shadow: `Operating from fear, this energy turns into rigidity — maintaining structure as an end in itself, even once it's stopped serving life and started containing it instead. That can look like an inability to tolerate uncertainty, enforcing rules mainly because your own sense of stability depends on them being followed, treating genuine creativity or spontaneity as a threat rather than a resource. It's worth noticing: a life full of people resisting your authority rather than recognizing it usually isn't a coincidence of difficult personalities — it's the world matching a kind of control that's coming from fear, not from real strength.`,
      path: `Try learning to tell the difference between structures that protect and structures that imprison — and have the courage to renovate the second kind without tearing down the first. Real authority doesn't need to be enforced. It gets recognized. Your work is building things strong enough to also be genuinely flexible — and the more your own relationship to authority relaxes out of fear, the less resistance you'll find yourself needing to manage in the people and structures around you.`,
      positive: `You build containers strong enough to let something important grow, and because your authority comes from genuine stability rather than fear, the people around you recognize and cooperate with it rather than resisting it.`,
      negative: `Rigid rules enforced from fear keep drawing resistance rather than recognition — the more the grip tightens to manage an internal sense of instability, the more the external world seems to rebel against it.`,
    },

    5: {
      heading: `You Carry Knowledge That's Meant to Move`,
      why: `Wherever the Hierophant lives in your matrix, it marks a place shaped by an awareness of social and spiritual codes — not as arbitrary rules, but as the accumulated crystallization of what previous generations learned the hard way. This energy carries the frequency of transmission: knowledge that moves through relationship, through teaching, through the passing of something carefully cultivated from one generation or context to the next. Your gift here is a genuine respect for what took time and difficulty to earn.`,
      shadow: `The shadow is living transmission turning into static doctrine — knowledge you defend instead of offer, tradition you enforce instead of invite people into, spiritual authority that becomes a position rather than a service. A specific trap for you: needing the student to remain a student, because your identity depends on there being someone who knows less. If students quietly drift away, or never quite surpass you, that's not simply an unlucky run of unmotivated people — they're often meeting the actual frequency you're offering, which is transmission conditioned on staying beneath you rather than genuinely rising.`,
      path: `The best version of this is a teacher who genuinely celebrates when the student surpasses them — someone who understands that the real goal of teaching is to eventually become unnecessary. That's the most advanced expression of this gift, and it requires real freedom from the part of your ego that's organized around being the one who knows. Once that freedom is real, the caliber of student and the depth of relationship that reach you rises to match it.`,
      positive: `You offer what you know freely enough that students genuinely rise past you, and that same generosity is what draws deeper knowledge and better collaborators back toward you in turn.`,
      negative: `A need to keep the student dependent quietly caps the relationship's growth — the frequency of "stay beneath me" is what students eventually sense and drift away from, or simply never outgrow.`,
    },

    6: {
      heading: `Your Choices Are Asking for Your Real Values`,
      why: `Wherever the Lovers live in your matrix, it marks a place governed by the fundamental experience of choice — specifically, by what happens inside you in the moment of genuinely choosing. This isn't primarily about romance. It's about the crossroads — the moment two genuinely different paths diverge, where logic alone can't decide, and where choosing one thing necessarily means leaving another behind. Here, you're being asked, again and again, to make choices that reflect your actual values rather than your desire to avoid conflict.`,
      shadow: `The shadow is indecision dressed up as openness — keeping every option alive as a way of avoiding the grief of the roads not taken. There's also a specific pattern of leaning on other people, circumstances, or belief systems to tell you what the right choice is, because real self-determination feels too exposing. This can show up as chronic people-pleasing: quietly subordinating your own preferences to keep the peace, until you've lost touch with what you actually want. If life keeps handing you decisions made for you instead of with you, that's often the world honoring the vacancy you left where your own choice was supposed to be.`,
      path: `Try letting yourself grieve the unchosen path as a way of honoring the one you did choose. Every real decision is also a real loss. Becoming someone who can make a choice and fully commit to it — while acknowledging what got released in that commitment — is exactly what this position is asking of you. The more clearly you occupy your own preference, the less the world seems to need to choose for you.`,
      positive: `You make choices that genuinely reflect your values and commit to them fully, and because that decisiveness is real, the people and circumstances around you stop trying to fill a vacancy you no longer leave open.`,
      negative: `A pattern of others deciding for you is not simply pushy people — it is the world filling the exact space left by an unoccupied preference, matching the vacancy with decisions made on your behalf.`,
    },

    7: {
      heading: `You're Meant to Steer, Not Just Endure`,
      why: `Wherever the Chariot lives in your matrix, it marks a place infused with navigation, direction, and the disciplined application of will toward a chosen course. This is one of the most internally demanding energies in the system — not because it requires force, but because it requires a sustained kind of self-authorship most people only touch in brief moments. Here, you're being asked to steer — to hold a direction that comes from genuine inner knowing rather than from whatever your environment happens to be pulling you toward.`,
      shadow: `The shadow is control that's lost its relationship with trust — gripping the reins so tightly the horses can't move with their own intelligence, mistaking iron self-discipline for genuine mastery, treating any deviation from the plan as personal failure. There's also the shadow of the solitary driver: struggling to let anyone else contribute to the journey, convinced that collaboration will compromise your direction. If you keep ending up with unreliable collaborators, that's often just meeting a frequency that never actually left room for anyone else to drive.`,
      path: `Mastery here doesn't mean you never veer — it means you know how to find your true north again after you do. The work is flexibility within your direction: trusting the horses enough to loosen the reins when the terrain calls for it, knowing the destination remains. That same trust is what finally lets genuinely capable people show up to help, because you're no longer sending a signal that leaves no room for them.`,
      positive: `You steer with genuine self-authorship while trusting others enough to let them actually contribute — and because that trust is real, capable collaborators keep showing up to help carry the direction.`,
      negative: `A grip too tight for anyone else to help drive keeps attracting collaborators who never quite measure up — not because good help is scarce, but because the frequency never left room for it to arrive.`,
    },

    8: {
      heading: `Fairness Starts With How You Judge Yourself`,
      why: `Wherever Justice lives in your matrix, it marks a place governed by balance, accountability, and the precision of genuine truth — not the truth that wins arguments, but the kind that's still standing after the argument ends. Here, you carry both the capacity and the responsibility to see clearly, call things by their accurate names, and hold yourself and others to a standard grounded in real fairness rather than in preference.`,
      shadow: `The shadow is being the judge who's never turned the scales on themselves — holding others to an extraordinarily high standard while quietly exempting your own behavior. There's also a pull toward black-and-white thinking, compressing genuinely complicated situations into simple verdicts, which can hurt your relationships and leave you feeling perpetually caught between an impossible standard and the inevitable shortfall. If life keeps handing you people to judge, that's rarely bad luck — it's often unresolved self-judgment finding somewhere external to land.`,
      path: `Try applying this gift's own medicine, compassionately, to yourself first — turning that honest, precise gaze inward. Not to condemn yourself; that's not what this is about. It's about calibration — making sure what you're asking of the world, you're genuinely offering yourself too. Once the scales settle within you, the external verdicts you used to attract have a lot less material to work with.`,
      positive: `You see clearly and call things by their accurate names, holding yourself to the same honest standard you hold others to — and because the scales are settled internally, the world stops handing you so much to judge.`,
      negative: `An unconscious exemption for yourself keeps drawing people and situations that mirror exactly the imbalance you refuse to see in your own conduct — the world supplying fresh material for a verdict that was never really about them.`,
    },

    9: {
      heading: `What You Learned Alone Was Never Just for You`,
      why: `Wherever the Hermit lives in your matrix, it marks a place governed by deep internal wisdom — the kind that comes not just from study but from genuine solitary integration of what you've lived through. Some of your most important knowing was gathered in periods of withdrawal, quiet, choosing depth over surface. You carry a lantern here not for your own navigation — you already know the path — but to light the way for others still finding their footing in the dark.`,
      shadow: `The shadow is withholding that dresses itself up as wisdom — believing that what you've gathered alone is too refined, too hard-won, or just too hard to translate for people who haven't done the same work. This can shade into isolation that's no longer a chosen practice of renewal but a permanent state — a life organized around protecting the conditions of contemplation instead of actually engaging with people. If the world keeps feeling distant and unreachable, that's often just a lantern that's quietly turned inward instead of out.`,
      path: `You've gathered something real in your solitude. The real question is what you'll do with it — not in a utilitarian sense, but in the deeper sense of recognizing your light was never just for you. Practice translation: finding language that makes what you know available to people around you without watering it down. As the lantern turns outward, connection stops feeling scarce, because you've finally given it something to gather around.`,
      positive: `Deep, hard-won inner knowing becomes a lantern for others, and because you're genuinely willing to translate and share it, connection and recognition gather around you rather than staying just out of reach.`,
      negative: `A lantern kept turned inward is what keeps the world feeling distant — withholding what you've gathered in the name of humility only confirms the isolation it was meant to protect against.`,
    },

    10: {
      heading: `Your Stability Lives in the Center of the Wheel`,
      why: `Wherever the Wheel of Fortune lives in your matrix, it marks a place infused with cycles, timing, and the intelligence of turning. Everything in material reality moves in cycles — seasons, economies, relationships, creative work, even your own internal states. Here, you're being asked to build a relationship with the turning of things: to recognize that what goes down eventually comes back up, and that what's up isn't permanent either — and to find your stability not in the wheel's position, but in your relationship to its center.`,
      shadow: `The shadow is experiencing cyclical change as something happening to you rather than through you. Operating from fear, that shows up as either a desperate grip on control — trying to freeze the wheel at its high point — or a passive resignation that uses "what goes up must come down" as an excuse not to fully invest in the upswing. If life keeps confirming "things always fall apart for me," that's often just the belief being handed back to you exactly as it was sent out — expectation working as a self-fulfilling frequency.`,
      path: `The deepest lesson here is active surrender, not passive giving-up. You don't resist the current — you learn to read it well enough to navigate within it. Start by mapping your own cycles: your creative rhythms, your social energy, your motivation. Over time you'll see the pattern, and in seeing it you'll find the stability this position is actually offering — one that stops broadcasting "collapse is coming" and so stops calling it in.`,
      positive: `You locate your stability in your relationship to the cycle itself, and because you're not broadcasting a fear of the downswing, the upswings you invest in get to run their full, uninterrupted course.`,
      negative: `A belief that things always eventually fall apart becomes a self-fulfilling frequency — the anxious grip on the high point, or the passive resignation before the low, calls in the exact collapse it was bracing for.`,
    },

    11: {
      heading: `Real Strength Doesn't Need to Prove Itself`,
      why: `Wherever Strength lives in your matrix, it marks a place where genuine power — not dominance, not force, but the quiet, sustained, deeply embodied kind of strength that tames rather than breaks — is asking to be expressed. Think of the gentle hand at the jaw of the lion: not overpowering the animal, but working with its nature. Here, you have real capacity, real endurance, a real ability to hold what others can't. And here, the difference between strength-as-service and strength-as-armor is the central question your life keeps asking.`,
      shadow: `The shadow is an identity built entirely around capability — unable to rest because resting feels like weakness, unable to receive help because receiving feels like incompetence, unable to show vulnerability because somewhere early on, vulnerability had real consequences for you. The physical cost adds up: your jaw, your lower back, your heart working overtime against a baseline of suppressed effort. If life keeps handing you people who lean on you but never lift, that's often matching a frequency that's never actually signaled it wants to be helped.`,
      path: `Real strength at this level isn't the absence of vulnerability — it's the capacity to stay present with vulnerability, yours and other people's, without needing to fix it immediately. That's the lion tamed, not broken — trusted, not suppressed. Once vulnerability is genuinely welcomed instead of defended against, the people who show up start offering real reciprocity instead of just more weight to carry.`,
      positive: `You hold real weight for others with a quiet, embodied endurance, and because you're genuinely open to receiving in return, the people around you offer real reciprocity rather than simply more to carry.`,
      negative: `A capability that never signals it wants help keeps attracting people who lean without lifting — the world matching the exact frequency of a strength that has never once asked to be met halfway.`,
    },

    12: {
      heading: `Some of Your Best Growth Happens Upside Down`,
      why: `Wherever the Hanged Man lives in your matrix, it marks a place infused with voluntary suspension — the willingness to let go of a position, a certainty, or a direction of movement in order to see something a different orientation simply couldn't show you. He's not a victim; he chose his place on the tree, and in releasing the ground beneath his feet, he discovers the world looks entirely different upside down. Here, your most significant growth has come, or will come, through the willingness to stop pushing and let something be revealed.`,
      shadow: `The shadow is martyrdom that won't admit it's chosen — voluntary suffering that gets framed as circumstance, sacrifice offered publicly and tracked carefully, a suspension that's gone on well past its teaching moment because being "the one who waits, who endures, who is misunderstood" has become more comfortable than actually returning to active life. If the world keeps failing to notice your sacrifice, that's not cruelty — it's often responding to a frequency that's quietly stopped expecting the return to actually happen.`,
      path: `Try recognizing that the suspension has both a purpose and an endpoint. You don't hang forever. The Hanged Man eventually comes down — changed, expanded, carrying knowledge only that particular angle could have given him. Ask yourself: what am I seeing differently from here that I couldn't see before? And then: what do I do with this new sight once I return to the ground? The moment you genuinely expect the descent, the ground has a way of showing up to meet you.`,
      positive: `You can voluntarily release a certainty in order to see from a new angle, and because you genuinely expect the return to active life, the ground reliably reappears when it's time to come down.`,
      negative: `A suspension that has quietly stopped expecting its own end keeps the ground from reappearing — the world matches an identity that has stopped believing the waiting was ever going to conclude.`,
    },

    13: {
      heading: `What Needs to End Is Making Room for What's Next`,
      why: `Wherever Transformation lives in your matrix, it marks a place governed by metamorphosis — specifically, the kind that can't happen without a genuine release. Not the controlled, scheduled kind of change, but the deep, cellular kind: a form that's completed its function dissolving so something more aligned can take its place. Here, clinging to what's already ended is the specific obstacle, and letting something fully die — a belief, a relationship, a version of yourself, a strategy that once worked — is the exact doorway to what comes next.`,
      shadow: `The shadow is someone who's survived so many real endings that they develop a kind of unconscious pull toward crisis — recreating the intensity of transformation as drama because the stillness of settling down feels dangerously close to the stillness before collapse. There's also the opposite pattern: refusing any real ending, keeping things alive through sheer will past their natural completion, accumulating the weight of what should have been released. If life keeps delivering abrupt collapses, that's often just matching a frequency still bracing for one — refusing the quieter release that was actually available.`,
      path: `Real mastery here comes from developing discernment — being able to sit with something and honestly ask whether it's in a difficult phase that wants working through, or whether it's actually completed and wants to be honored and released. These call for very different responses, and learning to tell them apart is the work. Once genuine endings are allowed to complete quietly, reality stops needing to manufacture dramatic ones just to get your attention.`,
      positive: `You let things end cleanly when they've actually completed, and because your relationship to endings is calm rather than crisis-driven, transitions arrive gently instead of as sudden collapse.`,
      negative: `A refusal to let anything genuinely end keeps accumulating weight until reality manufactures a dramatic collapse to force the release that a quiet letting-go could have handled all along.`,
    },

    14: {
      heading: `Your Genius Is Patient Combination`,
      why: `Wherever Temperance lives in your matrix, it marks a place infused with integration — specifically, the alchemical kind that combines apparently incompatible elements into something genuinely new. Picture Temperance pouring liquid between two cups, endlessly, with total patience — not because she doesn't know what she's doing, but because combining things takes exactly as long as it takes, and rushing it produces something other than what was intended. Here, your particular kind of genius involves patiently synthesizing opposites — ideas, people, timelines, strategies — that others can't imagine coexisting.`,
      shadow: `The shadow is a false middle ground — avoiding the discomfort of real polarity by papering it over with a premature harmony that doesn't actually satisfy anyone. There's also a pattern of avoidance through perpetual balancing: staying so focused on managing the equilibrium that genuine depth — which sometimes requires tipping fully into one direction before you can know the other — never quite becomes available. Relationships and situations that keep feeling watered-down instead of resolved are often matching a frequency that's been avoiding real contact rather than genuinely blending anything.`,
      path: `Try fully inhabiting the extremes long enough to actually understand them from the inside before you try to combine them. You can't blend what you haven't genuinely encountered. Your work is to stop moderating your experience prematurely and trust that the combining will happen — it just needs the full intensity of each ingredient first. Once you allow that intensity, life stops handing you diluted, unresolved versions of what you actually want.`,
      positive: `You patiently synthesize things that seem incompatible into something genuinely new, and because you let each ingredient reach full intensity first, what you draw together actually holds.`,
      negative: `A premature, papered-over harmony keeps drawing situations that feel watered-down rather than resolved — the avoidance of real polarity showing up as relationships and outcomes that never quite land.`,
    },

    15: {
      heading: `What You're Bound To Isn't Locked — It's Loose`,
      why: `Wherever the Devil lives in your matrix, it marks a place where material power, primal attachment, and the shadow of your relationship to security are asking to be honestly faced. This isn't evil in a cartoonish sense — it's the very human experience of being bound to something — a substance, a relationship dynamic, a financial pattern, a belief — that you know isn't serving your highest self but that offers a comfort or stimulation you haven't yet found a real substitute for. In the classic image, the figures aren't locked in chains — they're loosely bound, and the chains could slip off at any moment. The real question is what it would mean to let them.`,
      shadow: `The shadow is using material power — money, status, physical dominance, sexual energy — as a substitute for genuine intimacy or self-worth. Caught here, you can mistake accumulation for security, and control for love. There's also a pattern of projection: putting your own shadow qualities onto other people, which keeps you stuck in repetitive cycles of resentment and feeling like a victim. A cycle of people who seem to consistently take advantage of you is often the frequency of an unexamined attachment recreating the exact dynamic it resents.`,
      path: `The liberation here isn't eliminating pleasure or material engagement — it's unchaining pleasure from compulsion. The ability to fully enjoy something without needing it. To engage with the material world as a genuine participant rather than someone in its service. Start by naming what you're actually attached to, and ask, with honest curiosity instead of self-judgment, what that attachment is actually providing you. As the compulsion loosens, the relationships and resources that show up stop mirroring the old bind back to you.`,
      positive: `You engage fully with pleasure, money, and the material world as a genuine participant, and because the chains are genuinely loose, the relationships and resources that arrive feel like abundance rather than compulsion.`,
      negative: `An unexamined attachment to control or security keeps recreating the exact dynamic it resents — the same bind, mistaken for love or safety, showing up again in a different disguise.`,
    },

    16: {
      heading: `Sometimes You Have to Watch It Fall to See It Clearly`,
      why: `Wherever the Tower lives in your matrix, it marks a place governed by sudden, lightning-strike revelation — clarity that restructures reality faster than the mind can process it. The Tower itself isn't the collapse — it's the clarity the collapse makes available. Whatever was built on a false foundation eventually reveals itself, not as punishment but as structural inevitability. Here, you've experienced — or will experience — a moment of radical reorganization that felt like destruction from the inside, but turned out, in hindsight, to be the most important reorientation of your path.`,
      shadow: `The shadow is identifying so deeply with the drama of collapse that you recreate it over and over — burning down structures that still worked, out of a compulsive need for the intensity of that moment, or the freedom from responsibility a real crisis temporarily hands you. There's also the opposite: staying so afraid of the Tower that you maintain increasingly fragile structures through sheer will, refusing to let anything naturally complete, so the eventual collapse carries far more weight than it needed to. A life of repeated dramatic upheaval is rarely bad fortune — it's often a frequency still identified with crisis as the only believable form of change.`,
      path: `Try initiating necessary endings before they initiate themselves — surveying your life honestly and asking which structures rest on true foundations and which are being held up by pure avoidance. This isn't nihilism. It's architectural intelligence applied to how you're building your life. Once change no longer has to arrive as crisis to feel real, reality stops needing to deliver it that way.`,
      positive: `Sudden clarity becomes a tool you can use deliberately, and because change no longer needs to arrive as crisis to feel real, transitions in your life get to unfold gradually instead of catastrophically.`,
      negative: `An identity still organized around crisis as the only believable form of change keeps summoning collapse to prove that change is actually happening — the drama becoming necessary rather than incidental.`,
    },

    17: {
      heading: `Your Light Was Built to Meet the Wound, Not Float Above It`,
      why: `Wherever the Star lives in your matrix, it marks a place infused with genuine hope — not the brittle, conditional kind that depends on outcomes, but the structural kind: the ability to keep generating light even when nothing outside confirms that the light is warranted. In the Tarot, the Star follows the Tower — she rises after the collapse, pouring water from two vessels onto the earth and the stream at once, healing what broke, replenishing what emptied out. Here, your capacity for renewal is one of your most genuine gifts to the people around you.`,
      shadow: `The shadow is idealism that hasn't yet learned to land — a vision of what's possible so luminous it perpetually outpaces the actual, present, imperfect moment in front of you. That creates a quiet, persistent grief — the gap between the world as it is and the world as you see it could be — which can make close relationships genuinely hard, because no actual person can sustain the frequency of their own highest potential without interruption. A life that keeps disappointing your vision of it isn't the world failing you — it's often a light permanently pointed at potential instead of what's actually here to be met.`,
      path: `Try bringing your light into the wound instead of holding it above it. Not pretending the wound isn't there, not transcending it, but literally pouring light into the broken place and trusting the process to regenerate from there. That means being willing to get close to what's damaged — including in yourself — instead of keeping the vision of wholeness at a safe distance. Once your light meets what's actually present, the world stops arriving as a disappointment and starts arriving as material to work with.`,
      positive: `You generate genuine hope and renewal by meeting what is actually present rather than only its potential, so relationships and circumstances feel met and nourished instead of quietly judged against a vision.`,
      negative: `A frequency permanently pitched toward potential rather than the present keeps the actual world arriving as a disappointment — no person or moment can ever quite satisfy a light that's aimed somewhere else.`,
    },

    18: {
      heading: `Trust What You Sense Before You Can Explain It`,
      why: `Wherever the Moon lives in your matrix, it marks a place governed by the deep unconscious — the psychic and emotional currents moving beneath daily awareness, and the cyclical, non-linear intelligence of your interior life. The Moon doesn't illuminate the way the Sun does. It offers a softer, more ambiguous light that outlines things without fully explaining them — and that's not a failure, it's the Moon's specific contribution. Here, your most reliable guidance arrives through dreams, through the body, through a felt sense that something is true before you can say why.`,
      shadow: `The shadow is confusion that comes when your inner and outer worlds stop being clearly distinguishable — when the emotional weather of your subconscious gets projected onto circumstances without you recognizing it as projection. This can look like paranoia, a sense that reality is fundamentally threatening or deceptive, a chronic difficulty trusting appearances because you're always sensing what might lie underneath them. There's also the shadow of escapism — using the Moon's gift for fantasy and interior richness as a substitute for actually showing up in your life. A world that keeps confirming your suspicion is often just an unexamined subconscious mood finding matching evidence wherever it looks.`,
      path: `Try learning to move through the deep water without being swept away by it — keeping a thread back to the surface even while you're diving. This takes practices that ground your interior world in the physical: movement, breath, the specific materiality of your body as an anchor point for the sensitivity you carry. The clearer that anchor gets, the less circumstance is available to be misread as confirmation of an old fear.`,
      positive: `You sense what's true before you can explain it, and because your interior world is genuinely anchored, that intuition reads real undercurrents rather than projecting old fears onto ambiguous circumstances.`,
      negative: `An unexamined subconscious atmosphere gets projected outward and then finds matching "evidence" everywhere it looks — deepening a suspicion of reality that was never actually about the present moment.`,
    },

    19: {
      heading: `You Shine Because That's Just What You Do`,
      why: `Wherever the Sun lives in your matrix, it marks a place infused with genuine vitality — the kind that radiates outward not as performance, but as the natural consequence of being authentically alive in the direction of your actual nature. The Sun doesn't try to shine. It shines because that's what it does. Here, your most natural state — when you're not managing how other people perceive you, not dimming yourself to avoid the discomfort of your own brightness — is warmth, clarity, and the kind of joyful engagement with life that other people find both inspiring and, sometimes, a little confronting.`,
      shadow: `The shadow is confusing your radiance with your worth — needing to be the brightest source of light in any room, and feeling genuinely destabilized when someone else brings a comparably vivid energy. There's also a pattern of "burning" people — projecting so much intensity onto the people closest to you that they can't actually grow in your light, because there's simply too much of it. Wilted relationships that keep resulting aren't bad luck — they're the world honestly reporting back the actual heat being given off.`,
      path: `Try being genuinely delighted by other people's light — expanding in the presence of someone else's brightness instead of competing with it. That's this energy at its most evolved: not a single sun, but part of a galaxy. Your vitality, when it's genuinely integrated, becomes a climate other things can grow in — and a climate that lets other things grow is what finally draws people who want to stay in it.`,
      positive: `Your natural warmth and vitality become a climate other people genuinely grow in, and because your light doesn't need to compete, the people closest to you flourish rather than shrink or scorch.`,
      negative: `A need to be the brightest source of light in every room scorches what it touches, and the wilted or distant relationships that result are the world accurately reflecting the actual heat being given off.`,
    },

    20: {
      heading: `The Call Rarely Waits for You to Feel Ready`,
      why: `Wherever Judgement lives in your matrix, it marks a place governed by awakening — the moment the old version of you becomes genuinely untenable, when the life you've been living stops fitting the person you've become, and the inner summons to something fuller can't be postponed much longer without real cost. Judgement isn't punishment — it's revelation. The figures rising from their coffins aren't being called to account for their failures; they're being called home to what they actually are. Here, you've heard, or are about to hear, exactly this kind of summons.`,
      shadow: `The shadow is hearing the call and then spending years preparing to answer it — reading more, learning more, clearing more, refining more — because actually answering means being seen in full, and being seen in full feels, from the inside, like risking everything. There's also a pattern of perpetual reckoning without resolution: using self-awareness to maintain constant self-examination that substitutes for actually moving. A life that keeps signaling "not yet ready" is broadcasting exactly that, and the world simply keeps agreeing.`,
      path: `Answering this call doesn't require perfection, and it doesn't require clearing everything that's come before. It requires one courageous act: rising from where you've been lying down and starting to move in the direction the trumpet's pointing. The rest reveals itself in the moving — and the moment you actually move, the opportunities that once seemed to be waiting on your readiness start meeting you partway.`,
      positive: `You answer the summons when it arrives rather than endlessly preparing for it, and because you're actually moving, the opportunities and recognition you were waiting to feel ready for start meeting you partway.`,
      negative: `Endless preparation broadcasts "not yet ready" more clearly than any spoken doubt could — and the world, quietly matching that frequency, keeps agreeing and withholding the very opening you're waiting for.`,
    },

    21: {
      heading: `You're Allowed to Call It Finished`,
      why: `Wherever the World lives in your matrix, it marks a place infused with genuine completion — not the artificial kind declared before the work is done, but the real kind that arrives once a full cycle has actually been lived through, integrated, and allowed to reach its natural end. The World is the last card of the Major Arcana before the cycle starts over with the Fool — its figure dances inside the wreath, held by four elemental beings, fully contained and fully free at once. Here, mastery — genuine, hard-won, quietly radiant mastery — is either already present or is exactly where this part of your life is heading.`,
      shadow: `The shadow is fearing completion itself — specifically, fearing that finishing something means facing the next beginning, and the next beginning carries all the uncertainty this cycle has already absorbed. This can look like perfectionism that blocks completion: always one more thing to refine, one more element to add, one more preparation before it's "done." It can also look like compulsively restarting — dismantling something nearly finished, not because it's wrong but because completion itself feels too exposing. A life full of unfinished projects is broadcasting "almost" as its steady frequency, and the world keeps handing back exactly that: near-misses, not arrivals.`,
      path: `Try standing fully in what you've already accomplished before launching the next cycle. Let something actually be finished. Receive the completion before you move on. That's one of the most underrated acts of courage in a culture that rewards constant motion — the willingness to stop, acknowledge that something real got built here, and let that acknowledgment land. The moment completion is genuinely permitted, "almost" stops being what the world keeps handing back to you.`,
      positive: `You can stand fully in genuine completion, and because "finished" is a frequency you actually permit, recognition and reward arrive as real arrivals rather than as another near-miss.`,
      negative: `A frequency stuck on "almost" — never letting anything be genuinely done — keeps drawing near-misses rather than arrivals, the world simply matching the incompletion being broadcast.`,
    },

    22: {
      heading: `You're at Your Best Beginning Again With Your Eyes Open`,
      why: `Wherever the Fool lives in your matrix, it marks a place infused with pure potential — the energy of a beginning that hasn't yet been shaped by outcome, the step taken before the foot knows where it will land. The Fool isn't naive in the way people mean that as an insult — he carries a very specific intelligence: the intelligence of the present moment, unweighted by the accumulated baggage of past experience. Here, your most generative quality is your willingness to begin — again, and again, and again — without needing the safety of a guaranteed outcome.`,
      shadow: `The shadow is recklessness that refuses to absorb what previous cycles have already taught you — leaping repeatedly not from genuine freedom, but from an unexamined avoidance of the responsibility that growing up actually requires. In shadow, you can become the eternal beginner, using freshness as an exemption from depth, mistaking the excitement of starting for the richness only sustained engagement can give you. A life that keeps repeating the same lesson in a new costume isn't bad luck — it's often a refusal to actually absorb what you already encountered.`,
      path: `The most paradoxical achievement here is bringing the freshness, fearlessness, and genuine openness of a beginning through the full weight of your experience, rather than despite it. Knowing everything the previous cycles have taught you, and beginning again anyway, with your eyes open. That's this energy at full power — not innocent of difficulty, but genuinely undeterred by it. Once a lesson is genuinely absorbed instead of skipped past, life stops needing to hand it back to you in a new disguise.`,
      positive: `You begin again and again with real lessons genuinely absorbed rather than skipped past, so each new beginning meets fresh terrain instead of the same lesson wearing a different costume.`,
      negative: `Skipping past a lesson instead of absorbing it keeps that same lesson returning in a new disguise — the thrill of another fresh start standing in for the depth that was actually being asked for.`,
    },

  }; // end general


  // ── Public API ─────────────────────────────────────────────────────────────

  /**
   * get(arcanaNum, nodeKey)
   * Returns the richest content available for this arcana in this position.
   * Falls back to general[arcanaNum] if no position-specific entry exists.
   */
  function get(arcanaNum, nodeKey) {
    return nodes[arcanaNum + '_' + nodeKey] || general[arcanaNum] || null;
  }

  return { get };

})();
