'use strict';

/**
 * Destiny Matrix — Programs Database (Natalia Ladini system)
 * ----------------------------------------------------------
 * Each program is a 3-number combination found at specific
 * node intersections in the matrix. The `numbers` array is
 * order-independent — lookup matches any permutation.
 *
 * Fields mirror DMicroContent entries so they can render
 * inside the same info card:
 *   heading  — thematic title
 *   why      — core strategy / the subconscious tug-of-war
 *   shadow   — in the minus / the shadow self
 *   path     — integration / therapeutic recommendations
 *   health   — somatic / body manifestation (optional)
 */

window.DMPrograms = (function () {

  const programs = [

    // ── 1. SOCIAL STATUS & SELF-WORTH ──────────────────────────────────────

    {
      numbers: [16, 5, 7],
      name: 'Loss of Authority',
      category: 'Social Status & Self-Worth',
      heading: 'The Authority You Are Still Trying to Earn',
      why: `When the 16, the 5, and the 7 meet in the same program, they create one of the most psychologically complex tensions available in the matrix — a three-way negotiation between the collapse of established order (16), the inherited structure of social authority (5), and the deep drive toward purposeful, self-directed movement (7). The 16 is the Tower: the energy of sudden structural revelation, of what was built on a false foundation being returned to earth. In combination with the 5 — the Hierophant, the keeper of codes and institutional knowledge — this creates a person who has either witnessed or experienced a significant destabilization of authority: a father who fell from a position of power, a system that promised security and then withdrew it, a mentor who turned out to be less than their projected image. The 7 — the Chariot — enters this dynamic as the part of the psyche that is still trying to navigate forward despite having lost its map. The core strategy of this combination is the tension between the need to respect authority and the deep, justified skepticism that authority has earned through previous betrayal.`,
      shadow: `When operating from the unexamined wound of this program, the pattern is a specific and often invisible form of sabotage: the person who devalues the very authorities they are secretly seeking approval from. They may present as independent thinkers who have "seen through" the hierarchies that others trust, while simultaneously organizing their entire professional and social life around proving themselves to those same hierarchies. The gossip about colleagues is not cruelty — it is the externalization of an internal comparison that never resolves. The rejection of established experts is not confidence — it is the armor of someone who was once burned by expertise and has not finished grieving it. The sense of entitlement around material wealth — the feeling that it should arrive without the specific effort the world seems to require — is the remnant of a karmic expectation that the old structure owed them something, and now that the structure has collapsed, the debt feels unpayable. Financially, this program can generate a specific pattern of near-misses: genuine capability that somehow does not convert into stable accumulation, because the subconscious relationship to authority (which governs earning in almost every social system) remains ambivalent.`,
      path: `The integration of the 16-5-7 begins not with rebuilding authority from the outside but with a very specific internal act of mourning — grieving the version of authority that failed you, without transferring its failure onto every subsequent structure you encounter. The 16 always contains a gift inside the collapse: it makes visible what was never actually stable. The question is whether you can receive that visibility as information rather than as confirmation of a worldview in which nothing can be trusted. This is the harder, more empowering half of the pattern: the near-misses that keep converting capability into stalled accumulation are not the market's verdict on you, they are the vibration of unresolved distrust still being broadcast into every negotiation and opportunity. Concretely: practice the discipline of active listening without preparing your rebuttal. Accept that some people in positions of institutional knowledge have genuinely earned what they carry, even if others have not. Begin to separate "this specific person let me down" from "authority itself is a fraud." Once that distrust resolves internally, the external structures you engage with stop needing to keep proving themselves unreliable to you.`,
      health: `The somatic signature of this program tends to concentrate in the neck and the upper cervical spine — the literal place where the body holds the tension between "head" (authority, hierarchy, the mind's structure) and "body" (the felt sense of what is actually true). Chronic tension headaches, jaw clenching especially at night, and a restricted range of motion in the neck are common physical expressions. The adrenal pattern here is one of low-grade chronic activation rather than acute stress spikes — the body running a background program of vigilance that it has simply forgotten to turn off.`,
      positive: `You navigate forward with real capability and a healthy, resolved relationship to authority, and because that distrust has been metabolized rather than carried, opportunities convert cleanly into stable accumulation instead of near-misses.`,
      negative: `Unresolved distrust of authority gets broadcast into every negotiation, and the world keeps matching it — genuine capability stalling into near-misses because the vibration underneath is still bracing for another betrayal.`,
    },

    {
      numbers: [5, 17, 12],
      name: 'Public Disgrace / Fear of Shame',
      category: 'Social Status & Self-Worth',
      heading: 'The Performance of a Person Who Is Afraid to Be Seen Fully',
      why: `The 5-17-12 combination carries one of the most quietly devastating programs in the matrix — the person who has constructed a magnificent external presentation precisely because something deep inside them is convinced that the unadorned truth of who they are would not survive public exposure. The 5 (Hierophant) brings the awareness of social codes, of how things are supposed to look, of the standards by which people in the world judge credibility and worth. The 17 (The Star) — a luminous, vulnerable energy of hope and authentic radiance — finds itself in direct tension with the 5's concern for presentation, creating someone who genuinely possesses beauty and light but cannot allow it to arrive unmediated, unprepared, unstrategized. The 12 (The Hanged Man) is the deepest element: it is the energy of suspension, of the person who has chosen — usually without fully realizing it — to put their genuine life on hold while they perfect the conditions under which it will be safe to actually live it. Together, these three create the architecture of someone who is intensely aware of how they appear, perpetually preparing to make their real move, and somehow never quite making it.`,
      shadow: `The shadow of this program is a paralysis that presents as caution, and a perfectionism that presents as high standards. The person in the grip of the 5-17-12 does not experience themselves as afraid. They experience themselves as discerning: they know which opportunities are worth taking, which relationships are worth investing in, which projects have the structural integrity to survive the scrutiny of public exposure. What they rarely examine is whether this discernment is a genuine capacity or a sophisticated rationalization for never exposing themselves to the one thing they genuinely fear: being seen as insufficient, as ordinary, as less than the image they have so carefully constructed. The 12's energy here is particularly important — the Hanged Man is suspended, yes, but he chose the tree. The martyrdom of the 5-17-12 is the self-created nature of the waiting: the career that never quite launches, the relationship that never quite deepens, the creative work that is always almost ready to share. Publicly, they are often admired for their composure, their strategic intelligence, their unshakeable image. Internally, they are managing a constant low-level terror that the composure is the only thing standing between them and exposure.`,
      path: `The integration of this program begins with a single, specific reframe: public mistakes are not the enemy of credibility. They are the raw material from which genuine credibility is actually built. The people who command the deepest, most durable authority are not the ones who never failed publicly — they are the ones who failed publicly and allowed others to witness how they responded to that failure. The 17 inside this program is the doorway: the Star's luminosity is precisely the authentic, undefended quality that no amount of strategic presentation can replicate. Begin with low-stakes experiments in genuine visibility — share something real about a difficulty you have experienced, without packaging it for palatability. Notice what happens when you do. This is uncomfortable precisely because it removes the comfort of endless preparation and places the responsibility on the frequency being broadcast: a life that keeps offering "almost ready" opportunities is matching a vibration still unwilling to be seen unfinished. The terror predicted by the program almost never matches the reality of what arrives, and in that gap the 5-17-12 begins to discover that it was never the audience it was afraid of. It was itself.`,
      health: `The somatic signature of shame-based programs tends to manifest in the throat (the site of unspoken truth and suppressed self-expression), the skin (the body's primary interface with the external world and the gaze of others), and the immune system (which operates at a chronic low ebb in people who maintain high-tension presentation states for extended periods). Watch for recurring respiratory constriction — the literal tightening of the chest cavity around the breath — as the body's signal that the 12's suspension is asking for release.`,
      positive: `You let your genuine radiance arrive unmediated, and because you're broadcasting readiness rather than perpetual preparation, real opportunities arrive that are ready to be taken rather than endlessly rehearsed.`,
      negative: `A vibration still unwilling to be seen unfinished keeps drawing opportunities that stay perpetually "almost ready" — the world matching the exact frequency of a real move that never quite gets broadcast.`,
    },

    {
      numbers: [6, 5, 17],
      name: 'Strategy of Non-Recognition (Karmic Tail)',
      category: 'Social Status & Self-Worth',
      heading: 'The Hunger for Recognition That No Amount of Recognition Satisfies',
      why: `The 6-5-17 is one of the most aesthetically gifted and internally turbulent programs in the entire matrix. The 6 (The Lovers) brings the exquisite sensitivity of someone deeply attuned to beauty, to harmony, to the qualitative dimensions of experience that most people move through too quickly to notice. The 5 (Hierophant) brings the awareness of social codes and the desire for recognition within established systems of value. And the 17 (The Star) brings a genuine luminosity — a natural, authentic radiance that is not performed but simply present when this person is operating from their real frequency. The tension at the core of this combination is that all three of these energies are oriented outward in some fundamental way: the 6 toward beauty in the other, the 5 toward validation from the hierarchy, the 17 toward being received. This creates a person who is genuinely gifted — often in the arts, in aesthetic fields, in work that requires a refined sensory and emotional intelligence — but who cannot quite settle into that gift because their internal relationship to it is organized around whether other people see it.`,
      shadow: `The specific shadow of the 6-5-17 is what the Ladini system calls the "Karmic Tail" — the place where the very real gift becomes the site of the deepest wound. When not operating from their authentic frequency, this person can swing between two poles that appear to be opposites but are actually two faces of the same structure: devastating imposter syndrome (the conviction that they are a fraud, that their work is derivative, that others are more genuinely talented) and a compensatory arrogance (the defensive posture of someone who devalues others preemptively before others can devalue them). The pursuit of shortcuts — the trend-chasing, the search for the formula that will produce recognition without requiring the full depth of the craft — is not laziness. It is the desperate attempt to get the validation hit without fully exposing the authentic work to the scrutiny of a world that might not receive it. The financial pattern here is often one of large income variability: periods of genuine abundance when the authentic gift is flowing, followed by contraction when the shadow program takes over and the person begins performing their talent rather than embodying it.`,
      path: `The integration of the 6-5-17 is the single most important creative discipline this combination can practice: creating something and then not immediately measuring its worth by whether it was recognized. Begin with private work — work that no one will see, work that exists purely in the relationship between you and the material. Notice what happens to the quality of your attention, your craft, your genuine pleasure in the process when the audience is removed from the equation. This is not a permanent prescription for obscurity. It is a recalibration — a discovery that the gift does not actually require recognition to be real. Once that is genuinely known rather than intellectually assented to, the vibration underneath the work changes from "please see me" to simple presence, and the work that emerges for the public carries a completely different quality. Paradoxically, it tends to receive the recognition that the shadow-driven, approval-hungry work was always chasing but could never quite draw in.`,
      health: `The somatic expression of this program tends to live in the heart centre and the solar plexus — the places where the desire for connection and the wound of non-recognition meet. Cardiac irregularities under social stress, digestive sensitivity correlated with professional uncertainty, and a tendency toward skin conditions (the body's membrane between self and world) are common physical signatures. The eyes can also be affected: a hypervigilance of the gaze, always reading the room for signs of how the self is being received.`,
      positive: `The gift flows because you're creating for its own sake, and that settled, unhungry frequency is precisely what draws genuine recognition — arriving as a response to presence rather than to a request for approval.`,
      negative: `A frequency of "please see me" quietly undercuts the very recognition it's chasing — shortcuts and trend-formulas broadcasting hunger instead of the settled craft that recognition actually responds to.`,
    },

    // ── 2. INTELLECTUAL & MINDSET ALIGNMENT ────────────────────────────────

    {
      numbers: [17, 22, 5],
      name: 'Academic Knowledge / Rigid Dogma',
      category: 'Intellectual & Mindset Alignment',
      heading: 'The Mind That Has Decided It Already Knows',
      why: `The 17-22-5 combination creates one of the most intellectually formidable — and potentially most intellectually imprisoned — personalities in the matrix. The 17 (The Star) brings a genuine gift for pattern recognition, for seeing the larger structures that organize reality, for maintaining a sense of cosmic coherence even when circumstances are turbulent. The 22 (The Fool/completionist energy in Ladini's system) brings an enormous and sometimes unwieldy creative potential — the sense of unlimited possibility, of beginnings that have not yet been constrained by outcome. And the 5 (The Hierophant) sits at the centre of this combination as the defining energy: the deep need for the knowledge to be organized, categorized, transmitted through established channels, and measured against accepted standards of validity. The gift of this combination is extraordinary: these are the people who can take genuinely complex material and create reliable, transmissible systems from it. The potential prison is the same: the system, once built, can become more important than the living reality it was built to describe.`,
      shadow: `The shadow of the 17-22-5 is cognitive conservatism in someone who is too intelligent to recognize it as such. The specific mechanism is this: the person has built a framework for understanding reality that is genuinely sophisticated and has served them well — and so when new information arrives that does not fit within the framework, the automatic response is not curiosity but threat assessment. The framework is defended. The new information is examined for its flaws rather than its insights. The person who carries this experience is dismissed not with open hostility but with the more devastating instrument of intellectual contempt: their evidence is insufficient, their methodology is flawed, their sources are not credible. This shadow can make this combination extraordinarily frustrating to work with in collaborative settings, because their certainty is so well-constructed and so thoroughly articulated that it is very difficult to find the opening through which a genuinely new perspective might enter. Professionally, this pattern most often manifests as a resistance to methodological evolution — the expert who insists that the field has already established the correct approach and that departures from it represent regression rather than development.`,
      path: `The integration of the 17-22-5 begins with a single practice that is genuinely difficult for this combination: the deliberate and sustained engagement with a perspective that they have already decided is wrong, approached not to refute it but to find the specific, genuine insight that made someone intelligent enough to hold it. Every rigidly wrong position contains a real observation about reality that the more sophisticated framework has either not yet accounted for or has inadvertently excluded. The 22's potential for radical new beginnings is always present in this combination — it is the energy waiting beneath the 5's structured certainty. The path forward is learning to allow the 22 to periodically dismantle what the 5 has built, not as destruction but as the necessary renewal that keeps a living framework from becoming a museum exhibit — and a framework kept genuinely alive stops needing to encounter so much resistance, because it is no longer broadcasting a closed certainty for the world to push back against.`,
      health: `The somatic signature of cognitive rigidity tends to concentrate in the spinal column — specifically in the upper back and neck, where the literal rigidity of held positions is expressed through musculature. Tension headaches from the sustained mental effort of maintaining a complex internal certainty against the friction of a world that does not always conform to it, and eye strain from the hyperactive cognitive processing, are common. The vagus nerve — the primary regulator of the nervous system's flexibility — can be chronically under-stimulated in people whose cognitive style is dominantly analytical and control-oriented.`,
      positive: `You build genuinely reliable systems while staying curious enough to let them evolve, and that openness is what draws collaborators and new information toward you rather than resistance.`,
      negative: `A closed certainty broadcasts itself before a single word is spoken, and the friction and resistance that keeps arriving in collaborative settings is simply the world meeting that frequency in kind.`,
    },

    {
      numbers: [8, 13, 5],
      name: 'Displacement / In Someone Else\'s Place',
      category: 'Intellectual & Mindset Alignment',
      heading: 'The Feeling of Being Precisely One Step to the Left of Your Own Life',
      why: `The 8-13-5 program generates one of the most disorienting inner landscapes available in the matrix — the persistent, low-level sense that something is slightly off-centre, that the role one is occupying was designed for someone else, that the life one is inhabiting does not quite fit the shape of the person inhabiting it. The 8 (Strength) brings genuine capability — real endurance, real capacity to hold and manage complexity — but in this combination, that capability is often deployed in service of structures or relationships or professional contexts that were not built to the person's actual specifications. The 13 (Transformation) introduces the element of radical change — not gentle evolution but the kind of cellular restructuring that requires something to actually end before something new can begin. And the 5 (Hierophant) holds the whole thing in place through its deep attachment to established structures and earned positions: you do not simply walk away from what you have built, what you have sacrificed for, what the system says you should want. Together, these three create the specific experience of someone who is clearly in the wrong place but has an extraordinarily sophisticated set of reasons for staying.`,
      shadow: `The shadow of this program expresses most clearly in relationships and professional positioning. In relationships, the 8-13-5 can develop a pattern of attempting to claim what genuinely belongs to someone else — not through malicious intent but through a deep confusion between "what I want" and "what I am owed." This can manifest as the friend who gradually, subtly displaces another person in a social group, the professional who positions themselves for a role that someone else built, or the partner who unconsciously competes with their significant other for the primary position in shared social contexts. The analysis paralysis is real and significant: the 8's capacity for holding complexity, combined with the 13's awareness that any move will require a genuine ending, and the 5's reluctance to sacrifice earned position — this combination can create someone who has been in the analytical stage of a necessary transition for years, constructing ever more elaborate assessments of the situation without ever quite arriving at action.`,
      path: `The integration of the 8-13-5 requires the courage to allow what has already ended to be acknowledged as ended — to stop artificially sustaining something past its natural life with the considerable force that the 8's endurance can bring to the project of maintenance. The 13 is not asking for catastrophe. It is asking for honesty: the specific, courageous honesty of saying "this chapter is complete" rather than "I haven't found the right moment to transition yet." Practically: use a structured trial period — a defined window in which you test a new direction rather than requiring yourself to commit to it before you have enough information. And in relationships, begin the practice of wanting genuinely good things for the people whose positions you have been, even unconsciously, measuring yourself against. This is not altruism — it is the specific energetic act that releases the displacement pattern, because a life spent occupying spaces built for someone else is what a vibration of "I am owed this" reliably attracts.`,
      health: `The somatic signature of displacement often manifests in the joints — specifically the hips and the knees, which in energetic anatomy govern the flexibility and direction of one's path through life. Chronic hip tension, knee instability under periods of professional or relational stress, and lower back pain that correlates with decision-avoidance are common. The digestive system can also express the unresolved displacement through irritability correlated with environments where the sense of being out of place is strongest.`,
      positive: `You have the endurance to hold complexity and the honesty to act on genuine endings, and because you're no longer occupying a role built for someone else, the position you actually land in fits.`,
      negative: `A vibration of "I am owed this" keeps drawing you into roles and relationships built for someone else — the confusion between want and entitlement recreating the exact displacement it's trying to resolve.`,
    },

    {
      numbers: [9, 16, 7],
      name: 'The Program of Silence',
      category: 'Intellectual & Mindset Alignment',
      heading: 'Everything You Know and Have Not Yet Found the Words For',
      why: `The 9-16-7 is the program of the person who carries an extraordinary interior richness that the external world has not yet received in full — and in many cases, has not yet been offered in full. The 9 (The Hermit) brings the energy of deep interior knowing: the wisdom that comes from genuine solitude, from the sustained inward attention that most people only access briefly and under pressure. The 16 (The Tower) introduces an element of structural disruption — this is a person who has experienced, or is still processing, a significant moment of external collapse that reconfigured their relationship to trust, to openness, to the safety of being known. And the 7 (The Chariot) brings the drive toward purposeful movement — the internal compass that knows where it wants to go but has not always found the conditions in which it feels safe to announce the direction. Together, these three create a person of profound internal depth who has learned, somewhere along the way, that the expression of that depth carries risk.`,
      shadow: `The shadow of the 9-16-7 is the comfort of the interior life become a permanent residence rather than a sanctuary. The specific experience is this: the person says "everything is fine" while internally managing a complexity that, if it were spoken aloud, would require them to be genuinely vulnerable with another human being. The 16 in this program is often the explanation for the 9's retreat into silence: there was a moment — possibly more than one — where genuine expression was met with a response that felt like the Tower. The openness was punished. The authentic voice was ridiculed, dismissed, misused, or simply met with blankness. And the intelligent nervous system drew the correct conclusion: silence is safer. The tragedy is that this conclusion, correct in its original context, becomes a life sentence applied to every subsequent context — including the ones where genuine expression would be met with the recognition and resonance that the 9-16-7 is quietly, persistently hungry for. The missed opportunities here are not dramatic. They are the quiet ones: the conversation that stayed surface-level when something real was available, the connection that could not deepen because the drawbridge stayed up, the contribution that was never offered because the moment of offering felt too exposing.`,
      path: `The integration of the 9-16-7 is not the sudden, dramatic dismantling of the silence. It is the gradual, patient creation of new evidence — the slow accumulation of experiences in which genuine expression was offered and received without catastrophe. Begin with the mediums that feel least exposing: writing that no one reads yet, voice recordings that no one hears yet, conversations with people you trust absolutely. The practice is not the final product. The practice is the rehabilitation of the belief that expression is survivable, because a world that keeps meeting your voice with silence or misattunement is often just matching the muted frequency the voice itself is still broadcasting. And then, as the new evidence accumulates, allow the radius of sharing to expand — incrementally, on your own terms, in your own time. The silence was a necessary passage. It is not the destination.`,
      health: `The somatic expression of unexpressed inner life is almost universally located in the throat — the literal architecture of the voice — and frequently extends into the thyroid, which governs metabolic regulation and energetic output. Recurring sore throats, voice loss under periods of interpersonal stress, and thyroid irregularities are common physical signatures of this program. The shoulders hold unexpressed burdens and can become chronically elevated in people who are protecting the throat and chest from the vulnerability of genuine expression.`,
      positive: `Deep interior richness gets offered rather than withheld, and because the voice is genuinely broadcasting rather than muted, people finally meet it with the recognition and resonance it was always hungry for.`,
      negative: `A voice still bracing for the old wound broadcasts itself as muted before a word is even spoken — and connections keep landing at surface level, matching the guarded frequency actually being sent.`,
    },

    // ── 3. ABUNDANCE & FINANCIAL FLOW BLOCKS ───────────────────────────────

    {
      numbers: [4, 21, 17],
      name: 'Focus vs. Distraction',
      category: 'Abundance & Financial Flow',
      heading: 'The Brilliant Mind That Has Not Yet Decided Which Direction to Point',
      why: `The 4-21-17 program generates a genuinely paradoxical inner experience: a person who is, simultaneously, one of the most focused and one of the most scattered people you will ever meet. The 4 (The Emperor) brings a profound structural intelligence — the capacity to envision a complete system, to understand how all the parts relate, to build something that will hold its own weight through time. The 21 (The World) brings the energy of completion and mastery — this is a person who carries the frequency of someone who has finished a full cycle of development and arrived at genuine integration. And the 17 (The Star) brings the luminous, expansive quality of someone who can see possibility in every direction simultaneously. The tension: the 4 wants to build one thing, deeply and durably. The 17 wants to explore everything that glitters. And the 21 keeps reminding the system that completion is possible — while the gap between current reality and that completion can feel so large that the mind fractals into sub-projects, auxiliary strategies, and supporting initiatives that gradually consume the resources intended for the main structure.`,
      shadow: `The specific shadow of the 4-21-17 is not laziness and it is not lack of vision. It is the opposite: too much vision, too many genuinely good ideas, too real an ability to see how each of them could work — combined with a difficulty holding the container long enough for any one of them to reach the depth at which it becomes genuinely self-sustaining. The energy crashes that punctuate this pattern are not random. They tend to arrive at precisely the moment when a project is approaching the phase of genuine work — the unglamorous, repetitive, incrementally-improving phase that follows the initial vision and precedes the arrival of results. The 17's star-energy loves the beginning and the completion. The middle — the long, often invisible work of real development — is where the distraction arrives as rescue. The financial consequence is a pattern of expensive pivots: significant investment in the beginning of something that does not reach completion, followed by the next beginning, and the next, each one drawing resources from the previous incomplete cycle.`,
      path: `The integration of the 4-21-17 is the deliberate, almost counter-instinctive practice of choosing *one primary direction* and defending it against your own expansive intelligence for long enough to find out what it can actually become. This is not the permanent suppression of the 17's visionary gifts — it is the channelling of them. Write down every idea that comes to you. Do not discard them; they are real and they have value. But give them a container: a file, a list, a defined space in which they can wait without consuming the present project's oxygen. The 4 knows how to build. The 21 knows what completion feels like. Your work is to trust these frequencies long enough to experience the specific satisfaction of bringing one thing to its genuine conclusion — and once that frequency of committed follow-through is genuinely established, resources and money stop scattering across half-finished cycles and start compounding in one place.`,
      health: `The somatic expression of this program tends to manifest in the nervous system's regulation — specifically in the pattern of overactivation followed by sudden depletion. Adrenal fatigue from sustained multitasking, headaches correlated with context-switching, and sleep disruption from the mind's unwillingness to release its multiple active threads are common physical signatures. The eyes can be affected: a particular kind of visual fatigue that comes not from lack of sleep but from the sustained effort of holding multiple simultaneous focal points.`,
      positive: `You channel a genuinely visionary mind into one primary direction long enough to see it through, and because that frequency of follow-through is real, resources and money compound in one place instead of scattering.`,
      negative: `A frequency still oriented toward the next exciting start keeps fracturing resources across unfinished cycles — the expensive pivots are less bad luck than the natural harvest of an unsettled vibration.`,
    },

    {
      numbers: [9, 14, 5],
      name: 'The Revenge Pattern',
      category: 'Abundance & Financial Flow',
      heading: 'The Energy You Are Still Spending on People Who Have Moved On',
      why: `The 9-14-5 is the program of the person who has been genuinely wronged — or has experienced something that their nervous system registered as a genuine wrong — and has not yet found the energetic release valve that would allow that experience to complete its cycle and return its occupying resources. The 9 (The Hermit) brings a deep, precise, uncompromising inner standard: this combination knows, with a clarity that is almost structural, what is fair and what is not, what was earned and what was taken, what the correct accounting of events actually looks like. The 14 (Temperance) brings an extraordinary capacity for sustained effort and patient, meticulous execution — these are people who will work for a very long time toward a very specific outcome without losing the thread of their intention. And the 5 (The Hierophant) brings the awareness of public and social codes — the knowledge of how things are supposed to go, how recognition is supposed to be distributed, how systems are supposed to treat people who contribute what this person has contributed. The wound of the 9-14-5 is the gap between what the system was supposed to deliver and what it actually did.`,
      shadow: `The shadow of this program is not rage — it is something far more energetically expensive than rage. It is the meticulous, highly organized, deeply intelligent allocation of cognitive and emotional resources toward the construction of a detailed internal case for why the person or system that wronged them deserves to experience consequences. The blueprint for how this might occur — through their professional failure, their social exposure, their eventual recognition that they were wrong — is maintained with a specificity and a regularity that the person themselves often does not fully recognise as the preoccupation it has become. The financial consequence is significant: the 9's Hermit-energy, when turned toward this program, withdraws the light that would otherwise illuminate the person's own path forward, redirecting it into the long corridor of retrospective justice. The 14's patient execution, when pointed in this direction, produces not the alchemy of genuine transformation but the grinding repetition of accumulated grievance. And the 5's social awareness generates a perpetual monitoring of the offending party's public standing — a practice that keeps the wound fresh precisely because it keeps the person's attention inside the wound's frame.`,
      path: `The integration of the 9-14-5 begins with a distinction that is easy to state and genuinely difficult to enact: forgiveness is not the same as absolution. You are not being asked to decide that what happened was acceptable. You are being asked to make a very practical energetic decision: to stop allocating resources to an outcome — the other person's suffering, their recognition of their error, their public accountability — that you cannot control and that is not making your life larger. The 14's alchemical capacity is the key. This combination has the genuine ability to transform bitterness into fuel — but the direction of the transformation matters. Redirect the specificity of your planning, the patience of your execution, and the intelligence of your analysis toward building something in your own domain that is so clearly excellent that the comparison becomes irrelevant. Every hour spent monitoring the old wound is a vibration of lack still being broadcast; the moment that attention redirects toward your own building, abundance finally has somewhere to land.`,
      health: `The somatic signature of held resentment tends to concentrate in the liver — the organ that, in traditional medicine across multiple systems, is associated with the processing of anger and injustice. Recurring inflammatory conditions, skin irritations, and headaches correlated with the contemplation of the grievance are common. The cardiovascular system carries the sustained load of emotional activation: blood pressure irregularities and heart rate variability that tracks emotional rather than physical exertion are worth monitoring.`,
      positive: `Patient, meticulous execution gets redirected toward building something clearly excellent, and because your attention is no longer spent on old grievance, abundance finally has somewhere current to land.`,
      negative: `Hours spent monitoring an old wound keep broadcasting a vibration of lack — the same intelligence that could be building genuine abundance stays occupied re-litigating a debt that was never going to be repaid.`,
    },

    {
      numbers: [15, 19, 5],
      name: 'The Wealth Magnifier',
      category: 'Abundance & Financial Flow',
      heading: 'The Power That Must Choose What It Serves',
      why: `The 15-19-5 is one of the most financially potent programs in the matrix — and one of the most morally demanding. The 15 (The Devil) carries the raw frequency of material magnetism: the capacity to attract resources, to understand power dynamics intuitively, to navigate the energetic architecture of accumulation in ways that other people find mysterious and compelling. The 19 (The Sun) brings extraordinary personal radiance — the kind of natural authority and warmth that commands attention without effort, that makes rooms reorganize themselves around the person's presence. And the 5 (Hierophant) brings the social and institutional intelligence to deploy these gifts within existing structures of power in ways that generate real-world results. Together, these three create a combination that is genuinely built for scale: for large systems, large teams, large financial flows, large public platforms. The question that the program itself does not answer — and that the person must answer for themselves — is: what is all of this power in service of?`,
      shadow: `The shadow of the 15-19-5 is the specific corruption that arrives when the power generated by this combination is redirected from genuine creation into the management of psychological dominance. The 15's magnetic pull, when operating from its shadow, becomes the irresistible draw that creates dependency rather than empowerment — the leader whose team cannot make a decision without them, the partner who organizes the relationship so that they are always the one with more to lose, the business owner who structures compensation in ways that maintain a subtle but real asymmetry of power. The 19's radiance, when shadowed, becomes the performance of warmth — the public generosity that is genuinely charming and completely strategic. And the 5's social intelligence becomes the precise awareness of who in any given room has the most influence and the systematic cultivation of exactly those relationships. The financial trap of this combination is often excess without meaning: the accumulation of material resources that exceeds what any genuine life project could require, driven by a hunger that is not actually for money but for the specific feeling of being ungovernable — beyond the reach of scarcity, beyond the vulnerability of need.`,
      path: `The integration of the 15-19-5 is not the renunciation of power or wealth — it is the conscious decision about what those things are actually for. This combination has a genuine capacity to generate positive change at significant scale. The 19's radiance, when it is authentic rather than performed, creates the conditions for other people's growth. The 15's material intelligence, when directed toward genuine contribution, can build structures that outlast the individual. And the 5's institutional awareness can navigate the complex landscape of large-scale systems in ways that create durable, legitimate authority. The practical step: establish, in writing, and revisit regularly, a clear account of what your material accumulation is intended to accomplish in the world beyond your own comfort and status. This document is the anchor that keeps the 15's magnetic pull oriented toward creation rather than domination — and a frequency oriented toward genuine contribution is what allows real scale to arrive without the excess that domination always eventually requires defending.`,
      health: `The somatic signature of this program under shadow conditions tends to concentrate in the cardiovascular system — specifically in the places where ambition and its associated cortisol load meet the physical demands of sustained high-intensity operation. Blood pressure dysregulation, cardiac arrhythmias under periods of competitive pressure, and inflammation-based conditions are common. The shadow of the 15 also frequently expresses through the reproductive and endocrine systems, which govern the body's relationship to power, vitality, and the primal energy that the Devil archetype represents.`,
      positive: `Magnetic presence and material intelligence get pointed at genuine contribution, and because the frequency underneath is creation rather than domination, scale arrives without needing to be defended.`,
      negative: `Power redirected into managing dominance broadcasts a hunger that is never actually satisfied by accumulation — more keeps arriving because the underlying feeling of scarcity was never the thing being solved.`,
    },

    // ── 4. RELATIONSHIP & LOVE PROGRAMS ────────────────────────────────────

    {
      numbers: [6, 15, 3],
      name: 'The Love Addict',
      category: 'Relationship & Love',
      heading: 'The Hunger for Fusion That No Single Person Can Satisfy',
      why: `The 6-15-3 combination is the program of the person for whom love is not a complement to life but the primary architecture of it — the frame within which everything else is organized, measured, and given meaning. The 6 (The Lovers) brings an exquisite, almost painful sensitivity to the quality of connection: these are people who experience relationship not as a pleasant addition to an already full life but as a fundamental requirement of existence, the way others require air or structure or creative output. The 15 (The Devil) introduces the element of compulsion — the specific quality of attachment that has slipped from choice into necessity, where the presence of the beloved regulates the nervous system in a way that nothing else quite replicates. And the 3 (The Empress) brings an enormous creative and generative warmth — the genuine desire to pour into another person, to nurture, to create together, to experience the particular fullness that only comes through intimate co-creation. In their integrated form, these three energies produce extraordinary lovers: deeply felt, wildly creative, magnetically present, capable of an intimacy that the other person will remember for the rest of their life. In their unexamined form, they produce a specific and very human suffering.`,
      shadow: `The shadow of the 6-15-3 is the relationship that has become a regulatory mechanism rather than a genuine meeting of two people. The person in the grip of this program does not experience the beginning of a new connection as pleasant anticipation — they experience it as relief, as the temporary resolution of an internal state that has been unbearable. And because the connection is providing relief rather than joy, the quality of the connection matters far less than its presence. This is the specific mechanism of love addiction: the lowering of standards not because the person does not know better but because the need for relief overrides the knowledge. The 15's shadow is particularly important here — it generates the capacity to remain in connections that are clearly harmful because the familiarity of the harmful connection has become, through repetition, more tolerable than the unfamiliarity of the healthy one. The 3's creative energy, when turned toward this shadow, becomes the elaborate and unconscious work of making oneself indispensable to the other person — not through genuine contribution but through a systematic occupation of the spaces in the other person's life that creates dependency rather than desire.`,
      path: `The integration of the 6-15-3 begins with the most important distinction this program can learn: the difference between the hunger for fusion (which is the shadow's demand) and the genuine desire for intimacy (which is the gift's offering). Fusion collapses the boundary between self and other; intimacy requires that both people remain themselves while also choosing, actively and repeatedly, to move toward each other. The practical work: develop a life that is genuinely satisfying independently of whether any particular relationship is present or absent — not as a strategy for attracting better partners, but the frequency shift that makes that attraction almost inevitable anyway. The 3's creative energy is the key resource here: redirect it toward making something, building something, contributing something that belongs entirely to you and does not depend on being witnessed to be real. A self that no longer needs relief is what finally stops attracting relationships that only offer relief.`,
      health: `The somatic expression of love addiction tends to concentrate in the heart centre and the endocrine system — specifically in the dopamine and oxytocin pathways that govern bonding and reward. The physical experience of love withdrawal is neurologically similar to substance withdrawal: genuine symptoms of anxiety, restlessness, sleep disruption, and appetite dysregulation. The skin — which is the body's primary contact boundary — can express the longing for merger through chronic conditions that are sensitive to the quality of one's relational environment.`,
      positive: `You love with genuine depth and creative warmth, and because your life is satisfying independent of any one relationship, the connections that arrive offer real intimacy rather than mere relief.`,
      negative: `A need for relief rather than joy is the actual signal being emitted, and it keeps attracting connections that supply relief and little else — familiar harm feeling safer than the unfamiliar health that was actually wanted.`,
    },

    {
      numbers: [3, 18, 12],
      name: 'The Emotional Hostage',
      category: 'Relationship & Love',
      heading: 'The Love That Has Learned to Keep Itself Small',
      why: `When the 3, the 18, and the 12 meet in the same program, they create one of the most quietly painful relationship dynamics in the matrix — the person who has contracted the full range of their emotional and creative expression in order to maintain a connection that requires them to be less than they actually are. The 3 (The Empress) carries the frequency of creative abundance, of natural warmth and generative fullness — this is a person who, at their genuine core, has an enormous amount to give and an equally genuine desire to give it. The 18 (The Moon) introduces the deep, murky, psychically complex element: the unconscious tidal pull of early conditioning, of unexamined emotional inheritance, of the dream-logic that governs intimate life in ways that daylight consciousness rarely apprehends. And the 12 (The Hanged Man) is the defining energy of the combination: the voluntary suspension, the self-imposed limitation, the person who has hung themselves on the tree of a relationship that requires their smallness as the price of admission.`,
      shadow: `The shadow of the 3-18-12 is not passivity — it is something far more active and far more invisible than passivity. It is the continuous, sophisticated, emotionally exhausting labour of self-management: monitoring one's own emotional intensity for signs that it might be "too much," editing one's creative output for elements that might provoke the other person's insecurity, calibrating one's social presence to remain within the narrow band of expression that the relationship's implicit agreement permits. The 18's lunar quality generates a particular kind of confusion in this program: because so much of the dynamic is operating below the surface of conscious awareness, the person often cannot name what is happening. They know they are smaller than they used to be. They may attribute this to maturity, to compromise, to the necessary adjustments of long-term partnership. They may not yet have access to the recognition that they are not compromising — they are disappearing. The 12's Hanged Man energy provides the philosophical scaffolding for the suspension: "this is temporary," "I am waiting for the right moment," "things will open up when the circumstances change."`,
      path: `The integration of the 3-18-12 requires the recovery of a simple but profound permission: the permission to take up the full amount of space that you actually require. Not aggressively, not in reaction, but genuinely — the measured, non-negotiable act of returning to the original dimensions of yourself and discovering whether the relationship can accommodate them. Sometimes it can, and the revelation produces a depth of connection that the contracted version of the relationship could never access. Sometimes it cannot, and that information — though painful — is also a form of liberation. The 12's integration is always the same: the suspension is voluntary, which means it can be ended. A relationship that keeps requiring your smallness is meeting the exact size you have been offering it — reclaim the full dimension, and it either expands to meet you or reveals that it never could.`,
      health: `The somatic expression of emotional contraction tends to concentrate in the chest and the diaphragm — the literal anatomy of the breath, which is almost universally restricted in people who have learned to take up less space. Shallow breathing as a chronic state, chest tightness correlated with relational interaction, and recurring respiratory conditions are common. The immune system often reflects the long-term cost of sustained self-suppression, operating at reduced capacity in ways that appear as susceptibility rather than depletion.`,
      positive: `You take up the full amount of space you actually require, and the relationships that can hold that real size deepen precisely because you stopped offering anything smaller.`,
      negative: `A relationship kept small only ever meets the size you offer it — the "temporary" contraction becomes the whole shape of the connection because that is the exact dimension being broadcast.`,
    },

    {
      numbers: [2, 11, 9],
      name: 'The Invisible Partner',
      category: 'Relationship & Love',
      heading: 'The One Who Gives Everything and Remains Unknown',
      why: `The 2-11-9 program generates one of the most spiritually advanced and personally frustrating relationship experiences in the matrix — the experience of being genuinely, deeply present for other people in ways that are real and meaningful, while simultaneously feeling, at the core of one's intimate life, profoundly unseen. The 2 (The High Priestess) brings a quality of receptive, deeply perceptive attention: the capacity to know what another person needs before they have articulated it, to hold emotional space with extraordinary steadiness, to be present in the way that water is present — taking the shape of the container without losing its own essential nature. The 11 (Justice) brings a rigorous internal standard of fairness and accuracy — this is a person who sees clearly, who knows the difference between what is and what is being performed, and who applies this perception to relationships with a precision that can be both a gift and a source of isolation. And the 9 (The Hermit) deepens the interior quality: this combination is self-sufficient to a degree that others often misread as either contentment or coldness, when the reality is neither.`,
      shadow: `The shadow of the 2-11-9 is the gradual, largely unconscious construction of a relational life in which one is consistently the giver of perception and rarely its recipient. The person who carries this program tends to attract partners and friends who are engaged primarily with their own interior worlds — who benefit enormously from the 2-11-9's quality of attention without developing an equivalent capacity to turn that attention back. This is not random: at some level, the 2-11-9 chooses this dynamic because it is safer. The High Priestess behind the veil is not seen fully, which means she cannot be fully rejected. The Hermit who holds the light for others is too busy illuminating to require illumination himself. The 11's Justice carries a specific wound in this program: the person knows, with quiet precision, that the reciprocity they are providing is not being matched — and the combination of knowing and not speaking the knowing generates a specific interior accumulation that eventually manifests as either withdrawal or a sudden, bewildering loss of patience.`,
      path: `The integration of the 2-11-9 is the development of a genuine and specific appetite for being known — not just being useful, not just being present, but actively, courageously creating the conditions in which another person has genuine access to your interior. This requires the identification and challenging of the specific belief that keeps you behind the veil: that full visibility would reveal something insufficient, something that the other person would not choose if they saw it clearly. Begin with small, deliberate acts of disclosure — not confession, not performance, but the genuine sharing of your own experience with someone who has earned the context. Notice what happens. A veil kept up is what keeps drawing partners who only take, never turn the light back; drop it, and reciprocity has an actual opening to arrive through.`,
      health: `The somatic signature of the invisible partner program tends to manifest in the kidneys — the organs associated in energetic medicine with the deep reserves of vital energy, with fear, and with the exhaustion that comes from sustained giving without adequate replenishment. Chronic fatigue that is disproportionate to physical exertion, lower back pain in the kidney region, and susceptibility to urinary tract conditions under periods of relational stress are common signatures.`,
      positive: `You offer extraordinary perceptive presence and let yourself be genuinely known in return, and because the veil is actually down, reciprocity has somewhere real to land.`,
      negative: `A veil kept up for safety keeps drawing partners who take the perception offered and never turn it back — the world simply meeting the exact visibility that was actually extended.`,
    },

    // ── 5. HEALTH & VITALITY PROGRAMS ──────────────────────────────────────

    {
      numbers: [18, 9, 4],
      name: 'The Self-Dissolution Pattern',
      category: 'Health & Vitality',
      heading: 'The Body That Has Learned to Express What the Mind Will Not',
      why: `The 18-9-4 program is one of the most somatically expressive combinations in the matrix — a configuration in which the body has become the primary language for things that the conscious mind has not found another way to process. The 18 (The Moon) carries the deep psychic and somatic sensitivity of the unconscious: in this combination, the body is not a separate system from the emotional and energetic field but its most immediate and faithful recorder. The 9 (The Hermit) brings the tendency toward sustained interior processing — the person who holds a great deal inward for a great deal of time, who maintains an enormous amount of awareness without necessarily having an outlet for it. And the 4 (The Emperor) brings the structural quality: the attempt to maintain order, control, predictability, and reliable output in all circumstances — including the circumstances in which the body is clearly communicating that the current system is not sustainable. Together, these three create a person who is managing an extraordinarily rich and complex interior life within a framework of external reliability, using the body as the pressure valve when the gap between the two becomes too large.`,
      shadow: `The specific shadow of the 18-9-4 is the use of illness — consciously or entirely unconsciously — as the only socially acceptable form of rest, limit-setting, or need expression available within the person's self-constructed framework. The Emperor does not cancel. The Hermit does not complain. The Moon, however, will find a way to make the boundaries visible through the body, because the body cannot maintain the same quality of managed presentation that the mind can. Recurrent, seemingly idiopathic conditions — symptoms that appear in the absence of clear physical cause, that correlate with periods of sustained pressure or unexpressed need, that improve substantially when the person is finally forced to rest — are the signature of this program. The shadow is not hypochondria and it is not weakness. It is the intelligent adaptation of a system that has learned that the only language its environment will consistently respond to is the language of physical limitation.`,
      path: `The integration of the 18-9-4 begins with the development of direct channels for the things that are currently being routed through the body: rest that is chosen rather than forced, limits that are communicated rather than enacted through collapse, needs that are expressed rather than accumulated. The 4's structural intelligence is the resource here — the same capacity that builds reliable external systems can be turned toward building reliable internal protocols. A scheduled rest that is as non-negotiable as a professional commitment. A weekly practice of expressing something that has not yet been said. A regular audit of the gap between what you are carrying and what you have explicitly agreed to carry. The body is simply the most literal mirror available of an unspoken internal state, and it will step back from its role as spokesperson the moment the message is genuinely getting through by other means.`,
      health: `The somatic signatures of this program are among the most diverse in the matrix, precisely because the body is functioning as the primary expressive channel. Autoimmune conditions (the system attacking itself — a precise somatic metaphor for the internalization of conflict), chronic fatigue, hormonal dysregulation, skin conditions, and digestive disorders are all common. The pattern is almost always one of correlation with psychosocial stress rather than simple physical causation — which is not to say the symptoms are not real, but that their treatment requires engagement with the psychosocial layer.`,
      positive: `Rest gets chosen and needs get spoken directly, so the body — the most literal mirror of your internal state — no longer has to manufacture symptoms just to be heard.`,
      negative: `An unspoken internal state finds its most literal mirror in the body — illness becomes the only channel loud enough to communicate a boundary the mind has refused to say out loud.`,
    },

    {
      numbers: [16, 7, 14],
      name: 'The Burnout Spiral',
      category: 'Health & Vitality',
      heading: 'The System That Forgot It Was Built to Sustain a Human Being',
      why: `The 16-7-14 program describes the specific architecture of the person who burns out not from lack of capacity but from an excess of it — who has been able to sustain such a high level of output for so long that the warning signals have been normalized into background noise. The 16 (The Tower) introduces a structural volatility: in the physical domain, this manifests as the system that runs without apparent distress until the moment it collapses. The 7 (The Chariot) brings the directed, sustained, disciplined drive that can carry a person through enormous amounts of difficulty without demonstrating external signs of accumulation — this is the combination that works through illness, works through loss, works through exhaustion, because the forward momentum of the Chariot is a deeply ingrained identity component, not just a behaviour pattern. And the 14 (Temperance) brings the extraordinary capacity for balance and integration — which, in the shadow of this program, becomes the sophisticated rationalization of imbalance: the person who is genuinely excellent at making extreme output look sustainable because they have developed such refined management tools for the indicators that something is wrong.`,
      shadow: `The shadow of the 16-7-14 is the Tower event that arrives not as a surprising catastrophe but as the predictable outcome of a system that was never designed for indefinite operation at the level it was being run. The burnout of this combination is rarely acute — it tends to arrive as a gradual diminishment of the very qualities that defined the person: the creativity that was always effortless becomes effortful, then absent. The resilience that was always reliable becomes brittle, then unavailable. The tolerance for difficulty that seemed unlimited reveals its actual limit in a way that feels, from the inside, like a fundamental change in the self rather than what it actually is: the healthy refusal of a system that has been asked to do too much for too long. The shame that accompanies this revelation is often significant — the 7's identity is organized around reliable forward motion, and the Chariot that has stopped moving experiences this as failure rather than wisdom.`,
      path: `The integration of the 16-7-14 requires a fundamental reconfiguration of the relationship between productivity and worth. The Tower in this combination is not here to punish — it is here to clarify what the genuine foundation is and what was always a structure built on the unstable ground of output-as-identity. The 14's alchemical capacity is the key resource: this combination has the genuine ability to redesign its own operating system, to build something more sustainable than what preceded it. Begin with the identification of the specific beliefs that drove the pre-collapse pattern: "I should be able to handle this," "resting is wasting time," "my value to others depends on what I produce." These are not truths. They are the 16's false foundation, and a body kept running on that foundation will keep manufacturing collapse until the belief underneath it actually changes.`,
      health: `The somatic signatures of the burnout spiral are among the most recognizable in the matrix: adrenal exhaustion (the system that was running on cortisol discovering that the cortisol is gone), nervous system dysregulation (the chronic hyperactivation that finally tips into collapse), thyroid disruption, and immune suppression. The heart is often the most significant concern in this combination — both literally, through cardiovascular stress accumulated over periods of sustained extreme output, and in the energetic sense of the heart as the centre of the self's relationship to its own worthiness.`,
      positive: `Sustainable, disciplined output replaces extreme output, and because worth is no longer tied to constant production, the body no longer needs a collapse to earn a rest.`,
      negative: `A belief that worth depends on constant output keeps normalizing the warning signals until the body manufactures the collapse that was the only rest ever going to be permitted.`,
    },

    {
      numbers: [13, 4, 8],
      name: 'The Chronic Resistance',
      category: 'Health & Vitality',
      heading: 'What the Body Holds When the Mind Refuses to Release',
      why: `The 13-4-8 program describes the physical and psychological cost of sustained resistance to change in a life that requires it. The 13 (Transformation/Death) is, in this combination, the change that keeps arriving — the ending that presents itself, the transition that is being asked for, the release that would free the system from a significant load. The 4 (The Emperor) is the force that resists: the deep structural conservatism of someone who has organized their sense of safety around the maintenance of existing forms, for whom change represents not possibility but the threat of collapse. And the 8 (Strength) is the extraordinary resource deployed in the service of this resistance: the genuine, remarkable, almost admirable capacity to hold on, to endure, to maintain position under conditions that would have caused most people to release long ago. The tragedy of this combination is that the same strength that is one of the person's most real gifts has been redirected into the project of keeping something in place that the deeper intelligence of their life is actively trying to release.`,
      shadow: `The shadow of the 13-4-8 manifests primarily in the body — and it does so through a very specific mechanism: the physical holding that mirrors the psychological holding. The musculature of someone in the sustained grip of this program is often dense, contracted, and chronically over-recruited for the task of maintaining a structural position that the tissue itself is not designed to hold indefinitely. The chronic illness patterns of this combination tend to be those associated with immune dysregulation and inflammatory processes — the body's system for managing what no longer belongs becoming overactive because the manual override of the conscious mind keeps reintroducing what the body is attempting to clear. There is also a pattern of accidents and injuries that correlate precisely with the moments when a release is most urgently required and most actively resisted — the body creating, through external event, the forced rest or the forced transition that the person's will has been refusing.`,
      path: `The integration of the 13-4-8 begins with the recognition that what is being held is not being held because it is life-sustaining. It is being held because the act of holding has become identical with the sense of self. The Emperor and the Strength card are both, in their integrated forms, energies of genuine authority — but authority that has been turned inward, used to govern the self's own natural processes of ending and renewal, produces a very specific kind of imprisonment. The first step is not the grand release. It is the honest identification of what, specifically, is being held — in the body, in the psyche, in the relational or professional structures — and a genuine inquiry into what would actually be lost if that holding were to ease. What the mind refuses to release, the body will keep holding on its behalf, so the release has to begin at the level of belief before the tissue can genuinely follow.`,
      health: `The somatic signatures of this program are among the most physically pronounced in the matrix. Musculoskeletal conditions — particularly those involving chronic muscle tension, joint inflammation, and connective tissue disorders — are the primary physical language. The immune system is almost universally involved, often expressing as autoimmune activity. Digestive disruption, particularly in the large intestine (the organ of release), is common. The skin, as the body's containment boundary, can express chronic conditions that mirror the internal pattern of holding beyond capacity.`,
      positive: `Remarkable endurance gets pointed at releasing what's already run its course, and because the belief underneath finally agrees to let go, the body stops needing to hold it in muscle and joint.`,
      negative: `What the mind refuses to release, the body keeps holding on its behalf — genuine strength redirected into maintaining a position that a deeper intelligence has already tried to end.`,
    },

    // ── 6. PURPOSE & MISSION PROGRAMS ──────────────────────────────────────

    {
      numbers: [1, 10, 19],
      name: 'The Trailblazer',
      category: 'Purpose & Mission',
      heading: 'The One Who Arrives Before the Road Has Been Built',
      why: `The 1-10-19 program is the signature of the pioneer — the person whose sense of purpose is organized not around joining an existing current but around initiating one. The 1 (The Magician) carries the pure frequency of origination: the capacity to generate from intention, to initiate where there was nothing, to make the first move in a direction that has not yet been validated by precedent or consensus. The 10 (The Wheel of Fortune) brings the deep awareness of cycles — the understanding that timing is not incidental but structural, that the same action taken at different points in a turning cycle produces entirely different results. And the 19 (The Sun) brings the radiant, authoritative presence that allows the pioneer to be genuinely followed rather than merely observed from a distance. Together, these three create someone who is genuinely built to move into unmapped territory — not recklessly, but with the specific combination of visionary confidence and cyclical awareness that allows a genuine first-mover to navigate without a map by reading the terrain.`,
      shadow: `The shadow of the 1-10-19 is the isolation that pioneering creates when it is pursued without the equally important work of building the relational and structural foundations that allow what is created to sustain itself. The 1's originating energy is addicted to the moment of beginning — the Magician at the table with all four elements arranged is in his element. The ongoing management of what has been created, the patient institutional work of bringing others into sufficient understanding to carry the vision forward, the willingness to be wrong publicly and adjust — these are far less interesting to the 1 energy and are frequently underinvested. The 10's cyclical awareness, in the shadow, can become a justification for premature abandonment: "the cycle has turned," "the timing has shifted," "this is no longer the right moment" — used as an exit from the difficult middle phase of genuine creation rather than as a genuine read of external conditions.`,
      path: `The integration of the 1-10-19 is the development of what might be called a legacy consciousness — the awareness that the point of blazing a trail is that others can walk it. This requires two specific capacities that do not come naturally to this combination: the capacity to document and transmit (to make the implicit map explicit enough that others can navigate without the original pioneer present), and the capacity to endure the middle — to remain committed to what has been initiated through the unglamorous phase of consolidation, when the 1's energy would rather be beginning something new and the 19's radiance is not particularly engaged by the quiet work of maintenance. The Wheel's gift — the timing intelligence — is the resource: use it not as an exit strategy but as a navigation tool for knowing when to push and when to consolidate. A frequency that keeps broadcasting "beginning" and never "sustaining" is what keeps drawing ventures that never quite compound.`,
      health: `The somatic signature of the pioneer program tends to concentrate in the nervous system — specifically in the way the sympathetic activation that drives genuine innovation interacts with the body's need for recovery. Chronic low-grade hyperarousal, difficulty with genuine rest (the mind continuing to generate even when the body is technically still), and immune vulnerability in the post-peak phases of major creative or professional cycles are common. The heart — as both the physical pump and the energetic centre of the self's relationship to its own radiance — can be subject to arrhythmia and irregular load under the high-variability demands of a pioneering life.`,
      positive: `You initiate into unmapped territory and stay long enough to document the path, and because the frequency of commitment is real, what you build compounds instead of resetting.`,
      negative: `A frequency permanently tuned to beginning rather than sustaining keeps drawing exits disguised as good timing — the ventures never quite compound because "the timing shifted" is easier to believe than staying.`,
    },

    {
      numbers: [20, 11, 2],
      name: 'The Awakening Teacher',
      category: 'Purpose & Mission',
      heading: 'The Gift That Can Only Be Given After It Has Been Lived',
      why: `The 20-11-2 is the program of the person whose genuine contribution to the world cannot be separated from the specific form of their own awakening — who teaches not from a curriculum but from transformation, whose knowledge is not accumulated but metabolized. The 20 (Judgement) carries the frequency of the summons: the moment when the old version of the self is no longer adequate, when the call to a fuller expression arrives and the decision to answer it — or not — becomes the defining choice of the life. The 11 (Justice) brings the precise, uncompromising perceptual intelligence of the person who sees clearly — who can cut through the performed version of a situation to its structural truth, who cannot be deceived by surface presentations because their perceptual equipment simply does not register them. And the 2 (The High Priestess) brings the receptive, deeply attuned quality of someone who processes reality through an interior knowing that operates faster and with more accuracy than rational analysis can account for. Together, these three create someone who is genuinely capable of seeing people — of perceiving their actual state, their actual potential, and the actual gap between the two — in a way that changes the people who receive that perception.`,
      shadow: `The shadow of the 20-11-2 is the teacher who has not yet resolved their own relationship to the material they teach — who carries the specific discomfort of someone who knows a great deal about transformation from a position of incomplete personal transformation. The 20 in this combination creates a very specific pressure: the summons has arrived, the call is clear, and the gap between the current reality and the called-toward reality is a source of continuous internal friction. This friction can express as a very high standard for others that is unconsciously calibrated to the gap in themselves — the teacher who is most impatient with precisely the pattern in their students that they have not yet resolved in their own interior. The 11's Justice can become, in the shadow, a rigidity of moral and psychological standard that makes genuine compassion difficult — the clear-sightedness that sees the wound in another also sees the shadow, and the 2's receptivity can pull back from full presence when what is perceived is uncomfortable.`,
      path: `The integration of the 20-11-2 is the willingness to teach from exactly where you are — not from where you intend to arrive, not from the fully resolved version of yourself that is still in process, but from the genuine current state of your own ongoing awakening. This requires the specific courage of intellectual and personal honesty in the teaching relationship: the capacity to say "I know this because I have lived it and I am still living it" rather than "I know this because I have completed it and now I pass it to you." The 2's gift of presence is the foundation: the High Priestess does not need to have all the answers to offer the quality of attention that allows another person to find theirs. The impatience directed at a student is simply the unresolved gap in yourself reflected back at close range — resolve it there, and the mirror stops needing to appear in front of you.`,
      health: `The somatic expression of this program tends to involve the nervous system and the perceptual organs — specifically the eyes, which in energetic anatomy are the instruments of clear seeing, and which can be subject to strain and sensitivity in people whose perceptual gifts are operating at high load. The throat and the chest are also significant: the 20's summons asks for voice, and the period before the full integration of that voice can produce physical symptoms in the territory between the heart (where the knowing lives) and the throat (where it must exit to become teaching).`,
      positive: `You teach honestly from exactly where you are, and because your own gap has genuinely closed, the students and situations that arrive no longer need to mirror it back at you.`,
      negative: `Impatience with a student's unresolved pattern is the unresolved gap in yourself finding a convenient mirror — the world keeps handing you that exact reflection until you address the original.`,
    },

    {
      numbers: [21, 12, 3],
      name: 'The Artist\'s Sacrifice',
      category: 'Purpose & Mission',
      heading: 'The Creative Life That Has Not Yet Given Itself Full Permission',
      why: `The 21-12-3 program carries the specific tension of the person who is genuinely, unmistakably a creator — for whom the production of beauty, meaning, form, and aesthetic experience is not a hobby or a supplement but the actual substance of their contribution to the world — who has not yet arrived at the full permission to live this truth without apology or qualification. The 21 (The World) brings the energy of completion and mastery: this is a person who carries the frequency of someone who has genuinely arrived at something, who has integrated enough of the previous 20 stages of development to be able to offer something whole. The 12 (The Hanged Man) introduces the suspension: the waiting, the sacrifice, the voluntary or involuntary surrender of one trajectory in service of a deeper one. And the 3 (The Empress) is the creative abundance itself — the irrepressible generative impulse, the sensory richness, the desire to make things that are beautiful and give them away.`,
      shadow: `The shadow of the 21-12-3 is the creative life that is perpetually almost fully expressed — the artist who is always preparing the major work, the writer who has almost enough material, the musician who will record when the conditions are right. The 12's Hanged Man energy, in the shadow of this combination, produces a quality of suspension that wears the costume of integrity: "I will not share it until it is ready" — when ready is not a description of the work's state but of the person's relationship to the vulnerability of full creative exposure. The 21's energy of completion is the specific gift being held in abeyance: this combination knows, somewhere beneath the suspension, that it is capable of genuine mastery. The gap between that knowledge and the willingness to demonstrate it publicly is where the program lives. The 3's creative abundance can express this shadow through prolific private production that is rarely or never released — an entire inner world that the outer world has not yet been invited into.`,
      path: `The integration of the 21-12-3 is the single most consequential creative act this combination can perform: releasing the work before it feels ready, because the feeling of readiness that this combination awaits is not a description of the work — it is a description of a psychological threshold that recedes as you approach it. The Hanged Man must come down from the tree. Not because the suspension has not been valuable — it has; the private development that precedes genuine mastery is real and necessary — but because the purpose of the development is always ultimately the offering. Begin with the smallest possible public release: one piece, one showing, one sharing. A creative life kept perpetually private is a frequency of "not yet" broadcast outward, and the audience, recognition, and momentum you're waiting for are simply matching the exact signal you have been sending.`,
      health: `The somatic expression of blocked creative flow tends to concentrate in the sacral centre — the physical territory of the lower abdomen and reproductive system, which in energetic anatomy governs creative and generative impulse. Irregular cycles (in all senses), digestive sensitivity, and lower abdominal tension in the periods of maximum creative suppression are common. The hands — the instruments of making — can develop chronic tension, repetitive strain, and sensitivity that expresses the frustrated desire to create something that has not yet found its channel of release.`,
      positive: `The work gets released before it feels ready, and because "finished enough to share" is the frequency actually being broadcast, the audience and momentum you were waiting for start arriving in kind.`,
      negative: `A creative life kept perpetually private broadcasts "not yet" as its steady signal, and the audience and recognition that never quite arrive are only matching the exact frequency being sent outward.`,
    },

  ]; // end programs


  // ── Public API ─────────────────────────────────────────────────────────────

  /**
   * find(a, b, c) — returns the program matching all three numbers
   * in any order, or undefined if none exists.
   */
  function find(a, b, c) {
    const query = [a, b, c];
    return programs.find(p =>
      query.every(n => p.numbers.includes(n)) &&
      p.numbers.every(n => query.includes(n))
    );
  }

  /** findByCategory(cat) — returns all programs in a category. */
  function findByCategory(cat) {
    return programs.filter(p => p.category === cat);
  }

  /** all() — returns the full array (read-only copy). */
  function all() { return programs.slice(); }

  return { find, findByCategory, all };

})();
