'use strict';

/**
 * Destiny Matrix — Programs Database (Natalia Ladini system)
 * ----------------------------------------------------------
 * Each program is a 3-number combination found at specific
 * node intersections in the matrix. The `numbers` array is
 * order-independent — lookup matches any permutation.
 *
 * Fields mirror DMicroContent entries so they can render
 * inside the same info card:
 *   heading  — thematic title
 *   why      — core strategy / the subconscious tug-of-war
 *   shadow   — in the minus / the shadow self
 *   path     — integration / therapeutic recommendations
 *   health   — somatic / body manifestation (optional)
 */

window.DMPrograms = (function () {

  const programs = [

    // ── 1. SOCIAL STATUS & SELF-WORTH ──────────────────────────────────────

    {
      numbers: [16, 5, 7],
      name: 'Loss of Authority',
      category: 'Social Status & Self-Worth',
      heading: `You're Still Deciding Whether Authority Can Be Trusted`,
      why: `You've likely watched or lived through a real destabilization of authority — a father who fell from power, a system that promised security and then quietly withdrew it, a mentor who turned out to be less than the image they projected. When the 16, the 5, and the 7 meet in your chart, they set up one of the most tangled tensions the matrix has to offer: the collapse of an established order (16) meets an inherited structure of social authority (5), and both run straight into your own drive toward purposeful, self-directed movement (7). You're still trying to navigate forward, even though something along the way took your map. The core of it is a real tension between respecting authority and a hard-won, justified skepticism that authority has earned through past betrayal.`,
      shadow: `Left unexamined, this shows up as a specific and often invisible kind of sabotage: devaluing the very authorities you're secretly still seeking approval from. You might present as someone who's "seen through" the hierarchies other people trust, while quietly organizing your whole professional and social life around proving yourself to those same hierarchies. The gossip about colleagues isn't cruelty — it's an internal comparison that never resolves. Rejecting established experts isn't confidence — it's armor from someone once burned by expertise who hasn't finished grieving it. A sense of entitlement around money — the feeling that it should just arrive without the specific effort the world seems to demand — is the leftover of an old expectation that the system owed you something, and now that the system's collapsed, the debt feels unpayable. Financially, this can look like a string of near-misses: real capability that somehow doesn't convert into stable accumulation, because your relationship to authority — which governs earning in almost every social system — stays ambivalent.`,
      path: `Try starting not with rebuilding authority from the outside, but with a very specific internal act: grieving the version of authority that failed you, without handing its failure to every structure you encounter afterward. There's always a gift inside a collapse like this — it makes visible what was never actually stable. The question is whether you can take that as information instead of proof that nothing can be trusted. This is the harder, more empowering half of it: the near-misses that keep turning your capability into stalled accumulation aren't the market's verdict on you — they're old distrust still getting broadcast into every negotiation and opportunity. Practically: practice listening without preparing your rebuttal. Accept that some people in positions of institutional knowledge have genuinely earned what they carry, even if others haven't. Start separating "this specific person let me down" from "authority itself is a fraud." Once that distrust resolves in you, the structures you engage with stop needing to keep proving themselves unreliable.`,
      health: `This tends to show up in your neck and upper cervical spine — literally the place where your body holds the tension between "head" (authority, hierarchy, structure) and "body" (the felt sense of what's actually true). Watch for chronic tension headaches, jaw clenching especially at night, and a stiffness in your neck's range of motion. The pattern underneath is usually low-grade chronic activation rather than acute stress spikes — your body running a background vigilance program it's simply forgotten how to switch off.`,
      positive: `You navigate forward with real capability and a healthy, resolved relationship to authority, and because that distrust has been metabolized rather than carried, opportunities convert cleanly into stable accumulation instead of near-misses.`,
      negative: `Unresolved distrust of authority gets broadcast into every negotiation, and the world keeps matching it — genuine capability stalling into near-misses because the vibration underneath is still bracing for another betrayal.`,
    },

    {
      numbers: [5, 17, 12],
      name: 'Public Disgrace / Fear of Shame',
      category: 'Social Status & Self-Worth',
      heading: `You're Waiting to Feel Ready Before You Let Anyone See You`,
      why: `Somewhere deep down, you're convinced that the unadorned truth of who you are wouldn't survive being seen — so you've built a magnificent external presentation instead. The 5-17-12 combination is one of the quietest, most devastating patterns in the matrix. The 5 (Hierophant) gives you a sharp sense of social codes, of how things are supposed to look, of the standards people use to judge credibility. The 17 (The Star) — luminous, vulnerable, genuinely hopeful — runs straight into tension with the 5's concern for presentation, which means you may possess real beauty and light but can't quite let it arrive unmediated, unprepared, unstrategized. The 12 (The Hanged Man) is the deepest layer: the energy of suspension, of someone who's chosen — usually without fully realizing it — to put real life on hold while perfecting the conditions under which it will finally be safe to live it. Together, this makes you intensely aware of how you appear, perpetually preparing to make your real move, and somehow never quite making it.`,
      shadow: `You might experience this less as fear and more as discernment — you know which opportunities are worth taking, which relationships are worth investing in, which projects can survive real scrutiny. What's worth checking honestly is whether that discernment is a genuine capacity or a sophisticated reason to never expose yourself to the one thing you actually fear: being seen as insufficient, ordinary, less than the image you've so carefully built. The Hanged Man matters here — he's suspended, yes, but he chose the tree. The waiting is self-created: the career that never quite launches, the relationship that never quite deepens, the creative work that's always almost ready to share. Publicly, people often admire your composure, your strategic intelligence, your unshakeable image. Privately, you might be managing a constant low-level fear that the composure is the only thing standing between you and exposure.`,
      path: `Try this single reframe: public mistakes aren't the enemy of credibility — they're the raw material genuine credibility is actually built from. The people who carry the deepest, most durable authority aren't the ones who never failed publicly. They're the ones who failed publicly and let others see how they responded to it. The Star inside this pattern is your doorway — her luminosity is exactly the authentic, undefended quality no amount of strategic presentation can replicate. Start with low-stakes experiments in real visibility: share something true about a difficulty you've faced, without packaging it to be palatable. Notice what happens. This feels uncomfortable because it removes the comfort of endless preparation and puts the responsibility on what you're actually broadcasting: a life that keeps offering "almost ready" opportunities is matching a vibration still unwilling to be seen unfinished. The terror this pattern predicts almost never matches what actually arrives — and in that gap, you may discover it was never the audience you were afraid of. It was you.`,
      health: `Shame-based programs like this one tend to settle in the throat (where unspoken truth and suppressed expression live), the skin (your body's primary interface with the outside world and other people's gaze), and the immune system, which runs at a chronic low ebb in people maintaining high-tension presentation for long stretches. Watch for recurring tightness in the chest — your body's signal that the suspension is asking for release.`,
      positive: `You let your genuine radiance arrive unmediated, and because you're broadcasting readiness rather than perpetual preparation, real opportunities arrive that are ready to be taken rather than endlessly rehearsed.`,
      negative: `A vibration still unwilling to be seen unfinished keeps drawing opportunities that stay perpetually "almost ready" — the world matching the exact frequency of a real move that never quite gets broadcast.`,
    },

    {
      numbers: [6, 5, 17],
      name: 'Pride',
      category: 'Social Status & Self-Worth',
      heading: `Your Beauty Was Never Meant to Be a Verdict on Everyone Else`,
      why: `You carry something genuinely rare — a real magnetism, an ease in your own charm, a sense that rooms warm slightly when you enter them — and somewhere along the way that gift got quietly mistaken for evidence of your own superiority. The 6-5-17 is one of the most naturally radiant and most quietly arrogant programs in the matrix. The 6 (The Lovers) gives you a genuine sensitivity to beauty and an effortless charisma that draws people in. The 5 (Hierophant) brings a sharp awareness of social hierarchy — where you rank, who's above and below you, what earns respect within an established order. And the 17 (The Star) adds real luminosity, a sense of being naturally set apart, favored, meant for something more than the ordinary run of things. Together, these can curdle into a quiet certainty that your charm entitles you to more — more attention, more deference, more forgiveness — than anyone else in the room.`,
      shadow: `Off your authentic frequency, this shows up as a specific and often well-disguised superiority: using your attractiveness and social ease to get what you want from people, then losing interest in them the moment they stop reflecting your specialness back to you. You may find yourself quietly ranking people by how impressive they are to be seen with, judging others for their appearance or their standing while feeling exempt from the same judgment yourself. Criticism lands as an attack on a self-image that was never supposed to be questioned. There's often a pattern of leaving relationships, jobs, or whole social circles the moment you stop being the most admired person in them — not because the situation changed, but because being ordinary there became unbearable.`,
      path: `Try practicing a specific, uncomfortable exercise: go somewhere you won't be recognized as impressive, and stay there anyway. Notice what your worth actually feels like once the audience that used to confirm it is gone. The real work here is separating your beauty and charisma — which are simply true, and don't need defending — from the belief that they make you better than the people around you. True inner value was never actually competing with anyone else's; it only feels that way when self-worth has been quietly outsourced to comparison. Practice genuine curiosity about people you'd normally dismiss as beneath your notice. The humility this asks for isn't a diminishment — it's what finally lets your actual radiance be received as a gift instead of a hierarchy.`,
      health: `Pride like this tends to settle in the posture and the face — a held, elevated bearing that can translate into chronic neck and upper-back tension from literally carrying yourself above others. Watch for jaw tightness tied to unspoken judgment, and a skin/complexion sensitivity that flares under any threat to the self-image. The adrenal system often runs in a low-grade, status-monitoring vigilance, always scanning a room for where you rank.`,
      positive: `Your natural charm and radiance are simply true, and once they stop being used to rank yourself against others, they become a gift people are drawn to rather than a hierarchy people resent.`,
      negative: `A quiet certainty of being above the room keeps costing you the very rooms you needed to stay in — relationships and opportunities abandoned the moment they stop confirming a specialness that was never actually in question.`,
    },

    // ── 2. INTELLECTUAL & MINDSET ALIGNMENT ────────────────────────────────

    {
      numbers: [17, 22, 5],
      name: 'Academic Knowledge / Rigid Dogma',
      category: 'Intellectual & Mindset Alignment',
      heading: `You Might Be Too Smart to Notice When You've Closed a Door`,
      why: `You have a genuine gift for taking complicated material and turning it into something reliable, teachable, transmissible — but that same gift can quietly become a cage. The 17-22-5 combination is one of the most intellectually formidable, and potentially most intellectually imprisoned, personalities in the matrix. The 17 (The Star) gives you real pattern recognition and a sense of cosmic coherence even in turbulent conditions. The 22 (The Fool, completionist energy in this system) gives you an enormous, sometimes unwieldy creative potential — the sense of unlimited possibility, beginnings not yet constrained by outcome. And the 5 (Hierophant) sits at the center: your deep need for knowledge to be organized, categorized, transmitted through established channels, and measured against accepted standards. The system you build can become more important than the living reality it was meant to describe.`,
      shadow: `This is cognitive conservatism in someone too intelligent to recognize it as such. Here's the mechanism: you've built a framework for understanding the world that's genuinely sophisticated and has served you well — so when new information doesn't fit inside it, your automatic response isn't curiosity, it's threat assessment. You defend the framework. You examine the new information for its flaws rather than its insights. The person carrying that new experience doesn't get open hostility from you — they get something more devastating: intellectual contempt. Their evidence is insufficient. Their methodology is flawed. Their sources aren't credible. This can make you genuinely frustrating to collaborate with, because your certainty is so well-constructed and thoroughly articulated that it's hard to find an opening for anything genuinely new. Professionally, this often shows up as resistance to methodological evolution — insisting the field has already found the correct approach and any departure is regression, not development.`,
      path: `Try one practice that's genuinely difficult for you: deliberately, sustainedly engaging with a perspective you've already decided is wrong — not to refute it, but to find the specific, genuine insight that made someone intelligent enough to hold it. Every rigidly wrong position contains a real observation your more sophisticated framework either hasn't accounted for yet or has accidentally excluded. Your 22 energy — the potential for radical new beginnings — is always waiting underneath your 5's structured certainty. The path forward is letting the 22 periodically dismantle what the 5 has built, not as destruction but as the renewal that keeps a living framework from becoming a museum exhibit. A framework kept genuinely alive stops needing to run into so much resistance, because it's no longer broadcasting a closed certainty for the world to push back against.`,
      health: `Cognitive rigidity tends to concentrate in your spinal column, especially your upper back and neck, where held positions literally show up in your musculature. Watch for tension headaches from the sustained effort of maintaining a complex internal certainty against a world that doesn't always conform to it, plus eye strain from hyperactive cognitive processing. The vagus nerve — your nervous system's flexibility regulator — can go chronically under-stimulated in people whose cognitive style leans heavily analytical and control-oriented.`,
      positive: `You build genuinely reliable systems while staying curious enough to let them evolve, and that openness is what draws collaborators and new information toward you rather than resistance.`,
      negative: `A closed certainty broadcasts itself before a single word is spoken, and the friction and resistance that keeps arriving in collaborative settings is simply the world meeting that frequency in kind.`,
    },

    {
      numbers: [8, 13, 5],
      name: 'Displacement / In Someone Else\'s Place',
      category: 'Intellectual & Mindset Alignment',
      heading: `Something in You Knows This Isn't Quite Your Life`,
      why: `You might carry a persistent, low-level sense that something's slightly off-center — that the role you're occupying was built for someone else, that the life you're living doesn't quite fit your shape. The 8-13-5 program generates one of the most disorienting inner landscapes in the matrix. The 8 (Strength) gives you genuine capability — real endurance, a real capacity to hold complexity — but here that capability often gets deployed in service of structures, relationships, or professional contexts that weren't built to your actual specifications. The 13 (Transformation) brings radical change — not gentle evolution, but the kind of cellular restructuring that requires something to actually end before something new can begin. And the 5 (Hierophant) holds the whole thing in place through your deep attachment to established structures and earned position: you don't just walk away from what you've built, what you've sacrificed for, what the system says you should want. Together, these create someone who's clearly in the wrong place but has an extraordinarily sophisticated set of reasons for staying.`,
      shadow: `This tends to show up clearest in relationships and professional positioning. You might develop a pattern of trying to claim something that genuinely belongs to someone else — not through any malicious intent, but through a real confusion between "what I want" and "what I'm owed." That can look like gradually, subtly displacing another person in a social group, positioning yourself for a role someone else built, or unconsciously competing with your own partner for the primary spot in shared social settings. The analysis paralysis is real too: your capacity for holding complexity, combined with knowing any move will require a genuine ending, combined with your reluctance to give up an earned position — this combination can leave you years deep in the analytical stage of a transition you never quite arrive at.`,
      path: `Try finding the courage to let what's already ended actually be acknowledged as ended — to stop artificially propping up something past its natural life with the considerable force your endurance can bring to the project of maintenance. This isn't asking for catastrophe. It's asking for honesty — the specific, courageous honesty of saying "this chapter is complete" instead of "I haven't found the right moment to transition yet." Practically: use a defined trial period to test a new direction, instead of requiring yourself to fully commit before you have enough information. And in relationships, start practicing wanting genuinely good things for the people whose positions you've been, even unconsciously, measuring yourself against. That's not altruism — it's the specific move that releases the displacement pattern, because a life spent occupying spaces built for someone else is exactly what a feeling of "I am owed this" reliably attracts.`,
      health: `Displacement often shows up in your joints — specifically hips and knees, which in energetic anatomy govern flexibility and the direction of your path through life. Watch for chronic hip tension, knee instability under professional or relational stress, and lower back pain that correlates with avoiding a decision. Your digestive system can carry the unresolved feeling too, showing up as irritability in environments where feeling out of place is strongest.`,
      positive: `You have the endurance to hold complexity and the honesty to act on genuine endings, and because you're no longer occupying a role built for someone else, the position you actually land in fits.`,
      negative: `A vibration of "I am owed this" keeps drawing you into roles and relationships built for someone else — the confusion between want and entitlement recreating the exact displacement it's trying to resolve.`,
    },

    {
      numbers: [9, 16, 7],
      name: 'The Program of Silence',
      category: 'Intellectual & Mindset Alignment',
      heading: `You Know More Than You've Ever Said Out Loud`,
      why: `You carry an extraordinary interior richness the world hasn't fully received yet — and in a lot of cases, hasn't been fully offered yet either. The 9-16-7 is the program of someone with real depth who's learned, somewhere along the way, that expressing it carries risk. The 9 (The Hermit) gives you deep interior knowing — wisdom that comes from real solitude, from a sustained inward attention most people only touch briefly and under pressure. The 16 (The Tower) brings a moment of structural disruption — you've likely experienced, or are still processing, a significant external collapse that reshaped your relationship to trust and to being known. And the 7 (The Chariot) gives you a drive toward purposeful movement — an internal compass that knows where it wants to go, but hasn't always found the conditions that feel safe enough to announce the direction.`,
      shadow: `This can look like your interior life becoming a permanent residence instead of a sanctuary. You might say "everything's fine" while privately managing a complexity that, spoken out loud, would ask you to be genuinely vulnerable with another person. The 16 often explains the retreat: there was a moment — maybe more than one — where real expression met a response that felt like the Tower. Your openness got punished. Your authentic voice got ridiculed, dismissed, or just met with blankness. And your nervous system drew the reasonable conclusion: silence is safer. The tragedy is that conclusion, correct in its original context, becomes a life sentence applied to every context after — including the ones where real expression would actually be met with the recognition you're quietly, persistently hungry for. The missed opportunities aren't dramatic. They're quiet: the conversation that stayed surface-level when something real was available, the connection that couldn't deepen because the drawbridge stayed up, the contribution you never offered because the moment felt too exposing.`,
      path: `This isn't about suddenly, dramatically dismantling the silence. It's gradual — patiently building new evidence, slowly accumulating experiences where real expression got offered and received without disaster. Start with the mediums that feel least exposing: writing no one reads yet, voice recordings no one hears yet, conversations with people you trust completely. The practice isn't the final product — it's rehabilitating your belief that expression is survivable, because a world that keeps meeting your voice with silence or misattunement is often just matching the muted frequency the voice itself is still broadcasting. As new evidence builds, let the radius of sharing expand — a little at a time, on your own terms. The silence was a necessary passage. It's not the destination.`,
      health: `Unexpressed inner life almost always shows up in the throat — the literal architecture of your voice — and often extends into the thyroid, which governs your metabolic regulation and energetic output. Watch for recurring sore throats, voice loss under interpersonal stress, and thyroid irregularities. Your shoulders can hold unexpressed weight too, becoming chronically elevated when you're protecting your throat and chest from the vulnerability of real expression.`,
      positive: `Deep interior richness gets offered rather than withheld, and because the voice is genuinely broadcasting rather than muted, people finally meet it with the recognition and resonance it was always hungry for.`,
      negative: `A voice still bracing for the old wound broadcasts itself as muted before a word is even spoken — and connections keep landing at surface level, matching the guarded frequency actually being sent.`,
    },

    // ── 3. ABUNDANCE & FINANCIAL FLOW BLOCKS ───────────────────────────────

    {
      numbers: [4, 21, 17],
      name: 'Focus vs. Distraction',
      category: 'Abundance & Financial Flow',
      heading: `You Have Too Many Good Ideas to Finish Just One`,
      why: `You're simultaneously one of the most focused and one of the most scattered people anyone will ever meet — and both are true at once. The 4-21-17 program is a genuinely paradoxical inner experience. The 4 (The Emperor) gives you profound structural intelligence — the ability to envision a complete system and build something that will hold its own weight over time. The 21 (The World) gives you the energy of completion and mastery, the frequency of someone who's finished a full cycle and arrived at real integration. And the 17 (The Star) gives you a luminous, expansive quality that sees possibility in every direction at once. The 4 wants to build one thing, deeply and durably. The 17 wants to explore everything that glitters. And the 21 keeps reminding you that completion is possible — while the gap between where you are and that completion can feel so large your mind fractals into sub-projects, side strategies, and supporting initiatives that gradually eat the resources meant for the main thing.`,
      shadow: `This isn't laziness, and it isn't a lack of vision — it's the opposite. Too much vision, too many genuinely good ideas, too real a sense of how each one could work, combined with a real difficulty holding the container long enough for any one of them to reach the depth where it becomes self-sustaining. The energy crashes that punctuate this pattern aren't random — they tend to arrive right as a project approaches the unglamorous, repetitive, incrementally-improving phase that follows the initial vision and precedes actual results. Your Star energy loves the beginning and the completion. The middle — the long, invisible work of real development — is exactly where distraction arrives to "rescue" you. Financially, this often shows up as expensive pivots: real investment in the start of something that never reaches completion, followed by the next start, and the next, each one pulling resources from the previous unfinished cycle.`,
      path: `Try the deliberate, almost counter-instinctive practice of choosing one primary direction and defending it against your own expansive intelligence long enough to find out what it can actually become. This isn't about permanently suppressing your visionary gifts — it's about channeling them. Write down every idea that comes to you. Don't discard them — they're real and they have value. But give them a container: a file, a list, a defined space where they can wait without eating the current project's oxygen. You already know how to build. You already know what completion feels like. Your work is trusting those parts of yourself long enough to actually feel what it's like to bring one thing to its real conclusion — and once that frequency of committed follow-through is genuinely established, resources and money stop scattering across half-finished cycles and start compounding in one place.`,
      health: `This tends to show up in your nervous system's regulation — specifically in a pattern of overactivation followed by sudden depletion. Watch for adrenal fatigue from sustained multitasking, headaches tied to context-switching, and sleep disruption from a mind that won't release its multiple active threads. Your eyes can be affected too — a particular fatigue that comes not from lack of sleep but from the sustained effort of holding multiple focal points at once.`,
      positive: `You channel a genuinely visionary mind into one primary direction long enough to see it through, and because that frequency of follow-through is real, resources and money compound in one place instead of scattering.`,
      negative: `A frequency still oriented toward the next exciting start keeps fracturing resources across unfinished cycles — the expensive pivots are less bad luck than the natural harvest of an unsettled vibration.`,
    },

    {
      numbers: [9, 14, 5],
      name: 'The Revenge Pattern',
      category: 'Abundance & Financial Flow',
      heading: `Part of You Is Still Building a Case Against Someone`,
      why: `You've likely been genuinely wronged — or gone through something your nervous system registered as a genuine wrong — and haven't yet found the release that would let the experience complete its cycle and give you back the resources it's still occupying. The 9-14-5 is the program of someone with a clear, almost structural sense of what's fair and what isn't, what was earned and what was taken. The 9 (The Hermit) gives you a deep, precise, uncompromising inner standard. The 14 (Temperance) gives you an extraordinary capacity for sustained, patient, meticulous effort toward a specific outcome. And the 5 (Hierophant) gives you an awareness of public and social codes — how recognition is supposed to be distributed, how systems are supposed to treat people who've contributed what you've contributed. The wound here is the gap between what the system was supposed to deliver and what it actually did.`,
      shadow: `This isn't rage — it's something far more energetically expensive than rage. It's a meticulous, highly organized, deeply intelligent allocation of your mental and emotional resources toward building a detailed internal case for why the person or system that wronged you deserves consequences. You may keep a running, specific blueprint for how that might happen — through their professional failure, their social exposure, their eventual admission that they were wrong — with more regularity than you fully recognize as a preoccupation. Financially, this costs you: your Hermit-energy, turned toward this pattern, withdraws the light that would otherwise illuminate your own path forward, redirecting it into a long corridor of retrospective justice. Your patient execution, aimed here, produces not transformation but the grinding repetition of accumulated grievance. And your social awareness keeps a perpetual watch on the other person's standing — a habit that keeps the wound fresh precisely because it keeps your attention inside its frame.`,
      path: `Try a distinction that's easy to state and genuinely hard to actually do: forgiveness isn't the same as absolution. You're not being asked to decide what happened was okay. You're being asked to make a practical decision: stop allocating resources to an outcome — someone else's suffering, their recognition of their error, their public accountability — that you can't control and that isn't making your life bigger. Your real gift here is alchemical: you have the genuine ability to turn bitterness into fuel, but the direction of the transformation matters. Redirect your specificity, your patience, and your intelligence toward building something in your own domain so clearly excellent that the comparison becomes irrelevant. Every hour spent monitoring the old wound is a vibration of lack still being broadcast — the moment your attention redirects toward your own building, abundance finally has somewhere to land.`,
      health: `Held resentment tends to concentrate in the liver — the organ traditionally associated across multiple systems with processing anger and injustice. Watch for recurring inflammatory conditions, skin irritations, and headaches tied to dwelling on the grievance. Your cardiovascular system carries the sustained load too — blood pressure irregularities and heart rate variability that track emotional activation rather than physical exertion are worth watching.`,
      positive: `Patient, meticulous execution gets redirected toward building something clearly excellent, and because your attention is no longer spent on old grievance, abundance finally has somewhere current to land.`,
      negative: `Hours spent monitoring an old wound keep broadcasting a vibration of lack — the same intelligence that could be building genuine abundance stays occupied re-litigating a debt that was never going to be repaid.`,
    },

    {
      numbers: [15, 19, 5],
      name: 'The Wealth Magnifier',
      category: 'Abundance & Financial Flow',
      heading: `Your Power Is Real — the Question Is What It's For`,
      why: `You're genuinely built for scale — large systems, large teams, large financial flows, large public platforms. The 15-19-5 is one of the most financially potent programs in the matrix, and one of the most morally demanding. The 15 (The Devil) gives you a raw material magnetism — the capacity to attract resources, understand power dynamics intuitively, and navigate the energetics of accumulation in ways other people find mysterious. The 19 (The Sun) gives you extraordinary personal radiance — natural authority and warmth that commands attention without effort, that makes rooms reorganize around you. And the 5 (Hierophant) gives you the social and institutional intelligence to deploy those gifts within existing power structures and generate real-world results. The question this program doesn't answer for you — you have to answer it yourself — is: what is all this power actually in service of?`,
      shadow: `The shadow shows up when the power you generate gets redirected from genuine creation into managing psychological dominance. Your magnetic pull, in shadow, becomes the irresistible draw that creates dependency instead of empowerment — the leader whose team can't decide anything without them, the partner who structures the relationship so they're always the one with more to lose, the business owner whose compensation quietly maintains an asymmetry of power. Your radiance, shadowed, becomes performed warmth — public generosity that's genuinely charming and completely strategic. And your social intelligence becomes a precise read of who in any room holds the most influence, and a systematic cultivation of exactly those relationships. The financial trap here is often excess without meaning: accumulating far more than any genuine life project would need, driven by a hunger that isn't really for money but for the specific feeling of being ungovernable — beyond scarcity, beyond the vulnerability of need.`,
      path: `This isn't about renouncing power or wealth — it's about consciously deciding what those things are actually for. You have a genuine capacity to generate positive change at real scale. Your radiance, when it's authentic instead of performed, creates the conditions for other people's growth. Your material intelligence, aimed at genuine contribution, can build structures that outlast you. And your institutional awareness can navigate large systems in ways that create durable, legitimate authority. Practically: write down, and revisit regularly, a clear account of what your material accumulation is meant to accomplish in the world beyond your own comfort and status. That document anchors your magnetic pull toward creation rather than domination — and a frequency oriented toward genuine contribution is what lets real scale arrive without the excess that domination always eventually needs defending.`,
      health: `Under shadow conditions, this tends to concentrate in the cardiovascular system — where ambition and its cortisol load meet the physical demands of sustained high-intensity operation. Watch for blood pressure dysregulation, cardiac arrhythmias under competitive pressure, and inflammation-based conditions. This shadow also frequently expresses through your reproductive and endocrine systems, which govern your body's relationship to power, vitality, and primal energy.`,
      positive: `Magnetic presence and material intelligence get pointed at genuine contribution, and because the frequency underneath is creation rather than domination, scale arrives without needing to be defended.`,
      negative: `Power redirected into managing dominance broadcasts a hunger that is never actually satisfied by accumulation — more keeps arriving because the underlying feeling of scarcity was never the thing being solved.`,
    },

    // ── 4. RELATIONSHIP & LOVE PROGRAMS ────────────────────────────────────

    {
      numbers: [6, 15, 3],
      name: 'The Love Addict',
      category: 'Relationship & Love',
      heading: `For You, Love Isn't Part of Life — It's the Frame Around It`,
      why: `Love isn't a complement to your life — it's the architecture of it, the frame everything else gets organized, measured, and given meaning inside of. The 6-15-3 combination is the program of someone for whom relationship isn't a pleasant addition to an already full life, but a fundamental requirement, the way other people require air or structure. The 6 (The Lovers) gives you an exquisite, almost painful sensitivity to the quality of a connection. The 15 (The Devil) brings in compulsion — attachment that's slipped from choice into necessity, where a beloved's presence regulates your nervous system in a way nothing else quite matches. And the 3 (The Empress) brings a huge creative, generative warmth — a real desire to pour into another person, to nurture, to create together, to feel the fullness that only comes through intimate co-creation. Integrated, these produce extraordinary lovers: deeply felt, wildly creative, magnetically present. Unexamined, they produce a very human kind of suffering.`,
      shadow: `The relationship can become a regulatory mechanism instead of a genuine meeting between two people. The start of a new connection might not feel like pleasant anticipation to you — it might feel like relief, the temporary resolution of an internal state that's become unbearable. And because the connection is providing relief instead of joy, its actual quality matters far less than its presence. That's the mechanism of love addiction: lowering your standards not because you don't know better, but because the need for relief overrides what you know. You might stay in connections that are clearly harmful, because the familiarity of the harm has become, through repetition, more tolerable than the unfamiliarity of something healthy. Your creative energy, turned toward this shadow, can become the elaborate, unconscious work of making yourself indispensable to someone — not through genuine contribution, but by systematically occupying the spaces in their life in a way that creates dependency instead of desire.`,
      path: `The most important distinction you can learn here is the difference between the hunger for fusion (the shadow's demand) and a genuine desire for intimacy (the gift's offer). Fusion collapses the boundary between you and the other person; intimacy asks both of you to stay yourselves while actively, repeatedly choosing to move toward each other. Practically: build a life that's genuinely satisfying independent of whether any particular relationship is present — not as a strategy for attracting better partners, but because that shift is what makes the attraction almost inevitable anyway. Your creative energy is the key resource: redirect it toward making, building, contributing something that belongs entirely to you and doesn't need to be witnessed to be real. A self that no longer needs relief is what finally stops attracting relationships that only offer relief.`,
      health: `Love addiction tends to concentrate in the heart center and the endocrine system — specifically the dopamine and oxytocin pathways that govern bonding and reward. Love withdrawal is neurologically similar to substance withdrawal: real anxiety, restlessness, sleep disruption, and appetite changes. Your skin — your body's primary contact boundary — can express the longing for merger through chronic conditions sensitive to the quality of your relational environment.`,
      positive: `You love with genuine depth and creative warmth, and because your life is satisfying independent of any one relationship, the connections that arrive offer real intimacy rather than mere relief.`,
      negative: `A need for relief rather than joy is the actual signal being emitted, and it keeps attracting connections that supply relief and little else — familiar harm feeling safer than the unfamiliar health that was actually wanted.`,
    },

    {
      numbers: [3, 18, 12],
      name: 'Physical Suffering',
      category: 'Health & Vitality',
      heading: `Your Body Was Never the Verdict Against You It Learned to Seem`,
      why: `Somewhere in you, pain got recorded not as information but as injustice — proof that life had singled you out for something unfair. When the 3, the 18, and the 12 meet, they create one of the most physically preoccupied programs in the matrix. The 3 (The Empress) governs the body itself — its fullness, its fertility, its right to comfort and physical well-being. The 18 (The Moon) brings the deep, murky undercurrent: fear, distorted perception, the way old pain can blur into something bigger and more consuming than the original injury. And the 12 (The Hanged Man) defines the shape it takes: suspension, self-identification with the suffering itself, a life quietly organized around a wound that never got to fully resolve. Together, they can leave you carrying an old, intense physical pain as though it were still happening — a body that was taught to expect betrayal from itself.`,
      shadow: `This tends to surface as a genuinely distorted relationship with the body — swinging between two extremes that look opposite but come from the same root. One version becomes hypervigilant: obsessively monitoring symptoms, catastrophizing minor discomfort, treating every ache as the return of the old catastrophe. The other becomes its mirror: neglecting the body almost entirely, as if refusing to look at it is safer than confronting what it might reveal. Either way, your tolerance for pain — physical or emotional — runs low, and minor discomfort can trigger outsized irritation or panic. The Moon's fear often extends outward too, into an intense, sometimes disproportionate anxiety about the health of the people you love, especially anyone who feels vulnerable or unable to protect themselves.`,
      path: `The path here starts with a genuinely difficult reframe: pain is a signal, not a sentence. Try practicing acceptance of your body exactly as it is right now — its real strengths and its real limitations — rather than treating it as an adversary to be managed or a threat to be ignored. Caring for your own health isn't selfish; it's the actual foundation that lets you show up for anyone else. Consider putting your instinct to protect the vulnerable into direct use — volunteering with the sick, injured, or elderly can transform a private fear into a real, useful compassion. The old suffering doesn't have to keep defining your relationship to your body; it can become, instead, the exact reason you understand pain in others so well.`,
      health: `This program concentrates directly in the body's felt sense of safety — the nervous system runs a background alert for pain that's mostly historical rather than present. Watch for a genuinely low pain threshold, tension patterns that seem to guard old or even unrelated injuries, and stress responses that spike sharply around any health scare involving someone you love. Grounding, gentle movement, and consistent physical care tend to help far more than either hypervigilance or avoidance.`,
      positive: `You hold your body with steady, unafraid acceptance, and the old suffering becomes the exact source of a compassion that helps you genuinely support others through pain rather than fearing it.`,
      negative: `An old wound still read as injustice keeps the body on permanent alert — swinging between obsessive worry and total neglect because neither extreme has yet let the original pain finish being felt.`,
    },

    {
      numbers: [2, 11, 9],
      name: 'The Invisible Partner',
      category: 'Relationship & Love',
      heading: `You Give People Your Full Attention — Try Asking for It Back`,
      why: `You're genuinely, deeply present for other people in ways that are real and meaningful — and, at the same time, you may feel profoundly unseen at the core of your own intimate life. The 2-11-9 program creates one of the most spiritually advanced and personally frustrating relationship experiences in the matrix. The 2 (The High Priestess) gives you a receptive, deeply perceptive attention — you know what someone needs before they've said it, and you can hold emotional space with real steadiness, present the way water is present, taking the shape of whatever holds it without losing its own nature. The 11 (Justice) gives you a rigorous internal standard for fairness and accuracy — you see clearly, you know the difference between what's real and what's performed, and you apply that with a precision that's both a gift and a source of isolation. And the 9 (The Hermit) deepens the interior quality: you're self-sufficient to a degree others often misread as contentment or coldness, when the truth is neither.`,
      shadow: `Over time, you may have built a relational life where you're consistently the one giving perception and rarely receiving it. You might attract partners and friends who are mostly engaged with their own interior world — who benefit enormously from your attention without developing an equal capacity to turn it back your way. That's not random. At some level, you might choose this dynamic because it's safer. The High Priestess behind the veil isn't seen fully, which means she can't be fully rejected either. The Hermit who holds the light for others is too busy illuminating to need illumination himself. Your Justice carries a specific wound here: you know, with quiet precision, that the reciprocity you're providing isn't being matched — and the combination of knowing that and not saying it out loud builds up until it eventually shows as either withdrawal or a sudden, bewildering loss of patience.`,
      path: `Try developing a genuine, specific appetite for being known — not just being useful, not just being present, but actively creating the conditions where someone else has real access to your interior. That means identifying and challenging the specific belief keeping you behind the veil: that full visibility would reveal something insufficient, something the other person wouldn't choose if they saw it clearly. Start small — deliberate acts of disclosure, not confession, not performance, but genuinely sharing your own experience with someone who's earned the context. Notice what happens. A veil kept up is what keeps drawing partners who only take and never turn the light back; drop it, and reciprocity finally has an actual opening to arrive through.`,
      health: `This tends to show up in the kidneys — the organs energetic medicine associates with your deep reserves of vital energy, with fear, and with the exhaustion of sustained giving without enough replenishment. Watch for chronic fatigue disproportionate to physical exertion, lower back pain in the kidney region, and susceptibility to urinary tract issues under relational stress.`,
      positive: `You offer extraordinary perceptive presence and let yourself be genuinely known in return, and because the veil is actually down, reciprocity has somewhere real to land.`,
      negative: `A veil kept up for safety keeps drawing partners who take the perception offered and never turn it back — the world simply meeting the exact visibility that was actually extended.`,
    },

    // ── 5. HEALTH & VITALITY PROGRAMS ──────────────────────────────────────

    {
      numbers: [18, 9, 4],
      name: 'The Self-Dissolution Pattern',
      category: 'Health & Vitality',
      heading: `Your Body Might Be Saying What You Won't`,
      why: `Your body may have become the primary language for things your conscious mind hasn't found another way to process. The 18-9-4 program is one of the most somatically expressive combinations in the matrix. The 18 (The Moon) gives you the deep psychic and somatic sensitivity of the unconscious — your body isn't a separate system from your emotional and energetic field, it's its most immediate and faithful recorder. The 9 (The Hermit) brings a tendency toward sustained interior processing — you hold a lot inward for a long time, carrying an enormous amount of awareness without necessarily having an outlet for it. And the 4 (The Emperor) brings the structural piece: trying to maintain order, control, predictability, and reliable output in every circumstance — including the ones where your body is clearly telling you the current setup isn't sustainable. Together, this can mean managing a rich, complex interior life inside a framework of external reliability, using the body as a pressure valve when the gap between the two gets too large.`,
      shadow: `You may be using illness — consciously or entirely unconsciously — as the only socially acceptable way to rest, set a limit, or express a need inside your own self-constructed framework. The Emperor in you doesn't cancel. The Hermit in you doesn't complain. The Moon, though, will find a way to make the boundary visible through your body, because your body can't maintain the same managed presentation your mind can. Recurrent, seemingly unexplained conditions — symptoms that show up without a clear physical cause, that correlate with periods of sustained pressure or unexpressed need, that improve substantially when you're finally forced to rest — are the signature here. This isn't hypochondria, and it isn't weakness. It's an intelligent adaptation from a system that's learned the only language its environment consistently responds to is physical limitation.`,
      path: `Try building direct channels for the things currently getting routed through your body: rest that's chosen rather than forced, limits that are communicated rather than enacted through collapse, needs that are expressed rather than accumulated. Your structural intelligence is the resource here — the same capacity that builds reliable external systems can be turned toward building reliable internal ones. A scheduled rest as non-negotiable as a professional commitment. A weekly practice of saying something that hasn't been said yet. A regular check on the gap between what you're carrying and what you've actually agreed to carry. Your body is simply the most literal mirror available for an unspoken internal state, and it'll step back from that role the moment the message genuinely starts getting through by other means.`,
      health: `The physical signatures here are some of the most varied in the matrix, precisely because your body is functioning as the primary expressive channel. Autoimmune conditions (a precise somatic metaphor for internalized conflict), chronic fatigue, hormonal shifts, skin conditions, and digestive issues are all common. The pattern usually correlates with psychosocial stress rather than simple physical causation — which doesn't mean the symptoms aren't real, just that treating them may need to include that psychosocial layer.`,
      positive: `Rest gets chosen and needs get spoken directly, so the body — the most literal mirror of your internal state — no longer has to manufacture symptoms just to be heard.`,
      negative: `An unspoken internal state finds its most literal mirror in the body — illness becomes the only channel loud enough to communicate a boundary the mind has refused to say out loud.`,
    },

    {
      numbers: [16, 7, 14],
      name: 'The Burnout Spiral',
      category: 'Health & Vitality',
      heading: `You Kept Going So Long, You Stopped Noticing the Cost`,
      why: `You may be burning out not from a lack of capacity, but from an excess of it — you've been able to sustain such a high level of output for so long that the warning signals have quietly become background noise. The 16-7-14 program describes someone who runs at high output without much visible distress until the moment everything collapses. The 16 (The Tower) brings a structural volatility — physically, this shows up as a system that runs fine until it suddenly doesn't. The 7 (The Chariot) brings a directed, sustained, disciplined drive that can carry you through enormous difficulty without showing external signs of the toll — you're someone who works through illness, works through loss, works through exhaustion, because forward momentum is a real part of your identity, not just a habit. And the 14 (Temperance) brings an extraordinary capacity for balance and integration — which, in shadow, becomes a sophisticated rationalization of imbalance: you've gotten genuinely good at making extreme output look sustainable, because you've refined your tools for managing the signs that something's wrong.`,
      shadow: `The collapse this program predicts rarely arrives as a shocking surprise — it's usually the predictable outcome of a system that was never designed to run indefinitely at the level it was being pushed. This kind of burnout is rarely sudden — it tends to show up as a gradual diminishment of the very things that defined you: the creativity that always came easily starts feeling effortful, then goes quiet. The resilience that always felt reliable turns brittle, then unavailable. The tolerance for difficulty that felt unlimited reveals its actual limit in a way that feels, from the inside, like a fundamental change in who you are, rather than what it actually is: a healthy refusal from a system that's been asked to do too much for too long. The shame that comes with this is often significant — your identity is organized around reliable forward motion, and a Chariot that's stopped moving experiences that as failure rather than wisdom.`,
      path: `Try reconfiguring the relationship between your productivity and your worth. The Tower here isn't here to punish you — it's here to clarify what your genuine foundation actually is and what was always built on the unstable ground of output-as-identity. Your alchemical capacity is the key resource: you have the genuine ability to redesign your own operating system, to build something more sustainable than what came before. Start by naming the specific beliefs that drove the pre-collapse pattern: "I should be able to handle this," "resting is wasting time," "my value to others depends on what I produce." These aren't truths. They're the false foundation, and a body kept running on it will keep manufacturing collapse until the belief underneath actually changes.`,
      health: `Burnout signatures are some of the most recognizable in the matrix: adrenal exhaustion (a system that ran on cortisol discovering the cortisol is gone), nervous system dysregulation (chronic hyperactivation finally tipping into collapse), thyroid disruption, and immune suppression. The heart is often the biggest concern here — both literally, from accumulated cardiovascular stress, and in the sense of the heart as the center of your relationship to your own worthiness.`,
      positive: `Sustainable, disciplined output replaces extreme output, and because worth is no longer tied to constant production, the body no longer needs a collapse to earn a rest.`,
      negative: `A belief that worth depends on constant output keeps normalizing the warning signals until the body manufactures the collapse that was the only rest ever going to be permitted.`,
    },

    {
      numbers: [13, 4, 8],
      name: 'The Chronic Resistance',
      category: 'Health & Vitality',
      heading: `What You're Holding On To Is Costing You More Than You Think`,
      why: `You may be paying a real physical and psychological price for resisting a change your life actually requires. The 13-4-8 program describes exactly that cost. The 13 (Transformation/Death) is, here, the change that keeps arriving — the ending presenting itself, the transition being asked for, the release that would free your system from a significant load. The 4 (The Emperor) is the force resisting it: a deep structural conservatism from someone who's organized their sense of safety around keeping existing forms in place, for whom change represents not possibility but the threat of collapse. And the 8 (Strength) is the extraordinary resource you're pouring into that resistance: a genuine, remarkable, almost admirable capacity to hold on, endure, and maintain position under conditions that would've made most people let go long ago. The tragedy is that the same strength that's one of your most real gifts has gotten redirected into keeping something in place that the deeper intelligence of your own life is actively trying to release.`,
      shadow: `This shows up mainly in the body — through a specific mechanism where physical holding mirrors psychological holding. Your musculature under this pattern often runs dense, contracted, and chronically over-recruited to maintain a structural position your tissue isn't designed to hold indefinitely. The chronic illness patterns here tend toward immune dysregulation and inflammation — your body's system for clearing what no longer belongs becoming overactive because your conscious mind keeps reintroducing what the body is trying to release. There's also a pattern of accidents and injuries that line up precisely with the moments a release is most urgently needed and most actively resisted — your body creating, through an external event, the forced rest or forced transition your will keeps refusing.`,
      path: `Try recognizing that what you're holding isn't being held because it's life-sustaining — it's being held because the act of holding has become tangled up with your sense of self. Both the Emperor and Strength, at their best, are energies of genuine authority — but authority turned inward, used to govern your own natural processes of ending and renewal, produces a very specific kind of imprisonment. The first step isn't the grand release. It's honestly naming what, specifically, you're holding — in the body, in the psyche, in your relational or professional structures — and genuinely asking what would actually be lost if you let that holding ease. What the mind refuses to release, the body will keep holding on its behalf, so the release has to start at the level of belief before the tissue can genuinely follow.`,
      health: `This tends to show up in your musculoskeletal system especially — chronic muscle tension, joint inflammation, and connective tissue issues are the primary physical language. Your immune system is almost always involved too, often expressing as autoimmune activity. Digestive disruption, particularly in the large intestine (your organ of release), is common. Your skin, as your body's containment boundary, can express chronic conditions that mirror holding beyond capacity.`,
      positive: `Remarkable endurance gets pointed at releasing what's already run its course, and because the belief underneath finally agrees to let go, the body stops needing to hold it in muscle and joint.`,
      negative: `What the mind refuses to release, the body keeps holding on its behalf — genuine strength redirected into maintaining a position that a deeper intelligence has already tried to end.`,
    },

    // ── 6. PURPOSE & MISSION PROGRAMS ──────────────────────────────────────

    {
      numbers: [1, 10, 19],
      name: 'The Trailblazer',
      category: 'Purpose & Mission',
      heading: `You Were Built to Go First`,
      why: `Your sense of purpose isn't organized around joining an existing current — it's organized around starting one. The 1-10-19 program is the signature of the pioneer. The 1 (The Magician) gives you the pure frequency of origination — the ability to generate from intention, to initiate where there was nothing, to make the first move in a direction that hasn't been validated by precedent or consensus yet. The 10 (The Wheel of Fortune) gives you a deep awareness of cycles — timing isn't incidental to you, it's structural, and you understand the same action taken at different points in a turning cycle produces entirely different results. And the 19 (The Sun) gives you the radiant, authoritative presence that lets people genuinely follow you instead of just watching from a distance. Together, you're genuinely built to move into unmapped territory — not recklessly, but with the specific combination of visionary confidence and cyclical awareness that lets a real first-mover navigate without a map, by reading the terrain.`,
      shadow: `Pioneering can create real isolation when it isn't paired with the equally important work of building relational and structural foundations that let what you create actually sustain itself. Your originating energy is addicted to the moment of beginning — you're most in your element at the table with everything arranged for the start. The ongoing management of what's been created, the patient work of bringing others into full enough understanding to carry the vision forward, the willingness to be publicly wrong and adjust — these are far less interesting to you and frequently get underinvested. Your cyclical awareness, in shadow, can turn into a justification for leaving too early: "the cycle has turned," "the timing has shifted," "this isn't the right moment anymore" — used as an exit from the difficult middle phase of real creation, rather than an honest read of external conditions.`,
      path: `Try developing what might be called legacy consciousness — the awareness that the point of blazing a trail is that others can walk it after you. This takes two capacities that don't come naturally to you: documenting and transmitting (making the implicit map explicit enough that others can navigate it without you present), and enduring the middle — staying committed through the unglamorous consolidation phase, even though part of you would rather be starting something new. Your timing intelligence is the resource — use it not as an exit strategy but as a navigation tool for knowing when to push and when to consolidate. A frequency that keeps broadcasting "beginning" and never "sustaining" is what keeps drawing ventures that never quite compound.`,
      health: `The pioneer program tends to show up in the nervous system, especially in how the sympathetic activation that drives real innovation interacts with your body's need for recovery. Watch for chronic low-grade hyperarousal, difficulty with real rest (your mind keeps generating even when your body is technically still), and immune vulnerability in the post-peak phases of major creative or professional cycles. The heart — both as your physical pump and as the energetic center of your relationship to your own radiance — can be subject to arrhythmia and irregular load under the high-variability demands of a pioneering life.`,
      positive: `You initiate into unmapped territory and stay long enough to document the path, and because the frequency of commitment is real, what you build compounds instead of resetting.`,
      negative: `A frequency permanently tuned to beginning rather than sustaining keeps drawing exits disguised as good timing — the ventures never quite compound because "the timing shifted" is easier to believe than staying.`,
    },

    {
      numbers: [20, 11, 2],
      name: 'The Awakening Teacher',
      category: 'Purpose & Mission',
      heading: `You Teach What You've Actually Lived, Not What You've Memorized`,
      why: `Your genuine contribution to the world can't really be separated from your own particular awakening — you don't teach from a curriculum, you teach from transformation. The 20-11-2 is the program of someone whose knowledge isn't accumulated, it's metabolized. The 20 (Judgement) gives you the frequency of the summons — the moment the old version of yourself stops being adequate, when the call to something fuller arrives and answering it, or not, becomes the defining choice of your life. The 11 (Justice) gives you a precise, uncompromising perceptual intelligence — you see clearly, you can cut through the performed version of a situation to its structural truth, and you can't be fooled by surface presentations because your perception simply doesn't register them. And the 2 (The High Priestess) gives you a receptive, deeply attuned quality — you process reality through an interior knowing that moves faster and lands more accurately than rational analysis can account for. Together, you're genuinely capable of seeing people — their actual state, their actual potential, and the gap between the two — in a way that changes whoever receives that perception.`,
      shadow: `You might carry the specific discomfort of teaching material you haven't fully resolved in yourself yet — knowing a great deal about transformation from a position of incomplete personal transformation. Your Judgement energy creates a very specific pressure: the summons has arrived, the call is clear, and the gap between where you are and where you're called toward is a source of continuous internal friction. That friction can express as a very high standard for others, unconsciously calibrated to the gap in yourself — you may be most impatient with exactly the pattern in your students that you haven't resolved in your own interior yet. Your Justice can turn into a rigidity of moral and psychological standard that makes real compassion hard — the same clear-sightedness that sees the wound in someone else also sees the shadow, and your High Priestess receptivity can pull back from full presence when what you're perceiving gets uncomfortable.`,
      path: `Try teaching from exactly where you actually are — not from where you intend to arrive, not from some fully resolved version of yourself still in process, but from the genuine current state of your own ongoing awakening. That takes real intellectual and personal honesty in the teaching relationship — being able to say "I know this because I've lived it and I'm still living it" instead of "I know this because I've completed it and now I'm passing it to you." Your gift of presence is the foundation — the High Priestess doesn't need all the answers to offer the quality of attention that lets someone else find their own. The impatience you feel toward a student is often just the unresolved gap in yourself reflected back at close range — resolve it there, and the mirror stops needing to show up in front of you.`,
      health: `This tends to involve the nervous system and the perceptual organs — especially the eyes, which in energetic anatomy are the instruments of clear seeing, and which can carry strain and sensitivity in people whose perceptual gifts run at high load. The throat and chest are significant too: the summons asks for voice, and the period before you fully integrate that voice can produce physical symptoms in the territory between the heart, where the knowing lives, and the throat, where it has to exit to become teaching.`,
      positive: `You teach honestly from exactly where you are, and because your own gap has genuinely closed, the students and situations that arrive no longer need to mirror it back at you.`,
      negative: `Impatience with a student's unresolved pattern is the unresolved gap in yourself finding a convenient mirror — the world keeps handing you that exact reflection until you address the original.`,
    },

    {
      numbers: [21, 12, 3],
      name: 'The Artist\'s Sacrifice',
      category: 'Purpose & Mission',
      heading: `Your Work Is Ready Before You're Willing to Admit It`,
      why: `You're unmistakably a creator — for you, making beauty, meaning, form, and aesthetic experience isn't a hobby, it's the actual substance of your contribution to the world — but you may not have fully given yourself permission to live that truth without apology or hedge. The 21-12-3 program carries this specific tension. The 21 (The World) gives you the energy of completion and mastery — you carry the frequency of someone who's genuinely arrived at something, who's integrated enough of the journey to offer something whole. The 12 (The Hanged Man) introduces suspension: waiting, sacrifice, the voluntary or involuntary surrender of one path in service of a deeper one. And the 3 (The Empress) is the creative abundance itself — the irrepressible generative impulse, the sensory richness, the desire to make things that are beautiful and give them away.`,
      shadow: `Your creative life may be perpetually almost fully expressed — always preparing the major work, always feeling like you almost have enough material, always waiting until conditions are right to record it. Your Hanged Man energy can produce a suspension that wears the costume of integrity: "I won't share it until it's ready" — when "ready" doesn't actually describe the work's state, it describes your relationship to the vulnerability of full creative exposure. Your energy of completion is the specific gift being held in reserve here: somewhere beneath the waiting, you know you're capable of real mastery. The gap between that knowledge and your willingness to demonstrate it publicly is where this pattern lives. Your creative abundance can express itself as prolific private production that rarely or never gets released — a whole inner world the outer world hasn't been invited into yet.`,
      path: `Try the single most consequential creative act available to you: releasing the work before it feels ready, because the feeling of readiness you're waiting for doesn't describe the work — it describes a psychological threshold that keeps receding the closer you get to it. The Hanged Man has to come down from the tree eventually. Not because the suspension wasn't valuable — the private development before real mastery is real and necessary — but because the point of that development was always the offering. Start with the smallest possible public release: one piece, one showing, one share. A creative life kept perpetually private broadcasts "not yet" outward as its steady signal, and the audience, recognition, and momentum you're waiting for are simply matching the exact signal you've been sending.`,
      health: `Blocked creative flow tends to concentrate in the sacral center — the lower abdomen and reproductive system, which in energetic anatomy govern creative and generative impulse. Watch for irregular cycles (in every sense), digestive sensitivity, and lower abdominal tension during periods of maximum creative suppression. Your hands — the instruments of making — can develop chronic tension, repetitive strain, and sensitivity that expresses the frustrated desire to create something that hasn't yet found its release.`,
      positive: `The work gets released before it feels ready, and because "finished enough to share" is the frequency actually being broadcast, the audience and momentum you were waiting for start arriving in kind.`,
      negative: `A creative life kept perpetually private broadcasts "not yet" as its steady signal, and the audience and recognition that never quite arrive are only matching the exact frequency being sent outward.`,
    },

  ]; // end programs


  // ── Public API ─────────────────────────────────────────────────────────────

  /**
   * find(a, b, c) — returns the program matching all three numbers
   * in any order, or undefined if none exists.
   */
  function find(a, b, c) {
    const query = [a, b, c];
    return programs.find(p =>
      query.every(n => p.numbers.includes(n)) &&
      p.numbers.every(n => query.includes(n))
    );
  }

  /** findByCategory(cat) — returns all programs in a category. */
  function findByCategory(cat) {
    return programs.filter(p => p.category === cat);
  }

  /** all() — returns the full array (read-only copy). */
  function all() { return programs.slice(); }

  return { find, findByCategory, all };

})();
