'use strict';

/**
 * Destiny Matrix — Talent Star Line Content
 * ──────────────────────────────────────────
 * Archetype-level readings, keyed by the 5-bucket `iconType` string
 * computed in js/matrix-engine.js (LEADER_ACTION, INTUITION_WISDOM,
 * CREATIVITY_ART, TEACHER_FREEDOM, TRANSFORMATION_POWER).
 *
 * One entry per bucket — not per-arcana — since the Talent Star Line
 * is presented through the archetype abstraction, not the raw number.
 *
 * API:
 *   DTalentContent.get(iconType) → { heading, why, shadow, path } or null
 */

window.DTalentContent = (function () {

  const archetypes = {

    LEADER_ACTION: {
      title: 'You Move Before Anyone Else Is Ready To',
      mastery: `There is something you do that looks like courage to everyone else but feels, to you, like the only bearable option. When a room hesitates, you move. Hand you a half-formed plan and a circle of uncertain faces, and you'll be the one who steps across the threshold first — not because you're fearless, but because waiting sits in your body worse than acting ever has. People feel this in you almost immediately. They fall in behind your momentum without being asked, because something in the way you carry a decision tells them it's already happening. You are the starter, the closer, the steady hands a stalled moment has been waiting for. Here, your drive and your discernment work together instead of one racing ahead of the other: you still move first, but there's a half-second pause before the push, just long enough to ask whether this moment actually wants your speed or your stillness. People feel the difference immediately, even if they couldn't name it, and projects you lead actually finish, because you're no longer abandoning the unglamorous middle for the next exciting start.`,
      shadow: `The trouble begins when you push where you should have paused. You can mistake speed for progress, and control for leadership, driving a plan forward long after the moment that needed it has quietly closed behind you. When that happens, you burn through people faster than you realize — not because you meant to, but because your pace left no room for anyone to catch their breath. Imposing your pace on people who never agreed to it, and refusing to slow down even when the room is visibly asking you to, is what actually blocks this talent. If people have been quietly dropping off, agreeing with you less than they used to, that isn't bad luck, it's an echo coming back to you. Underneath the compulsion to keep moving, there is often a younger you who learned that hesitating meant being overlooked or left behind — a child for whom constant motion became the only way to feel safe or seen. That child wasn't wrong to learn it. It worked. It kept you visible.`,
      invitation: `Ask yourself when the last time was that you let a moment pass without acting on it, and what the stillness tried to tell you. Ask a second question before you move — not just "can I push this forward," but "should I, right now, like this." Your drive is real and it is rare; most people freeze where you act. Notice that you're allowed to pause without disappearing — the mastery isn't slowing down for its own sake, it's choosing your moments as carefully as you already execute them, so people stop bracing against you and start moving with you.`,
    },

    INTUITION_WISDOM: {
      title: 'You Know Before You Can Explain How',
      mastery: `You sense what's true before anyone hands you the proof. A room shifts and you feel it in your body before a word is spoken. A pattern repeats and you've clocked it three instances before anyone else notices there is one. This isn't guessing, and it isn't luck — it's a genuine gift for depth: for research, for reading people, for holding a complicated situation open without needing to resolve it just to feel comfortable. Most people can't tolerate that depth. You live in it. The knowing is exactly as sharp as it's always been, and once it stops dying in the privacy of your own mind, and you say the thing before you can fully justify it, people stop experiencing you as unreadable and start experiencing you as someone whose read they can trust, because you've actually offered it enough times for them to test it against reality.`,
      shadow: `The catch is what you do with what you know. It's easy to let your perception become a private world instead of something you share — to stay quiet when speaking up could genuinely help, because turning a felt sense into plain words feels like it will lose something in translation. Keeping your perception entirely private, and treating the mess of saying it out loud as a reason not to try, is what actually blocks this talent. You may prefer the certainty of working things out alone over the mess of working them out with people. And if it ever feels like nobody's really listening to you, it's worth asking gently whether you've actually said the thing out loud yet. Somewhere behind that silence there is often a child who spoke what they sensed and wasn't believed — who learned that voicing the invisible wasn't welcome, and so made quiet into a fortress long before it became a spiritual style. That fortress protected you once. It's allowed to have been necessary.`,
      invitation: `Ask yourself what is one thing you've known for a long time that you have never once said out loud. Your work now is translation: finding the words, the timing, the moment that lets what you already sense reach the people who need it. The more you say the true thing out loud, in real time, the more the world finally has something of yours to answer. Notice that you're allowed to be heard — not just to know, but to be known for what you know.`,
    },

    CREATIVITY_ART: {
      title: 'You Make Things That Are Meant to Be Seen',
      mastery: `You have a gift for taking what's happening inside you and giving it a form other people can feel. Aesthetics, performance, public creative work — wherever this lands on your Talent Star Line, it marks a real talent for making things that move people, and for standing visible while you do it. This isn't vanity, whatever you may have been told. It's closer to translation: a private feeling finding its outer body, a thread pulled from somewhere wordless and woven into something someone else can hold. The work still comes from that same private, wordless place, and once you stop editing it down before it's fully arrived, making the true thing first and letting it be seen second, people can feel the difference instantly, even if they can't say why one piece moves them and another merely impresses them. An audience built on genuine expression doesn't just admire the work, it recognizes something in itself through it.`,
      shadow: `Where this gets complicated is when you start needing the reaction more than you trust the work. You might notice yourself quietly shrinking a piece — making it safer, more predictable, more likely to be liked — trading its truth for its reception. Softening the work to make it more likeable, and needing the reaction more than you trust what you actually made, is what actually blocks this talent. Visibility starts to feel like the point instead of the natural echo of expressing something real. If audiences keep feeling lukewarm, it's worth asking whether the work got softened somewhere on its way out of you. And beneath that softening there is often a child whose creativity was only truly welcomed when it pleased — who learned early that being seen depended on being palatable first. That child made a reasonable bargain with the world it was given. You're allowed to grieve that it was ever the price.`,
      invitation: `Ask yourself, if no one ever reacted to your work again, what you would make next, and for whom. Let being seen become a consequence of expression rather than its goal. Your talent is real, and it deserves an audience, but it doesn't need one to already be valid while you're making it. Notice that you're allowed to make something true before you make it likeable.`,
    },

    TEACHER_FREEDOM: {
      title: 'You Teach Best When You Let People Outgrow You',
      mastery: `You have a real talent for passing on what you know while leaving room for the other person to eventually go further than you did. It shows up as an aptitude for teaching, for building systems other people can actually use, for walking unconventional paths that others can later walk without you beside them. The best version of this gift was never about being needed. It's about building a container strong enough to hold people while they grow, and open enough that they can leave it when they're ready. What's real is that you can also, deliberately, build the exit — teaching the thing and then stepping back far enough to let someone actually use it without you, resisting the old pull to stay just slightly indispensable. Students launch. Teams run without your constant presence. Whatever you built keeps compounding on its own momentum, which is the only kind of legacy that was ever actually durable.`,
      shadow: `The risk here is subtle: a quiet need to stay necessary. You might catch yourself keeping a student, a team, or a system just slightly dependent on you continuing to show up — even while telling yourself, and them, that you're giving them freedom. Keeping people quietly dependent on you, or rejecting structure so completely that nothing durable ever gets passed on, is what actually blocks this talent. The opposite trap exists too: rejecting structure so completely that nothing durable ever gets built or passed on. If the people you teach never quite launch on their own, it's worth asking gently whether the freedom you're offering is real or just the word you use for it. Underneath, there is often a child whose place in the family depended on being needed — for whom being indispensable became identity long before it became a teaching style. That child found belonging the only way that was offered. It made sense then.`,
      invitation: `Ask yourself, if everyone you've ever taught outgrew you tomorrow, what would be left that's just yours. Teach yourself out of a job, building something, or someone, fully capable of standing without you. Once the freedom you offer is genuine rather than managed, the people you teach actually take it and run. Notice that you're allowed to matter without being needed.`,
    },

    TRANSFORMATION_POWER: {
      title: 'You Find Clarity Right Where Everyone Else Loses It',
      mastery: `You have a talent that only reveals itself when things fall apart. You step into collapse, crisis, real upheaval — and where other people freeze or scatter, something in you steadies. You can see what the breakdown is actually clearing space for while everyone around you is still grieving the rubble. This is a genuine capacity to turn a mess into a foundation, not just survive it. In the storm, you are the still point, and people sense it, moving toward you when everything else is moving away. When you've learned to tell the difference between change that's genuinely needed and change that's just familiar, you no longer have to manufacture upheaval just to feel like yourself — the quiet stretches between real crises get to stay quiet too, instead of being sacrificed to a restlessness that used to read as instinct.`,
      shadow: `The risk is that crisis becomes your only comfortable terrain. Without quite meaning to, you can find yourself drawn toward drama or upheaval because stillness feels unfamiliar by comparison — even tearing down things that still had value, simply because tearing down is the move your hands know best. Seeking out upheaval because stillness feels untrustworthy, and tearing down things that still had real value out of habit, is what actually blocks this talent. If upheaval keeps arriving in your life more often than seems reasonable, it's worth asking whether some part of you still doesn't trust the quiet. Often there's a child underneath this — one raised where only crisis reliably got attention, where calm was just the held breath before something broke. For that child, chaos was legible and peace was suspicious. Learning to read the storm was how you survived it. Of course calm still feels like a stranger.`,
      invitation: `Ask yourself, when your life is finally calm, what you notice yourself waiting for. Learn to tell the difference between change that's genuinely needed and change that's merely familiar. Your capacity for transformation is real — the mastery is saving it for the moments that actually call for it, and letting the quiet stretches be quiet. Notice that you're allowed to rest inside a life that isn't on fire.`,
    },

  };

  /**
   * PER-POSITION, PER-ARCANA TIER (added 2026-07-28)
   * ─────────────────────────────────────────────────
   * The archetype tier above has only 5 entries, shared across 3-5 arcana
   * each — the last remaining spot in the app where genuinely different
   * readers could see identical copy. Two star positions actually render
   * this content: `pastLife` (P, "Hidden Past-Life Talent") and `personal`
   * (K, "Self-Expression & Social Interaction") — see js/matrix-engine.js's
   * TALENT STAR LINE comment for the naming correction this followed. Crown
   * (B) is not included here: it's already rendered as the Sky Line arcana
   * star with its own full micro-content.js position-specific reading.
   *
   * P and K happen to be the same raw values used as Ajna's and Vishuddha's
   * Physical/Energy inputs in js/chakra-content.js, but per NON_NEGOTIABLE_
   * RULES' Absolute System Isolation, this is written as its own distinct
   * content — a shared numeric source doesn't mean shared language. The
   * Talent Star Line asks a different question of the same number: not "how
   * does this chakra feel" but "what is this talent, and what blocks it."
   *
   * Field shape matches the archetype tier: heading / why / shadow / blocks
   * / path (written, not rendered — same decision as everywhere else) /
   * positive / negative.
   *
   * API: DTalentContent.getForPosition(key, arcanaNum) → entry or null
   */
  const positions = {

    pastLife: {
      1: {
        title: `A Skill You Already Have, From Before You Learned It Here`,
        mastery: `Something in you can already initiate — decisively, without the usual runway most people need to work up to starting. It doesn't feel learned because it wasn't, not fully, not this time. You watch other people build up courage to begin something and feel a faint impatience, as though you're waiting for them to catch up to a starting line you were already standing past. You're capable of pairing that instinct with real preparation, at least once, in a genuinely new arena. The head start compounds once it's paired with the homework, instead of occasionally running out from under you.`,
        shadow: `The risk is treating an inherited fluency as proof you should never need to prepare, so you skip the groundwork a genuinely new situation actually requires, trusting old instinct to carry you through unfamiliar terrain it was never built for. Assuming the old fluency transfers automatically to situations it was never actually tested against is what actually blocks this talent. You've stumbled somewhere unfamiliar precisely because starting has always come so easily that preparing never occurred to you. The inherited ease with initiating is genuine, and it's being trusted past where it was actually tested.`,
        invitation: `Ask yourself where you've skipped preparing because starting has always come easily. Pair the instinct with real preparation, at least once, in a genuinely new arena. Do the homework this time, not just the leap. Notice that you're allowed to have a head start and still do the homework.`,
      },
      2: {
        title: `A Perceptiveness You Brought With You, Already Trained`,
        mastery: `You read situations with an accuracy that outpaces your actual experience of them, as though some prior fluency in reading people and rooms simply carried over. It rarely feels like learning; it feels more like remembering something you already knew how to do. You're capable of verifying one inherited read against the actual present facts before acting on it. Your accuracy is even higher once it's being tested, not just trusted automatically.`,
        shadow: `The risk is trusting this inherited perceptiveness so completely that you stop checking it against present reality, treating an old, well-worn read as sufficient for a genuinely new situation it wasn't actually calibrated for. Applying an old pattern-read to a new situation without checking whether it actually still fits is what actually blocks this talent. You've misjudged something specifically because the old pattern felt too familiar to question. The inherited perceptiveness is genuine, and it's being trusted without verification.`,
        invitation: `Ask yourself where you've trusted an old pattern that might not fit this particular situation. Verify one inherited read against the actual present facts before acting on it. Check it against reality this time, not just instinct. Notice that you're allowed to have deep perceptiveness and still fact-check it sometimes.`,
      },
      3: {
        title: `A Capacity to Nurture That Arrived Already Fluent`,
        mastery: `You know how to tend, grow, and provide for people with a fluency that feels inherited rather than built — as though some prior lifetime of caretaking simply carried its skill forward into this one, already practiced. It rarely feels like learning; it feels more like something you already knew how to do. You're capable of entering one new situation without automatically becoming its caretaker. Your care lands more precisely once the role is chosen rather than defaulted into.`,
        shadow: `The risk is that this inherited fluency makes you the automatic caretaker in any new situation, regardless of whether that role actually fits or whether anyone's asked for it, because providing is simply what the old skill knows how to do. Stepping into the caretaker role automatically, whether or not it's actually needed or wanted, is what actually blocks this talent. You've taken on care nobody requested, simply because providing is what the old skill knows how to do. The inherited nurturing fluency is genuine, and it's deploying automatically in situations that never actually asked for it.`,
        invitation: `Ask yourself where you've taken on care nobody actually asked you for. Enter one new situation without automatically becoming its caretaker. Let the role stay unfilled unless it's genuinely asked for. Notice that you're allowed to have deep nurturing fluency and not deploy it by default.`,
      },
      4: {
        title: `A Command Over Structure That Feels Older Than Your Actual Practice`,
        mastery: `You can organize, direct, and hold authority with a steadiness that outpaces how much practice you've actually had at it in this life — as though some prior fluency in structure and command carried forward, already seasoned. It rarely feels like learning; it feels more like remembering a role you've already held. You're capable of stepping back from one situation your inherited command reflex wants to direct, and checking whether it's actually yours. Your authority lands better once it's invited more often than assumed.`,
        shadow: `The danger is that this inherited authority applies itself to situations that were never actually yours to direct, an old command reflex reaching for control in territory that belongs to someone else. Directing situations reflexively, out of old habit, that were never actually yours to control, is what actually blocks this talent. You've taken charge somewhere out of old habit, only to find the control wasn't wanted or needed there. The inherited authority is genuine, and it's reaching reflexively into situations that were never actually yours to direct.`,
        invitation: `Ask yourself where you've taken charge out of old habit rather than actual invitation. Step back from one situation your inherited command reflex wants to direct, and check whether it's actually yours. Let someone else's turn actually be theirs. Notice that you're allowed to hold deep authority and still ask whose turn it is.`,
      },
      5: {
        title: `A Body of Knowledge That Feels Already Studied`,
        mastery: `You grasp frameworks, traditions, and teachings with a speed that suggests you've studied this before — some prior fluency in transmitted wisdom carrying forward, ready to be picked back up rather than learned from nothing. It rarely feels like learning; it feels more like resuming a study you'd already begun. You're capable of testing one piece of your inherited certainty against something you're currently learning fresh. Your knowledge is more alive once it's still being updated, not just inherited.`,
        shadow: `The risk is treating inherited certainty as settled fact rather than as a starting hypothesis, defending an old framework more fiercely than the actual evidence in front of you currently warrants. Defending an inherited framework out of old certainty, rather than testing it against present evidence, is what actually blocks this talent. You've resisted updating something simply because it arrived already feeling certain. The inherited body of knowledge is genuine, and it's being defended as settled fact rather than tested as a starting point.`,
        invitation: `Ask yourself what old certainty of yours might need a second look. Test one piece of your inherited certainty against something you're currently learning fresh. Let the fresh evidence actually count. Notice that you're allowed to hold deep prior knowledge and still update it.`,
      },
      6: {
        title: `A Way of Choosing That Feels Already Practiced`,
        mastery: `You choose people and paths with a discernment that feels inherited — as though some prior lifetime of relational decision-making carried its skill forward, already fluent at knowing what genuinely fits. It rarely feels like learning; it feels more like recognizing a fit you already knew how to spot. You're capable of meeting one person without the inherited template, actually seeing them as new rather than as a variation on someone before. Your choices land better once they're based on who's actually there.`,
        shadow: `This inherited discernment applies an old template to new people, reading someone through the shape of a prior choice rather than actually seeing who's in front of you now. Reading a new person through an old relational template instead of actually seeing them fresh is what actually blocks this talent. You've misjudged someone specifically because they resembled a prior pattern that didn't actually apply. The inherited relational discernment is genuine, and it's reading new people through an old template rather than actually seeing them.`,
        invitation: `Ask yourself who you've been reading through an old pattern instead of actually seeing. Meet one person without the inherited template, actually seeing them as new. Look freshly, without the prior shape overlaid. Notice that you're allowed to have deep relational instinct and still look freshly.`,
      },
      7: {
        title: `A Drive That Already Knows How to Move`,
        mastery: `You move toward goals with a momentum that feels seasoned rather than newly built — some prior fluency in directed pursuit carrying forward, already knowing how to steer toward something. It rarely feels like learning; it feels more like resuming a pursuit you already knew how to run. You're capable of pausing the momentum once to check whether the current direction is actually yours, not just familiar. Your drive is more precisely aimed once it's been recalibrated rather than assumed.`,
        shadow: `What can go wrong is that this inherited momentum keeps moving toward goals that mattered in some other context, without checking whether the current direction is actually the one that matters now. Pursuing an old, inherited direction without checking whether it's actually where you want to go now is what actually blocks this talent. Real energy is being spent on a goal that no longer fits, simply because the drive toward it feels so familiar. The inherited momentum is genuine, and it keeps moving toward a direction that may have mattered in some other context.`,
        invitation: `Ask yourself where your momentum might be pointed at an old goal rather than a current one. Pause the momentum once to check whether the current direction is actually yours, not just familiar. Redirect it if it's not. Notice that you're allowed to have deep drive and still redirect it.`,
      },
      8: {
        title: `A Sense of Fairness That Arrived Already Calibrated`,
        mastery: `You read what's fair and what isn't with a precision that feels inherited — some prior fluency with justice and balance carrying forward, already trained rather than newly developed. It rarely feels like learning; it feels more like applying a calibration you already carried. You're capable of checking one inherited fairness judgment against the actual specifics of your current situation. Your fairness lands more accurately once it's calibrated to what's actually in front of you.`,
        shadow: `The risk is applying an old standard of fairness to a present situation that actually calls for a different calibration, holding everyone to a bar set somewhere else, in some other context. Applying an inherited fairness standard rigidly, without checking whether it actually fits the present situation, is what actually blocks this talent. A judgment that felt certain turned out to be measuring the wrong thing for this particular situation. The inherited fairness calibration is genuine, and it's being applied rigidly to situations that actually call for different terms.`,
        invitation: `Ask yourself where your sense of what's fair might be set by an old standard rather than this particular case. Check one inherited fairness judgment against the actual specifics of your current situation. Recalibrate it if it doesn't fit. Notice that you're allowed to have deep moral instinct and still recalibrate it.`,
      },
      9: {
        title: `A Depth You Already Know How to Reach`,
        mastery: `You can go inward and find real understanding with a fluency that feels practiced rather than newly discovered — some prior lifetime of solitary depth-work carrying forward, already knowing the way down. It rarely feels like learning; it feels more like returning to a depth you already knew how to reach. You're capable of meeting one difficulty without your automatic retreat into solitude, at least at first. Your solitude is more chosen once it's not just the old default.`,
        shadow: `Left unexamined, this inherited fluency for solitude makes withdrawal your automatic answer to anything difficult, reaching for the old, familiar depth instead of trying a genuinely new approach a current situation might actually need. Retreating into old, familiar solitude by default, instead of trying an approach the current situation actually needs, is what actually blocks this talent. You've retreated somewhere that could have used a different, less practiced response. The inherited capacity for solitary depth is genuine, and it's become the automatic answer to anything difficult.`,
        invitation: `Ask yourself where you've withdrawn out of old habit rather than genuine current need. Meet one difficulty without your automatic retreat into solitude, at least at first. Try something else before reaching for the old depth. Notice that you're allowed to have deep inner resources and still try something else first.`,
      },
      10: {
        title: `An Adaptability That Already Knows the Turning`,
        mastery: `You move with change more fluently than your actual experience would predict, as though some prior lifetime of navigating cycles and reversals carried its skill forward, already knowing how circumstances turn. It rarely feels like learning; it feels more like remembering how circumstances tend to turn. You're capable of treating one current change as genuinely new, rather than assuming it follows the old, familiar turning. Your adaptability is sharper once it's checking rather than just assuming.`,
        shadow: `The trouble is that this same inherited fluency with change makes you expect every situation to turn the way old ones did, missing that a genuinely new circumstance might follow a different pattern entirely. Expecting a present situation to follow an old cyclical pattern that may not actually apply here is what actually blocks this talent. You braced for a turning that never came, because a new circumstance simply didn't follow the old shape. The inherited adaptability is genuine, and it's assuming present situations follow old cyclical patterns that may not actually apply here.`,
        invitation: `Ask yourself where you might be expecting an old cycle that this situation isn't actually following. Treat one current change as genuinely new, rather than assuming it follows the old, familiar turning. Check the pattern before trusting it. Notice that you're allowed to have deep adaptive instinct and still check the pattern.`,
      },
      11: {
        title: `A Steadiness That Arrived Already Tested`,
        mastery: `You hold up under pressure with a calm that feels inherited rather than newly built — some prior lifetime of enduring real strain carrying its steadiness forward, already proven rather than freshly discovered. It rarely feels like learning; it feels more like a steadiness that was already proven somewhere else. You're capable of checking your actual current capacity before absorbing one more thing, rather than trusting the old steadiness automatically. Your endurance is more sustainable once it's being measured, not just assumed.`,
        shadow: `The risk is that this inherited steadiness gets assumed to be limitless, so you keep absorbing new strain on old confidence without checking whether this particular load is actually within current capacity. Assuming an inherited steadiness is limitless, absorbing new strain without checking your actual current capacity, is what actually blocks this talent. You're carrying more than you can currently sustain, simply because the steadiness has always held before. The inherited steadiness is genuine, and it's being assumed limitless.`,
        invitation: `Ask yourself what load you're carrying on old confidence rather than current capacity. Check your actual current capacity before absorbing one more thing, rather than trusting the old steadiness automatically. Name your actual limit today. Notice that you're allowed to have deep endurance and still have a limit today.`,
      },
      12: {
        title: `A Capacity for Stillness That Already Knows How to Wait`,
        mastery: `You can hold suspension and uncertainty with a patience that feels practiced rather than newly learned — some prior lifetime of waiting and reflecting carrying its skill forward, already fluent at not-yet. It rarely feels like learning; it feels more like a patience you'd already practiced. You're capable of acting on one thing you'd normally let sit in inherited patience, checking whether waiting is actually still called for. Your patience is more discerning once it's not just a comfortable default.`,
        shadow: `The danger is that this inherited patience becomes an automatic response even to situations that actually need action now, mistaking old, comfortable waiting for the wisdom of the pause. Waiting reflexively, out of old comfort with suspension, even when a situation actually calls for action, is what actually blocks this talent. Something has sat too long in stillness that actually needed you to move. The inherited patience is genuine, and it's becoming an automatic response even where action is actually needed.`,
        invitation: `Ask yourself where your patience has become avoidance rather than genuine waiting. Act on one thing you'd normally let sit in inherited patience, checking whether waiting is actually still called for. Move on it if the waiting has run its course. Notice that you're allowed to have deep capacity for stillness and still move when it's time.`,
      },
      13: {
        title: `A Fluency With Ending and Rebuilding That Feels Already Practiced`,
        mastery: `You move through endings and reconstructions with a fluency that outpaces your actual experience — some prior lifetime of transformation carrying its skill forward, already knowing how to let something die and build again. It rarely feels like learning; it feels more like a fluency with loss you already carried in. You're capable of checking one thing your ending-instinct wants to close, to see whether it's actually finished. Your endings land more accurately once they're timed to what's actually finished.`,
        shadow: `This inherited fluency with ending makes you end things prematurely, applying old transformation instinct to situations that might actually have more life left in them than the reflex assumes. Ending things prematurely out of old reflex, before checking whether they actually still have life in them, is what actually blocks this talent. You've ended something that, checked more carefully, wasn't actually done. The inherited fluency with ending is genuine, and it's closing things prematurely.`,
        invitation: `Ask yourself what you've been ready to end that might not actually be done. Check one thing your ending-instinct wants to close, to see whether it's actually finished. Look closely before you close it. Notice that you're allowed to have deep transformative fluency and still ask if it's really over.`,
      },
      14: {
        title: `A Balance That Arrived Already Calibrated`,
        mastery: `You find equilibrium between competing demands with a fluency that feels inherited — some prior lifetime of blending and moderating carrying its skill forward, already practiced at finding the workable mix. It rarely feels like learning; it feels more like a mix you already knew how to strike. You're capable of letting one situation find its own proportion, rather than defaulting to the old inherited blend. Your calibration is more precise once it's fitted to what's actually in front of you.`,
        shadow: `What can go wrong is that this inherited calibration applies an old blend to a new situation that might actually need a different, less familiar proportion entirely. Applying an old, familiar balance to a situation that might actually need a different proportion is what actually blocks this talent. A balance that's always worked before isn't quite fitting this particular case. The inherited calibration is genuine, and it's applying an old, familiar blend to situations that might need a different proportion entirely.`,
        invitation: `Ask yourself where your usual balance might not actually fit this particular situation. Let one situation find its own proportion, rather than defaulting to the old inherited blend. Recheck the mix instead of assuming it. Notice that you're allowed to have deep calibration instinct and still recheck the mix.`,
      },
      15: {
        title: `An Intensity You Already Know How to Hold`,
        mastery: `You carry strong appetite and desire with a fluency that feels inherited — some prior lifetime of wanting deeply carrying its intensity forward, already practiced at holding what most people find overwhelming. It rarely feels like learning; it feels more like an intensity you already knew how to hold. You're capable of examining one piece of inherited intensity honestly, checking what it's actually serving. Your capacity for wanting is more consciously held once it's not just running on old, unexamined pattern.`,
        shadow: `Left unexamined, this inherited intensity gets treated as simply how you are, rather than examined for whether it's actually serving you now, letting an old pattern of wanting run unexamined. Treating inherited intensity as simply fixed, rather than examining whether it's actually serving you now, is what actually blocks this talent. A pattern of wanting has never been questioned, simply because it arrived already this strong. The inherited intensity is genuine, and it's running unexamined.`,
        invitation: `Ask yourself what intense pattern you've never questioned because it's simply always been there. Examine one piece of inherited intensity honestly, checking what it's actually serving. Look at it directly, without assuming it's fixed. Notice that you're allowed to have deep capacity for wanting and still examine it.`,
      },
      16: {
        title: `A Resilience That Was Already Proven Before This Life`,
        mastery: `You come back from collapse with a speed that feels inherited — some prior lifetime of surviving sudden rupture carrying its resilience forward, already tested rather than newly discovered. It rarely feels like learning; it feels more like a resilience that was already proven before this. You're capable of applying some of your rebuilding capacity toward prevention, for once, instead of only trusting recovery. You're building safeguards once some of that capacity goes toward prevention, not just trusting the old rebuilding skill to handle everything after the fact.`,
        shadow: `The trouble is that this same inherited resilience gets relied on so completely that you stop taking precautions against collapse, trusting the old recovery skill to handle whatever comes rather than working to prevent it. Relying on inherited resilience instead of taking reasonable precautions against a collapse actually being preventable is what actually blocks this talent. Something fell that reasonable safeguards could have caught, because the recovery skill felt sufficient on its own. The inherited resilience is genuine, and it's being relied on so completely that precautions against collapse go unconsidered.`,
        invitation: `Ask yourself what you could protect now, rather than trusting you'll rebuild it later. Apply some of your rebuilding capacity toward prevention, for once, instead of only trusting recovery. Build the safeguard before the collapse, not after. Notice that you're allowed to have deep resilience and still build safeguards.`,
      },
      17: {
        title: `A Hope That Arrived Already Trusting`,
        mastery: `You carry an undertone of trust that things turn out well, a fluency that feels inherited — some prior lifetime of hoping through difficulty carrying its quiet trust forward, already practiced. It rarely feels like learning; it feels more like a trust you already carried in. You're capable of letting the inherited hope be fully sized once, checking whether your current circumstances actually warrant the old caution. Your hope carries more weight once it's matched to what's actually possible.`,
        shadow: `The risk is that this inherited hope stays deliberately modest, protecting itself from disappointment the way it may have needed to before, even when your current circumstances could actually support wanting more. Keeping inherited hope modest out of old protective habit, even when current circumstances could support more, is what actually blocks this talent. You underclaim a hope that your actual situation would justify at full size. The inherited hope is genuine, and it's staying deliberately modest out of old protective habit.`,
        invitation: `Ask yourself what hope you've been keeping small out of an old habit that might not fit anymore. Let the inherited hope be fully sized once, checking whether your current circumstances actually warrant the old caution. Say the full-sized version, not the guarded one. Notice that you're allowed to hope at full size now.`,
      },
      18: {
        title: `A Sensitivity That Arrived Already Attuned, Even If Foggy`,
        mastery: `You sense undercurrents and hidden material with a fluency that feels inherited — some prior lifetime of perceiving below the surface carrying its attunement forward, real even when it's hard to fully articulate. It rarely feels like learning; it feels more like an attunement you already carried in, even half-formed. You're capable of sorting one piece of foggy perception, asking whether it's genuinely current or something older you're still carrying. Your perception is clearer once some of it has been sorted.`,
        shadow: `The danger is that this inherited sensitivity stays entirely unsorted, so old, absorbed material and genuinely current perception blur together, making it hard to tell which fog belongs to now. Leaving inherited and current sensitivity unsorted, so old absorbed material gets mistaken for present signal, is what actually blocks this talent. An unease you can't quite place may belong to something older than your present circumstances. The inherited sensitivity is genuine, and it's staying entirely unsorted.`,
        invitation: `Ask yourself what unease you've been carrying that might actually belong to somewhere else. Sort one piece of foggy perception, asking whether it's genuinely current or something older you're still carrying. Trace it to its actual source. Notice that you're allowed to have deep sensitivity and still do the sorting work.`,
      },
      19: {
        title: `A Warmth That Arrived Already Open`,
        mastery: `You carry vitality and open-heartedness with a fluency that feels inherited — some prior lifetime of resilient warmth carrying itself forward, already practiced at staying bright. It rarely feels like learning; it feels more like a brightness that was already yours. You're capable of letting one real difficulty be named plainly, before the inherited warmth automatically smooths it over. Your brightness includes honesty once it's not just performance.`,
        shadow: `This inherited warmth becomes a requirement rather than a genuine expression, staying visibly bright even in moments that would reasonably call for acknowledging real difficulty. Performing inherited warmth even in moments that actually call for acknowledging real difficulty first is what actually blocks this talent. A hard thing got smoothed over by old, automatic brightness before it was actually addressed. The inherited warmth is genuine, and it's performing even in moments that actually call for acknowledging real difficulty first.`,
        invitation: `Ask yourself what difficulty your warmth has been quietly covering. Let one real difficulty be named plainly, before the inherited warmth automatically smooths it over. Say it directly, without the brightness attached. Notice that you're allowed to have deep vitality and still sit with something hard.`,
      },
      20: {
        title: `A Readiness to Answer a Call That Was Already Familiar`,
        mastery: `You sense a summons — a bigger purpose, a reckoning — with a fluency that feels inherited, some prior lifetime of answering a call carrying its readiness forward, already primed for this. It rarely feels like learning; it feels more like recognizing a call you'd already heard once. You're capable of converting the inherited readiness into one actual step, rather than letting the primed feeling stand in for the answer. The summons is being answered once you've converted readiness into action, not just sensed.`,
        shadow: `What can go wrong is that this inherited readiness stays permanently primed without ever actually answering, since the sense of being called can feel complete on its own, without the corresponding action. Staying inherited-ready to answer a call indefinitely, without the readiness ever converting into actual response, is what actually blocks this talent. You've felt ready for something important for a long time without ever actually responding to it. The inherited readiness is genuine, and it's staying permanently primed without converting into actual action.`,
        invitation: `Ask yourself what call you've felt ready for, for a long time, without actually answering it. Convert the inherited readiness into one actual step, rather than letting the primed feeling stand in for the answer. Take the step now, imperfectly. Notice that you're allowed to act on the summons now, imperfectly.`,
      },
      21: {
        title: `A Sense of the Whole That Arrived Already Integrated`,
        mastery: `You see how pieces connect into a larger picture with a fluency that feels inherited — some prior lifetime of synthesizing and integrating carrying its wholeness forward, already practiced at seeing the whole system. It rarely feels like learning; it feels more like a wholeness you already knew how to see. You're capable of acting on one isolated thing you're ready for, without waiting for the inherited need for the whole picture first. Your capability is more available once it's not gated behind needing to see everything at once.`,
        shadow: `Left unexamined, this inherited need for wholeness delays action on things you're actually ready to do, waiting for a comprehensive picture that isn't always necessary before moving. Waiting for the inherited whole-picture view before acting on something you're actually already ready for is what actually blocks this talent. Something you were ready to do got delayed simply because the full picture wasn't yet visible. The inherited need for wholeness is genuine, and it's delaying action on things you're actually ready for.`,
        invitation: `Ask yourself what you've delayed because you were waiting to see how it all connects. Act on one isolated thing you're ready for, without waiting for the inherited need for the whole picture first. Take the fragment as enough. Notice that you're allowed to have deep integrative capacity and still act on a fragment.`,
      },
      22: {
        title: `A Trust in the Leap That Was Already Practiced`,
        mastery: `You move toward the unknown with a fluency that feels inherited — some prior lifetime of trusting uncertain leaps carrying its openness forward, already practiced at not needing the guarantee first. It rarely feels like learning; it feels more like a trust you'd already practiced somewhere else. You're capable of pairing one leap with real preparation, rather than trusting the inherited openness alone. Your capacity for the unknown is more grounded once it's paired with preparation, not just braver.`,
        shadow: `The trouble is that this same inherited trust in leaping gets used to skip preparation that a genuinely new situation would actually benefit from, relying on old courage rather than building anything new to stand on. Leaping on inherited courage alone, skipping preparation a genuinely new situation would actually benefit from, is what actually blocks this talent. A leap could have used more groundwork than the old courage provided. The inherited trust in leaping is genuine, and it's being used to skip preparation a genuinely new situation would actually benefit from.`,
        invitation: `Ask yourself what leap could use a little more groundwork than your old courage usually bothers with. Pair one leap with real preparation, rather than trusting the inherited openness alone. Add the groundwork this time. Notice that you're allowed to have deep trust in uncertainty and still prepare.`,
      },
    },

    personal: {
      1: {
        title: `You Present Yourself by Simply Starting`,
        mastery: `Your self-expression in this lifetime is decisive and immediate — you're known by what you initiate, not by what you deliberate about. People read your identity through your actions the moment you take them, often before you've said anything about your intentions at all. You're capable of narrating the why behind one action, out loud, before or after you take it. Your social presence can have depth now, not just visible capability, once people know the mover and the motive.`,
        shadow: `The risk is that people only get to know the mover, never the reasoning behind the moves, so your social presence reads as capable but somewhat opaque, since you rarely narrate the why behind the what. Acting without ever explaining the reasoning, leaving your social presence capable but hard to actually know, is what actually blocks this talent. People trust your competence and still feel they don't quite know you. Your self-expression stays almost entirely in the doing, so people know your actions without ever really knowing your reasoning.`,
        invitation: `Ask yourself what you've done recently that people never actually understood the motive for. Narrate the why behind one action, out loud, before or after you take it. Say the reasoning, not just the result. Notice that you're allowed to be known for your reasoning, not just your results.`,
      },
      2: {
        title: `You Present Yourself Carefully, Revealing Only What's Been Earned`,
        mastery: `Your self-expression in this lifetime is deliberately selective — you're known by what you choose to reveal, and the revealing itself is a considered act, not an accident. This gives your social presence a real, felt depth: people sense there's more, and that sense is accurate. You're capable of revealing something real to one person who's already shown they can be trusted with it. Your social presence still carries real depth once it's accessible to the people who've actually proven trustworthy.`,
        shadow: `The risk is that the selectivity becomes so complete that almost no one actually gets past the surface, so your social presence stays intriguing but essentially unknown, even to people who've genuinely earned more access. Keeping the selectivity so tight that even people who've earned more access rarely get it is what actually blocks this talent. Someone trustworthy still only knows the surface of you, simply because the selectivity never actually opened for them. Your selective self-presentation is genuine, and it's staying so tightly closed that even people who've earned more access rarely get it.`,
        invitation: `Ask yourself who has already earned a level of access they're not currently getting. Reveal something real to one person who's already shown they can be trusted with it. Let them in faster than feels automatic. Notice that you're allowed to let someone in faster than feels automatic.`,
      },
      3: {
        title: `You Present Yourself Through What You Provide`,
        mastery: `Your self-expression in this lifetime shows through generosity and care — people know you by what you make for them, how you tend to them, the warmth you generate in a room. That's genuine self-expression, embodied in giving rather than only in speaking. You're capable of presenting an opinion or a need, plainly, without wrapping it in something you're providing. People can know more of you once you've stated an opinion or a need plainly, not just what you do for them.`,
        shadow: `The risk is that people know the giver so thoroughly that they never get introduced to your own needs or opinions, so your social identity becomes almost entirely defined by what you do for others. Being known almost entirely for what you provide, with your own needs and opinions staying largely invisible, is what actually blocks this talent. You're deeply appreciated and only partially known, because your own wants have stayed quietly offstage. Your self-expression stays almost entirely in what you provide, so people know the giver thoroughly and rarely meet your own needs or opinions.`,
        invitation: `Ask yourself what you've never said because you were too busy being useful. Present an opinion or a need, plainly, without wrapping it in something you're providing. Say it directly, not as a favor. Notice that you're allowed to be known for what you want, not just what you give.`,
      },
      4: {
        title: `You Present Yourself as Someone in Command`,
        mastery: `Your self-expression in this lifetime carries real authority — people know you as someone capable of structure and direction, and that read tends to be accurate. You're identified by your competence at holding things together. You're capable of letting one moment of genuine uncertainty be visible, rather than defaulting to the capable presentation. People can know the whole of you once uncertainty gets shown too, not just the person in charge.`,
        shadow: `The risk is that this authoritative presentation leaves little room for people to see you uncertain or in need, so your social identity becomes the capable one, permanently, even in moments that would benefit from being seen otherwise. Being seen only as capable and in-command, with little room left to be seen uncertain or in need, is what actually blocks this talent. You're respected and somewhat unreachable, because the presentation never lets anyone see past it. Your self-expression stays almost entirely in the capable, in-command register, leaving little room for people to see genuine uncertainty or need.`,
        invitation: `Ask yourself where you've performed competence when you actually needed something else to be seen. Let one moment of genuine uncertainty be visible, rather than defaulting to the capable presentation. Show the uncertainty directly, not managed. Notice that you're allowed to be known as more than the person in charge.`,
      },
      5: {
        title: `You Present Yourself Through What You Believe`,
        mastery: `Your self-expression in this lifetime is grounded in conviction — people know you by your principles, your framework, what you stand for. That's genuine, consistent self-presentation, and it gives people something real to trust. You're capable of presenting one genuine uncertainty, out loud, instead of your usual settled conviction. People can know a fuller version of you once the parts still being worked out get shown too.`,
        shadow: `The risk is that people know your positions thoroughly and rarely meet the parts of you that are still uncertain, so your social identity becomes the person who always has an answer, even in moments you genuinely don't. Being known only for settled conviction, with genuine uncertainty rarely shown or admitted, is what actually blocks this talent. You're seen as someone who always has an answer, which leaves little room to actually not know something out loud. Your self-expression stays almost entirely in settled conviction, so people rarely meet the parts of you that are genuinely still uncertain.`,
        invitation: `Ask yourself what you actually feel unsure about that you've been presenting as settled. Present one genuine uncertainty, out loud, instead of your usual settled conviction. Say it as unresolved, not settled. Notice that you're allowed to be known for not-knowing sometimes too.`,
      },
      6: {
        title: `You Present Yourself Most Fully in Chosen Relationship`,
        mastery: `Your self-expression in this lifetime opens most completely in close, chosen connection — people who are genuinely close to you know a different, fuller version of you than casual acquaintances ever get to see. People who know you casually see a real version; the people closest to you see a fuller one. You're capable of letting a little more of your real self show in a less intimate setting than usual. More people can get to know an actual version of you once a little more shows outside the inner circle.`,
        shadow: `The risk is that this relational gating means most people only ever meet a more guarded, general-purpose version of you, since your fullest self-expression is reserved almost entirely for the inner circle. Reserving your fuller self-expression so tightly for close relationships that most people only meet a guarded version is what actually blocks this talent. You're well-liked broadly and genuinely known narrowly, because the fuller self rarely leaves the inner circle. Your self-expression stays gated almost entirely behind close relationship, so most people only ever meet a more guarded version of you.`,
        invitation: `Ask yourself where you've presented a more guarded version simply because the setting wasn't intimate enough. Let a little more of your real self show in a less intimate setting than usual. Let it show without the usual gate. Notice that you're allowed to be known beyond just your closest relationships.`,
      },
      7: {
        title: `You Present Yourself Through Forward Momentum`,
        mastery: `Your self-expression in this lifetime shows through drive — people know you as someone in motion, pursuing something, rarely standing still. That momentum is a real and visible part of your social identity. You're capable of letting someone see you at rest, on purpose, without a project or pursuit attached. People can know a fuller version of you once someone sees you at rest too, not just the person always in motion.`,
        shadow: `The risk is that people rarely see you at rest, so your social identity becomes almost entirely the mover, with little room for anyone to know what you're like when you're not actively pursuing something. Being known almost entirely in motion, with little social space left for who you are at rest, is what actually blocks this talent. People know your drive well and your stillness barely at all. Your self-expression stays almost entirely in motion, so people rarely see who you are at rest.`,
        invitation: `Ask yourself who has never seen you simply not moving toward something. Let someone see you at rest, on purpose, without a project or pursuit attached. Let the stillness be visible, unattached to output. Notice that you're allowed to be known for stillness too, not just momentum.`,
      },
      8: {
        title: `You Present Yourself as Someone Who Deals Fairly`,
        mastery: `Your self-expression in this lifetime carries real integrity — people know you as someone who's honest and equitable, and that reputation is earned and accurate. You're identified by your fairness. You're capable of stating one want plainly, as a want, without framing it as fair or justified first. People can know you're allowed to just want things once a want gets stated plainly, not justified.`,
        shadow: `The risk is that this fairness-forward presentation makes it hard to be seen wanting something for purely selfish reasons, so you dress your actual wants in the language of fairness even when a plain want would be more honest. Dressing plain, personal wants in the language of fairness rather than just naming them directly is what actually blocks this talent. You've argued for something as fair when you could have just said you wanted it. Your self-expression stays tied to fairness, so plain personal wants get dressed in the language of justification rather than simply stated.`,
        invitation: `Ask yourself what you actually want that you've been justifying instead of just stating. State one want plainly, as a want, without framing it as fair or justified first. Say it as a want, not a case. Notice that you're allowed to be known for wanting things, not just for deserving them.`,
      },
      9: {
        title: `You Present Yourself Sparingly, in Person and in Groups`,
        mastery: `Your self-expression in this lifetime is genuinely more solitary — you're known less through constant social presence and more through what surfaces when you do choose to engage. That's a real, legitimate mode of self-presentation. You're capable of showing up a little more than feels automatic in one social setting that matters to you. People who matter to you can know you a little better once you show up a bit more, without losing the solitude you actually need.`,
        shadow: `The risk is that this sparing presence means most people simply don't know much about you at all, since the withdrawal that protects your energy also limits how much of you actually reaches anyone. Withdrawing so consistently that most people simply don't get enough exposure to actually know you is what actually blocks this talent. You're a mystery to people you'd actually like to be known by. Your self-expression stays genuinely sparing, and the withdrawal that protects your energy is also limiting how much of you actually reaches people.`,
        invitation: `Ask yourself where your withdrawal has cost you being known by people you'd actually want to know you. Show up a little more than feels automatic in one social setting that matters to you. Show up despite the automatic pull to withdraw. Notice that you're allowed to need solitude and still let yourself be known somewhat.`,
      },
      10: {
        title: `You Present Yourself Differently Depending on the Season`,
        mastery: `Your self-expression in this lifetime genuinely shifts with circumstance — how you show up socially isn't constant, it moves with your own cycles. That's an accurate read of how you actually present, not inconsistency. You're capable of naming the cycle to someone, so a quieter presentation doesn't get mistaken for your whole range. People can understand more of your actual variation once the cycle itself gets named.`,
        shadow: `The risk is that people meeting you in a quieter season assume that's simply who you are, missing the fuller range you actually have, since your presentation in any given moment is only ever a partial sample. Letting people assume a quiet-season version of you is your whole range, rather than naming the variation, is what actually blocks this talent. Someone has an inaccurate, narrow read on you, simply because they never saw a different season. Your self-expression genuinely shifts with circumstance, and people who've only met you in one season can mistake that sample for your whole range.`,
        invitation: `Ask yourself who might have only ever met one season of you. Name the cycle to someone, so a quieter presentation doesn't get mistaken for your whole range. Explain that you vary, plainly. Notice that you're allowed to explain that you vary.`,
      },
      11: {
        title: `You Present Yourself as Gentle, Which Can Be Mistaken for Simple`,
        mastery: `Your self-expression in this lifetime is soft rather than forceful — people know you as calm and steady, and that read is accurate, even though it doesn't announce the actual strength underneath it. The calm is genuine, not a performance of ease. You're capable of letting your actual capability be visible once, plainly, alongside the gentleness. People can know your real strength now once the capability shows up alongside the calm, not just your gentleness.`,
        shadow: `The risk is that the gentleness gets read as an absence of real capability, so people underestimate you socially, missing the considerable strength that's simply not presenting itself loudly. Presenting so gently that real strength and capability get underestimated by the people around you is what actually blocks this talent. People are surprised by what you can actually do, because the gentleness never announced it. Your gentle self-presentation is genuine, and it's letting real capability go underestimated, since the strength underneath isn't presenting itself loudly.`,
        invitation: `Ask yourself where your gentle presentation has left people underestimating what you're actually capable of. Let your actual capability be visible once, plainly, alongside the gentleness. Show the strength without dropping the softness. Notice that you're allowed to be known as strong, not just calm.`,
      },
      12: {
        title: `You Present Yourself Most Clearly After You've Had Time to Reflect`,
        mastery: `Your self-expression in this lifetime needs space to form — you're known most accurately by the considered version of you, the one that shows up after reflection, not the immediate reaction. The immediate reaction is real too, just less polished than what comes after. You're capable of presenting something in the moment, unpolished, before you've had the usual time to reflect. People can get access to more of you once something unpolished gets shown in real time too, not only the fully considered version.`,
        shadow: `The risk is that real-time, in-the-moment presentation suffers, since your best self-expression needs the pause you don't always get, leaving spontaneous interactions feeling like a lesser version of who you actually are. Needing reflection time so completely that real-time, spontaneous self-expression feels like a lesser version of you is what actually blocks this talent. You come across better after the fact than you did live, and rarely get credit for the in-the-moment version. Your self-expression genuinely needs reflection time to form clearly, which leaves real-time interactions feeling like a lesser version of who you actually are.`,
        invitation: `Ask yourself what you've held back in a live moment, waiting for time to consider it first. Present something in the moment, unpolished, before you've had the usual time to reflect. Say the unpolished version now. Notice that you're allowed to be known in real time too, not just after reflection.`,
      },
      13: {
        title: `You Present Yourself as Someone Who's Been Remade`,
        mastery: `Your self-expression in this lifetime carries the marks of real transformation — people know you as someone who's ended and rebuilt versions of themselves, and that history is genuinely part of how you present. Each version of you that ended made room for the one that came after. You're capable of letting one stable period of your self-presentation just be stable, without needing it to be evidence of the next transformation. People can know a settled version of you once a stable period gets to simply be stable, not only the one mid-change.`,
        shadow: `The risk is that people expect you to keep transforming indefinitely, so a stable, unchanging period of your life can read to others — and to you — as somehow incomplete or overdue for another ending. Expecting yourself to keep transforming, so a genuinely stable period feels incomplete rather than simply settled, is what actually blocks this talent. You feel restless in a period that's actually just settled, simply because settled feels unfamiliar to present. Your self-expression carries real transformation history, and there's an expectation that you'll keep transforming, so genuine stability can read as incomplete.`,
        invitation: `Ask yourself what part of you has been stable long enough to just be presented as itself. Let one stable period of your self-presentation just be stable, without needing it to be evidence of the next transformation. Let it simply be settled, without signaling more change coming. Notice that you're allowed to be known as settled sometimes, not only as someone mid-change.`,
      },
      14: {
        title: `You Present Yourself as Balanced, Consistently`,
        mastery: `Your self-expression in this lifetime is calibrated — people know you as measured, rarely swinging to extremes, and that consistency is a real and valuable part of your social identity. The steadiness is real, not a lid kept on something bigger. You're capable of letting one moment be presented at full intensity, without the usual calibration softening it. Your range can read wider once a moment gets shown at full intensity, not just steady.`,
        shadow: `The risk is that this balanced presentation filters out genuinely intense moments, so people rarely see you at full volume even when a situation actually calls for it, and your range reads narrower than it actually is. Presenting so consistently balanced that genuinely intense moments rarely get shown, even when warranted, is what actually blocks this talent. Something important got presented in your usual measured tone when it actually needed more. Your balanced self-presentation is genuine, and it's filtering out moments that actually deserved more intensity.`,
        invitation: `Ask yourself where you've toned down a presentation that actually deserved more intensity. Let one moment be presented at full intensity, without the usual calibration softening it. Let it be loud, without the usual moderation. Notice that you're allowed to be known at full volume sometimes.`,
      },
      15: {
        title: `You Present a Version of Yourself That Isn't the Whole Story`,
        mastery: `Your self-expression in this lifetime carries real intensity that you may not fully show — people know a calibrated version of you, while a stronger, more appetite-driven layer stays mostly private. The calibrated version people see is accurate as far as it goes. You're capable of letting one person see a truer, more intense version of you than you usually present. Being known can cost less effort than hiding did once at least one person sees the truer version.`,
        shadow: `The risk is that the concealment itself, not the intensity, becomes the actual problem, since hiding a real part of yourself takes ongoing effort and creates a gap between the presented self and the actual one. Hiding a genuinely intense part of yourself so consistently that maintaining the gap becomes its own quiet cost is what actually blocks this talent. That effort is more tiring than the intensity itself would be. Your presented self is genuine, and it's leaving out a real intensity that stays mostly hidden, which means maintaining the gap takes ongoing, quiet effort.`,
        invitation: `Ask yourself who might be trusted with more of your actual intensity. Let one person see a truer, more intense version of you than you usually present. Let them see it fully, not managed down. Notice that you're allowed to be known more fully, without it meaning something's wrong with you.`,
      },
      16: {
        title: `You Present Yourself as Someone Who Survived Something`,
        mastery: `Your self-expression in this lifetime carries the marks of real disruption — people can sense you've been through something and come out the other side, and that history genuinely informs how you present. What came after the disruption is genuinely part of who you are now. You're capable of presenting yourself fully, once, without the protective hedge you've built in since the disruption. Being fully known can start to feel safe again once you present yourself fully at least once.`,
        shadow: `The risk is that you present a slightly guarded version of yourself as a precaution against another sudden rupture, holding back the full extent of who you are in case presenting fully invites the same kind of disruption again. Presenting a guarded version of yourself as an unconscious precaution against another disruption is what actually blocks this talent. You hold back the full extent of who you are, as though full presentation would invite the same rupture. Your self-expression carries a real disruption in its history, and you're still presenting a guarded version as an unconscious precaution against it happening again.`,
        invitation: `Ask yourself what you've been holding back out of a caution that might not be necessary anymore. Present yourself fully, once, without the protective hedge you've built in since the disruption. Drop the hedge and see what happens. Notice that you're allowed to be known completely again.`,
      },
      17: {
        title: `You Present Yourself With Quiet, Guarded Hope`,
        mastery: `Your self-expression in this lifetime carries a hopeful undertone — people sense that you trust things can be good, even though you tend to present that hope modestly rather than loudly. The hope itself is real, whatever size you present it at. You're capable of presenting your hope at full size once, without the protective downgrade. People can know how much you actually trust things can work out once the hope shows at full size, not just the modest version.`,
        shadow: `The risk is that the modesty meant to protect your hope also makes you present as less optimistic than you actually are, so people underestimate how much you genuinely believe things can work out. Presenting your hope so modestly that people underestimate how much you actually trust things can work out is what actually blocks this talent. You're read as more guarded than you actually feel, because the hope has been presented smaller than it really is. Your hopeful self-expression stays deliberately modest, which means people consistently underestimate how much you actually believe things can be good.`,
        invitation: `Ask yourself where you've presented a smaller hope than the one you actually carry. Present your hope at full size once, without the protective downgrade. Say the full-sized version, not the guarded one. Notice that you're allowed to be known as genuinely hopeful, not just quietly so.`,
      },
      18: {
        title: `You Present Yourself in a Way That's Hard to Fully Pin Down`,
        mastery: `Your self-expression in this lifetime is genuinely harder to read clearly than most people's — there's real depth there, but it often comes across as slightly foggy rather than sharply defined, which isn't a flaw in who you are. The depth is real; it simply doesn't announce itself the way sharper presentations do. You're capable of presenting one thing about yourself more plainly than feels natural, accepting the loss of some nuance for the gain in clarity. People can have a more accurate sense of you once something gets stated plainly, even if the full depth still takes time to reach.`,
        shadow: `The risk is that this fog leaves people with an inaccurate or incomplete sense of you, since what you're actually presenting doesn't always land as clearly as what you intend. Presenting in a way that's genuinely harder to read, leaving people with an incomplete sense of who you actually are, is what actually blocks this talent. Someone's sense of who you are doesn't quite match who you actually are, simply because the clearer version has never quite been said. Your self-expression is genuinely foggy in a way that isn't a flaw but does leave people with an incomplete read on you.`,
        invitation: `Ask yourself what you've never said clearly because the clear version felt like it lost something. Present one thing about yourself more plainly than feels natural, accepting the loss of some nuance for the gain in clarity. Say the plain version, even if it loses some texture. Notice that you're allowed to be known plainly sometimes, not only atmospherically.`,
      },
      19: {
        title: `You Present Yourself as Warm and Easy to Be Around`,
        mastery: `Your self-expression in this lifetime comes across easily and warmly — people know you as approachable and bright, and that read is genuine, not performed. It's a real social gift. You're capable of presenting a real difficulty without the automatic warmth softening it first. People can know the whole of you once a real difficulty gets shown plainly, not just the bright, easy version.`,
        shadow: `The risk is that this easy warmth makes it hard for you to present as genuinely struggling, since your default social mode pulls toward brightness even in moments that would call for something more serious to be shown. Presenting warmly even in moments that actually call for showing genuine difficulty instead is what actually blocks this talent. You've come across as fine when you were actually not. Your easy warmth is genuine, and it makes presenting genuine struggle difficult, since your default social mode pulls toward brightness even when something more serious needs to be shown.`,
        invitation: `Ask yourself what hard thing you've smoothed over in how you present it. Present a real difficulty without the automatic warmth softening it first. Say it plainly, without the usual brightness. Notice that you're allowed to be known as struggling sometimes, not only as easy to be around.`,
      },
      20: {
        title: `You Present Yourself as Someone Waiting to Answer Something`,
        mastery: `Your self-expression in this lifetime carries an undertone of unfinished business — people can sense you're oriented toward something you haven't fully done yet, even if they couldn't name what it is. People pick up on the orientation before either of you can name what it's toward. You're capable of answering the thing you already sense you're meant to answer, in some concrete form. Your presentation can settle once you actually respond, not because everything is resolved, but because the waiting has ended.`,
        shadow: `The risk is that this waiting-to-answer quality becomes a permanent feature of how you present, rather than something that resolves once you actually respond to the call, leaving your presentation perpetually a little unsettled. Presenting as perpetually unresolved, when the unsettled quality would actually resolve if the call were answered, is what actually blocks this talent. People sense something unresolved in you without either of you being able to name it. Your self-expression carries a persistent, unsettled quality that traces back to a call you haven't yet answered.`,
        invitation: `Ask yourself what you've been sensing you're meant to do that you haven't yet acted on. Answer the thing you already sense you're meant to answer, in some concrete form. Respond now, even imperfectly. Notice that you're allowed to let your presentation settle by actually responding.`,
      },
      21: {
        title: `You Present Yourself Most Fully Once Everything Connects`,
        mastery: `Your self-expression in this lifetime deepens with integration — people know the fullest version of you once you can see how the pieces of your life fit together, rather than in isolated fragments. The fragments people see along the way are real, even before they connect. You're capable of presenting one isolated piece of yourself, without waiting for it to connect to the whole picture first. People can get to know parts of you sooner once an isolated piece gets shown, not only the fully integrated version.`,
        shadow: `The risk is that this need for integration delays presenting something you're actually ready to show, waiting for a comprehensive coherence that isn't always necessary before letting people see a piece of you. Waiting for full integration before presenting something you're actually ready to show now is what actually blocks this talent. You've held back something simple because the larger context wasn't yet clear to you. Your self-expression tends to wait for integration, so pieces of you that are actually ready to be shown get delayed.`,
        invitation: `Ask yourself what you've held back because it hadn't yet connected to everything else. Present one isolated piece of yourself, without waiting for it to connect to the whole picture first. Let the fragment stand on its own. Notice that you're allowed to be known in fragments sometimes, not only wholly.`,
      },
      22: {
        title: `You Present Yourself Openly, Trusting the Reception as You Go`,
        mastery: `Your self-expression in this lifetime is genuinely spontaneous — you present yourself as you actually are in the moment, trusting how it lands rather than managing the impression carefully in advance. What lands in the moment is actually you, not a rough draft of you. You're capable of presenting yourself a little more deliberately in one situation that actually calls for it. Your presence can be more grounded once real consideration gets combined with your natural openness, not just more open.`,
        shadow: `The risk is that this spontaneous openness avoids the different value of a more considered presentation in situations that actually call for it, so something that deserved more forethought gets the same unguarded approach as everything else. Presenting with the same spontaneous openness even in situations that actually deserved more consideration first is what actually blocks this talent. A presentation that could have used more care instead came across too openly, and it showed. Your trust in spontaneous self-presentation is genuine, and it's being applied even to situations that actually deserved more consideration.`,
        invitation: `Ask yourself what upcoming presentation of yourself could use more forethought than your usual openness provides. Present yourself a little more deliberately in one situation that actually calls for it. Prepare it, rather than winging it. Notice that you're allowed to combine your natural openness with real consideration sometimes.`,
      },
    },

  };

  function get(iconType) {
    return archetypes[iconType] || null;
  }

  function getForPosition(key, arcanaNum) {
    const group = positions[key];
    if (!group) return null;
    return group[Number(arcanaNum)] || null;
  }

  return { get, getForPosition };

})();
