'use strict';

/**
 * Destiny Matrix — Talent Star Line Content
 * ──────────────────────────────────────────
 * Archetype-level readings, keyed by the 5-bucket `iconType` string
 * computed in js/matrix-engine.js (LEADER_ACTION, INTUITION_WISDOM,
 * CREATIVITY_ART, TEACHER_FREEDOM, TRANSFORMATION_POWER).
 *
 * One entry per bucket — not per-arcana — since the Talent Star Line
 * is presented through the archetype abstraction, not the raw number.
 *
 * API:
 *   DTalentContent.get(iconType) → { heading, why, shadow, path } or null
 */

window.DTalentContent = (function () {

  const archetypes = {

    LEADER_ACTION: {
      heading: 'You Move Before Anyone Else Is Ready To',
      why: `There is something you do that looks like courage to everyone else but feels, to you, like the only bearable option. When a room hesitates, you move. Hand you a half-formed plan and a circle of uncertain faces, and you'll be the one who steps across the threshold first — not because you're fearless, but because waiting sits in your body worse than acting ever has. People feel this in you almost immediately. They fall in behind your momentum without being asked, because something in the way you carry a decision tells them it's already happening. You are the starter, the closer, the steady hands a stalled moment has been waiting for.`,
      shadow: `The trouble begins when you push where you should have paused. You can mistake speed for progress, and control for leadership, driving a plan forward long after the moment that needed it has quietly closed behind you. When that happens, you burn through people faster than you realize — not because you meant to, but because your pace left no room for anyone to catch their breath. If people have been quietly dropping off, agreeing with you less than they used to, that isn't bad luck. It's an echo coming back to you. And underneath the compulsion to keep moving, there is often a younger you who learned that hesitating meant being overlooked or left behind — a child for whom constant motion became the only way to feel safe or seen. That child wasn't wrong to learn it. It worked. It kept you visible.`,
      blocks: `What can block this talent: imposing your pace on people who never agreed to it, and refusing to slow down even when the room is visibly asking you to.`,
      path: `You are allowed to pause without disappearing. That is the quiet threshold you're standing at now: the old rule said motion equals safety, and something in you is beginning to sense that it no longer has to. Try asking a second question before you move — not just "can I push this forward," but "should I, right now, like this." Your drive is real and it is rare; most people freeze where you act. The mastery isn't slowing down for its own sake. It's choosing your moments as carefully as you already execute them, so people stop bracing against you and start moving with you. When was the last time you let a moment pass without acting on it — and what did the stillness try to tell you?`,
      positive: `Here, your drive and your discernment are working together instead of one racing ahead of the other. You still move first — that hasn't changed, and it isn't supposed to — but now there's a half-second pause before the push, just long enough to ask whether this moment actually wants your speed or your stillness. People feel the difference immediately, even if they couldn't name it. Your momentum stops reading as pressure and starts reading as invitation. The room falls in behind you not because they've been swept along, but because they trust the read that got you moving in the first place. Projects you lead actually finish, because you're no longer abandoning the unglamorous middle for the next exciting start. And the people closest to you stop bracing for your next sudden shift, because your motion has become something they can plan their own lives around instead of something they have to survive. This is what the talent was always for — not constant motion, but motion that lands.`,
      negative: `Here, the same force that could move a room instead becomes the thing everyone in it is quietly organizing around avoiding. You push when the moment was asking for patience, and mistake the resulting friction for resistance to your vision rather than a signal about your timing. People stop offering their honest reservations, not because they agree, but because disagreeing with your momentum has stopped feeling worth the cost. Over time this creates a specific, lonely kind of leadership: you're technically followed, but no longer really joined — compliance standing in for the collaboration you actually wanted. Projects launch fast and stall in the same unglamorous middle every time, because the push that started them never learned to become the patience that would finish them. And underneath it, the same old fear keeps running the show: that stopping, even for a moment, means disappearing. It never quite lets you find out that the opposite might be true.`,
    },

    INTUITION_WISDOM: {
      heading: 'You Know Before You Can Explain How',
      why: `You sense what's true before anyone hands you the proof. A room shifts and you feel it in your body before a word is spoken. A pattern repeats and you've clocked it three instances before anyone else notices there is one. This isn't guessing, and it isn't luck — it's a genuine gift for depth: for research, for reading people, for holding a complicated situation open without needing to resolve it just to feel comfortable. Where this sits in your chart, it marks a talent for going below the surface and staying down there long enough to actually understand something. Most people can't tolerate that depth. You live in it.`,
      shadow: `The catch is what you do with what you know. It's easy to let your perception become a private world instead of something you share — to stay quiet when speaking up could genuinely help, because turning a felt sense into plain words feels like it will lose something in translation. You may prefer the certainty of working things out alone over the mess of working them out with people. And if it ever feels like nobody's really listening to you, it's worth asking gently whether you've actually said the thing out loud yet. Somewhere behind that silence there is often a child who spoke what they sensed and wasn't believed — who learned that voicing the invisible wasn't welcome, and so made quiet into a fortress long before it became a spiritual style. That fortress protected you once. It's allowed to have been necessary.`,
      blocks: `What can block this talent: keeping your perception entirely private, and treating the mess of saying it out loud as a reason not to try.`,
      path: `You are allowed to be heard — not just to know, but to be known for what you know. Your work now is translation: finding the words, the timing, the moment that lets what you already sense reach the people who need it. What you carry was never meant to stay entirely internal, and the recognition you've been quietly hoping for can only respond to something you've actually offered. The more you say the true thing out loud, in real time, the more the world finally has something of yours to answer. What is one thing you've known for a long time that you have never once said out loud?`,
      positive: `The knowing is exactly as sharp as it's always been — what's changed is that it no longer dies in the privacy of your own mind. You feel a room shift, and instead of quietly filing it away, you say the thing, even before you can fully justify it, and let people respond to something real instead of guessing at your silence. This changes what depth actually gets you. People stop experiencing you as unreadable and start experiencing you as someone whose read they can trust, because you've actually offered it enough times for them to test it against reality. Collaboration deepens, because insight that's spoken can be built on, argued with, refined — insight that's withheld can only ever be admired from a distance, if it's noticed at all. And the specific ache of feeling unseen starts to loosen, not because anyone finally looked hard enough, but because you finally gave them something real to look at.`,
      negative: `The perception is still there, running exactly as accurately as ever — it's just staying entirely inside you, which means it might as well not exist for anyone else. You sense what's true and say nothing, or say something so hedged and softened it barely counts as having spoken at all, and then feel the particular loneliness of being surrounded by people who have no idea how clearly you actually see them. Collaboration stays shallow, because no one can build on a read you never offered. Recognition never arrives, because it can't respond to a silence, however accurate that silence turns out to be later. And the old fear that first built the fortress — that speaking the invisible thing out loud will get it dismissed or disbelieved again — keeps getting a strange kind of confirmation: no one disbelieves you, because no one ever actually heard what you knew.`,
    },

    CREATIVITY_ART: {
      heading: 'You Make Things That Are Meant to Be Seen',
      why: `You have a gift for taking what's happening inside you and giving it a form other people can feel. Aesthetics, performance, public creative work — wherever this lands on your Talent Star Line, it marks a real talent for making things that move people, and for standing visible while you do it. This isn't vanity, whatever you may have been told. It's closer to translation: a private feeling finding its outer body, a thread pulled from somewhere wordless and woven into something someone else can hold.`,
      shadow: `Where this gets complicated is when you start needing the reaction more than you trust the work. You might notice yourself quietly shrinking a piece — making it safer, more predictable, more likely to be liked — trading its truth for its reception. Visibility starts to feel like the point instead of the natural echo of expressing something real. If audiences keep feeling lukewarm, it's worth asking whether the work got softened somewhere on its way out of you. And beneath that softening there is often a child whose creativity was only truly welcomed when it pleased — who learned early that being seen depended on being palatable first. That child made a reasonable bargain with the world it was given. You're allowed to grieve that it was ever the price.`,
      blocks: `What can block this talent: softening the work to make it more likeable, and needing the reaction more than you trust what you actually made.`,
      path: `You are allowed to make something true before you make it likeable. That's the threshold in front of you: letting being seen become a consequence of expression rather than its goal. Your talent is real, and it deserves an audience — but it doesn't need one to already be valid while you're making it. The more the work comes from genuine expression instead of approval-seeking, the more the audience it draws responds to something alive instead of something merely safe. If no one ever reacted to your work again — what would you make next, and for whom?`,
      positive: `The work still comes from the same private, wordless place it always has — what's different is that you stop editing it down before it's fully arrived. You make the true thing first and let it be seen second, instead of pre-shrinking it to something safer on its way out. This is where the actual gift lives, and people can feel the difference instantly, even if they can't say why one piece moves them and another merely impresses them. An audience built on genuine expression doesn't just admire the work, it recognizes something in itself through it — which is a different, deeper kind of response than approval, and it tends to be the kind that lasts. Visibility stops being the anxious goal and becomes what it was always meant to be: the natural, secondary echo of having made something real. And because the work isn't performing for reception anymore, making it again gets easier instead of harder each time.`,
      negative: `The instinct to create is still fully intact — it's just getting filtered through a question the work was never supposed to answer: will this be liked. Each piece gets quietly rounded off, softened, made a little safer than the version that first moved through you, and the audience — sensing something withheld even if they can't name it — responds with the same muted warmth the work was made with. This can look, from the outside, like steady output and reasonable reception, which makes the actual cost easy to miss: a slow substitution of truth for likability that eventually makes it hard to remember what the unshrunk version even sounded like. The old bargain that first taught you to please before you expressed keeps renewing itself here, one small edit at a time, and the applause it earns never quite reaches the place in you that was originally trying to be known.`,
    },

    TEACHER_FREEDOM: {
      heading: 'You Teach Best When You Let People Outgrow You',
      why: `You have a real talent for passing on what you know while leaving room for the other person to eventually go further than you did. It shows up as an aptitude for teaching, for building systems other people can actually use, for walking unconventional paths that others can later walk without you beside them. The best version of this gift was never about being needed. It's about building a container strong enough to hold people while they grow — and open enough that they can leave it when they're ready.`,
      shadow: `The risk here is subtle: a quiet need to stay necessary. You might catch yourself keeping a student, a team, or a system just slightly dependent on you continuing to show up — even while telling yourself, and them, that you're giving them freedom. The opposite trap exists too: rejecting structure so completely that nothing durable ever gets built or passed on. If the people you teach never quite launch on their own, it's worth asking gently whether the freedom you're offering is real or just the word you use for it. Underneath, there is often a child whose place in the family depended on being needed — for whom being indispensable became identity long before it became a teaching style. That child found belonging the only way that was offered. It made sense then.`,
      blocks: `What can block this talent: keeping people quietly dependent on you, or rejecting structure so completely that nothing durable ever gets passed on.`,
      path: `You are allowed to matter without being needed. That's the threshold: teaching yourself out of a job, building something — or someone — fully capable of standing without you, and discovering that your worth survives their independence. That's the true measure of this talent. Once the freedom you offer is genuine rather than managed, the people you teach actually take it and run, and what you built keeps compounding long after you've stepped back. If everyone you've ever taught outgrew you tomorrow, what would be left that's just yours?`,
      positive: `You still build the container the same way you always have — strong enough to actually hold someone while they grow. What's different is that you're also, deliberately, building the exit. You teach the thing and then step back far enough to let someone actually use it without you, resisting the old pull to stay just slightly indispensable. This is where the real measure of the gift shows up: not in how needed you are, but in how far the people and systems you built travel once you're no longer holding them up. Students launch. Teams run without your constant presence. Whatever you built keeps compounding on its own momentum, which is the only kind of legacy that was ever actually durable. And the specific fear underneath this talent — that your worth was tied to being needed — gets to quietly, finally, prove itself wrong.`,
      negative: `The teaching still happens, the systems still get built, but there's a small, consistent gap left in every one of them — a dependency, barely visible even to you, that keeps the whole structure oriented around your continued presence. You call it support. The people relying on it eventually feel it as something closer to a leash. Whatever you've built stops compounding on its own, because it was never actually designed to survive without you standing somewhere inside it. This can go on for a long time without anyone naming it, because it looks so much like generosity from the outside — until a student or a team finally attempts to stand alone and discovers how much of the structure was actually you. The old fear that first built this pattern, that being needed was the only guaranteed place in the family or the room, keeps recreating the exact conditions that let it stay true.`,
    },

    TRANSFORMATION_POWER: {
      heading: 'You Find Clarity Right Where Everyone Else Loses It',
      why: `You have a talent that only reveals itself when things fall apart. You step into collapse, crisis, real upheaval — and where other people freeze or scatter, something in you steadies. You can see what the breakdown is actually clearing space for while everyone around you is still grieving the rubble. This is a genuine capacity to turn a mess into a foundation, not just survive it. In the storm, you are the still point. People sense it, and they move toward you when everything else is moving away.`,
      shadow: `The risk is that crisis becomes your only comfortable terrain. Without quite meaning to, you can find yourself drawn toward drama or upheaval because stillness feels unfamiliar by comparison — even tearing down things that still had value, simply because tearing down is the move your hands know best. If upheaval keeps arriving in your life more often than seems reasonable, it's worth asking whether some part of you still doesn't trust the quiet. Often there's a child underneath this — one raised where only crisis reliably got attention, where calm was just the held breath before something broke. For that child, chaos was legible and peace was suspicious. Learning to read the storm was how you survived it. Of course calm still feels like a stranger.`,
      blocks: `What can block this talent: seeking out upheaval because stillness feels untrustworthy, and tearing down things that still had real value out of habit.`,
      path: `You are allowed to rest inside a life that isn't on fire. That's the threshold you're standing at: learning to tell the difference between change that's genuinely needed and change that's merely familiar. Your capacity for transformation is real — the mastery is saving it for the moments that actually call for it, and letting the quiet stretches be quiet. Once stillness stops registering as a threat, change gets to arrive on its own terms instead of needing a crisis to get your attention. When your life is finally calm — what do you notice yourself waiting for?`,
      positive: `The clarity you find inside real crisis is still exactly as sharp as it's always been — the difference is that crisis has stopped being the only place you can access it. You've learned to tell the difference between change that's genuinely needed and change that's just familiar, which means you no longer have to manufacture upheaval just to feel like yourself. When something actually does fall apart, you're still the still point everyone gravitates toward, steady while the room scatters. But now the quiet stretches between those moments get to stay quiet too, instead of being sacrificed to a restlessness that used to read as instinct. Change, when it comes, arrives on its own timeline instead of needing a crisis to summon it — deliberate instead of catastrophic, chosen instead of triggered. And stillness, once a stranger, starts to feel like something you can actually live inside.`,
      negative: `The gift for finding clarity in collapse hasn't gone anywhere — it's just that some part of you has quietly started arranging for collapse to keep arriving, because a life without it feels unfamiliar in a way that reads, wrongly, as unsafe. Stillness sits like a held breath waiting for the next disruption, and if one doesn't show up on its own, you may find yourself the one pulling something down that still had real value, just to have the reliable terrain back under your feet. This can look, for a long stretch, like resilience — you always handle the crisis well, so no one questions why there's always another one. Underneath it, the same old wiring keeps running: chaos is legible, and calm is the thing that can't yet be trusted. Until that trust is rebuilt, the quiet keeps getting interrupted before it ever has the chance to prove itself safe.`,
    },

  };

  function get(iconType) {
    return archetypes[iconType] || null;
  }

  return { get };

})();
