/* =============================================================
   DTzolkinContent — interpretation prose for the Tzolk'in page
   =============================================================
   Voice: docs/GOLDEN-STANDARD.md register (Destiny Matrix family).
   Structure per day sign: title / tagline / essence / gift / shadow / invitation.
   Tones: name / title / essence.
   Indexed by sign index 0..19 and tone 1..13.
   ============================================================= */
(function () {
  'use strict';

  var SIGNS = [
    { title: 'The Primordial Waters', tagline: 'Everything begins in the dark sea before form.',
      essence: 'Imix is the first day because it is the day before days — the crocodile floating in the waters that existed before the world was named. People born under it carry the raw material of beginnings: instinct, nourishment, the urge to bring something out of nothing.',
      gift: 'A bottomless creative source. When you trust the first impulse, whole worlds come out of you.',
      shadow: 'Drowning in your own depths — chaos, overwhelm, feeding everyone but yourself.',
      invitation: 'Give the waters a shore. One vessel, one form, one thing carried all the way into daylight.' },
    { title: 'The Breath of Spirit', tagline: 'What cannot be seen still moves everything.',
      essence: "Ik' is wind — the invisible current that carries voice, weather, and spirit. It rules communication in its oldest sense: breath given shape. Those born here are messengers whether they choose it or not.",
      gift: 'Words that move people. Ideas arrive on you like weather fronts.',
      shadow: 'Inconstancy — scattering, saying everything and landing nothing, moods that flip with the wind.',
      invitation: 'Choose what your breath is for. A message repeated with intention becomes a force.' },
    { title: 'The House of Night', tagline: 'The dawn is dreamed before it is seen.',
      essence: "Ak'b'al is the dark interior — the cave, the hearth before sunrise, the dreaming mind. It holds the mystery hours where intuition speaks plainly. Its people are dreamers with an uncanny feel for what is still hidden.",
      gift: 'Access to the unformed. You sense what is coming before there is evidence for it.',
      shadow: 'Staying in the cave — secrecy, self-doubt, mistaking the dream for the deed.',
      invitation: 'Bring one dream per season across the threshold into morning.' },
    { title: 'The Ripe Seed', tagline: 'Abundance is a seed that insists on becoming.',
      essence: "K'an is the yellow kernel of maize — germination, ripeness, the net that gathers plenty. It carries the generative power of the field: plant honestly and the harvest is disproportionate.",
      gift: 'Things grow around you — projects, families, gardens, wealth of every kind.',
      shadow: 'Entanglement in the net — debts, obligations, growth for its own sake.',
      invitation: 'Plant only what you are willing to harvest. Then tend it without apology.' },
    { title: 'The Serpent of Lifeforce', tagline: 'The body knows before the mind agrees.',
      essence: 'Chikchan is the feathered serpent as pure vitality — the electric current that runs the spine, the sky, the storm. Its people run hot with charisma and instinct; energy moves through them visibly.',
      gift: 'Magnetism and physical wisdom. When you are aligned, rooms reorganize around you.',
      shadow: 'The strike — temper, desire that consumes, energy leaking through drama.',
      invitation: 'Treat your lifeforce as sacred voltage: ground it daily, spend it deliberately.' },
    { title: 'The Great Transformer', tagline: 'Only what dies can be reborn.',
      essence: 'Kimi is death as the Maya held it — not an ending but the hinge between worlds, keeper of ancestors, patron of midwives and undertakers alike. Its people are at ease at thresholds that frighten everyone else.',
      gift: 'Fearless companionship through endings. You help things die well so they can begin again.',
      shadow: 'Clinging — refusing the necessary ending, or courting collapse to feel alive.',
      invitation: 'Ask of everything you hold: is this alive, or am I carrying its corpse?' },
    { title: 'The Healing Hand', tagline: 'The deer walks softly and carries the forest.',
      essence: "Manik' is the deer and the open hand — grace, pilgrimage, and the power to heal through touch and steadiness. It is a day of quiet strength: the strongest pillar draws no attention to itself.",
      gift: 'Hands that mend — bodies, tools, situations. People stabilize in your presence.',
      shadow: 'Wandering off — avoidance, carrying others until your own legs buckle.',
      invitation: 'Stand still long enough to be found. Your medicine works at close range.' },
    { title: 'The Star of Abundance', tagline: 'Venus rises on the ordinary and makes it shine.',
      essence: 'Lamat is the rabbit, the star, the overflowing — Venus as morning star scattering luck like seed. It multiplies whatever it touches: joy, harvests, mischief.',
      gift: 'Natural luminosity. Abundance follows you when you stop chasing it.',
      shadow: 'Excess — intoxication, scattering yourself across too many pleasures.',
      invitation: 'Shine on purpose. Pick the fields worth multiplying.' },
    { title: 'The Offering of Water', tagline: 'What is paid freely returns as rain.',
      essence: 'Muluk is water as offering — the jade droplet given back to the gods, the debt honoured before it is called. It governs gratitude, atonement, and emotional tides.',
      gift: 'Deep feeling turned to generosity. Your giving restores balances others cannot see.',
      shadow: 'The flood — guilt, moods that swamp the house, paying debts that were never yours.',
      invitation: 'Make your offerings clean: give from fullness, and let the tide also come in.' },
    { title: 'The Loyal Companion', tagline: 'Love is the oldest form of guidance.',
      essence: 'Ok is the dog — guide of souls through the underworld, keeper of loyalty and warmth. Its people love with rare constancy and can find the path through any darkness by heart alone.',
      gift: 'Unshakeable fidelity. You guide others through passages they could not walk alone.',
      shadow: 'The stray — misplaced loyalty, appetite without discrimination.',
      invitation: 'Be as loyal to your own path as you are to the people on it.' },
    { title: 'The Weaver of Time', tagline: 'All threads answer to the one who weaves.',
      essence: "Chuwen is the monkey artisan — patron of weavers, artists, and time itself, which the Maya understood as something woven. Play and mastery are the same motion in this sign.",
      gift: 'Effortless artistry. You braid disparate strands — people, ideas, days — into pattern.',
      shadow: 'The trickster loop — cleverness without completion, performance instead of craft.',
      invitation: 'Finish the weave. A completed cloth outlives a thousand brilliant beginnings.' },
    { title: 'The Sacred Road', tagline: 'The journey itself is the destination’s first gift.',
      essence: 'Eb is the road — the grass-lined path of the traveler and the life-road (saqb’e) each person walks. It carries humility, service, and the slow accumulation of blessing through movement.',
      gift: 'You open roads. Where you have walked, others find the way easier.',
      shadow: 'Wear — resentment gathered silently, poison swallowed instead of spoken.',
      invitation: 'Speak what the road costs you. Service without voice becomes erosion.' },
    { title: 'The Living Pillar', tagline: 'The reed bends, and the house stands because of it.',
      essence: "B'en is the reed — the cornstalk pillar of the home, authority that grows upward joint by joint. It governs family, leadership, and renewal of the house in every sense.",
      gift: 'Quiet authority. Structures — homes, teams, traditions — hold because you hold.',
      shadow: 'Rigidity — the pillar that cannot bend, standards no one can live inside.',
      invitation: 'Grow like the reed: strong, hollow enough for wind to pass through.' },
    { title: 'The Jaguar of Earth Magic', tagline: 'The wild heart of the world still prowls.',
      essence: 'Ix is the jaguar — night-walker, shaman’s twin, spirit of the untamed earth and its shrines. Its people carry feminine earth-power: patience, ferocity, and access to the hidden.',
      gift: 'Earth-deep intuition and the courage to move alone in the dark.',
      shadow: 'The predator — manipulation, vanity, power hoarded in shadow.',
      invitation: 'Serve the wild with your magic; power kept only for the self turns feral.' },
    { title: 'The Eagle of Vision', tagline: 'From high enough, every maze is a map.',
      essence: 'Men is the eagle — the far-seer, messenger between the sun and the world, patron of fortune found through vision. It grants the long view and the boldness to act on it.',
      gift: 'You see the whole board. Opportunity is visible to you before it exists for others.',
      shadow: 'Detachment — circling forever, too high to land, too proud to ask.',
      invitation: 'Dive. Vision becomes fortune only in the moment of commitment.' },
    { title: 'The Ancestral Pardon', tagline: 'The ancestors are forgiven in us, and we in them.',
      essence: 'Kib is the vulture and the candle-wax — the day of ancestors, old karma, and the profound cleansing of pardon. It transmutes what generations could not digest.',
      gift: 'You metabolize the past. Old wounds — yours, your line’s — end their journey in you.',
      shadow: 'Carrying the graveyard — inherited guilt mistaken for identity.',
      invitation: 'Forgive specifically and out loud. Each pardon releases someone unborn.' },
    { title: 'The Mind of the Earth', tagline: 'The world thinks, and its thought is movement.',
      essence: "Kab'an is earth-in-motion — earthquake, incense, and No'j, the day of knowledge itself. It carries the planet’s intelligence: ideas that arrive with tectonic force.",
      gift: 'Original thought. You synthesize what the age needs before it knows it needs it.',
      shadow: 'The tremor — overthinking, ideas that shake but never build.',
      invitation: 'Let one great thought become ground others can stand on.' },
    { title: 'The Obsidian Blade', tagline: 'Truth cuts once; everything else saws.',
      essence: "Etz'nab' is flint and obsidian — the mirror-blade that divides true from false, heals as scalpel or harms as knife. Its people are given the terrible gift of clarity.",
      gift: 'Surgical discernment. You end confusion the way lightning ends darkness.',
      shadow: 'The cut that serves the ego — gossip, betrayal, sharpness as reflex.',
      invitation: 'Cut only to heal. Sheathed, your blade is a mirror; ask what it shows you.' },
    { title: 'The Storm of Renewal', tagline: 'The rain that floods is the rain that feeds.',
      essence: 'Kawak is the storm — thunder, midwives, the drenching that ends the dry season. It gathers community the way clouds gather, and releases what the land has been begging for.',
      gift: 'Catalytic energy. Your arrival breaks stagnation; abundance follows your weather.',
      shadow: 'The unending storm — crisis as habit, drama as climate.',
      invitation: 'Storm with a season. Then clear, and let everyone see what grew.' },
    { title: 'The Lord of the Sun', tagline: 'The flower is the sun’s answer to the dark.',
      essence: 'Ajaw is the day of the Sun itself — the hero twins risen, the hunter, the flower, the face of completion. The count ends and begins here: it holds mastery, enlightenment, and the audacity of full bloom. The ancient katun endings were fixed to Ajaw; it is the day of culminations.',
      gift: 'Solar presence. You are built for wholeness — finishing things so completely they become light for others.',
      shadow: 'The eclipse — perfectionism, needing to be seen to feel real, unrealized potential worn like a crown.',
      invitation: 'Bloom without permission. Your work is not to seem radiant but to ripen — fully, publicly, and on time.' }
  ];

  var TONES = [
    null,
    { name: 'Hun',    title: 'Unity',        essence: 'The first light — initiation, the undivided impulse. Tone 1 begins the wave: everything after it unpacks this seed.' },
    { name: 'Ka',     title: 'Polarity',     essence: 'The second day names the challenge — the pole that gives the wave its tension and therefore its power.' },
    { name: 'Ox',     title: 'Rhythm',       essence: 'Movement begins. Three points make the first pattern; the impulse learns to travel.' },
    { name: 'Kan',    title: 'Foundation',   essence: 'Four directions, four corners — the wave takes measure and builds a floor to stand on.' },
    { name: 'Ho',     title: 'Center',       essence: 'The fifth tone gathers force at the core. Resources organize; the reason clarifies.' },
    { name: 'Uak',    title: 'Flow',         essence: 'Steadiness in motion — the rhythm found at four and five becomes an effortless stride.' },
    { name: 'Uk',     title: 'Attunement',   essence: 'The mystical midpoint of the thirteen — the mirror where the wave sees its whole span at once.' },
    { name: 'Uaxak',  title: 'Integrity',    essence: 'Harmony through form: what was inspired now must be made just, balanced, and true.' },
    { name: 'Bolon',  title: 'Completion in Motion', essence: 'The great nine — patience and mastery; the wave carries its full intention into the world.' },
    { name: 'Lahun',  title: 'Manifestation', essence: 'Ten makes it real. What began as impulse now has weight, name, and consequence.' },
    { name: 'Buluk',  title: 'Release',      essence: 'Eleven dissolves what manifestation made rigid — creative dissonance that lets the essential survive.' },
    { name: 'Lahka',  title: 'Understanding', essence: 'Twelve gathers every day of the wave into retrospect: the parts become a teaching.' },
    { name: 'Oxlahun', title: 'Transcendence', essence: 'Thirteen is the door out — completion that immediately seeds the next beginning.' }
  ];

  var LORDS = {
    G1: 'first of the Nine Lords of the Night, associated with beginnings in darkness',
    G2: 'second Lord of the Night, keeper of the buried seed',
    G3: 'third Lord of the Night, guardian of the underworld waters',
    G4: 'fourth Lord of the Night, the maize lord below',
    G5: 'fifth Lord of the Night, the midpoint of the dark procession',
    G6: 'sixth Lord of the Night, keeper of buried fires',
    G7: 'seventh Lord of the Night, guardian of the jaguar hours',
    G8: 'eighth Lord of the Night, the lord nearest dawn',
    G9: 'ninth Lord of the Night — the eldest, who ruled the night of creation itself'
  };

  window.DTzolkinContent = { SIGNS: SIGNS, TONES: TONES, LORDS: LORDS };
})();
