/* Interpretation library: signs, planets, houses, aspects, karmic themes. */
(function (global) {
  "use strict";
  const VS = "︎"; // force text (not emoji) presentation for symbols

  const SIGNS = {
    aries: {
      name: "Aries", glyph: "♈" + VS, element: "fire", mode: "cardinal", ruler: "mars", polarity: "yang", dates: "21 Mar – 19 Apr", body: "Head & face",
      keywords: ["initiative", "courage", "independence", "impulse"],
      essence: "The first spark of the zodiac. Aries is the urge to begin, to act before thinking and to prove existence through movement.",
      how: "boldly, directly and with a pioneer's urgency",
      gifts: "courage, initiative and a refreshing honesty",
      shadow: "impatience, anger that flares fast, and starting more than you finish",
      sun: "You are here to initiate. Identity is forged through action, challenge and being first — you feel most alive when something needs a leader and nobody else has moved yet. Your growth lies in learning that strength also includes patience.",
      moon: "Your feelings arrive instantly and leave just as fast. You need freedom, movement and a sense of agency to feel safe; being told to wait is emotionally draining. Honest, quick releases of emotion keep you balanced.",
      rising: "You meet the world head-on. People read you as direct, energetic and competitive, and you tend to act first and reflect later. Life keeps asking you to be brave on your own behalf.",
      nn: "Your soul is learning independence. After lifetimes of accommodating others (South Node in Libra), growth comes from trusting your own instincts, taking the first step and allowing yourself to want things for yourself.",
      chiron: "The wound is around the right to exist and assert yourself — a sense of not being allowed to take up space. Healing comes as you model courage for others who were taught to shrink.",
    },
    taurus: {
      name: "Taurus", glyph: "♉" + VS, element: "earth", mode: "fixed", ruler: "venus", polarity: "yin", dates: "20 Apr – 20 May", body: "Throat & neck",
      keywords: ["stability", "sensuality", "worth", "patience"],
      essence: "The builder of the zodiac. Taurus slows the spark of Aries into something tangible — a body, a home, a resource that lasts.",
      how: "steadily, sensually and with deep loyalty",
      gifts: "patience, reliability and a gift for making things real",
      shadow: "stubbornness, possessiveness and resisting necessary change",
      sun: "You are here to build something of lasting value. You shine through consistency, taste and an unhurried relationship with the physical world. Your growth lies in knowing when holding on has become holding back.",
      moon: "The Moon is exalted here: your emotions are steady and grounded. You need comfort, routine, good food, touch and financial security to feel safe, and you soothe yourself through the senses.",
      rising: "You come across as calm, grounded and quietly magnetic. People find your presence reassuring. You move at your own pace and life rewards you for trusting it.",
      nn: "Your soul is learning simplicity and self-worth. Leaving behind the crisis, intensity and entanglement of the South Node in Scorpio, growth comes from building your own resources, enjoying the body and trusting slow, steady progress.",
      chiron: "The wound touches self-worth, security and the body — a feeling of never having quite enough. Healing comes through learning that your value is inherent, not earned.",
    },
    gemini: {
      name: "Gemini", glyph: "♊" + VS, element: "air", mode: "mutable", ruler: "mercury", polarity: "yang", dates: "21 May – 20 Jun", body: "Lungs, arms & hands",
      keywords: ["curiosity", "communication", "versatility", "wit"],
      essence: "The messenger. Gemini names things, connects them and passes them on — it is the mind discovering that there is always another angle.",
      how: "quickly, curiously and in many directions at once",
      gifts: "wit, adaptability and a talent for connecting ideas and people",
      shadow: "scattered focus, restlessness and staying on the surface",
      sun: "You are here to learn and to share what you learn. Identity lives in conversation, variety and the joy of a new idea. Your growth lies in going deep enough to turn information into wisdom.",
      moon: "You process feelings by talking and thinking them through. You need mental stimulation, variety and people to bounce off to feel emotionally safe; boredom feels like a threat.",
      rising: "You come across as bright, youthful and conversational. People experience you as curious and quick, and you tend to approach every situation by asking questions.",
      nn: "Your soul is learning curiosity and listening. Moving away from the certainty and preaching of the South Node in Sagittarius, growth comes through asking questions, staying open to other viewpoints and valuing everyday connection.",
      chiron: "The wound is around being heard or understood — perhaps a sense that your mind or voice did not count. Healing comes as you become a translator for others.",
    },
    cancer: {
      name: "Cancer", glyph: "♋" + VS, element: "water", mode: "cardinal", ruler: "moon", polarity: "yin", dates: "21 Jun – 22 Jul", body: "Chest & stomach",
      keywords: ["nurture", "memory", "belonging", "protection"],
      essence: "The protector. Cancer creates the shell in which life can grow safely — home, family, emotional memory and the instinct to care.",
      how: "protectively, intuitively and through emotional bonds",
      gifts: "empathy, loyalty and a powerful instinct to nurture",
      shadow: "moodiness, clinging to the past and defending through withdrawal",
      sun: "You are here to create belonging. You shine when you care for people and places, and your identity is deeply tied to roots, memory and family — chosen or inherited. Your growth lies in nurturing yourself as generously as others.",
      moon: "The Moon rules Cancer, so emotions run deep and instinctive. You need a safe home base and close bonds to feel secure. You remember how everything felt, which makes you deeply intuitive.",
      rising: "You come across as warm, receptive and a little guarded at first. People sense your care before they know you well. You read the emotional climate of every room.",
      nn: "Your soul is learning emotional openness. Leaving behind the control, status-seeking and self-sufficiency of the South Node in Capricorn, growth comes from letting yourself need others, tending your inner life and building a true home.",
      chiron: "The wound lives in family, belonging or mothering — a sense of not having been held. Healing comes as you become the nurturer you once needed.",
    },
    leo: {
      name: "Leo", glyph: "♌" + VS, element: "fire", mode: "fixed", ruler: "sun", polarity: "yang", dates: "23 Jul – 22 Aug", body: "Heart & spine",
      keywords: ["creativity", "heart", "pride", "play"],
      essence: "The performer and the heart. Leo is the self radiating outward, creating for the joy of it and asking to be seen.",
      how: "warmly, dramatically and from the heart",
      gifts: "generosity, creativity and a contagious confidence",
      shadow: "pride, a need for applause and difficulty sharing the stage",
      sun: "The Sun rules Leo: you are here to shine. Creativity, romance and play are how you come alive, and your warmth gives others permission to be themselves. Your growth lies in creating from joy rather than for approval.",
      moon: "You need to feel appreciated, admired and loved in a visible way. Your emotions are big and generous; when you feel ignored you may withdraw proudly or perform for attention.",
      rising: "You make an entrance. People notice your warmth, style and confidence, even when you feel shy inside. You lead naturally and are asked to live with an open heart.",
      nn: "Your soul is learning self-expression. Leaving behind the detachment and group-mind of the South Node in Aquarius, growth comes from taking creative risks, following your heart and allowing yourself to be seen as an individual.",
      chiron: "The wound is around being seen and celebrated — creativity or joy that felt unwelcome. Healing comes as you help others shine unapologetically.",
    },
    virgo: {
      name: "Virgo", glyph: "♍" + VS, element: "earth", mode: "mutable", ruler: "mercury", polarity: "yin", dates: "23 Aug – 22 Sep", body: "Digestion & nervous system",
      keywords: ["discernment", "service", "craft", "health"],
      essence: "The healer and craftsperson. Virgo refines, sorts and improves — it is devotion expressed through useful, careful work.",
      how: "carefully, precisely and with a drive to improve",
      gifts: "analysis, skill and a quiet devotion to being useful",
      shadow: "perfectionism, worry and turning criticism inward",
      sun: "You are here to perfect a craft and be of real use. You shine through competence, attention to detail and caring for the body and the everyday. Your growth lies in accepting that things — and you — can be whole without being flawless.",
      moon: "You feel safest when things are in order. You process emotion by analysing it and by being helpful; routines, tidy spaces and good health habits soothe your nervous system.",
      rising: "You come across as composed, observant and modest. People trust your judgement and your eye for detail. You tend to approach life by figuring out how to make it work better.",
      nn: "Your soul is learning practical service. Leaving behind the escapism and boundlessness of the South Node in Pisces, growth comes through routine, discernment, healthy boundaries and turning compassion into concrete help.",
      chiron: "The wound is around never being good enough — a critical voice about the body, work or usefulness. Healing comes as you learn and teach self-acceptance.",
    },
    libra: {
      name: "Libra", glyph: "♎" + VS, element: "air", mode: "cardinal", ruler: "venus", polarity: "yang", dates: "23 Sep – 22 Oct", body: "Kidneys & lower back",
      keywords: ["harmony", "partnership", "beauty", "justice"],
      essence: "The diplomat. Libra discovers the self through the other — it seeks balance, beauty and a fair exchange between people.",
      how: "gracefully, diplomatically and in relation to others",
      gifts: "charm, fairness and a fine aesthetic sense",
      shadow: "indecision, people-pleasing and avoiding conflict at your own cost",
      sun: "You are here to create harmony and meaningful partnership. You shine through relationship, beauty and fairness. Your growth lies in knowing your own opinion as clearly as you understand everyone else's.",
      moon: "You need peace and connection to feel safe. Discord upsets your equilibrium, and you process feelings in dialogue with a partner. Beauty around you is emotional nourishment.",
      rising: "You come across as charming, balanced and easy to be with. People feel considered in your presence. Life keeps teaching you through one-on-one relationships.",
      nn: "Your soul is learning partnership. Leaving behind the self-reliance and impulsiveness of the South Node in Aries, growth comes from cooperation, considering others' needs and discovering who you are through relationship.",
      chiron: "The wound lives in relationship — feeling unbalanced, abandoned or lost in others. Healing comes as you help others find fair, equal connection.",
    },
    scorpio: {
      name: "Scorpio", glyph: "♏" + VS, element: "water", mode: "fixed", ruler: "pluto", tradRuler: "mars", polarity: "yin", dates: "23 Oct – 21 Nov", body: "Reproductive organs",
      keywords: ["depth", "intensity", "transformation", "intimacy"],
      essence: "The alchemist. Scorpio goes beneath the surface to what is hidden, taboo and powerful — and is transformed by what it finds.",
      how: "intensely, privately and all-or-nothing",
      gifts: "emotional depth, insight and extraordinary resilience",
      shadow: "jealousy, control and holding grudges",
      sun: "You are here to transform. Identity is forged in depth, intimacy and crisis, and you have an instinct for what others try to hide. Your growth lies in trusting enough to let go of control.",
      moon: "The Moon is in fall here: feelings are intense, private and hard to shake. You need emotional honesty and deep loyalty to feel safe, and you rarely trust easily — but when you do, it is total.",
      rising: "You come across as magnetic, perceptive and hard to read. People sense your intensity even when you say little. Life takes you through repeated cycles of death and rebirth.",
      nn: "Your soul is learning to go deep. Leaving behind the comfort, possessions and predictability of the South Node in Taurus, growth comes from embracing change, merging with others and letting old structures die.",
      chiron: "The wound touches intimacy, trust and power — betrayal or loss that went deep. Healing comes as you accompany others through their own dark nights.",
    },
    sagittarius: {
      name: "Sagittarius", glyph: "♐" + VS, element: "fire", mode: "mutable", ruler: "jupiter", polarity: "yang", dates: "22 Nov – 21 Dec", body: "Hips & thighs",
      keywords: ["meaning", "freedom", "adventure", "faith"],
      essence: "The seeker. Sagittarius aims its arrow at the horizon — philosophy, travel, faith and the belief that life means something.",
      how: "expansively, optimistically and with a search for meaning",
      gifts: "optimism, vision and a generous love of truth",
      shadow: "restlessness, overpromising and preaching",
      sun: "You are here to seek meaning. You shine through exploration — of the world, of ideas, of belief — and you inspire others with your faith that things can be better. Your growth lies in honouring the details along the way.",
      moon: "You need freedom and a horizon to feel emotionally well. Feeling trapped is your greatest discomfort. You process feelings through movement, humour and big-picture perspective.",
      rising: "You come across as open, enthusiastic and frank. People experience you as fun and inspiring. Life keeps pulling you toward new places, teachers and philosophies.",
      nn: "Your soul is learning faith and perspective. Leaving behind the chatter, second-guessing and information overload of the South Node in Gemini, growth comes from trusting your intuition, finding your truth and living by it.",
      chiron: "The wound is around belief and meaning — a crisis of faith or a sense that life lacked purpose. Healing comes as you help others find their own truth.",
    },
    capricorn: {
      name: "Capricorn", glyph: "♑" + VS, element: "earth", mode: "cardinal", ruler: "saturn", polarity: "yin", dates: "22 Dec – 19 Jan", body: "Bones, knees & skin",
      keywords: ["ambition", "discipline", "mastery", "responsibility"],
      essence: "The architect. Capricorn climbs — it builds structures that outlast a lifetime and earns authority through time and effort.",
      how: "strategically, patiently and with an eye on the long game",
      gifts: "discipline, integrity and the ability to achieve real mastery",
      shadow: "coldness, pessimism and measuring worth by achievement",
      sun: "You are here to build and to lead with integrity. You shine through responsibility, effort and long-term goals, and you often grow younger as you age. Your growth lies in remembering that you are more than what you accomplish.",
      moon: "The Moon is in detriment here: you may have learned early to be self-sufficient and keep emotions contained. You feel safe when things are under control, and you show love through reliability and practical care.",
      rising: "You come across as capable, serious and mature beyond your years. People trust you with responsibility early. Life rewards patience and a slow, determined climb.",
      nn: "Your soul is learning maturity and authority. Leaving behind the dependence and emotional comfort-seeking of the South Node in Cancer, growth comes from taking responsibility, setting goals and stepping into a public role.",
      chiron: "The wound is around authority, achievement and the father — feeling that nothing was ever enough. Healing comes as you become a wise, humane authority for others.",
    },
    aquarius: {
      name: "Aquarius", glyph: "♒" + VS, element: "air", mode: "fixed", ruler: "uranus", tradRuler: "saturn", polarity: "yang", dates: "20 Jan – 18 Feb", body: "Ankles & circulation",
      keywords: ["originality", "community", "freedom", "vision"],
      essence: "The visionary. Aquarius steps back from the crowd to see the whole system — and imagines how it could work better for everyone.",
      how: "independently, inventively and on behalf of the collective",
      gifts: "originality, humanitarian ideals and clear-eyed objectivity",
      shadow: "detachment, contrarianism and rigid ideals",
      sun: "You are here to innovate and to belong to something bigger. You shine as the one who sees differently, and your identity is linked to friends, groups and future-facing ideals. Your growth lies in letting people close as well as far.",
      moon: "You need space and intellectual freedom to feel safe. You process emotions by stepping back and understanding them; too much emotional intensity can feel overwhelming. Friendship is emotional nourishment.",
      rising: "You come across as unusual, friendly and a little aloof. People notice your independence and originality. Life keeps asking you to be yourself, even when it sets you apart.",
      nn: "Your soul is learning to serve the collective. Leaving behind the need for applause and personal drama of the South Node in Leo, growth comes from teamwork, friendship and contributing your gifts to a larger vision.",
      chiron: "The wound is around belonging — feeling like an outsider or alien. Healing comes as you create community for everyone who never fit in.",
    },
    pisces: {
      name: "Pisces", glyph: "♓" + VS, element: "water", mode: "mutable", ruler: "neptune", tradRuler: "jupiter", polarity: "yin", dates: "19 Feb – 20 Mar", body: "Feet & lymphatic system",
      keywords: ["compassion", "imagination", "surrender", "spirit"],
      essence: "The mystic. The last sign dissolves boundaries — between self and other, dream and reality — and remembers that everything is connected.",
      how: "intuitively, compassionately and through imagination",
      gifts: "empathy, artistry and a deep spiritual sensitivity",
      shadow: "escapism, confusion and losing yourself in others",
      sun: "You are here to feel, imagine and connect with something larger than yourself. You shine through compassion, art and intuition. Your growth lies in building boundaries so your sensitivity becomes strength rather than overwhelm.",
      moon: "You absorb the feelings around you like a sponge. You need solitude, music, water and creative outlets to feel safe and to sort out which emotions are actually yours.",
      rising: "You come across as gentle, dreamy and hard to pin down. People confide in you. Life asks you to trust intuition and to protect your energy.",
      nn: "Your soul is learning surrender and faith. Leaving behind the perfectionism, worry and need for control of the South Node in Virgo, growth comes from trusting the flow, embracing compassion and making space for spirit and imagination.",
      chiron: "The wound feels spiritual or existential — boundless sensitivity, loss or a longing for something unnamed. Healing comes through compassion, art and spiritual practice.",
    },
  };

  const PLANETS = {
    sun: {
      name: "Sun", glyph: "☉" + VS, color: "#f3c86b", cycle: "1 year",
      keywords: ["identity", "vitality", "purpose", "ego"],
      lead: "Your core identity shines", focus: "your vitality and sense of purpose", core: "your identity",
      desc: "The Sun is the centre of the chart: conscious identity, life force and the path you are here to grow into. It shows how you shine and what makes you feel most alive.",
    },
    moon: {
      name: "Moon", glyph: "☽" + VS, color: "#cfd8ea", cycle: "27.3 days",
      keywords: ["emotions", "instinct", "needs", "memory"],
      lead: "Your emotional nature responds", focus: "your emotional needs and instincts", core: "your emotions",
      desc: "The Moon is your inner life — feelings, habits, instinctive reactions and what you need to feel safe. It also describes early nurturing and how you care for others.",
    },
    mercury: {
      name: "Mercury", glyph: "☿" + VS, color: "#7fd6cf", cycle: "88 days",
      keywords: ["mind", "communication", "learning", "perception"],
      lead: "Your mind works", focus: "your thinking and communication", core: "your mind",
      desc: "Mercury governs thought, speech, learning style and how you process information — the messenger between your inner world and everyone else.",
    },
    venus: {
      name: "Venus", glyph: "♀" + VS, color: "#eeaacb", cycle: "225 days",
      keywords: ["love", "beauty", "values", "pleasure"],
      lead: "You love and attract", focus: "your capacity for love, pleasure and value", core: "your heart",
      desc: "Venus shows what you find beautiful, how you love and want to be loved, your relationship to money and pleasure, and what you truly value.",
    },
    mars: {
      name: "Mars", glyph: "♂" + VS, color: "#f28b6d", cycle: "687 days",
      keywords: ["drive", "desire", "courage", "anger"],
      lead: "You pursue what you want", focus: "your drive, courage and desire", core: "your drive",
      desc: "Mars is your engine — how you assert yourself, pursue desire, handle anger and compete. It shows the kind of action that energises you.",
    },
    jupiter: {
      name: "Jupiter", glyph: "♃" + VS, color: "#f2b77c", cycle: "11.9 years",
      keywords: ["growth", "luck", "wisdom", "faith"],
      lead: "You grow and find meaning", focus: "your luck, faith and growth", core: "your faith",
      desc: "Jupiter expands whatever it touches. It shows where life is generous, where you find meaning and how you grow through belief, teaching and opportunity.",
    },
    saturn: {
      name: "Saturn", glyph: "♄" + VS, color: "#cdb98c", cycle: "29.5 years",
      keywords: ["discipline", "structure", "time", "mastery"],
      lead: "You build structure and meet your tests", focus: "your discipline, fears and lasting achievements", core: "your sense of responsibility",
      desc: "Saturn is the teacher: limits, responsibility, fear and the mastery that comes from facing them. Where Saturn sits, success comes late but lasts.",
    },
    uranus: {
      name: "Uranus", glyph: "♅" + VS, color: "#7dcaf2", cycle: "84 years",
      keywords: ["freedom", "innovation", "awakening", "disruption"],
      lead: "Your generation rebels and innovates", focus: "your need for freedom and change", core: "your need for freedom",
      desc: "Uranus brings sudden awakenings and the urge to break free. By sign it describes a generation; by house and aspect it shows where you are uniquely original.",
    },
    neptune: {
      name: "Neptune", glyph: "♆" + VS, color: "#93a8f6", cycle: "165 years",
      keywords: ["dreams", "spirit", "imagination", "illusion"],
      lead: "Your generation dreams and dissolves boundaries", focus: "your imagination, ideals and spiritual longing", core: "your ideals",
      desc: "Neptune is the dissolver: imagination, compassion, spirituality, and also illusion. By house it shows where you idealise — and where you must look clearly.",
    },
    pluto: {
      name: "Pluto", glyph: "♇" + VS, color: "#b695f2", cycle: "248 years",
      keywords: ["power", "transformation", "depth", "rebirth"],
      lead: "Your generation transforms", focus: "your power and capacity for transformation", core: "your deepest power",
      desc: "Pluto rules death and rebirth. It shows where life asks you to surrender control, face the shadow and emerge transformed — the soul's evolutionary engine.",
    },
    northNode: {
      name: "North Node", short: "N. Node", glyph: "☊" + VS, color: "#e9eef8", cycle: "18.6 years",
      keywords: ["destiny", "growth", "direction", "future"],
      focus: "your soul's growth direction", core: "your life direction",
      desc: "The North Node (Rahu) is the point where the Moon's orbit crosses the ecliptic heading north. It points toward unfamiliar territory your soul is growing into this lifetime.",
    },
    southNode: {
      name: "South Node", short: "S. Node", glyph: "☋" + VS, color: "#9aa6c4", cycle: "18.6 years",
      keywords: ["past", "gifts", "comfort zone", "release"],
      focus: "your inherited gifts and old habits", core: "your past patterns",
      desc: "The South Node (Ketu) is the karmic past — talents and habits already mastered. It is comfortable, but over-relying on it keeps you from growing.",
    },
    chiron: {
      name: "Chiron", glyph: "⚷" + VS, color: "#9fdbab", cycle: "50.7 years",
      keywords: ["wound", "healing", "wisdom", "mentor"],
      focus: "your deepest wound and healing wisdom", core: "your core wound",
      desc: "Chiron, the wounded healer, marks the place of an early, tender hurt that never fully closes — and the wisdom that lets you heal others through it.",
    },
    lilith: {
      name: "Lilith", glyph: "⚸" + VS, color: "#d98ac0", cycle: "8.85 years",
      keywords: ["shadow", "raw power", "rejection", "autonomy"],
      focus: "your untamed, unapologetic self", core: "your shadow self",
      desc: "Black Moon Lilith (the mean lunar apogee) marks exiled, rejected parts of the self — raw desire, anger and autonomy — that reclaim their power when owned.",
    },
    fortune: {
      name: "Part of Fortune", short: "Fortune", glyph: "⊗", color: "#f3d68b",
      keywords: ["luck", "ease", "prosperity", "joy"],
      focus: "your natural luck and ease", core: "your good fortune",
      desc: "The Part of Fortune blends Sun, Moon and Ascendant. It shows where happiness and material well-being come most naturally.",
    },
    ceres: {
      name: "Ceres", glyph: "⚳" + VS, color: "#c8d88c", cycle: "4.6 years",
      keywords: ["nurture", "self-care", "loss and return", "nourishment"],
      focus: "how you nurture and need to be nurtured", core: "your nurturing instinct",
      desc: "Ceres, the largest body in the asteroid belt, is the great mother of harvest and grief. She shows how you care for others, how you need to be cared for, and how you move through loss and return.",
    },
    pallas: {
      name: "Pallas", glyph: "⚴" + VS, color: "#9ec4ea", cycle: "4.6 years",
      keywords: ["wisdom", "strategy", "pattern recognition", "creative intelligence"],
      focus: "your strategic, pattern-seeing intelligence", core: "your creative intelligence",
      desc: "Pallas Athena is the warrior of wisdom. She shows how you see patterns, solve problems and fight for what is fair with your mind rather than force.",
    },
    juno: {
      name: "Juno", glyph: "⚵" + VS, color: "#eaa8c8", cycle: "4.4 years",
      keywords: ["commitment", "partnership", "loyalty", "equality"],
      focus: "what you need in committed partnership", core: "your need for committed partnership",
      desc: "Juno, the wife of Jupiter, rules committed partnership. She shows what you need to feel an equal in a long-term bond, and where issues of loyalty, jealousy and power arise.",
    },
    vesta: {
      name: "Vesta", glyph: "⚶" + VS, color: "#f1b37c", cycle: "3.6 years",
      keywords: ["devotion", "focus", "the sacred flame", "dedication"],
      focus: "what you devote yourself to", core: "your sacred focus",
      desc: "Vesta, keeper of the hearth flame, shows what you give yourself to wholeheartedly, where you need solitude to stay focused, and how you keep your inner fire alight.",
    },
    vertex: {
      name: "Vertex", glyph: "Vx", color: "#b8c3dd",
      keywords: ["fate", "encounters", "turning points"],
      focus: "fated encounters and turning points", core: "fated encounters",
      desc: "The Vertex, on the western side of the chart, is often active in fated meetings and turning points that feel beyond your control.",
    },
    asc: {
      name: "Ascendant", short: "ASC", glyph: "AC", color: "#ffffff",
      keywords: ["persona", "body", "approach"],
      focus: "your outward approach", core: "your outward self",
      desc: "The Ascendant is the sign rising on the eastern horizon at birth — your body, first impressions and the lens through which you meet life.",
    },
    mc: {
      name: "Midheaven", short: "MC", glyph: "MC", color: "#ffffff",
      keywords: ["career", "reputation", "calling"],
      focus: "your public direction", core: "your public path",
      desc: "The Midheaven is the highest point of the chart — vocation, reputation and the legacy you build in the world.",
    },
  };

  const HOUSES = [
    null,
    { title: "Self", areas: "identity, appearance and new beginnings", sign: "aries",
      desc: "The house of self: body, temperament and the way you begin things. Planets here are highly visible and colour your whole personality." },
    { title: "Resources", areas: "money, possessions and self-worth", sign: "taurus",
      desc: "The house of value: income, possessions, talents and your sense of what you are worth." },
    { title: "Communication", areas: "learning, siblings, neighbours and everyday exchange", sign: "gemini",
      desc: "The house of the mind in motion: early education, siblings, short trips, writing and conversation." },
    { title: "Home & Roots", areas: "home, family, ancestry and private life", sign: "cancer",
      desc: "The foundation of the chart: home, family, heritage and emotional roots. One of the karmic houses — it holds inherited family patterns." },
    { title: "Creativity", areas: "creativity, romance, children and play", sign: "leo",
      desc: "The house of joy: self-expression, romance, children, hobbies and risk-taking. What makes your heart come alive." },
    { title: "Health & Service", areas: "work routines, health and service", sign: "virgo",
      desc: "The house of daily life: work habits, health, service, pets and the craft of improving things." },
    { title: "Partnership", areas: "partnership, marriage and open adversaries", sign: "libra",
      desc: "The house of the other: committed partnerships, contracts and what you seek (or project) in a partner." },
    { title: "Transformation", areas: "intimacy, shared resources and transformation", sign: "scorpio",
      desc: "The house of merging: sex, shared money, inheritance, psychology, death and rebirth. A karmic house of deep bonds and power exchange." },
    { title: "Philosophy", areas: "higher learning, travel, belief and publishing", sign: "sagittarius",
      desc: "The house of the far horizon: higher education, philosophy, religion, long journeys and teaching." },
    { title: "Career", areas: "career, reputation and public standing", sign: "capricorn",
      desc: "The top of the chart: vocation, ambition, public image and authority figures. Planets here are what the world sees." },
    { title: "Community", areas: "friendships, groups and future hopes", sign: "aquarius",
      desc: "The house of the collective: friends, networks, causes and your hopes for the future." },
    { title: "The Unseen", areas: "solitude, the unconscious and spiritual life", sign: "pisces",
      desc: "The hidden house: dreams, retreat, the unconscious, hidden support and hidden enemies. The most karmic house — what is unresolved from the past lives here." },
  ];

  const ASPECTS = {
    conjunction: { name: "Conjunction", glyph: "☌" + VS, verb: "merges with", color: "#f3c86b",
      desc: "A conjunction (0°) fuses two energies into one. They act together — powerfully, and without much objectivity." },
    opposition: { name: "Opposition", glyph: "☍" + VS, verb: "is pulled against", color: "#f28b6d",
      desc: "An opposition (180°) sets two energies on either side of a seesaw. Awareness comes through relationship and learning to balance both." },
    trine: { name: "Trine", glyph: "△", verb: "flows easily with", color: "#7fb6f0",
      desc: "A trine (120°) is natural harmony — talent that comes so easily it can be taken for granted." },
    square: { name: "Square", glyph: "□", verb: "clashes with", color: "#f28b6d",
      desc: "A square (90°) is friction that demands action. It is uncomfortable, and it is where most of your drive and growth comes from." },
    sextile: { name: "Sextile", glyph: "⚹" + VS, verb: "supports", color: "#7fd6cf",
      desc: "A sextile (60°) is an opportunity. The energies cooperate well once you make the effort to use them." },
    quincunx: { name: "Quincunx", glyph: "⚻" + VS, verb: "has to adjust to", color: "#9fdbab",
      desc: "A quincunx (150°) links energies that have nothing in common. It asks for constant small adjustments and can feel like an itch." },
    semisextile: { name: "Semi-sextile", glyph: "⚺" + VS, verb: "gently nudges", color: "#8fb6cf",
      desc: "A semi-sextile (30°) connects neighbouring signs — a subtle growth link that needs conscious attention." },
    semisquare: { name: "Semi-square", glyph: "∠", verb: "irritates", color: "#e2a08b",
      desc: "A semi-square (45°) is a minor friction — a low-grade tension that prompts action." },
    sesquiquadrate: { name: "Sesquiquadrate", glyph: "⚼" + VS, verb: "unsettles", color: "#e2a08b",
      desc: "A sesquiquadrate (135°) is a minor stress aspect that tends to trigger sudden adjustments." },
    quintile: { name: "Quintile", glyph: "Q", verb: "inspires", color: "#c7a8f2",
      desc: "A quintile (72°) is a creative aspect of talent and style — a signature gift you develop with practice." },
    parallel: { name: "Parallel", glyph: "∥", verb: "is parallel to", color: "#e6c98f",
      desc: "A parallel means both planets sit at the same declination, the same distance north or south of the celestial equator. It works much like a conjunction: the two energies blend and strengthen each other." },
    contraparallel: { name: "Contra-parallel", glyph: "⋕", verb: "is contra-parallel to", color: "#e2a08b",
      desc: "A contra-parallel means the planets sit at equal declination on opposite sides of the celestial equator. It works much like an opposition: awareness through contrast and the need for balance." },
    biquintile: { name: "Bi-quintile", glyph: "bQ", verb: "sparks", color: "#c7a8f2",
      desc: "A bi-quintile (144°) is a subtle creative link that often shows in unusual talents." },
  };

  const NATURE = {
    harmony: "This is a supportive link — use it deliberately and it becomes one of your greatest assets.",
    tension: "This is a growth edge. Friction here pushes you to integrate two parts of yourself that do not naturally agree.",
    fusion: "These energies are inseparable in you; which way they express depends on the planets involved.",
    adjust: "Neither side understands the other, so life keeps asking for flexibility and fine-tuning.",
    creative: "A mark of personal talent and creative style.",
  };

  const DIGNITY = {
    domicile: "is in domicile — at home in this sign. Its qualities flow naturally and powerfully.",
    exaltation: "is exalted — an honoured guest in this sign. It expresses at its most refined.",
    detriment: "is in detriment — in the sign opposite its home. It has to work harder and often develops unusual strength.",
    fall: "is in fall — opposite its exaltation. Its expression can feel awkward until it is consciously developed.",
  };

  const CRITICAL = {
    anaretic: "At 29° — the anaretic degree. There is urgency and a sense of completion here: lessons of this sign culminate, and mastery feels required rather than optional. Often considered a karmic degree.",
    initial: "At 0° — a fresh, raw expression of the sign, pure and a little untested.",
    critical: "On a critical degree for its modality, adding emphasis and intensity to this placement.",
  };

  const ELEMENTS = {
    fire: { name: "Fire", color: "#f28b6d", strong: "Enthusiasm, courage and inspiration drive you. You act on faith and energise others.", weak: "You may struggle to find motivation or spontaneity; enthusiasm is built through doing, not waiting." },
    earth: { name: "Earth", color: "#a8d49a", strong: "You are practical, grounded and reliable. You need results you can touch.", weak: "Practical matters, the body and routines may feel foreign; grounding habits help you thrive." },
    air: { name: "Air", color: "#f1d37e", strong: "You live through ideas, words and connection. Objectivity is your gift.", weak: "You may feel before you can explain; learning to step back and name experience brings clarity." },
    water: { name: "Water", color: "#7fb6f0", strong: "Emotion, intuition and empathy guide you. You understand what is unspoken.", weak: "Feelings may be hard to access or express; emotional literacy is a lifelong gift you can develop." },
  };
  const MODES = {
    cardinal: { name: "Cardinal", strong: "You are an initiator — quick to start, lead and change direction.", weak: "Starting may be harder than sustaining; practise taking the first step." },
    fixed: { name: "Fixed", strong: "You are a stabiliser — loyal, determined and able to see things through.", weak: "Commitment and follow-through may need conscious effort." },
    mutable: { name: "Mutable", strong: "You are an adapter — flexible, curious and good at transitions.", weak: "Change may feel threatening; flexibility is a muscle you can build." },
  };

  const PATTERNS = {
    grandTrine: { name: "Grand Trine", desc: "Three planets form an equilateral triangle of trines — a closed circuit of natural talent and ease. It is protective and gifted, but can breed complacency unless consciously put to work." },
    tSquare: { name: "T-Square", desc: "Two planets in opposition both square a third, the apex. The apex planet is a pressure point and a source of tremendous drive: this is where you are pushed to act." },
    grandCross: { name: "Grand Cross", desc: "Four planets locked in two oppositions and four squares. Strength and stamina are built through constant, many-sided challenge." },
    yod: { name: "Yod · Finger of God", desc: "Two planets in sextile both quincunx a third, the apex. Traditionally a karmic, fated configuration: the apex planet points to a special mission that requires ongoing adjustment." },
    stellium: { name: "Stellium", desc: "Three or more planets clustered in one sign or house concentrate life energy there — an area of intense focus and experience." },
  };

  const MOON_PHASES = [
    { name: "New Moon", from: 0, desc: "Born at the new moon: instinctive, subjective and future-oriented. You are here to start something new and project yourself into life." },
    { name: "Crescent", from: 45, desc: "Born in the crescent phase: you push forward against the pull of the past, building something with determination." },
    { name: "First Quarter", from: 90, desc: "Born at the first quarter: a crisis-in-action personality. You thrive on challenge and on building strong structures." },
    { name: "Gibbous", from: 135, desc: "Born in the gibbous phase: you are a refiner and analyst, driven to perfect and to find meaning." },
    { name: "Full Moon", from: 180, desc: "Born at the full moon: relationship-oriented and highly aware. Life brings illumination through others and fulfilment of purpose." },
    { name: "Disseminating", from: 225, desc: "Born in the disseminating phase: a teacher and communicator who shares what has been learned." },
    { name: "Last Quarter", from: 270, desc: "Born at the last quarter: a crisis-in-consciousness personality — you reorient values and quietly lead change." },
    { name: "Balsamic", from: 315, desc: "Born in the balsamic phase: a prophetic, old-soul energy. You complete cycles and prepare the seeds of the future. Often considered a karmic birth." },
  ];

  const RETRO_KARMIC = {
    mercury: "Mercury retrograde: thinking is internal and reflective. Karmically, you may be revisiting how you speak truth — ideas mature slowly but deeply.",
    venus: "Venus retrograde: love and values are re-examined from the inside. Karmic relationships and old-soul standards of beauty and worth are common themes.",
    mars: "Mars retrograde: drive and anger turn inward. You may be re-learning how to act on desire without repeating past-life battles.",
    jupiter: "Jupiter retrograde: faith is personal rather than borrowed. You grow by developing your own philosophy.",
    saturn: "Saturn retrograde: you are your own harshest authority. Karmic duties feel internal; mastery comes through self-discipline, not outside approval.",
    uranus: "Uranus retrograde: rebellion is inner and quiet — freedom is found through inner awakening.",
    neptune: "Neptune retrograde: spiritual sensitivity is turned inward, with strong inner visions and a need to discern illusion.",
    pluto: "Pluto retrograde: transformation happens deep inside — you are revisiting old themes of power and control from a past cycle.",
    chiron: "Chiron retrograde: the wound is worked through privately, and healing is found by looking within.",
  };

  const HOUSE_NODE = [
    null,
    "North Node in the 1st house: your destiny is to become your own person — to act, lead and put yourself first. The South Node in the 7th shows past lives lived through partners.",
    "North Node in the 2nd house: growth comes from building your own values, income and self-worth. The South Node in the 8th leans on other people's resources and intensity.",
    "North Node in the 3rd house: growth comes through curiosity, local connection, learning and communicating clearly. The South Node in the 9th already knows the big truths — now listen.",
    "North Node in the 4th house: your path leads inward to home, family and emotional foundations. The South Node in the 10th has already climbed the career ladder.",
    "North Node in the 5th house: your destiny is creative self-expression, romance and joy. The South Node in the 11th is used to blending into the group.",
    "North Node in the 6th house: growth comes through daily practice, health and humble service. The South Node in the 12th wants to escape into the spiritual or the dreamlike.",
    "North Node in the 7th house: your destiny unfolds through partnership and collaboration. The South Node in the 1st knows independence very well already.",
    "North Node in the 8th house: growth comes through intimacy, shared resources and transformation. The South Node in the 2nd clings to comfort and self-sufficiency.",
    "North Node in the 9th house: your path is to seek meaning, travel, study and trust your own truth. The South Node in the 3rd is lost in details and other people's opinions.",
    "North Node in the 10th house: your destiny is public — a vocation and a visible role in the world. The South Node in the 4th is comfortable at home and in the family.",
    "North Node in the 11th house: growth comes through community, friendship and a shared vision. The South Node in the 5th is used to being the star.",
    "North Node in the 12th house: your path is spiritual — surrender, compassion and inner work. The South Node in the 6th tries to control life through order and busyness.",
  ];

  const HOUSE_SYSTEMS = {
    placidus: "Placidus", koch: "Koch", regiomontanus: "Regiomontanus", porphyry: "Porphyry", equal: "Equal", whole: "Whole Sign",
    topocentric: "Topocentric", campanus: "Campanus",
  };

  global.AstroContent = {
    SIGNS, PLANETS, HOUSES, ASPECTS, NATURE, DIGNITY, CRITICAL, ELEMENTS, MODES, PATTERNS, MOON_PHASES, RETRO_KARMIC, HOUSE_NODE, HOUSE_SYSTEMS,
  };
})(typeof window !== "undefined" ? window : globalThis);
