/* Readings for aspect patterns, the Part of Fortune and the Vertex. */
window.AstroDeep = window.AstroDeep || {};

window.AstroDeep.patterns = {
  grandTrine: {
    text: "A grand trine links three planets in the same element, each one supporting the other two, so energy flows round the circuit without friction. Living with it feels like having a room in yourself where things simply work. Talents arrive early, certain moods come easily, and they are easy to overlook as gifts because they have never cost you anything.\n\nThat ease is also the catch. A closed loop can become self-contained, circling comfortably without ever reaching outward, and you may drift toward what feels pleasant rather than what stretches you. People sometimes see enormous potential in you and wonder why you do not use more of it. The pattern comes alive when something in your life, often a harder aspect elsewhere in the chart, gives it a reason to leave the room and put that natural flow to work.",
    focal: "Read the element first, since fire, earth, air or water tells you what kind of ease you have. Then look at which planets form it: with the Sun or Moon involved the gift sits at the core of your identity or emotional life, while outer planets make it feel more like a generational or intuitive talent.",
    gifts: ["Natural, unforced talent", "Emotional self-sufficiency", "Resilience that recovers quickly"],
    challenges: ["Complacency", "Taking gifts for granted", "A closed circuit that resists input"],
    growth: "In youth the grand trine often feels like luck. Over time it matures into something you deliberately offer, as you learn that ease is a resource to spend on purpose rather than a place to rest."
  },
  tSquare: {
    text: "A T-square forms when two planets oppose each other and both square a third, the apex. It is one of the most dynamic patterns in a chart, and living with it can feel like being permanently under construction. The opposition sets up a tug of war, and all that tension pours into the apex planet, which becomes the pressure point where you keep acting, pushing and reacting.\n\nYou are rarely idle with a T-square. It drives ambition, persistence and a stubborn refusal to give up, and many people with strong achievements carry one. The strain shows when the same crisis seems to replay in new costumes. Learning the pattern means noticing that the apex is not the problem: it is the outlet. Once you channel it consciously, the friction becomes fuel instead of fire damage.",
    focal: "The apex planet shows where the pressure lands and what you are pushed to develop. An apex Mars pushes you toward action and conflict, an apex Saturn toward responsibility and structure, an apex Moon toward emotional reactivity that slowly becomes emotional strength.",
    gifts: ["Drive and stamina", "Problem-solving under pressure", "Hard-won competence"],
    challenges: ["Recurring crises", "Overcompensation at the apex", "Chronic inner tension"],
    growth: "Early on the T-square tends to erupt through the apex planet in clumsy or excessive ways. With experience you learn to use the empty point opposite the apex, the missing leg, as a release valve, and the pattern becomes a powerful engine for achievement."
  },
  grandCross: {
    text: "A grand cross joins four planets in two oppositions and four squares, usually all in the same modality. It is a heavy, load-bearing pattern. It feels like being pulled in four directions at once, with every move in one area creating pressure somewhere else, and there is no easy exit because the cross has no open side to release through.\n\nThat can make life feel like a series of demands that never quite resolve. Yet people with a grand cross are often remarkably steady once they have found their footing. You learn to hold complexity that would flatten someone else, and your strength becomes the ability to stand in the middle of competing claims without collapsing. The modality matters: cardinal crosses meet life through initiative, fixed crosses through endurance, mutable crosses through adaptation.",
    focal: "Look at the four planets as four voices at the same table. When a personal planet like the Sun, Moon or Venus is involved, the tension runs through your daily sense of self; when the cross is mostly outer planets, it tends to feel like wider forces you are asked to carry.",
    gifts: ["Enormous resilience", "Capacity to hold complexity", "Determined, grounded strength"],
    challenges: ["Feeling stuck or trapped", "Overwhelm from competing demands", "Exhaustion"],
    growth: "The grand cross rarely softens, but you get better at carrying it. Midlife often brings the realisation that balance comes from rotating attention between all four points rather than trying to satisfy them at once."
  },
  yod: {
    text: "A yod forms when two planets sextile each other and both make a quincunx to a third, creating a long narrow triangle sometimes called the finger of fate. It carries an awkward, restless quality. The quincunx links planets that share nothing natural, so the adjustments it asks for never feel quite finished.\n\nPeople with a yod often report a sense of special purpose that they cannot fully explain, along with a feeling of being slightly out of step with others. Life may seem to redirect you at key moments, closing one door so firmly that you are nudged toward another. It can be uncomfortable not knowing exactly what you are for. Over time, though, the pattern tends to reveal a distinctive role that uses the odd combination of skills only you seem to have.",
    focal: "The apex planet is the point the finger aims at, and it shows the task you are being refined for. An apex Venus might point toward a calling in beauty or relating, an apex Mercury toward teaching or writing, and the house it occupies shows where that calling plays out.",
    gifts: ["A sense of mission", "Unusual combinations of skill", "Adaptability through adjustment"],
    challenges: ["Feeling misplaced", "Health or stress linked to strain", "Uncertainty about direction"],
    growth: "The yod often makes little sense until later in life, when the detours start forming a pattern. Its maturity comes from accepting that your path is meant to be unusual and treating each forced adjustment as part of the design."
  },
  stellium: {
    text: "A stellium is a cluster of three or more planets gathered in one sign or house. It concentrates a great deal of energy in one place, so that part of life becomes the centre of gravity for your whole personality. Others notice it quickly, even when you do not, because it colours everything you do.\n\nThe benefit is depth. You can pour yourself into one theme with focus and staying power that more scattered charts lack, and you often develop real mastery there. The cost is imbalance. Areas of life outside the cluster may feel underfed or unfamiliar, and you can overidentify with one role until it squeezes out the rest. A stellium asks you to own that intensity while deliberately building bridges to the parts of the chart that sit quieter.",
    focal: "The sign of the stellium describes your style, the flavour that saturates your character, while the house shows the arena where your energy keeps gathering. A stellium in Virgo in the tenth house, for example, points to a methodical temperament aimed squarely at career and reputation.",
    gifts: ["Concentrated focus", "Depth and mastery", "A strong, recognisable identity"],
    challenges: ["Lopsided priorities", "Overidentification with one theme", "Neglected areas of life"],
    growth: "A young stellium can feel all-consuming. With age it usually settles into a trusted specialism, and the work shifts toward rounding out the rest of your life so that the concentration serves you instead of confining you."
  }
};

window.AstroDeep.fortune = {
  signs: {
    aries: "With the Part of Fortune in Aries, joy comes when you take the first step before anyone else. You prosper by acting on instinct, starting fresh projects and trusting your own courage. Waiting for permission drains your luck, while bold, honest initiative tends to open doors. Physical activity, competition and a sense of personal challenge all bring out your natural buoyancy. You are happiest when you feel free, direct and slightly ahead of the pack.",
    taurus: "Your Part of Fortune in Taurus finds happiness in the tangible: good food, comfortable surroundings, nature and steady progress you can measure. Prosperity grows slowly and reliably for you when you build on solid ground and resist the urge to rush. Pleasure is not a distraction here but a genuine source of wellbeing. Tending a garden, saving patiently or crafting something with your hands can restore you like nothing else.",
    gemini: "In Gemini, the Part of Fortune shines through conversation, curiosity and variety. You feel most at ease when you are learning, connecting ideas and swapping stories with people. Luck often travels to you through messages, short trips, siblings, neighbours and chance meetings. Boredom is your real enemy. Let yourself follow interesting threads, since many of your best opportunities begin as a casual chat or a question you could not leave alone.",
    cancer: "When the Part of Fortune sits in Cancer, contentment comes from belonging. Home, family and the people you care for are where you feel most yourself, and nurturing others tends to bring good things back to you. Prosperity often grows through property, food, caregiving or anything that helps people feel safe. Trust your emotional instincts, because your gut read of a situation is usually a reliable guide to where your luck lies.",
    leo: "A Leo Part of Fortune finds joy in self-expression and wholehearted play. You come alive when you are creating, performing, leading or simply being generous with your warmth. Recognition feeds you, and that is nothing to be ashamed of. Prosperity follows when you put your personal stamp on things instead of blending in. Children, romance, art and celebration are all places where life feels effortlessly good to you.",
    virgo: "Your Part of Fortune in Virgo delights in being useful. Ease arrives through craft, routine and the quiet satisfaction of doing something well. Improving a system, helping someone solve a practical problem or caring for your health can lift your mood more than grand gestures. Prosperity grows through skill, attention to detail and service. Small, consistent habits are your hidden source of luck, so give them the respect they deserve.",
    libra: "With the Part of Fortune in Libra, happiness flows through partnership, beauty and fairness. You feel at your best when relationships are balanced and your surroundings are harmonious. Collaboration tends to bring more luck than going it alone, and your gift for diplomacy can open doors that force never would. Art, design, music and good company restore you. Prosperity often comes through contracts, alliances and people who appreciate your grace.",
    scorpio: "Placed in Scorpio, the Part of Fortune finds its reward in depth. Surface-level living leaves you flat; real contentment comes from intimacy, research, transformation and getting to the truth of things. You may prosper through shared resources, investments, healing work or psychology. Crises that frighten others can bring out your best. Your luck strengthens every time you let go of something outgrown and trust what emerges in its place.",
    sagittarius: "A Sagittarius Part of Fortune thrives on horizons. Travel, study, philosophy and big-picture thinking make you feel expansive and alive. Luck tends to find you when you say yes to adventure and follow your curiosity across borders, literal or intellectual. Teaching, publishing and cross-cultural connections can all be sources of prosperity. Optimism is not naive for you: it is genuinely one of the ways your life works out well.",
    capricorn: "Your Part of Fortune in Capricorn finds satisfaction in achievement you have earned. Joy comes from setting a long-term goal, working toward it steadily and seeing a structure rise because of your effort. You prosper through responsibility, discipline and a reputation built over time. Recognition often comes later rather than early, but it lasts. Respecting your ambition, rather than downplaying it, is a key part of your wellbeing.",
    aquarius: "In Aquarius, the Part of Fortune rewards individuality and community in the same breath. You feel happiest when you are free to think differently and connect with people who share your ideals. Luck often arrives through friendships, groups, networks and forward-looking ideas. Technology, innovation and social causes may all prosper for you. The more fully you accept your own strangeness, the more good fortune seems to find you.",
    pisces: "A Pisces Part of Fortune finds peace in imagination, compassion and surrender. You feel most at ease when you let yourself drift into music, art, water, meditation or quiet service. Your intuition is a genuine source of luck, often guiding you better than logic. Prosperity can flow through creative, spiritual or healing work. Solitude restores you, and trusting the invisible current of your life tends to bring the right things at the right time."
  },
  houses: {
    1: "The Part of Fortune in the first house places your luck right in your own presence. People respond to you readily, and prosperity often follows your personal initiative and the way you carry yourself. You thrive when you act as yourself rather than as someone's idea of you. Physical vitality, a strong first impression and trust in your own instincts are all channels for your good fortune.",
    2: "In the second house, the Part of Fortune links happiness with resources and self-worth. You tend to have a knack for earning, saving and understanding value, and financial security brings you real contentment. Your talents are marketable, and recognising what you are good at is part of the gift. Enjoying physical comforts, without guilt, helps you feel grounded and fortunate.",
    3: "A third house Part of Fortune finds ease in communication and learning. Writing, speaking, teaching, networking and quick local travel can all bring luck your way. Siblings, neighbours and everyday contacts may open unexpected doors. You feel happiest when your mind is busy and your days hold variety. Sharing information is not just a skill for you but a genuine source of prosperity.",
    4: "With the Part of Fortune in the fourth house, contentment is rooted at home. A secure base, close family ties and a sense of belonging are what make you feel prosperous. Property, family businesses or ancestral connections can be lucky areas. Your life often grows easier and more fulfilling in later years. Time spent creating a nest you love is one of the best investments you can make.",
    5: "The fifth house Part of Fortune brings joy through creativity, romance and play. You prosper when you give yourself room to have fun, make things and express your heart openly. Children, hobbies, performance and speculative ventures can all carry luck. Taking life too seriously dims your spark. When you follow what delights you, good fortune tends to follow close behind.",
    6: "In the sixth house, the Part of Fortune finds happiness in work and wellbeing. Daily routines, a job you find meaningful and a healthy body give you a deep sense of ease. You often prosper through service, skilled labour or health-related fields. Colleagues and pets may bring small, steady joys. Getting the everyday details right is where your luck quietly builds.",
    7: "A seventh house Part of Fortune shines through partnership. Marriage, business partners and close one-to-one relationships tend to bring luck and opportunity. You feel happiest when you are sharing life with someone who complements you. Negotiation, counselling and client work can be fruitful. The people you choose to stand beside you matter enormously, so choose with care and generosity. Your luck grows when you let yourself be supported.",
    8: "The Part of Fortune in the eighth house finds its reward in depth and shared resources. You may benefit through investments, inheritance, a partner's money or work involving other people's assets. Emotional intimacy and psychological insight bring real satisfaction. Crises tend to transform you for the better. Letting go and trusting the process of renewal is one of your most reliable sources of luck.",
    9: "With the Part of Fortune in the ninth house, prosperity comes through expansion. Travel, higher education, foreign cultures, publishing and spiritual exploration all feel lucky for you. You are happiest when you are learning something that broadens your worldview. Mentors and teachers can open significant doors. Following a sense of meaning, rather than mere security, tends to bring the best results.",
    10: "A tenth house Part of Fortune places your luck in career and public life. Recognition, achievement and a clear sense of direction make you feel at your best. Authority figures often help you, and your reputation can become a real asset. You prosper by stepping into visible roles. Choosing a vocation that reflects who you truly are brings both success and contentment.",
    11: "In the eleventh house, the Part of Fortune finds joy through friendship and shared dreams. Groups, communities, networks and like-minded allies bring you luck and opportunity. Your hopes for the future tend to have real momentum. Collaboration on a cause you believe in feels deeply satisfying. Many of your best breaks come through a friend of a friend or an organisation you belong to.",
    12: "The Part of Fortune in the twelfth house finds peace behind the scenes. Solitude, reflection, spiritual practice and quiet service restore you. You may prosper through work in hospitals, retreats, research or the arts, or anywhere that asks for compassion without fanfare. Hidden help often arrives when you need it. Trusting your inner life, and giving it time, is the key to your contentment."
  }
};

window.AstroDeep.vertex = {
  signs: {
    aries: "A Vertex in Aries brings fated encounters that demand courage. The people who change your life tend to arrive suddenly and challenge you to act, stand up for yourself or begin something new. Turning points often feel like a spark catching: fast, bold and impossible to ignore. These meetings teach you to assert your needs and trust your own will, even when you would rather wait.",
    taurus: "With the Vertex in Taurus, destiny often arrives through matters of value, stability and the body. Significant people may show you what you truly treasure or shake up your sense of security. Turning points can involve money, land, possessions or a slow but decisive change in what you consider worth keeping. These encounters teach patience and a deeper appreciation of what sustains you.",
    gemini: "A Gemini Vertex brings fateful meetings through words and ideas. A conversation, a letter, a chance remark or a sibling's influence might redirect your life. Turning points often arrive as information: news that changes your plans or a person whose way of thinking rewires your own. These encounters invite you to stay curious and listen closely, because destiny tends to speak rather than shout.",
    cancer: "When the Vertex falls in Cancer, fated encounters touch on home, family and emotional safety. You may meet people who feel instantly familiar, as though you have known them before. Turning points often involve moving house, starting a family or healing an old family pattern. These connections ask you to open your heart and discover what real belonging means to you.",
    leo: "A Vertex in Leo draws significant people who call out your creativity and heart. Romance, children or a stage of some kind can become the setting for destiny. Turning points often arrive when someone recognises your talent or asks you to step into the spotlight. These encounters teach you to shine without apology and to love generously, even when it feels exposing.",
    virgo: "With the Vertex in Virgo, destiny often arrives through work, health or service. A colleague, a mentor in a practical craft or a health challenge can redirect your path. Turning points tend to feel humble but profound, reshaping your daily habits and sense of purpose. These encounters teach you the value of competence and the quiet power of being genuinely useful.",
    libra: "A Libra Vertex brings fated meetings through partnership. Significant relationships, whether romantic, creative or professional, often arrive with a sense of inevitability. Turning points frequently involve commitment, separation or learning to share decisions. These encounters mirror you back to yourself and teach balance: how to stay true to your own values while meeting someone else halfway. The right partner arrives when you stop performing agreeableness.",
    scorpio: "With the Vertex in Scorpio, fated encounters are intense and transformative. People who enter your life this way often stir deep emotions, power struggles or profound intimacy. Turning points may involve loss, shared finances or a crisis that strips something away. These meetings rarely leave you unchanged. They teach you to face what is hidden and trust your capacity to be reborn.",
    sagittarius: "A Sagittarius Vertex brings destiny through travel, learning and belief. Life-changing people may come from another culture, a university, a spiritual path or a journey abroad. Turning points often expand your worldview in a single stroke. These encounters teach you to follow meaning and to hold your truths with an open hand, because your beliefs are meant to grow over time.",
    capricorn: "When the Vertex sits in Capricorn, fateful meetings often involve authority, career and responsibility. An employer, elder or mentor may appear at a decisive moment and set your path in a new direction. Turning points tend to arrive as serious commitments or tests of maturity. These encounters teach you to build something lasting and to carry weight without losing yourself.",
    aquarius: "An Aquarius Vertex brings destiny through friendship, community and sudden insight. Significant people often arrive through groups, causes or unusual circumstances and may seem ahead of their time. Turning points can feel like lightning: unexpected, liberating and a little disruptive. These encounters teach you to value your individuality and to find the people who share your vision of the future.",
    pisces: "With the Vertex in Pisces, fated encounters carry a dreamy, almost otherworldly quality. You may meet people through art, spirituality, healing or moments of vulnerability. Turning points often involve surrender, compassion or letting go of control. These connections can feel mysterious, sometimes confusing, but they teach you to trust intuition and recognise grace when it arrives. Not every meeting needs a practical explanation to matter."
  },
  houses: {
    1: "The Vertex in the first house suggests that encounters reshape how you see yourself and how you present to the world. Other people may appear at key moments and draw out qualities you did not know you had. Turning points often change your appearance, identity or personal direction. Your destiny is tied to becoming more fully and visibly yourself. Hiding tends to delay these meetings rather than prevent them.",
    2: "In the second house, the Vertex links fated meetings with money, possessions and self-worth. Someone may enter your life and change your finances, your values or your sense of what you deserve. Turning points often involve earning, losing or rethinking resources. These experiences teach you what real security looks like, and it may not be what you expected. Your sense of worth is often the real currency being traded.",
    3: "A third house Vertex brings turning points through communication, study and your immediate surroundings. A neighbour, sibling, teacher or passing conversation could set your life on a new course. Writing, speaking or short journeys may become the setting for destiny. Pay attention to messages that arrive unexpectedly, as they often carry more weight than they first appear to. A single sentence, heard at the right time, can alter years of your life.",
    4: "With the Vertex in the fourth house, fated encounters centre on home and family. A move, a family event or a meeting with someone who feels like kin can be pivotal. Turning points may involve your roots, ancestry or the private foundation of your life. These experiences teach you where you truly belong and what kind of home you need to build.",
    5: "The Vertex in the fifth house often brings destined romance and creative awakening. A love affair, a child or a creative collaboration can mark a significant turning point. Encounters here tend to be joyful, dramatic and heart-opening. They teach you to take risks for love and self-expression, and to let pleasure be part of your purpose rather than a distraction from it.",
    6: "In the sixth house, the Vertex brings fateful meetings through work, health and daily life. A colleague, employee, doctor or practitioner might change your direction. Turning points often come through a new job, a shift in routine or a health matter that redefines your priorities. These encounters teach you that meaningful change can begin in the most ordinary places. Your destiny may walk in on an unremarkable Tuesday.",
    7: "A seventh house Vertex is one of its most classic placements, pointing to fated partnerships. Marriage, business alliances and significant one-to-one relationships often arrive with an unmistakable sense of destiny. Turning points tend to come through other people rather than solo decisions. These encounters show you who you are in relationship and what you are learning through committed connection. You rarely find yourself by standing entirely alone.",
    8: "With the Vertex in the eighth house, destiny arrives through intimacy, crisis and transformation. Relationships may begin with an intense, magnetic pull, or a shared financial matter might change your life. Turning points can involve inheritance, loss, sexuality or deep psychological change. These experiences teach you to let go, to trust, and to discover your own resilience. What you share with another person changes you at the root.",
    9: "The Vertex in the ninth house brings turning points through travel, education and philosophy. A foreign journey, a teacher, a book or a spiritual encounter can open a new chapter. People from different backgrounds often play a pivotal role. These experiences expand your horizons and teach you to seek meaning beyond what you grew up with. Some of your most important teachers will speak a different language, literally or otherwise.",
    10: "In the tenth house, the Vertex links fated encounters with career and public standing. A boss, mentor or influential contact may arrive at just the right moment to redirect your professional path. Turning points often involve promotions, public recognition or a calling you cannot ignore. These experiences shape your reputation and your sense of what you are here to contribute.",
    11: "An eleventh house Vertex brings destiny through friends, groups and shared ideals. A community, organisation or network can be the stage for key meetings. Turning points often involve changing social circles or committing to a cause. These encounters teach you where you fit in the wider world and how your hopes connect with those of others. A shared purpose can bring you the people you have been waiting to meet.",
    12: "With the Vertex in the twelfth house, fated encounters tend to unfold quietly or behind the scenes. You may meet significant people in hospitals, retreats, spiritual settings or through secret or private circumstances. Turning points often involve solitude, endings or inner revelation. These experiences teach you to trust the unseen and to find strength in surrender. What is decided in private often shapes everything that follows in public."
  }
};
