/* Deep sign interpretations: overview, Venus, Descendant, MC, IC, 2nd cusp, growth, Saturn, Lilith, South/North Node */
window.AstroDeep = window.AstroDeep || {};
window.AstroDeep.signs = {
  aries: {
    overview: "Aries opens the zodiac, and it carries the raw charge of beginnings. As a cardinal fire sign ruled by Mars, it moves first and thinks on the way. You tend to feel most alive when something is at stake: a new project, a physical challenge, a problem nobody else wants to touch. Courage comes naturally, and so does impatience. Aries energy is honest to the point of bluntness; if you are annoyed, people usually know within seconds, and the anger tends to burn out just as fast. Underneath the drive is a simple need to feel that you exist as a separate, capable person. Competition sharpens you, while routine can make you restless and snappy. At its best, Aries gives others permission to act, showing them that the first brave step often matters more than the perfect plan.",
    love: "With Venus in Aries you love with heat and directness. Attraction tends to hit quickly, and you would rather make the first move than wait to be chosen. The chase itself can be part of the pleasure. You want a partner who can match your spirit, argue back without sulking and keep some independence of their own. Feeling smothered or managed cools your interest fast, while playful rivalry keeps it alive.",
    partner: "With Aries on your Descendant, you are often drawn to people who seem bold, decisive and a little combative. They tend to act out the assertiveness you are still learning to own. You may read partners as selfish when they are simply asking for what they want. Relationships grow when conflict is allowed to be clean and honest, and when you claim some of that fire yourself.",
    career: "Aries on the Midheaven suits work where you lead, launch or compete. Entrepreneurship, emergency services, sport, surgery, sales and any role that rewards initiative can fit well. You are often seen as a self-starter who gets things moving when others stall. Recognition tends to come from being first, or from taking a risk others avoided. Long stretches under a slow hierarchy can wear down your motivation.",
    home: "With Aries on the IC, early home life may have been lively, noisy or marked by lessons in standing up for yourself. Many people with this placement learned independence young. As an adult you often want a base that supports action: room to move, a shed or spare room full of projects, and the freedom to come and go.",
    money: "Aries on the 2nd house cusp tends to earn through initiative, and it can spend just as quickly. You may prefer building income through your own efforts to waiting on anyone else. Impulse purchases are a known weak spot. Your sense of worth often rises when you take a bold step and see a direct, visible result.",
    growth: "The Aries growth edge is learning to pause long enough to consider other people and to finish what you start. Speed is a gift, and so is follow-through. When patience sits alongside courage, your initiatives tend to last longer, and people begin to trust you with bigger and more lasting responsibilities.",
    saturn: "Saturn in Aries tests your right to act on your own behalf. Early on, you may have hesitated to assert yourself, or sensed that anger and ambition were dangerous things to show. Sometimes the pattern flips into forcing things through with rigid will. The lesson is disciplined courage: acting decisively without recklessness, and leading without needing to win every round. Over time this builds a steady, earned confidence that others come to rely on.",
    lilith: "Lilith in Aries points to anger, ambition and raw self-interest that were shamed early, perhaps labelled selfish or aggressive. Suppressed, this energy tends to erupt as sudden rage, reckless risk-taking or cold defiance over small things. You may also swing into passivity and quietly resent those who take what they want. Owned, this placement becomes fierce autonomy: the ability to say no, to fight cleanly and to put yourself first without apology.",
    southNode: "Symbolically, a South Node in Aries suggests a past self who lived by the sword or the frontier: a warrior, scout or settler who survived by acting alone and trusting instinct. That self may have learned that hesitation was dangerous and that no one would come to help. The mastery lingers as quick reflexes, physical courage and a knack for handling crisis. The habit that follows you now is going it alone, reacting before listening and treating relationships as a contest. The old self knew how to fight. The present life asks you to learn how to partner.",
    northNodeSteps: [
      "Make one decision this week without polling friends first, then notice how it feels afterwards.",
      "Name your own preference early in conversations, before adjusting to what others seem to want.",
      "Start a small solo project that belongs only to you, and let it be imperfect."
    ],
    strengths: ["Natural courage", "Quick decisive action", "Honest directness", "Infectious enthusiasm"],
    challenges: ["Impatience with process", "Quick temper", "Starting without finishing", "Overlooking others' needs"]
  },

  taurus: {
    overview: "Taurus is fixed earth, ruled by Venus, and it knows that good things take time. Where Aries sparks, Taurus settles in and builds. You tend to trust what you can touch, taste and count, and you judge people by what they keep doing over months. Comfort matters, and so does beauty: good bread, soft wool, a garden that rewards patience. This sign has remarkable staying power once committed, and a calm presence that steadies others in a crisis. The same steadiness can harden into stubbornness, especially when change is imposed from outside. Security is the core motivation, both material and emotional. When you feel grounded, you are generous, sensual and deeply loyal, and your quiet persistence often outlasts flashier talent by years.",
    love: "Venus in Taurus loves slowly and for keeps. You tend to show affection through touch, food, shared routines and steady presence. Trust builds over time, and once it forms you are deeply loyal. You want to be loved in ways you can feel: physical closeness, reliability, small daily comforts. Games, sudden changes of heart and flaky plans can make you withdraw quietly, and sometimes for good.",
    partner: "Taurus on the Descendant draws you to partners who seem calm, sensual and financially or emotionally steady. They may carry the patience and groundedness you are still growing into. You can project stubbornness onto them, or lean on them for all your security. The healthiest bonds grow slowly and include shared pleasures, clear agreements and a real sense of comfort together.",
    career: "With Taurus on the Midheaven, you are often seen as dependable and competent. Work that builds something tangible or lasting tends to suit you: finance, property, food, design, horticulture, craft, music or work with the voice. You usually prefer steady progress to dramatic leaps. Recognition often comes slowly and then holds firm, earned through consistent quality and a reputation for delivering exactly what you said you would.",
    home: "Taurus on the IC often points to a childhood centred on comfort, food and stability, or a strong longing for those things. You may need a physical base that feels solid and beautiful. Inner security grows through routine, time in nature and the senses. Moving house or upheaval at home can shake you more than you expect.",
    money: "Taurus on the 2nd cusp is a natural placement for building resources. You often earn steadily and save well, valuing quality over quantity. Money is closely tied to your sense of safety. The risk is holding on too tightly, whether to possessions or to a job that no longer fits, simply because it feels secure.",
    growth: "Taurus grows by learning that change can be nourishing. Your steadiness is valuable, and it can also keep you in situations long past their season. When you allow small, chosen changes, you often discover that your security lives inside you, and that you can carry it anywhere you go.",
    saturn: "Saturn in Taurus tests your relationship with security, money and your own body. You may have felt early scarcity, or a lingering fear that there would never be quite enough. That fear can show up as over-saving, overwork or clinging to possessions long after they serve you. The lesson is building real stability patiently, and learning that worth and wealth are separate things. Mastery brings grounded resourcefulness and a calm, practical authority.",
    lilith: "Lilith in Taurus points to sensuality, bodily pleasure and material desire that may have been shamed as greedy, lazy or indulgent. Suppressed, it can erupt as compulsive spending, bingeing, possessiveness or an immovable refusal to budge. You might also deny yourself comfort to prove you need nothing at all. Owned, this becomes sovereign embodiment: trusting your senses, enjoying pleasure without guilt and knowing your value without asking anyone's permission.",
    southNode: "Told as a symbolic past-life story, a South Node in Taurus suggests someone who tended land, kept the stores or crafted beautiful objects, a person whose world was shaped by the seasons and by what could be held in the hand. That self may have mastered patience, loyalty and the art of making resources last through lean years. The wisdom remains as a calm, practical core. The habit that follows you is holding on: to routines, to possessions, to people who no longer fit. Comfort can quietly turn into stagnation. This life invites intensity, shared risk and transformation in.",
    northNodeSteps: [
      "Build one simple daily routine, such as a morning walk, and keep it for a month.",
      "Before reacting to a crisis, eat, breathe and touch something solid, then decide what matters.",
      "Set a modest savings goal from your own earnings and track it without judging yourself."
    ],
    strengths: ["Steady persistence", "Sensual appreciation", "Deep loyalty", "Practical resourcefulness"],
    challenges: ["Stubborn resistance", "Possessive attachment", "Choosing comfort over growth", "Slow to forgive"]
  },

  gemini: {
    overview: "Gemini is mutable air, ruled by Mercury, and it lives on curiosity. Your mind tends to move quickly, picking up ideas, phrases and people with ease. You probably learn best by talking things through, and you may carry several interests at once, from a podcast habit to three half-read books by the bed. This is the sign of the messenger and the translator: you connect people, notice patterns and can explain almost anything to almost anyone. Humour and wit come easily. The flip side is restlessness. Boredom can arrive fast, and depth sometimes gets traded for variety. You may also think about feelings at length instead of sitting with them. At its best, Gemini keeps life fresh and conversations alive, reminding everyone that there is always another way to see a question.",
    love: "Venus in Gemini tends to fall for a quick mind before anything else. Flirting often happens through banter, messages and shared jokes. You want a partner who keeps you interested, will talk about anything and gives you room to roam socially. Long silences or total predictability can feel like distance. You tend to show love by sharing ideas, news, links and a steady stream of conversation.",
    partner: "With Gemini on the Descendant, you often attract partners who are talkative, witty, restless or youthful in spirit. They may express the curiosity and flexibility you have not fully claimed. You might see them as flighty or inconsistent when they simply need variety. Relationships thrive on ongoing conversation, shared learning and a partner who also feels like a close friend.",
    career: "Gemini on the Midheaven suits communication in many forms: writing, teaching, media, marketing, sales, translation, technology or transport. You are often known for versatility and a quick grasp of new material. Many people with this placement hold more than one role at once or change careers several times. Recognition tends to come through your voice, your ideas and your knack for connecting people who need each other.",
    home: "Gemini on the IC often describes a busy, talkative household, perhaps with siblings, frequent moves or plenty of books and screens. Home can feel more like a crossroads than a retreat. As an adult, you may want a space full of reading material and conversation, and a base that makes coming and going easy.",
    money: "Gemini on the 2nd cusp tends to earn through communication, trade, ideas or several income streams at once. Money may come and go in bursts. You often value information as much as possessions. Your sense of worth grows when you trust your mind as a real asset and stop chasing every opportunity that catches your eye.",
    growth: "Gemini's growth edge is depth. Your curiosity is a real gift, and it becomes wisdom when you stay with one question long enough to find its roots. Choosing fewer commitments and following them through can turn scattered talent into genuine expertise, and earn you a deeper kind of trust.",
    saturn: "Saturn in Gemini tests your confidence in your own mind and voice. You may have felt slow, misunderstood or criticised when speaking or learning as a child. That can lead to anxious overthinking, or rigid, overly careful speech that hides what you really mean. The lesson is disciplined learning and responsible communication. Through practice, you often become a clear, credible thinker whose words carry weight precisely because you chose them with care.",
    lilith: "Lilith in Gemini points to a voice or mind that was dismissed, silenced or called too much. Perhaps your questions were unwelcome at the dinner table, or your truth-telling got you into trouble. Suppressed, this can erupt as cutting words, gossip, compulsive talking or sudden secrecy. Owned, it becomes a fearless intelligence: the right to ask awkward questions, to say what others will not and to change your mind freely.",
    southNode: "Symbolically, a South Node in Gemini evokes a past self who lived by wit and information: a scribe, trader, messenger or storyteller moving between towns and carrying news from one place to the next. That self may have mastered language, adaptability and the art of reading a room. Those skills remain as quick thinking and social ease. The habit that follows you now is gathering endless facts while avoiding a deeper truth, or talking around your feelings. You may keep every option open to stay safe. This life asks you to commit to meaning, belief and a larger vision.",
    northNodeSteps: [
      "Ask three genuine questions in your next conversation before sharing any opinion of your own.",
      "Take a short course in something practical and finish every single lesson.",
      "When certain you are right, find one credible source that disagrees and read it fully."
    ],
    strengths: ["Quick adaptable mind", "Gift for communication", "Playful humour", "Connecting people and ideas"],
    challenges: ["Restless scattering", "Surface over depth", "Overthinking feelings", "Inconsistent follow-through"]
  },

  cancer: {
    overview: "Cancer is cardinal water, ruled by the Moon, and its strength is care. You tend to feel the emotional weather in a room before anyone speaks, and you respond by protecting, feeding and holding people close. Home, family and belonging sit at the centre of this sign, whether that means blood relatives or a chosen circle. Memory runs deep, and so do loyalties. Like the crab, you often show a hard shell to the world while keeping a soft interior for those who have earned trust. Moods can move with the tides, and hurt may be stored away instead of spoken. Because Cancer is cardinal, it is more initiating than it looks: you create safety, start traditions and build the nests others rest in. Your tenderness is a quiet form of strength.",
    love: "Venus in Cancer loves by nurturing. You tend to show affection through cooking, remembering details, checking in and making someone feel at home. Emotional safety usually matters more than excitement. You want a partner who is gentle with your feelings, values family and stays through your difficult moods. Criticism or coldness can send you back into your shell for a long time.",
    partner: "Cancer on the Descendant draws you to caring, sensitive and family-minded partners, or to people who seem to need looking after. They may carry the emotional openness you keep guarded. You might project neediness onto them while hiding your own. Relationships deepen when both people can offer and receive care, and build something together that feels like home.",
    career: "With Cancer on the Midheaven, your public role often involves caring for others. Nursing, hospitality, early childhood education, social work, real estate, food, history or counselling can all suit you. You may be seen as protective and approachable. Recognition tends to come when people feel genuinely looked after by you. Workplaces with a family feel often bring out your best, loyal and inventive side.",
    home: "Cancer on the IC sits in its natural place. Family, ancestry and emotional roots tend to matter enormously to you. Early home life may have been close, intense or emotionally complex. You often need a private sanctuary to recharge, and home can quietly become the centre of your whole life.",
    money: "Cancer on the 2nd cusp links money closely to emotional safety. You may save for a rainy day, hold on to sentimental objects and earn through care, food, property or a family business. Spending can rise and fall with mood. Self-worth grows when you feel secure within, and stop measuring your value by how much you give.",
    growth: "Cancer grows by learning that caring for yourself matters as much as caring for others. Your sensitivity is a strength. It matures when you name your needs directly instead of hoping someone will notice, and when you let the past inform you without holding you in place.",
    saturn: "Saturn in Cancer tests emotional security and belonging. You may have grown up in a home where feelings were restrained, responsibilities came early or care felt conditional. That can leave you guarded, self-reliant to a fault or overly dutiful toward family. The lesson is learning to parent yourself with both warmth and structure. With maturity, you often become a steady emotional anchor for others, with healthy boundaries intact.",
    lilith: "Lilith in Cancer points to needs, dependency and emotional hunger that were shamed or ignored. Perhaps you learned to mother others while no one really mothered you. Suppressed, this can erupt as smothering, emotional manipulation, sulking or sudden coldness toward those closest to you. Owned, it becomes fierce protective power: the right to need, to set limits on caretaking and to define family entirely on your own terms.",
    southNode: "As a symbolic past-life story, a South Node in Cancer suggests someone who kept the hearth: a mother, healer, clan elder or guardian of a household, whose life was measured by who was fed and kept safe through winter. That self may have mastered emotional attunement and loyalty. The gift remains as a deep instinct to protect. The habit that follows you now is retreating into the familiar, taking care of everyone and avoiding public risk. Old wounds may be tended long after they could have healed. This life calls you toward purpose and responsibility beyond the home.",
    northNodeSteps: [
      "Each evening, name one feeling you had today and say it aloud to someone you trust.",
      "Let a friend help with something practical, even when you could manage it yourself.",
      "Schedule one unhurried meal at home each week with no talk of work at all."
    ],
    strengths: ["Deep emotional intelligence", "Protective loyalty", "Nurturing instinct", "Strong memory"],
    challenges: ["Changeable moods", "Holding grudges", "Caretaking to exhaustion", "Retreating when hurt"]
  },

  leo: {
    overview: "Leo is fixed fire, ruled by the Sun, and it carries the warmth of midsummer. You tend to want your life to mean something and to be seen living it. Creativity, play and generosity come naturally, and many Leos light up a room without trying. This sign is loyal, big-hearted and proud, with a strong sense of dignity. You often lead by example, inspiring others through confidence and heart. Because the fire is fixed, it burns steadily: once you love something or someone, you stay. The challenge is that recognition can start to feel essential. A lack of appreciation may wound more than you let on, and pride can get in the way of an apology. At its most mature, Leo shines in a way that makes room for everyone else to shine too.",
    love: "Venus in Leo loves grandly and generously. You enjoy romance with some theatre: thoughtful gifts, compliments, date nights that feel like occasions. Loyalty runs deep once you commit. You want to be adored, admired and chosen openly, and you tend to give the same in return. Indifference or public embarrassment can hurt your pride and cool your affection surprisingly quickly.",
    partner: "Leo on the Descendant attracts confident, expressive and charismatic partners. They may carry the self-assurance and creative spark you are still learning to show. You might admire them deeply, or resent them for taking the spotlight. The strongest partnerships let both people shine, with generous praise, loyalty and genuine play flowing in both directions.",
    career: "With Leo on the Midheaven, you are drawn to visible, creative or leading roles. Performing arts, entertainment, management, teaching, design, work with children or anything with your name on it can fit. People often see you as warm and authoritative. Recognition matters to you, and it tends to come through personal style, confident leadership and work you can take real pride in.",
    home: "Leo on the IC suggests a home you want to be proud of, a place for hospitality, creativity and celebration. Early family life may have revolved around a strong parent, or around the question of being noticed. At a deep level, you need to feel special and loved within your own four walls.",
    money: "Leo on the 2nd cusp tends to spend generously, especially on gifts, pleasure and things that reflect personal style. Earning can come through creativity, leadership or visibility. Pride and money are often linked for you. Self-worth grows when you value yourself from within, independent of applause or outward displays of status.",
    growth: "Leo's growth edge is learning to shine without needing constant confirmation. Your warmth is real and powerful. It deepens when you share the stage, celebrate other people's wins and hear honest feedback without feeling diminished. A little humility gives your natural radiance a sturdier foundation.",
    saturn: "Saturn in Leo tests your right to be seen and to express yourself fully. You may have felt overlooked as a child, or learned that creativity and play had to be earned. That can produce stage fright, harsh self-judgement or a controlling need for respect. The lesson is steady, authentic self-expression built through practice and courage. Mastery brings dignified leadership and creative work that endures because it comes straight from the heart.",
    lilith: "Lilith in Leo points to a need for attention, pride and creative self-display that was mocked or suppressed. You may have been told you were showing off or asking for too much. Suppressed, it can erupt as dramatic outbursts, jealousy toward anyone in the spotlight or brittle arrogance. Owned, this becomes unapologetic presence: the freedom to take up space, create boldly and be adored without shrinking yourself to fit.",
    southNode: "Symbolically, a South Node in Leo tells of a past self who stood at the centre: a ruler, performer or favoured child whose worth was measured in applause and loyalty. That self may have mastered charisma, creative courage and the art of commanding a room. Those gifts linger as natural confidence and warmth. The habit that follows you now is needing to feel special, taking things personally and expecting admiration as your due. Pride can quietly block collaboration. This life invites you to put your light to work for a group or a cause larger than yourself.",
    northNodeSteps: [
      "Share a piece of your creative work publicly this month, even if it feels unfinished.",
      "When you feel proud of something, say so plainly instead of deflecting the compliment.",
      "Spend one hour each week on play that has no purpose beyond your own enjoyment."
    ],
    strengths: ["Generous warmth", "Creative confidence", "Loyal heart", "Natural leadership"],
    challenges: ["Need for recognition", "Wounded pride", "Dramatic reactions", "Sharing the spotlight"]
  },

  virgo: {
    overview: "Virgo is mutable earth, ruled by Mercury, and it expresses intelligence through usefulness. You tend to notice details other people miss, from a typo in a contract to the reason a friend seems tired. This sign wants things to work well and people to be well, and it often shows love through practical help. Skill, craft and gradual improvement bring deep satisfaction. Health, routine and daily habits often matter to you more than grand plans. Because Virgo is mutable, it adapts easily and can reorganise almost any mess. The difficulty is that the same eye for flaws can turn inward, becoming self-criticism or worry, and perfectionism may delay you. At its best, Virgo offers humble, skilful service and a clear, discerning mind that makes life better for everyone around it.",
    love: "Venus in Virgo loves through attention and small acts of service. You may fix a partner's bike, remember their allergies or quietly handle the boring paperwork. Affection grows as trust builds. You want to be appreciated for these efforts and loved without having to be perfect. Carelessness, mess or broken promises can dampen attraction, even when the chemistry is strong.",
    partner: "Virgo on the Descendant draws you to capable, modest, helpful or analytical partners. They may carry the discernment and practicality you haven't fully owned. You might experience them as critical when they are simply being precise. Relationships work best when both people share the daily load, communicate clearly and allow each other to be imperfect.",
    career: "Virgo on the Midheaven suits work built on skill, accuracy and service. Health care, research, editing, accounting, nutrition, IT, administration or the skilled trades can all fit. You are often seen as the reliable expert who notices what needs fixing. Recognition tends to come from competence and quiet excellence, and from making systems run so smoothly that others can finally relax.",
    home: "Virgo on the IC points to a home that feels best when it is orderly, clean and practical. Early family life may have emphasised duty, health or doing things properly. As an adult, you may find calm through tidying and routine. The lesson is letting home be a place of rest as well as productivity.",
    money: "Virgo on the 2nd cusp tends to be careful and methodical with money. You may budget well, research purchases thoroughly and earn through skill, service or detailed work. Worth can feel tied to usefulness. You grow when you charge fairly for your expertise and stop underselling the care you put into everything.",
    growth: "Virgo's growth edge is trusting that good enough is often good enough. Your discernment is valuable, and it serves you best when paired with self-compassion. Letting go of constant fixing can free energy for rest, faith and joy, and remind you that your worth reaches well beyond your output.",
    saturn: "Saturn in Virgo tests your relationship with work, health and competence. You may carry a fear of making mistakes, or a belief that rest must always be earned. That can lead to anxious perfectionism, overwork or nervous tension held in the body. The lesson is building steady, sustainable routines and realistic standards. Mastery brings genuine expertise, sound daily habits and the ability to serve others without depleting yourself.",
    lilith: "Lilith in Virgo points to an untamed, messy or instinctive side that was shamed into neatness. You may have learned that bodily needs, imperfection or refusing to help were unacceptable. Suppressed, this can erupt as obsessive control, harsh criticism, health anxiety or a sudden refusal to help anyone at all. Owned, it becomes sovereign discernment: honouring your body, choosing whom you serve and trusting your own standards over anyone else's.",
    southNode: "As a symbolic past-life story, a South Node in Virgo suggests someone who served: a healer, clerk, monastery worker or skilled artisan, whose days were shaped by duty, craft and careful ritual. That self may have mastered precision, humility and practical care. Those gifts remain as quiet competence. The habit that follows you now is over-analysing, worrying and trying to earn your place through usefulness. Control can crowd out faith, and fixing can crowd out feeling. This life asks you to trust the unseen, soften the rules and let compassion lead.",
    northNodeSteps: [
      "Choose one small daily habit, such as a ten-minute tidy, and track it for a month.",
      "Break a vague dream into three concrete tasks and complete the first one this week.",
      "Offer practical help to someone in a specific way, alongside your usual sympathy."
    ],
    strengths: ["Attention to detail", "Practical helpfulness", "Analytical clarity", "Dedicated craftsmanship"],
    challenges: ["Harsh self-criticism", "Paralysing perfectionism", "Worry and overthinking", "Difficulty resting"]
  },

  libra: {
    overview: "Libra is cardinal air, ruled by Venus, and it seeks harmony through relationship. You tend to see every side of a situation, which makes you a natural diplomat, mediator and host. Beauty matters to you: in design, manners, clothing and the way people treat each other. This sign often has a strong sense of fairness and can be surprisingly firm when justice is at stake. Because Libra is cardinal, it initiates connection, bringing people together and setting the tone of a gathering. The challenge is that keeping the peace can become a habit that quietly costs you your own preferences. Indecision often comes from weighing everyone else's needs first. At its best, Libra creates balance that honours both self and other, and brings grace to the hardest conversations.",
    love: "Venus in Libra is at home, and it loves with charm, courtesy and a strong sense of partnership. You enjoy romance, beauty and shared rituals like a well-set table or a thoughtful gift. Fairness matters deeply. You want a partner who treats you as an equal and speaks kindly, even in disagreement. Crudeness, constant conflict or neglect can switch off your attraction faster than distance ever could.",
    partner: "Libra on the Descendant draws refined, sociable and diplomatic partners. They may reflect a grace and balance you are still learning to develop. You might project indecisiveness onto them, or expect them to keep the peace for both of you. Healthy partnerships include genuine equality and honest disagreement, handled with care and a willingness to meet in the middle.",
    career: "With Libra on the Midheaven, you tend to do well where people, aesthetics or fairness are central. Law, mediation, design, fashion, the arts, human resources, diplomacy or client-facing roles often suit. People tend to see you as pleasant, polished and fair. Recognition comes through partnerships, collaboration and your ability to make things work beautifully for everyone involved.",
    home: "Libra on the IC points to a longing for peace and beauty at home. Early family life may have involved keeping the peace, or parents who cared a great deal about appearances. You often need a harmonious, attractive space to feel settled. Conflict under your own roof can unsettle you deeply.",
    money: "Libra on the 2nd cusp tends to spend on beauty, social life and shared experiences. Income may come through partnerships, design or people-facing work. You often value fairness in money matters. Self-worth grows when you stop measuring yourself by others' approval and trust your own sense of what things are worth.",
    growth: "Libra grows by learning that honesty can be a form of kindness. Your gift for harmony is real, and it deepens when you let others know what you actually want. Choosing, even at the risk of disapproval, turns diplomacy into integrity and makes your relationships more genuine and more durable.",
    saturn: "Saturn in Libra, where it is exalted, tests fairness and commitment in relationships. You may have witnessed early imbalances between the adults around you, or felt that love came with heavy duties. That can lead to a fear of commitment, or to staying too long in unequal arrangements. The lesson is building partnerships on clear agreements and mutual respect. Mastery brings wise judgement, mature relating and a reputation for integrity.",
    lilith: "Lilith in Libra points to anger, self-interest or disagreement that was shamed as unattractive or impolite. You may have learned to smile through injustice and keep everyone comfortable. Suppressed, this can erupt as passive aggression, sudden relationship ruptures or a cold withdrawal of charm. Owned, it becomes sovereign equality: the right to name imbalance, refuse unfair deals and define partnership on your own terms.",
    southNode: "Symbolically, a South Node in Libra evokes a past self who lived through others: a courtier, consort, diplomat or artist dependent on a patron, whose safety rested on keeping people pleased. That self may have mastered grace, tact and the fine art of partnership. Those skills remain as social ease and charm. The habit that follows you now is deferring, avoiding conflict and defining yourself by who you are with. Decisions may stall while you wait for approval that never quite arrives. This life asks you to act on your own instincts and trust your individual courage.",
    northNodeSteps: [
      "Before acting on a decision, ask one affected person how they see it and listen fully.",
      "Practise pausing for three breaths when irritated, then respond with a question.",
      "Plan one shared project with a partner or friend where both roles carry equal weight."
    ],
    strengths: ["Diplomatic grace", "Strong sense of fairness", "Aesthetic sense", "Relationship skill"],
    challenges: ["Chronic indecision", "Pleasing people first", "Conflict avoidance", "Dependence on approval"]
  },

  scorpio: {
    overview: "Scorpio is fixed water, traditionally ruled by Mars and in modern astrology by Pluto. It seeks truth at depth and rarely settles for the surface. You tend to feel intensely and read people with uncanny accuracy, sensing motives others would rather hide. Trust is given slowly and guarded carefully, and once you commit, loyalty can be absolute. This sign understands power, intimacy, loss and renewal, and it often passes through several deep transformations in a lifetime. The fixed quality lends determination and staying power. The difficulty is that fear of betrayal can lead to secrecy, jealousy or control, and hurt may be remembered for years. At its best, Scorpio has a rare courage to face what others avoid, and helps people heal through unflinching honesty.",
    love: "Venus in Scorpio loves with total intensity. Attraction is magnetic and often immediate, and you want emotional and physical depth over anything casual. Loyalty is essential. You want a partner who can handle your intensity, share secrets and stay present through hard truths. Betrayal or shallowness can end your interest completely, sometimes without any warning at all.",
    partner: "Scorpio on the Descendant draws intense, private and powerful partners, often with an air of mystery. They may carry emotional depth or personal power you haven't fully claimed. You might project control or jealousy onto them. Relationships become transformative when both people can be vulnerable, share power fairly and speak honestly about difficult feelings.",
    career: "With Scorpio on the Midheaven, you are often drawn to work that involves depth, investigation or transformation. Psychology, research, medicine, finance, crisis work, investigation or anything involving hidden resources can suit. You may be seen as intense, private and highly capable. Recognition tends to come from handling what others avoid and holding power responsibly when it is placed in your hands.",
    home: "Scorpio on the IC suggests an early home life with intensity, secrets or significant change. You may have learned to guard your private world closely. As an adult, you often need a home that feels safe, private and emotionally honest, a place where you can retreat and recover fully.",
    money: "Scorpio on the 2nd cusp tends to be strategic and private about money. You may earn through research, shared resources, investments or crisis work. Money can carry emotional weight, tied to power and control. Self-worth grows when you trust your own resilience and stop holding on to resources out of fear.",
    growth: "Scorpio's growth edge is trust. Your depth and perception are powerful, and they mature when you allow vulnerability without testing people first. Releasing old grudges and letting some things stay light makes room for intimacy that feels safe, and for a lighter heart.",
    saturn: "Saturn in Scorpio tests your relationship with power, intimacy and loss. You may have faced early experiences of control, betrayal or taboo that taught you to guard yourself closely. That can lead to secrecy, fear of vulnerability or controlling behaviour when you feel exposed. The lesson is facing your depths with honesty and discipline. Mastery brings emotional resilience, psychological insight and the steadiness to support others through crisis.",
    lilith: "Lilith in Scorpio points to sexuality, rage or psychic intensity that was shamed as dangerous or taboo. You may have learned to hide your power to keep others comfortable. Suppressed, this can erupt as jealousy, vengeance, manipulation or self-destructive episodes. Owned, it becomes sovereign depth: the capacity to hold your own power, name hidden truths and turn pain into regeneration.",
    southNode: "As a symbolic past-life story, a South Node in Scorpio suggests someone who lived close to life and death: a healer, occultist, spy or keeper of dangerous secrets, used to crisis and binding loyalties. That self may have mastered survival, strategy and emotional endurance under pressure. Those gifts linger as courage and sharp perception. The habit that follows you now is expecting betrayal, seeking drama or controlling situations to feel safe. Intensity can feel like home, even when it exhausts you. This life invites you to find peace in simple, steady pleasures and shared ease.",
    northNodeSteps: [
      "Share one fear with someone you trust instead of handling it quietly on your own.",
      "Let go of one possession or habit you keep only because it feels comfortable.",
      "Discuss one shared financial or emotional commitment openly and honestly with your partner."
    ],
    strengths: ["Emotional depth", "Perceptive insight", "Deep resilience", "Fierce loyalty"],
    challenges: ["Jealous suspicion", "Guarded secrecy", "Controlling tendencies", "Holding onto hurt"]
  },

  sagittarius: {
    overview: "Sagittarius is mutable fire, ruled by Jupiter, and it is driven by a hunger for meaning. You tend to want to know why things matter and where they lead. Travel, study, philosophy and big late-night conversations often feed you, along with the freedom to move. This sign is optimistic, candid and often very funny, with a gift for inspiring others and seeing the larger pattern. Because it is mutable, Sagittarius adapts quickly and enjoys trying new paths. The shadow side includes restlessness, overcommitment and a bluntness that sometimes wounds without meaning to. Promises can be made in enthusiasm and dropped when a new horizon appears. At its best, Sagittarius brings faith, generosity and a sense of adventure, helping people believe that life is bigger than their current circumstances.",
    love: "Venus in Sagittarius loves with humour, openness and a craving for adventure. You may fall for someone from a different background, or bond over travel and ideas. Freedom matters a great deal. You want a partner who shares your curiosity and gives you room to explore. Possessiveness, rigid routine or small-minded criticism can send you galloping off toward the horizon.",
    partner: "Sagittarius on the Descendant draws adventurous, philosophical and free-spirited partners, sometimes from another culture or country. They may carry the optimism and faith you haven't fully owned. You might see them as unreliable or preachy. Relationships grow when both people learn and travel together, respect each other's independence and share a larger sense of purpose.",
    career: "With Sagittarius on the Midheaven, you are drawn to work with meaning and scope. Teaching, publishing, law, tourism, higher education, religion, international business or coaching can suit. You are often seen as inspiring and knowledgeable. Recognition tends to come through big ideas, broad experience and your ability to motivate others toward a shared vision they can believe in.",
    home: "Sagittarius on the IC often suggests an early home life with travel, cultural mixing or strong beliefs. You may have moved often, or grown up between worlds. As an adult, you might need a home with space, books and an open door. Your inner foundation rests on faith and a sense of meaning.",
    money: "Sagittarius on the 2nd cusp tends to be generous and optimistic with money, sometimes too optimistic. Income may come through teaching, travel, publishing or international work. You often value experiences over possessions. Self-worth grows when you match your ideals with practical planning and follow through on what you promise.",
    growth: "Sagittarius grows by pairing vision with commitment. Your enthusiasm lifts people, and it becomes trustworthy when you stay the course and attend to the details. When you listen as much as you teach, you often find the wisdom you are searching for in the people right in front of you.",
    saturn: "Saturn in Sagittarius tests your beliefs, education and faith. You may have met rigid dogma early, at school or in religion, or doubted your right to a philosophy of your own. That can lead to cynicism, or to clinging to fixed opinions for safety. The lesson is developing a grounded worldview through patient study and lived experience. Mastery brings earned wisdom, credible teaching and ethical leadership that others respect.",
    lilith: "Lilith in Sagittarius points to a wild, free, questioning spirit that was shamed as irresponsible or heretical. You may have been punished for doubting accepted truths. Suppressed, this can erupt as reckless escapes, self-righteous preaching or sudden abandonment of commitments. Owned, it becomes sovereign freedom: the right to seek your own truth, roam widely and speak candidly without apology or permission.",
    southNode: "Symbolically, a South Node in Sagittarius evokes a past self who was a wanderer, preacher, scholar or explorer, free to roam and quick to pass judgement. That self may have mastered faith, broad knowledge and the art of seeing the larger picture. Those gifts remain as optimism and vision. The habit that follows you now is preaching, assuming you already know and skipping the details. Restlessness may pull you away from local, everyday connection with the people nearby. This life asks you to listen closely, keep learning and communicate with genuine curiosity.",
    northNodeSteps: [
      "Choose one belief you hold and write a page on why it genuinely matters to you.",
      "Plan a trip or course that stretches your worldview, then commit and book it.",
      "When you catch yourself gathering more facts, stop and decide what you actually think."
    ],
    strengths: ["Infectious optimism", "Philosophical vision", "Honest candour", "Adventurous spirit"],
    challenges: ["Chronic restlessness", "Promising too much", "Tactless bluntness", "Avoiding the details"]
  },

  capricorn: {
    overview: "Capricorn is cardinal earth, ruled by Saturn, and it builds for the long term. You tend to think in years and decades, setting goals and climbing toward them with patience and resolve. Responsibility often arrives early for this sign, and many Capricorns seem older than their age in youth and younger in later life. You value competence, integrity and a job done properly. Humour is often dry and quietly wicked. Because Capricorn is cardinal, it initiates structure: businesses, systems, family traditions. The challenge is that work can crowd out feeling, and self-worth can come to hinge on achievement. Fear of failure may make you cautious or controlling. At its best, Capricorn becomes a wise elder in any setting, offering reliability, practical leadership and a model of dignity under pressure.",
    love: "Venus in Capricorn loves with seriousness and commitment. You may take time to open up, preferring to prove your affection through reliability and practical support. Quality matters far more than quantity. You want a partner who is dependable, ambitious in their own right and respectful of your goals. Flakiness or emotional chaos can make you retreat behind a cool, capable surface.",
    partner: "Capricorn on the Descendant draws mature, responsible and often older or well-established partners. They may carry the authority and discipline you haven't fully claimed. You might see them as controlling or cold. Relationships work best when both people share responsibility, build long-term plans together and make deliberate room for warmth alongside duty.",
    career: "Capricorn on the Midheaven is its natural home, pointing to strong ambition and a desire for standing in the world. Management, law, government, finance, engineering, architecture or running your own business can suit. You are often seen as capable and serious. Recognition tends to come slowly and last, earned through proven results and authority built patiently over time.",
    home: "Capricorn on the IC suggests early home life marked by structure, responsibility or emotional reserve. You may have grown up fast. As an adult, you often want a home that feels solid, well-managed and secure, and emotional openness within the family may take some practice.",
    money: "Capricorn on the 2nd cusp tends to be disciplined and long-sighted with money. You often plan carefully, buy quality and build resources gradually. Earning can come through management, structure or hard-won expertise. Self-worth grows when you value yourself for who you are, as well as for what you achieve.",
    growth: "Capricorn's growth edge is allowing softness. Your discipline and ambition are real strengths, and they become more fulfilling when you let yourself rest, receive support and feel emotions fully. Success tends to mean more when it is shared, and joy is part of what makes the climb worthwhile.",
    saturn: "Saturn in Capricorn is in its own sign, doubling the emphasis on duty, ambition and authority. You may have felt heavy expectations early, or feared you would never quite measure up. That can lead to overwork, rigidity or chronic self-doubt hidden behind competence. The lesson is building authority through integrity and patience. Mastery brings real accomplishment, trustworthy leadership and the kind of respect that grows with age.",
    lilith: "Lilith in Capricorn points to ambition, authority or a hunger for power that was shamed or blocked. You may have been told, in words or silence, to know your place. Suppressed, this can erupt as ruthless control, bitterness toward authority or workaholic self-punishment. Owned, it becomes sovereign authority: the right to lead, build your own structures and succeed on your own terms, without apology.",
    southNode: "As a symbolic past-life story, a South Node in Capricorn suggests someone who carried authority: a magistrate, head of a family line or builder of institutions, whose life was defined by duty and reputation. That self may have mastered discipline, strategy and responsibility. Those gifts remain as competence under pressure. The habit that follows you now is putting achievement ahead of feeling and controlling situations instead of trusting others. Status may still feel like the only real safety. This life invites you to soften, nurture and let yourself be cared for.",
    northNodeSteps: [
      "Set one clear long-term goal and write down the first three measurable steps toward it.",
      "Take responsibility for a decision you usually leave to others, and see it through.",
      "When emotions run high, name the practical outcome you want before you respond."
    ],
    strengths: ["Disciplined ambition", "Rock-solid reliability", "Strategic patience", "Dry wit"],
    challenges: ["Work before rest", "Emotional reserve", "Fear of failure", "Rigid expectations"]
  },

  aquarius: {
    overview: "Aquarius is fixed air, traditionally ruled by Saturn and in modern astrology by Uranus, and it often thinks ahead of its time. You tend to value independence, originality and fairness for everyone, and you can usually see how systems could work better. Friendship matters deeply to this sign, as does belonging to a group with shared ideals. Many Aquarians feel slightly outside the norm, which gives them valuable perspective. Because the sign is fixed, convictions can be very firm, even when they are progressive. The challenge is emotional distance: feelings may be intellectualised or kept at arm's length, and you can care for humanity while finding one person's needs hard to meet. At its best, Aquarius brings innovation, loyalty to principle and a friendly, accepting spirit that makes room for difference.",
    love: "Venus in Aquarius loves through friendship and freedom. You are attracted to originality and to minds that surprise you. Space matters, and so does being accepted exactly as you are. You want a partner who is also a close friend, respects your independence and shares your ideals. Clinginess or pressure to conform can make you detach suddenly, sometimes before you understand why yourself.",
    partner: "Aquarius on the Descendant draws unconventional, independent and friendly partners, some of them emotionally distant. They may carry the individuality and detachment you haven't fully owned. You might see them as aloof or unpredictable. Relationships thrive with space, honest conversation and a shared commitment to growth that lets neither person be squeezed into a conventional mould.",
    career: "With Aquarius on the Midheaven, you are drawn to innovative, humanitarian or technological work. Science, technology, social justice, community organising, astrology or unconventional entrepreneurship can suit. You are often seen as original and forward-thinking. Recognition tends to come through ideas that change systems, and through collaboration with like-minded groups who share your vision.",
    home: "Aquarius on the IC suggests an unconventional early home, perhaps with instability, unusual parenting or a sense of not quite belonging. As an adult, you might create a home that feels like a community hub or a living experiment. Freedom within your own space is essential to your wellbeing.",
    money: "Aquarius on the 2nd cusp tends to approach money unconventionally. Income may come through technology, groups, innovation or causes you believe in. Spending can be erratic. Self-worth grows when you value your originality as a resource and build stable systems that still leave plenty of room for freedom.",
    growth: "Aquarius grows by letting feelings in. Your vision and independence are gifts, and they deepen when you allow closeness without fearing a loss of self. Caring for the individual in front of you, as well as the collective, makes your ideals real and your relationships noticeably warmer.",
    saturn: "Saturn in Aquarius, one of its traditional homes, tests your relationship with groups, belonging and individuality. You may have felt like an outsider early, or come under pressure to conform. That can lead to rigid ideals, defensive detachment or a lonely sense of standing apart. The lesson is giving innovation a responsible structure. Mastery brings practical vision, the ability to lead reform and a steady, dependable commitment to community.",
    lilith: "Lilith in Aquarius points to eccentricity, rebellion or radical thinking that was shamed or excluded. You may have been pushed out of groups for being different, or learned to hide your stranger ideas. Suppressed, this can erupt as cold detachment, sudden rebellion or contempt for the mainstream. Owned, it becomes sovereign individuality: the freedom to be unusual, think radically and belong without conforming.",
    southNode: "Symbolically, a South Node in Aquarius evokes a past self who belonged to a movement, collective or society of thinkers, perhaps a reformer, scientist or rebel who always put the group first. That self may have mastered objectivity, invention and idealism. Those gifts remain as a wide, clear perspective. The habit that follows you now is emotional detachment, intellectualising and hiding in the crowd. Personal creativity and heartfelt self-expression may feel risky or even self-indulgent. This life invites you to step forward, be seen and express your heart openly.",
    northNodeSteps: [
      "Join a group or cause that matters to you and attend regularly for three months.",
      "Share credit for a success publicly, naming everyone who contributed to the result.",
      "Try one idea that feels unconventional to you, and ask friends for honest feedback."
    ],
    strengths: ["Original thinking", "Humanitarian ideals", "Loyal friendship", "Fierce independence"],
    challenges: ["Emotional detachment", "Stubborn convictions", "Cool aloofness", "Rebellion for its own sake"]
  },

  pisces: {
    overview: "Pisces is mutable water, traditionally ruled by Jupiter and in modern astrology by Neptune, and it is the sign of compassion and imagination. You tend to absorb the feelings of people around you, sometimes without realising it, and you may have a rich inner life of dreams, art, music or spirituality. Boundaries can be porous, which makes you empathetic and intuitive and also easily overwhelmed in crowds or conflict. This sign often serves, heals or creates, finding meaning in something larger than the self. Because Pisces is mutable, it flows and adapts, taking the shape of whatever it enters. The challenge is losing yourself: escapism, confusion or martyrdom may follow. At its best, Pisces brings gentle wisdom, creative vision and a forgiving heart that softens the world.",
    love: "Venus in Pisces loves romantically and devotedly. You may idealise partners, seeing their potential and making sacrifices on their behalf. Compassion comes easily. You want a partner who understands your sensitivity and shares a sense of magic or spirituality. Harshness or cynicism can wound you deeply, and learning to see a partner clearly, flaws included, is often a lifelong practice.",
    partner: "Pisces on the Descendant draws sensitive, artistic, spiritual or sometimes elusive partners. They may carry the compassion and imagination you haven't fully owned. You might cast them as someone to rescue, or as the one who will rescue you. Relationships heal and deepen when both people keep healthy boundaries, share dreams and see each other clearly.",
    career: "With Pisces on the Midheaven, you are drawn to creative, healing or spiritual work. The arts, film, music, health care, therapy, charity, marine work or spiritual guidance can suit. You are often seen as intuitive and compassionate. Recognition may follow a winding path, arriving through artistic vision, quiet service and your ability to inspire others with something they can feel.",
    home: "Pisces on the IC suggests an early home life that was fluid, spiritual or confusing, perhaps with a sensitive or absent parent. As an adult, you might need a peaceful, dreamy sanctuary, ideally near water or full of art and music. Your inner foundation rests on faith and imagination.",
    money: "Pisces on the 2nd cusp tends to be generous and sometimes vague with money. Income may come through art, healing, care or intuition. Money can slip away without clear limits. Self-worth grows when you value your sensitivity and gifts, and put simple, practical systems around your finances to protect them.",
    growth: "Pisces grows by building boundaries. Your compassion and imagination are gifts, and they flourish when you protect your energy and ground your dreams in practical steps. Knowing where you end and others begin allows you to help people without drowning in their troubles.",
    saturn: "Saturn in Pisces tests your faith, boundaries and ability to face reality. You may have felt early confusion, loss or a fear of chaos, perhaps in a home where things were never quite clear. That can lead to escapism, or to rigid control of your feelings. The lesson is giving form to compassion and imagination. Mastery brings grounded spirituality, disciplined creativity and the ability to serve without sacrificing yourself.",
    lilith: "Lilith in Pisces points to mystical, psychic or deeply sensitive parts that were shamed as unreal or weak. You may have been told you were too emotional or too dreamy. Suppressed, this can erupt as escapism, victimhood, addictive patterns or sudden disappearance from people's lives. Owned, it becomes sovereign mysticism: trusting your intuition, honouring your sensitivity and channelling it into art or healing.",
    southNode: "As a symbolic past-life story, a South Node in Pisces suggests someone devoted to the spiritual or artistic: a mystic, monastic, healer or poet, living on the margins and serving others quietly. That self may have mastered compassion, intuition and surrender. Those gifts remain as empathy and a vivid imagination. The habit that follows you now is escapism, confusion or losing yourself in other people's needs. Practical matters may feel foreign or even beneath you. This life asks you to ground your gifts through useful, organised service in the everyday world.",
    northNodeSteps: [
      "Spend ten minutes daily in silence, prayer or meditation without trying to fix anything.",
      "Let one small task stay imperfect this week and notice what actually happens.",
      "Make art, music or writing purely for its own sake, with no plan to improve it."
    ],
    strengths: ["Deep compassion", "Creative imagination", "Intuitive sensitivity", "Forgiving nature"],
    challenges: ["Escaping into fantasy", "Weak boundaries", "Self-sacrificing martyrdom", "Confusion under stress"]
  }
};
